@extends('layouts.app')

@section('title', __('maintenance.material_requests.title'))

@section('content')
    <div class="production-mobile-workflow">
        @if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
        @can('maintenance.material_requests.create')
            <form method="POST" action="{{ route('admin.maintenance.material-requests.store') }}" class="card mb-3" data-maintenance-material-form>@csrf
                <div class="card-header"><h5 class="mb-0">{{ __('maintenance.material_requests.create') }}</h5><p class="small text-600 mb-0">{{ __('maintenance.material_requests.help') }}</p></div>
                <div class="card-body"><div class="row g-3">
                    <div class="col-12 col-md-6"><label class="form-label">{{ __('maintenance.fields.work_order') }}</label><x-forms.select name="maintenance_work_order_id" required><option value="">{{ __('common.placeholders.select') }}</option>@foreach($orders as $order)<option value="{{ $order->id }}" @selected(old('maintenance_work_order_id', request('order')) == $order->id)>{{ $order->doc_num }} — {{ $order->asset?->asset_name }}</option>@endforeach</x-forms.select></div>
                    <div class="col-12 col-md-6"><label class="form-label">{{ __('maintenance.fields.store') }}</label><x-forms.select name="branch_store_id" required><option value="">{{ __('common.placeholders.select') }}</option>@foreach($stores as $store)<option value="{{ $store->id }}">{{ $store->name }}</option>@endforeach</x-forms.select></div>
                    <div class="col-12"><label class="form-label">{{ __('maintenance.fields.reason') }}</label><x-forms.input name="reason" :value="old('reason')" /></div>
                    <div class="col-12"><div class="table-responsive"><table class="table table-sm align-middle mb-0"><thead><tr><th>{{ __('maintenance.fields.item') }}</th><th>{{ __('maintenance.fields.item_type') }}</th><th>{{ __('maintenance.fields.quantity') }}</th><th>{{ __('maintenance.fields.notes') }}</th><th></th></tr></thead><tbody data-maintenance-material-rows>
                        @foreach(old('lines', [['product_id' => '', 'item_type' => 'spare_part', 'quantity' => '', 'notes' => '']]) as $index => $line)
                            <tr data-maintenance-material-row><td><x-forms.select name="lines[{{ $index }}][product_id]" required><option value="">{{ __('common.placeholders.select') }}</option>@foreach($products as $product)<option value="{{ $product->id }}" @selected(($line['product_id'] ?? '') == $product->id)>{{ $product->doc_num }} — {{ $product->name }}</option>@endforeach</x-forms.select></td><td><x-forms.select name="lines[{{ $index }}][item_type]">@foreach(['spare_part', 'oil', 'consumable'] as $type)<option value="{{ $type }}" @selected(($line['item_type'] ?? '') === $type)>{{ __('maintenance.item_types.'.$type) }}</option>@endforeach</x-forms.select></td><td><x-forms.input name="lines[{{ $index }}][quantity]" type="number" min="0.00000001" step="0.00000001" inputmode="decimal" :value="$line['quantity'] ?? ''" required /></td><td><x-forms.input name="lines[{{ $index }}][notes]" :value="$line['notes'] ?? ''" /></td><td><button type="button" class="btn btn-sm btn-falcon-danger" data-remove-maintenance-material><span class="fas fa-times"></span></button></td></tr>
                        @endforeach
                    </tbody></table></div></div>
                    <div class="col-12"><button type="button" class="btn btn-sm btn-falcon-default" data-add-maintenance-material><span class="fas fa-plus me-1"></span>{{ __('maintenance.actions.add_item') }}</button></div>
                </div></div>
                <div class="card-footer d-grid d-sm-flex justify-content-sm-end"><button class="btn btn-primary">{{ __('maintenance.actions.submit_request') }}</button></div>
                <template data-maintenance-material-template><tr data-maintenance-material-row><td><x-forms.select name="lines[__INDEX__][product_id]" required><option value="">{{ __('common.placeholders.select') }}</option>@foreach($products as $product)<option value="{{ $product->id }}">{{ $product->doc_num }} — {{ $product->name }}</option>@endforeach</x-forms.select></td><td><x-forms.select name="lines[__INDEX__][item_type]">@foreach(['spare_part', 'oil', 'consumable'] as $type)<option value="{{ $type }}">{{ __('maintenance.item_types.'.$type) }}</option>@endforeach</x-forms.select></td><td><x-forms.input name="lines[__INDEX__][quantity]" type="number" min="0.00000001" step="0.00000001" required /></td><td><x-forms.input name="lines[__INDEX__][notes]" /></td><td><button type="button" class="btn btn-sm btn-falcon-danger" data-remove-maintenance-material><span class="fas fa-times"></span></button></td></tr></template>
            </form>
        @endcan
        <div class="card erp-datatable-card"><div class="card-header"><h5 class="mb-0">{{ __('maintenance.material_requests.title') }}</h5></div><div class="table-responsive"><table class="table table-sm table-hover align-middle mb-0 data-table erp-datatable" data-server-table data-url="{{ route('admin.maintenance.material-requests.index') }}" data-order-column="1" data-order-direction="desc" data-columns='[{"data":"doc_num","name":"maintenance_material_requests.doc_num"},{"data":"request_date","name":"request_date"},{"data":"work_order_number","name":"work_order_number"},{"data":"asset_name","name":"asset_name"},{"data":"store_name","name":"store_name"},{"data":"lines_count","name":"lines_count","searchable":false},{"data":"issue_number","name":"issue_number","defaultContent":"—"},{"data":"return_number","name":"return_number","defaultContent":"—"},{"data":"status","name":"status"},{"data":"actions","name":"actions","orderable":false,"searchable":false}]'><thead><tr><th>{{ __('maintenance.fields.document') }}</th><th>{{ __('maintenance.fields.date') }}</th><th>{{ __('maintenance.fields.work_order') }}</th><th>{{ __('maintenance.fields.asset') }}</th><th>{{ __('maintenance.fields.store') }}</th><th>{{ __('maintenance.fields.lines_count') }}</th><th>{{ __('maintenance.fields.issue_document') }}</th><th>{{ __('maintenance.fields.return_document') }}</th><th>{{ __('maintenance.fields.status') }}</th><th></th></tr></thead></table></div></div>
    </div>
@endsection

@push('styles')<link rel="stylesheet" href="{{ app(\Modules\Core\Services\AssetVersionService::class)->url('assets/css/modules/Production/execution.css') }}">@endpush
@push('scripts')<script src="{{ app(\Modules\Core\Services\AssetVersionService::class)->url('assets/js/modules/Production/execution.js') }}"></script>@endpush
