@if($canRecognize) @can('fixed_assets.activate')
<div class="modal fade" id="recognition-modal" tabindex="-1" aria-labelledby="recognition-title" aria-hidden="true"><div class="modal-dialog modal-lg modal-dialog-scrollable modal-dialog-centered"><div class="modal-content">
<div class="modal-header"><h5 class="modal-title" id="recognition-title">{{ $recognitionLabel }} — {{ $asset->doc_num }}</h5><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="{{ __('common.actions.close') }}"></button></div>
<div class="modal-body"><form method="POST" action="{{ route('admin.fixed-assets.lifecycle.activate', $asset) }}" class="row g-3 align-items-end">@csrf
<input type="hidden" name="_workflow" value="recognition">
                    <div class="col-md-4"><label class="form-label" for="activation_date">{{ __('fixed_assets.lifecycle.activation_date') }}</label><input class="form-control js-date-picker" id="activation_date" name="activation_date" value="{{ old('activation_date', $dates->formatDate($asset->previous_depreciation_until_date?->copy()->addDay() ?: $asset->operation_date ?: now(), '')) }}" data-date-format="{{ $dates->jsDateFormat() }}" data-locale="{{ app()->getLocale() }}" autocomplete="off" required></div>
                    <div class="col-12"><details><summary class="small text-600">{{ __('fixed_assets.product.legacy_link') }}</summary><label class="form-label" for="recognition-existing_journal_doc_num">{{ __('fixed_assets.cycle.legacy_journal') }}</label><input id="recognition-existing_journal_doc_num" class="form-control" name="existing_journal_doc_num" value="{{ old('existing_journal_doc_num') }}"></details></div><div class="col-auto"><button class="btn btn-success" type="submit">{{ $recognitionLabel }}</button></div>
                </form></div>
</div></div></div>
@endcan @endif

@if($canTransact) @can('fixed_assets.improvement.post')
<div class="modal fade" id="addition-modal" tabindex="-1" aria-labelledby="addition-title" aria-hidden="true"><div class="modal-dialog modal-lg modal-dialog-scrollable modal-dialog-centered"><div class="modal-content">
<div class="modal-header"><h5 class="modal-title" id="addition-title">{{ __('fixed_assets.cycle.addition') }} — {{ $asset->doc_num }}</h5><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="{{ __('common.actions.close') }}"></button></div>
<div class="modal-body"><form method="POST" action="{{ route('admin.fixed-assets.movements.addition', $asset) }}" class="row g-3 js-addition-form" data-current-cost="{{ $position['acquisition_cost'] }}">@csrf
<input type="hidden" name="_workflow" value="addition">
<div class="col-12"><div class="alert alert-info mb-0">{{ __('fixed_assets.product.addition_hint') }}</div></div>
<div class="col-sm-4"><span class="text-600">{{ __('fixed_assets.reports.columns.cost') }}</span><strong class="d-block" dir="ltr">{{ $numbers->format($position['acquisition_cost']) }}</strong></div>
<div class="col-sm-4"><span class="text-600">{{ __('fixed_assets.attributes.useful_life') }}</span><strong class="d-block">{{ $position['useful_life'] ?? $asset->useful_life }}</strong></div>
<div class="col-sm-4"><span class="text-600">{{ __('fixed_assets.reports.columns.residual_value') }}</span><strong class="d-block" dir="ltr">{{ $numbers->format($position['residual_value']) }}</strong></div>
<div class="col-12"><span>{{ __('fixed_assets.product.new_cost') }}: </span><output class="js-addition-new-cost fw-bold" dir="ltr">{{ $position['acquisition_cost'] }}</output></div>
<input type="hidden" name="submission_key" value="{{ old('submission_key', (string) \Illuminate\Support\Str::uuid()) }}">
<div class="col-md-4"><label class="form-label" for="addition-movement_date">{{ __('fixed_assets.lifecycle.movement_date') }}</label><input id="addition-movement_date" type="text" class="form-control js-date-picker" name="movement_date" value="{{ old('movement_date', $today) }}" data-date-format="{{ $dates->jsDateFormat() }}" data-locale="{{ app()->getLocale() }}" autocomplete="off" required></div>
<div class="col-md-4"><label class="form-label" for="addition-amount">{{ __('fixed_assets.cycle.addition_value') }} ({{ $asset->currency?->code }} × {{ $asset->exchange_rate }})</label><input id="addition-amount" class="form-control js-number-input" name="amount" value="{{ old('amount') }}" required inputmode="decimal"></div>
<div class="col-md-4"><label class="form-label" for="addition-counter_account_doc_num">{{ __('fixed_assets.attributes.credit_account') }}</label><select id="addition-counter_account_doc_num" class="form-select js-select2-ajax" name="counter_account_doc_num" data-url="{{ route('admin.fixed-assets.select2.credit-accounts') }}" required></select></div>
@unless($asset->currency?->is_main)<div class="col-md-4"><label class="form-label" for="addition-exchange_rate">{{ __('fixed_assets.attributes.exchange_rate') }}</label><input id="addition-exchange_rate" class="form-control js-number-input" name="exchange_rate" value="{{ $asset->exchange_rate }}" required></div>@endunless
@if($asset->depreciation_method === 'units_of_production')<div class="col-md-6"><label class="form-label" for="addition-estimated_remaining_units">{{ __('fixed_assets.cycle.remaining_units') }}</label><input id="addition-estimated_remaining_units" class="form-control js-number-input" name="estimated_remaining_units" value="{{ old('estimated_remaining_units') }}" inputmode="decimal"></div>@endif
@if($asset->depreciation_method === 'units_of_production')<div class="col-md-6"><label class="form-label" for="addition-actual_usage_before_addition">{{ __('fixed_assets.cycle.usage_before_addition') }}</label><input id="addition-actual_usage_before_addition" class="form-control js-number-input" name="actual_usage_before_addition" value="{{ old('actual_usage_before_addition') }}" inputmode="decimal" required><small class="text-muted">{{ __('fixed_assets.cycle.usage_before_hint') }}</small></div>@endif
<div class="col-12"><label class="form-label" for="addition-description">{{ __('fixed_assets.attributes.description') }}</label><textarea id="addition-description" class="form-control" name="description" required>{{ old('description') }}</textarea></div>
@if(in_array($asset->depreciation_method, ['straight_line', 'double_declining_balance', 'sum_of_years_digits'], true))<div class="col-md-6"><label class="form-label" for="addition-revised_useful_life">{{ __('fixed_assets.cycle.revised_life') }}</label><input id="addition-revised_useful_life" class="form-control js-number-input" name="revised_useful_life" value="{{ old('revised_useful_life') }}" inputmode="decimal"></div>@endif
<div class="col-md-6"><label class="form-label" for="addition-revised_residual_value">{{ __('fixed_assets.cycle.revised_residual') }}</label><input id="addition-revised_residual_value" class="form-control js-number-input" name="revised_residual_value" value="{{ old('revised_residual_value') }}" inputmode="decimal"></div>
<div class="col-12"><label class="form-label" for="addition-notes">{{ __('fixed_assets.attributes.notes') }}</label><textarea id="addition-notes" class="form-control" name="notes"></textarea></div>
<div class="col-12"><button class="btn btn-success" type="submit">{{ __('fixed_assets.cycle.post') }}</button></div>
</form></div>
</div></div></div>
@endcan @endif

@if($canTransact) @can('fixed_assets.custody.post')
<div class="modal fade" id="custody-modal" tabindex="-1" aria-labelledby="custody-title" aria-hidden="true"><div class="modal-dialog modal-lg modal-dialog-scrollable modal-dialog-centered"><div class="modal-content">
<div class="modal-header"><h5 class="modal-title" id="custody-title">{{ __('fixed_assets.cycle.custody') }} — {{ $asset->doc_num }}</h5><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="{{ __('common.actions.close') }}"></button></div>
<div class="modal-body"><form method="POST" action="{{ route('admin.fixed-assets.movements.custody', $asset) }}" class="row g-3 js-custody-form" data-current-custodian="{{ $custody?->destinationCustodian?->doc_num }}">@csrf
<input type="hidden" name="_workflow" value="custody"><div class="col-12 alert alert-info">{{ __('fixed_assets.cycle.current_custodian') }}: {{ $custody?->destinationCustodian?->full_name ?: __('common.empty_value') }}</div>
<div class="col-md-4"><label class="form-label" for="custody-movement_date">{{ __('fixed_assets.lifecycle.movement_date') }}</label><input id="custody-movement_date" type="text" class="form-control js-date-picker" name="movement_date" value="{{ old('movement_date', $today) }}" data-date-format="{{ $dates->jsDateFormat() }}" data-locale="{{ app()->getLocale() }}" autocomplete="off" required></div>
<div class="col-md-8"><label class="form-label" for="custody-custodian_doc_num">{{ __('fixed_assets.cycle.to_custodian') }}</label><select id="custody-custodian_doc_num" class="form-select" name="custodian_doc_num"><option value="">{{ __('fixed_assets.cycle.return_custody') }}</option>@foreach($custodians as $employee)<option value="{{ $employee->doc_num }}">{{ $employee->doc_num }} / {{ $employee->full_name }}</option>@endforeach</select></div>
<div class="col-12"><label class="form-label" for="custody-reason">{{ __('fixed_assets.lifecycle.reason') }}</label><textarea id="custody-reason" class="form-control" name="reason" required>{{ old('reason') }}</textarea></div>
<div class="col-12"><label class="form-label" for="custody-notes">{{ __('fixed_assets.attributes.notes') }}</label><textarea id="custody-notes" class="form-control" name="notes"></textarea></div>
<div class="col-12"><button class="btn btn-falcon-primary" type="submit">{{ __('common.actions.save') }}</button></div>
</form></div>
</div></div></div>
@endcan @endif

@if($canTransact) @can('fixed_assets.transfer')
<div class="modal fade" id="transfer-modal" tabindex="-1" aria-labelledby="transfer-title" aria-hidden="true"><div class="modal-dialog modal-lg modal-dialog-scrollable modal-dialog-centered"><div class="modal-content">
<div class="modal-header"><h5 class="modal-title" id="transfer-title">{{ __('fixed_assets.cycle.transfer') }} — {{ $asset->doc_num }}</h5><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="{{ __('common.actions.close') }}"></button></div>
<div class="modal-body"><form method="POST" action="{{ route('admin.fixed-assets.lifecycle.transfer', $asset) }}" class="row g-3 js-transfer-form" id="transfer">@csrf
<input type="hidden" name="_workflow" value="transfer"><div class="col-12 alert alert-info">{{ __('fixed_assets.product.current_location') }}: {{ implode(' / ', array_filter([$asset->branch?->name, $asset->branchHall?->name, $asset->location_address, $asset->costCenter?->codeNameLabel()])) }}</div>
                        <div class="col-md-6"><label class="form-label" for="transfer-movement_date">{{ __('fixed_assets.lifecycle.movement_date') }}</label><input id="transfer-movement_date" class="form-control js-date-picker" name="movement_date" value="{{ old('movement_date', $today) }}" data-date-format="{{ $dates->jsDateFormat() }}" data-locale="{{ app()->getLocale() }}" required></div>
                        <div class="col-md-6"><label class="form-label">{{ __('fixed_assets.lifecycle.destination_branch') }}</label><select class="form-select js-select2-ajax" id="destination_branch_doc_num" name="destination_branch_doc_num" data-url="{{ route('admin.fixed-assets.select2.branches') }}" required>@if($asset->branch)<option value="{{ $asset->branch->doc_num }}" selected>{{ $asset->branch->doc_num }} / {{ $asset->branch->name }}</option>@endif</select></div>
                        <div class="col-md-6"><label class="form-label" for="transfer-destination_branch_hall_uuid">{{ __('fixed_assets.lifecycle.destination_hall') }}</label><select id="transfer-destination_branch_hall_uuid" class="form-select js-select2-ajax" name="destination_branch_hall_uuid" data-url="{{ route('admin.fixed-assets.select2.branch-halls') }}" data-depends-on="#destination_branch_doc_num" data-dependent-param="branch_doc_num" data-allow-clear="true">@if($asset->branchHall)<option value="{{ $asset->branchHall->public_uuid }}" selected>{{ $asset->branchHall->name }}</option>@endif</select></div>
                        <div class="col-md-6"><label class="form-label" for="transfer-destination_cost_center_doc_num">{{ __('fixed_assets.lifecycle.destination_cost_center') }}</label><select id="transfer-destination_cost_center_doc_num" class="form-select js-select2-ajax" name="destination_cost_center_doc_num" data-url="{{ route('admin.fixed-assets.select2.cost-centers') }}" data-allow-clear="true">@if($asset->costCenter)<option value="{{ $asset->costCenter->doc_num }}" selected>{{ $asset->costCenter->codeNameLabel() }}</option>@endif</select></div>
                        <div class="col-12"><label class="form-label" for="transfer-destination_location_address">{{ __('fixed_assets.attributes.location_address') }}</label><input id="transfer-destination_location_address" class="form-control" name="destination_location_address" value="{{ old('destination_location_address', $asset->location_address) }}"></div>
                        <div class="col-12"><label class="form-label" for="transfer-reason">{{ __('fixed_assets.lifecycle.reason') }}</label><textarea id="transfer-reason" class="form-control" name="reason" required>{{ old('reason') }}</textarea></div>
                        <div class="col-12"><label class="form-label" for="transfer-notes">{{ __('fixed_assets.attributes.notes') }}</label><textarea id="transfer-notes" class="form-control" name="notes">{{ old('notes') }}</textarea></div>
                        <div class="col-12"><button class="btn btn-falcon-primary" type="submit">{{ __('fixed_assets.lifecycle.post_transfer') }}</button></div>
                    </form></div>
</div></div></div>
@endcan @endif

@if($canTransact) @can('fixed_assets.dispose')
<div class="modal fade" id="disposal-modal" tabindex="-1" aria-labelledby="disposal-title" aria-hidden="true"><div class="modal-dialog modal-lg modal-dialog-scrollable modal-dialog-centered"><div class="modal-content">
<div class="modal-header"><h5 class="modal-title" id="disposal-title">{{ __('fixed_assets.cycle.disposal') }} — {{ $asset->doc_num }}</h5><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="{{ __('common.actions.close') }}"></button></div>
<div class="modal-body"><form method="POST" action="{{ route('admin.fixed-assets.lifecycle.dispose', $asset) }}" class="row g-3 js-disposal-form" id="disposal" data-account-label="{{ __('journal_entries.attributes.account') }}" data-debit-label="{{ __('journal_entries.attributes.debit') }}" data-credit-label="{{ __('journal_entries.attributes.credit') }}" data-preview-url="{{ route('admin.fixed-assets.lifecycle.disposal-preview', $asset) }}">@csrf
<input type="hidden" name="_workflow" value="disposal">
                        <div class="col-md-6"><label class="form-label" for="disposal-disposal_date">{{ __('fixed_assets.lifecycle.disposal_date') }}</label><input id="disposal-disposal_date" class="form-control js-date-picker" name="disposal_date" value="{{ old('disposal_date', $today) }}" data-date-format="{{ $dates->jsDateFormat() }}" data-locale="{{ app()->getLocale() }}" required></div>
                        <div class="col-md-6"><label class="form-label" for="disposal-disposition_type">{{ __('fixed_assets.lifecycle.disposition_type') }}</label><select id="disposal-disposition_type" class="form-select" name="disposition_type" required>@foreach(\Modules\FixedAssets\Models\FixedAssetDisposal::types() as $type)<option value="{{ $type }}">{{ __('fixed_assets.lifecycle.disposition_types.'.$type) }}</option>@endforeach</select></div>
                        <div class="col-md-6" data-disposal-field="sale"><label class="form-label" for="disposal-proceeds">{{ __('fixed_assets.lifecycle.proceeds') }}</label><input id="disposal-proceeds" class="form-control js-number-input" name="proceeds" value="{{ old('proceeds', '0') }}" inputmode="decimal"></div>
                        <div class="col-md-6" data-disposal-field="sale"><label class="form-label" for="disposal-settlement_path">{{ __('fixed_assets.product.settlement') }}</label><select id="disposal-settlement_path" class="form-select" name="settlement_path"><option value="direct_settlement">{{ __('fixed_assets.product.direct_settlement') }}</option><option value="customer_invoice">{{ __('fixed_assets.product.customer_invoice') }}</option></select></div>
                        <div class="col-md-6" data-disposal-field="invoice"><label class="form-label" for="disposal-tax_rate">{{ __('fixed_assets.product.tax_rate') }}</label><input id="disposal-tax_rate" class="form-control js-number-input" name="tax_rate" value="{{ old('tax_rate', '0') }}" inputmode="decimal"></div>
                        <div class="col-md-6" data-disposal-field="invoice"><label class="form-label" for="disposal-due_date">{{ __('fixed_assets.product.due_date') }}</label><input id="disposal-due_date" class="form-control js-date-picker" name="due_date" value="{{ old('due_date', $today) }}" data-date-format="{{ $dates->jsDateFormat() }}" data-locale="{{ app()->getLocale() }}"></div>
                        <div class="col-md-6" data-disposal-field="direct"><label class="form-label" for="disposal-proceeds_account_doc_num">{{ __('fixed_assets.lifecycle.proceeds_account') }}</label><select id="disposal-proceeds_account_doc_num" class="form-select js-select2-ajax" name="proceeds_account_doc_num" data-url="{{ route('admin.fixed-assets.select2.credit-accounts') }}" data-allow-clear="true"></select></div>
                        <div class="col-md-6" data-disposal-field="sale"><label class="form-label" for="disposal-customer_doc_num">{{ __('fixed_assets.lifecycle.customer') }}</label><select id="disposal-customer_doc_num" class="form-select js-select2-ajax" name="customer_doc_num" data-url="{{ route('admin.fixed-assets.select2.customers') }}" data-allow-clear="true"></select></div>
                        <div class="col-12"><label class="form-label" for="disposal-reason">{{ __('fixed_assets.lifecycle.reason') }}</label><textarea id="disposal-reason" class="form-control" name="reason" required>{{ old('reason') }}</textarea></div>
                        <div class="col-12"><label class="form-label" for="disposal-notes">{{ __('fixed_assets.attributes.notes') }}</label><textarea id="disposal-notes" class="form-control" name="notes">{{ old('notes') }}</textarea></div>
                        <div class="col-md-6"><label class="form-label" for="disposal-disposal_expenses">{{ __('fixed_assets.cycle.disposal_expenses') }}</label><input id="disposal-disposal_expenses" class="form-control js-number-input" name="disposal_expenses" value="{{ old('disposal_expenses', '0') }}"></div>
                        <div class="col-md-6"><label class="form-label" for="disposal-expenses_account_doc_num">{{ __('fixed_assets.cycle.expenses_account') }}</label><select id="disposal-expenses_account_doc_num" class="form-select js-select2-ajax" name="expenses_account_doc_num" data-url="{{ route('admin.fixed-assets.select2.credit-accounts') }}" data-allow-clear="true"></select></div>
                        <div class="col-12"><p class="small text-600">{{ __('fixed_assets.cycle.disposal_policy') }}</p><button type="button" class="btn btn-falcon-primary js-disposal-preview">{{ __('fixed_assets.cycle.preview') }}</button><div class="js-disposal-result mt-2" aria-live="polite"></div></div>
                        <div class="col-12"><button class="btn btn-danger js-disposal-post" type="submit" disabled>{{ __('fixed_assets.lifecycle.post_disposal') }}</button></div>
                    </form></div>
</div></div></div>
@endcan @endif
