<?php

return [
    'self_service' => ['title' => 'Employee Self Service', 'not_linked_title' => 'Account not linked to an employee', 'not_linked_help' => 'Ask HR to link your user account to your employee record.', 'location_help' => 'Your mobile location is captured when the punch is recorded. Allow browser location access.', 'recent_events' => 'Recent Attendance Events'],
    'admin' => ['title' => 'Employee Attendance', 'manual_title' => 'Manual Attendance Event'],
    'states' => ['not_linked' => 'Account not linked', 'not_checked_in' => 'Not checked in yet', 'working' => 'You are checked in', 'on_break' => 'You are on a break', 'inactive' => 'Employee account is inactive', 'company_missing' => 'Employee company is not configured', 'tracking_disabled' => 'Attendance tracking is disabled'],
    'actions' => ['check_in' => 'Check In', 'break_start' => 'Start Break', 'break_end' => 'End Break', 'check_out' => 'Check Out'],
    'labels' => ['employee' => 'Employee', 'from' => 'From', 'to' => 'To', 'status' => 'Status', 'event' => 'Event', 'time' => 'Time', 'reason' => 'Manual entry reason', 'check_in' => 'Check In', 'check_out' => 'Check Out', 'worked' => 'Worked', 'breaks' => 'Breaks', 'minutes' => 'minutes', 'checked_in_at' => 'Checked in since :time', 'not_checked_in' => 'No open work session', 'no_branch' => 'No assigned branch', 'no_events' => 'No attendance events yet.', 'no_sessions' => 'No matching attendance sessions.'],
    'session_status' => ['open' => 'Open', 'closed' => 'Closed'],
    'geofence' => ['inside' => 'Inside branch range', 'outside' => 'Outside branch range', 'poor_accuracy' => 'Poor location accuracy', 'unavailable' => 'Location unavailable', 'unconfigured' => 'Branch location not configured'],
    'messages' => ['employee_account_not_linked' => 'Your account is not linked to an employee record.', 'employee_inactive' => 'The employee record is inactive.', 'employee_company_missing' => 'The employee record is not assigned to a company.', 'tracking_disabled' => 'Attendance tracking is disabled for this employee.', 'already_checked_in' => 'An attendance session is already open.', 'no_open_session' => 'There is no open attendance session for this action.', 'event_before_previous' => 'The event time cannot be before the previous event.', 'illegal_transition' => 'This action is not allowed in the current state.', 'idempotency_conflict' => 'This request identifier was already used for another attendance action.', 'location_rejected' => 'The punch could not be recorded because the location is outside the branch range or inaccurate.', 'punch_recorded' => 'Attendance event recorded.', 'manual_recorded' => 'Manual attendance event recorded.'],
    'report' => [
        'description' => 'Attendance sessions, location decisions, working time, breaks and shift variances.',
        'table_title' => 'Attendance details',
        'summary' => ['sessions' => 'Sessions', 'employees' => 'Employees', 'open' => 'Open now', 'worked' => 'Worked minutes', 'breaks' => 'Break minutes', 'late' => 'Late minutes', 'early' => 'Early leave', 'overtime' => 'Overtime'],
        'columns' => ['work_date' => 'Work date', 'employee_code' => 'Employee code', 'employee' => 'Employee', 'branch' => 'Branch', 'shift' => 'Shift', 'status' => 'Status', 'check_in' => 'Check in', 'check_out' => 'Check out', 'worked_minutes' => 'Worked minutes', 'break_minutes' => 'Break minutes', 'events' => 'Events', 'location_result' => 'Location result'],
    ],
    'javascript' => ['locating' => 'Locating you and recording the event…', 'failed' => 'The event could not be recorded. Try again.', 'saved' => 'Event recorded.', 'checkedInAt' => 'Checked in since :time', 'notCheckedIn' => 'No open work session', 'states' => ['not_checked_in' => 'Not checked in yet', 'working' => 'You are checked in', 'on_break' => 'You are on a break', 'inactive' => 'Employee account is inactive', 'company_missing' => 'Employee company is not configured', 'tracking_disabled' => 'Attendance tracking is disabled']],
];
