<?php

return [
    'types' => [
        'account_ledger' => 'Account Ledger',
        'customer_statement' => 'Customer Statement',
        'supplier_statement' => 'Supplier Statement',
    ],
    'filters' => [
        'account_doc_num' => 'Account',
        'customer_doc_num' => 'Customer',
        'supplier_doc_num' => 'Supplier',
        'from_date' => 'From date',
        'to_date' => 'To date',
        'branch' => 'Branch',
        'cost_center' => 'Cost center',
        'all' => 'All',
    ],
    'actions' => ['run' => 'Run report'],
    'summary' => [
        'opening' => 'Opening balance',
        'period' => 'Period movement',
        'ending' => 'Ending balance',
    ],
    'columns' => [
        'date' => 'Date',
        'source_type' => 'Source type',
        'document' => 'Document',
        'reference' => 'Reference',
        'description' => 'Description',
        'cost_center' => 'Cost center',
        'branch' => 'Branch',
        'debit' => 'Debit',
        'credit' => 'Credit',
        'running_debit' => 'Running debit',
        'running_credit' => 'Running credit',
    ],
    'sources' => [
        'manual' => 'Manual journal',
        'opening_balance' => 'Opening balance',
        'purchase_invoice' => 'Purchase invoice',
    ],
    'audit' => [
        'generated_by' => 'Generated by',
        'generated_at' => 'Generated at',
    ],
    'messages' => [
        'posted_source_only' => 'This report is calculated from posted journal lines in the current operating company and financial period.',
        'no_movements' => 'No posted movements match the selected filters.',
        'operating_context_required' => 'Select an operating company and financial period first.',
        'date_outside_period' => 'The report date range must be inside the selected financial period.',
        'filter_invalid' => 'The selected filter is not available in the operating company.',
        'partner_account_missing' => 'The selected business partner does not have a linked accounting account.',
    ],
];
