<?php

return [
    'title' => 'Trial Balance',
    'actions' => [
        'run' => 'Run report',
    ],
    'filters' => [
        'from_date' => 'From date',
        'to_date' => 'To date',
        'branch' => 'Branch',
        'cost_center' => 'Cost center',
        'include_zero' => 'Include accounts with no balance or movement',
        'all' => 'All',
    ],
    'columns' => [
        'account_code' => 'Account code',
        'account_name' => 'Account name',
        'status' => 'Status',
        'opening' => 'Opening balance',
        'period' => 'Period movement',
        'ending' => 'Ending balance',
        'opening_debit' => 'Debit',
        'opening_credit' => 'Credit',
        'period_debit' => 'Debit',
        'period_credit' => 'Credit',
        'ending_debit' => 'Debit',
        'ending_credit' => 'Credit',
    ],
    'status' => [
        'active' => 'Active',
        'inactive' => 'Inactive / historical',
    ],
    'audit' => [
        'generated_by' => 'Generated by',
        'generated_at' => 'Generated at',
    ],
    'messages' => [
        'posted_source_only' => 'Calculated exclusively from posted journal lines in the operating company. Opening balances include posted entries before the selected range.',
        'balanced' => 'Balanced',
        'unbalanced' => 'Out of balance',
        'no_accounts' => 'No posted balances or movements match the selected filters.',
        'operating_context_required' => 'Select an operating company and financial period first.',
        'date_outside_period' => 'The report date range must be inside the selected financial period.',
        'filter_invalid' => 'The selected filter is not available in the operating company.',
    ],
    'total' => 'Grand total',
];
