@extends('layouts.app')

@section('title', __('Inventory Operational Reports'))

@section('content')
<div class="card mb-3"><div class="card-header"><h5 class="mb-0">{{ __('Stock Balance by Status and Location') }}</h5></div><div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>{{ __('Store') }}</th><th>{{ __('Location') }}</th><th>{{ __('Product') }}</th><th>{{ __('Status') }}</th><th>{{ __('Batch') }}</th><th>{{ __('On hand') }}</th><th>{{ __('Value') }}</th></tr></thead><tbody>@foreach($balances as $row)<tr><td>{{ $row->branchStore?->name }}</td><td>{{ $row->warehouseLocation?->code }}</td><td>{{ $row->product?->doc_num }} — {{ $row->product?->name }}</td><td>{{ $row->stock_status }}</td><td>{{ $row->batch_lot }}</td><td>{{ $row->on_hand }}</td><td>{{ $row->inventory_value }}</td></tr>@endforeach</tbody></table></div></div>
<div class="card"><div class="card-header"><h5 class="mb-0">{{ __('Active Reservations') }}</h5></div><div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>{{ __('Product') }}</th><th>{{ __('Store') }}</th><th>{{ __('Sales order') }}</th><th>{{ __('Production order') }}</th><th>{{ __('Run') }}</th><th>{{ __('Remaining') }}</th></tr></thead><tbody>@foreach($reservations as $row)<tr><td>{{ $row->product?->name }}</td><td>{{ $row->branchStore?->name }}</td><td>{{ $row->order?->doc_num }}</td><td>{{ $row->productionOrder?->doc_num }}</td><td>{{ $row->productionRun?->run_number }}</td><td>{{ $row->remaining_quantity }}</td></tr>@endforeach</tbody></table></div></div>
<div class="card mt-3"><div class="card-header"><h5 class="mb-0">{{ __('Inventory Movement Ledger') }}</h5></div><div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>{{ __('Date') }}</th><th>{{ __('Source') }}</th><th>{{ __('Type') }}</th><th>{{ __('Store / status') }}</th><th>{{ __('Product') }}</th><th>{{ __('In') }}</th><th>{{ __('Out') }}</th><th>{{ __('Run') }}</th></tr></thead><tbody>@foreach($movements as $row)<tr><td>{{ $row->transaction_date?->toDateString() }}</td><td>{{ $row->source_doc_num }}</td><td>{{ $row->transaction_type }}</td><td>{{ $row->branchStore?->name }} / {{ $row->stock_status }}</td><td>{{ $row->product?->doc_num }} — {{ $row->product?->name }}</td><td>{{ $row->quantity_in }}</td><td>{{ $row->quantity_out }}</td><td>{{ $row->productionRun?->run_number }}</td></tr>@endforeach</tbody></table></div></div>
@endsection
