@extends('layouts.app')

@section('title', __('Inventory Operational Reports'))

@section('content')
<div class="production-mobile-workflow" data-client-report-tables>
<div class="d-flex justify-content-between align-items-center mb-3">
    <div><h4 class="mb-0">{{ __('Inventory Operational Reports') }}</h4></div>
    @can('inventory.reports.export')<div class="d-flex gap-2"><a class="btn btn-outline-success" href="{{ route('admin.inventory.reports.export', request()->query()) }}">{{ __('Export XLSX') }}</a><a class="btn btn-outline-secondary" target="_blank" href="{{ route('admin.inventory.reports.print', request()->query()) }}">{{ __('Print PDF') }}</a></div>@endcan
</div>

<form class="card card-body mb-3" method="GET">
    <div class="row g-2 align-items-end">
        <div class="col-md-3"><label class="form-label" for="inventory-report-as-of">{{ __('As of') }}</label><x-forms.date-input id="inventory-report-as-of" name="as_of" :value="request('as_of', today()->toDateString())" /></div>
        <div class="col-md-3"><label class="form-label" for="inventory-report-batch">{{ __('Batch / lot') }}</label><x-forms.input class="form-control" id="inventory-report-batch" name="batch_lot" value="{{ request('batch_lot') }}" /></div>
        <div class="col-md-3"><label class="form-label" for="inventory-report-expiry">{{ __('Expiry horizon') }}</label><x-forms.select class="form-select" id="inventory-report-expiry" name="expiry_within_days">@foreach([30, 60, 90] as $days)<option value="{{ $days }}" @selected((int) request('expiry_within_days', 90) === $days)>{{ trans_choice('inventory.reports.day_count', $days, ['count' => $days]) }}</option>@endforeach</x-forms.select></div>
        <div class="col-md-3"><button class="btn btn-primary w-100" type="submit">{{ __('Apply filters') }}</button></div>
    </div>
</form>

<div class="card mb-3">
    <div class="card-header"><h5 class="mb-0">{{ __('Stock Balance by Status and Location') }}</h5></div>
    <div class="table-responsive"><table class="table table-sm mb-0">
        <thead><tr><th>{{ __('Store') }}</th><th>{{ __('Location') }}</th><th>{{ __('Product') }}</th><th>{{ __('Status') }}</th><th>{{ __('Batch') }}</th><th class="text-end">{{ __('On hand') }}</th>@if($canViewFinancial)<th>{{ __('Value') }}</th><th class="text-end">{{ __('Unvalued receipt quantity') }}</th><th>{{ __('Valuation status') }}</th>@endif</tr></thead>
        <tbody>@forelse($balances as $row)<tr><td>{{ $row->branchStore?->name }}</td><td>{{ $row->warehouseLocation?->code }}</td><td>{{ $row->product?->doc_num }} — {{ $row->product?->name }}</td><td>{{ __('inventory.movements.stock_statuses.'.$row->stock_status) }}</td><td>{{ $row->batch_lot }}</td><td class="text-end">{{ $numbers->format($row->on_hand) }}</td>@if($canViewFinancial)<td class="text-end">{{ $row->inventory_value }}</td><td class="text-end">{{ $numbers->format($row->unvalued_receipt_quantity) }}</td><td>{{ (float) $row->unvalued_receipt_quantity > 0 ? __('Pending Supplier Invoice valuation') : __('Valued') }}</td>@endif</tr>@empty<tr><td colspan="{{ $canViewFinancial ? 9 : 6 }}" class="text-center text-muted">{{ __('No stock balances match the filters.') }}</td></tr>@endforelse</tbody>
        <tfoot><tr class="fw-bold"><td colspan="5">{{ __('Total') }}</td><td class="text-end">{{ $numbers->format($reportTotals['on_hand']) }}</td>@if($canViewFinancial)<td class="text-end">{{ $reportTotals['inventory_value'] }}</td><td class="text-end">{{ $numbers->format($reportTotals['unvalued_receipt_quantity']) }}</td><td></td>@endif</tr></tfoot>
    </table></div>
</div>

<div class="d-none" data-report-count="low_stock">{{ $reorder->count() }}</div>
<div class="card mb-3"><div class="card-header"><h5 class="mb-0">{{ __('Available vs Reserved and Reorder Shortage') }}</h5></div><div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>{{ __('Product') }}</th><th>{{ __('Store') }}</th><th class="text-end">{{ __('On hand') }}</th><th class="text-end">{{ __('Reserved') }}</th><th class="text-end">{{ __('Available') }}</th><th class="text-end">{{ __('Reorder point') }}</th><th class="text-end">{{ __('Shortage') }}</th><th class="text-end">{{ __('Production demand') }}</th></tr></thead><tbody>@forelse($reorder as $row)<tr><td>{{ $row->product?->doc_num }} — {{ $row->product?->name }} ({{ $row->product?->unit?->name }})</td><td>{{ $row->branchStore?->name }}</td><td class="text-end">{{ $numbers->format($row->physical) }}</td><td class="text-end">{{ $numbers->format($row->reserved) }}</td><td class="text-end">{{ $numbers->format($row->available) }}</td><td class="text-end">{{ $numbers->format($row->reorder_point) }}</td><td class="text-end text-danger fw-bold">{{ $numbers->format($row->shortage) }}</td><td class="text-end">{{ $numbers->format($row->production_demand) }}</td></tr>@empty<tr><td colspan="8" class="text-center text-muted">{{ __('inventory.reports.no_reorder_shortages') }}</td></tr>@endforelse</tbody></table></div></div>

<div class="card mb-3"><div class="card-header"><h5 class="mb-0">{{ __('Active Reservations') }}</h5></div><div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>{{ __('Product') }}</th><th>{{ __('Store') }}</th><th>{{ __('Sales order') }}</th><th>{{ __('Production order') }}</th><th>{{ __('Run') }}</th><th class="text-end">{{ __('Remaining') }}</th></tr></thead><tbody>@forelse($reservations as $row)<tr><td>{{ $row->product?->name }}</td><td>{{ $row->branchStore?->name }}</td><td>{{ $row->order?->doc_num }}</td><td>{{ $row->productionOrder?->doc_num }}</td><td>{{ $row->productionRun?->run_number }}</td><td class="text-end">{{ $numbers->format($row->remaining_quantity) }}</td></tr>@empty<tr><td colspan="6" class="text-center text-muted">{{ __('No active reservations.') }}</td></tr>@endforelse</tbody></table></div></div>

<div class="card mb-3"><div class="card-header"><h5 class="mb-0">{{ __('Inventory Movement Ledger / Stock Card') }}</h5></div><div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>{{ __('Date') }}</th><th>{{ __('Source') }}</th><th>{{ __('Type') }}</th><th>{{ __('Store / status') }}</th><th>{{ __('Product') }}</th><th class="text-end">{{ __('In') }}</th><th class="text-end">{{ __('Out') }}</th><th>{{ __('Run') }}</th></tr></thead><tbody>@forelse($movements as $row)<tr><td>{{ $row->transaction_date?->toDateString() }}</td><td>@if($row->sourceDocument instanceof \Modules\Inventory\Models\InventoryDocument) @can('inventory.documents.view')<a href="{{ route('admin.inventory.documents.show', $row->sourceDocument) }}">{{ $row->source_doc_num }}</a>@else{{ $row->source_doc_num }}@endcan @elseif($row->sourceDocument instanceof \Modules\Inventory\Models\OpeningStock) @can('inventory.opening_stocks.view')<a href="{{ route('admin.inventory.opening-stocks.show', $row->sourceDocument) }}">{{ $row->source_doc_num }}</a>@else{{ $row->source_doc_num }}@endcan @elseif($row->source_type === \Modules\Inventory\Models\UnpricedInventoryReceipt::class)
@can('purchases.goods_receipt_notes.view')<a href="{{ route('admin.purchases.goods-receipt-notes.show', $row->source_doc_num) }}">{{ $row->source_doc_num }}</a>@else{{ $row->source_doc_num }}@endcan
@elseif($row->source_type === \Modules\Purchases\Models\PurchaseReturn::class)
@can('purchases.purchase_returns.view')<a href="{{ route('admin.purchases.purchase-returns.show', $row->source_doc_num) }}">{{ $row->source_doc_num }}</a>@else{{ $row->source_doc_num }}@endcan
@else{{ $row->source_doc_num }}@endif</td><td>{{ __('inventory.movements.types.'.$row->transaction_type) }}</td><td>{{ $row->branchStore?->name }} / {{ __('inventory.movements.stock_statuses.'.$row->stock_status) }}</td><td>{{ $row->product?->doc_num }} — {{ $row->product?->name }}</td><td class="text-end">{{ $numbers->format($row->quantity_in) }}</td><td class="text-end">{{ $numbers->format($row->quantity_out) }}</td><td>@if($row->productionRun) @can('production.runs.view')<a href="{{ route('admin.production.runs.show', $row->productionRun) }}">{{ $row->productionRun->run_number }}</a>@else{{ $row->productionRun->run_number }}@endcan @endif</td></tr>@empty<tr><td colspan="8" class="text-center text-muted">{{ __('No movements match the filters.') }}</td></tr>@endforelse</tbody><tfoot><tr class="fw-bold"><td colspan="5">{{ __('Total') }}</td><td class="text-end">{{ $numbers->format($reportTotals['quantity_in']) }}</td><td class="text-end">{{ $numbers->format($reportTotals['quantity_out']) }}</td><td></td></tr></tfoot></table></div></div>

<div class="row g-3 mb-3">
    <div class="col-xl-6"><div class="card h-100"><div class="card-header"><h5 class="mb-0">{{ __('QC / Quarantine / Rework') }}</h5></div><div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>{{ __('Product') }}</th><th>{{ __('Store') }}</th><th>{{ __('Status') }}</th><th>{{ __('Batch') }}</th><th class="text-end">{{ __('On hand') }}</th></tr></thead><tbody>@forelse($qualityBalances as $row)<tr><td>{{ $row->product?->name }}</td><td>{{ $row->branchStore?->name }}</td><td>{{ __('inventory.movements.stock_statuses.'.$row->stock_status) }}</td><td>{{ $row->batch_lot }}</td><td class="text-end">{{ $numbers->format($row->on_hand) }}</td></tr>@empty<tr><td colspan="5" class="text-center text-muted">{{ __('No quality-held stock.') }}</td></tr>@endforelse</tbody></table></div></div></div>
    <div class="col-xl-6"><div class="card h-100"><div class="card-header"><h5 class="mb-0">{{ __('Damage and Scrap Movements') }}</h5></div><div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>{{ __('Date') }}</th><th>{{ __('Document') }}</th><th>{{ __('Product') }}</th><th>{{ __('Type') }}</th><th class="text-end">{{ __('Out') }}</th></tr></thead><tbody>@forelse($damageAndScrap as $row)<tr><td>{{ $row->transaction_date?->toDateString() }}</td><td>{{ $row->source_doc_num }}</td><td>{{ $row->product?->name }}</td><td>{{ __('inventory.movements.types.'.$row->transaction_type) }}</td><td class="text-end">{{ $numbers->format($row->quantity_out) }}</td></tr>@empty<tr><td colspan="5" class="text-center text-muted">{{ __('No damage or scrap movements.') }}</td></tr>@endforelse</tbody></table></div></div></div>
</div>

<div class="card mb-3"><div class="card-header"><h5 class="mb-0">{{ __('Stock Count Variances') }}</h5></div><div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>{{ __('Count') }}</th><th>{{ __('Date') }}</th><th>{{ __('Store') }}</th><th>{{ __('Product') }}</th><th class="text-end">{{ __('System') }}</th><th class="text-end">{{ __('Physical') }}</th><th class="text-end">{{ __('Variance') }}</th><th>{{ __('Reason') }}</th></tr></thead><tbody>@forelse($stockCountVariances as $row)<tr><td>{{ $row->stockCount?->doc_num }}</td><td>{{ $row->stockCount?->count_date?->toDateString() }}</td><td>{{ $row->stockCount?->branchStore?->name }}</td><td>{{ $row->product?->name }}</td><td class="text-end">{{ $numbers->format($row->system_quantity) }}</td><td class="text-end">{{ $numbers->format($row->physical_quantity) }}</td><td class="text-end">{{ $numbers->format($row->variance_quantity) }}</td><td>{{ $row->variance_reason }}</td></tr>@empty<tr><td colspan="8" class="text-center text-muted">{{ __('No stock count variances.') }}</td></tr>@endforelse</tbody></table></div></div>

@if($glReconciliation !== null)
<div class="card mb-3"><div class="card-header"><h5 class="mb-0">{{ __('Inventory / Production to General Ledger Reconciliation') }}</h5></div><div class="table-responsive"><table class="table table-sm table-bordered mb-0"><thead><tr><th>{{ __('Control') }}</th><th class="text-end">{{ __('Subledger') }}</th><th class="text-end">{{ __('General Ledger') }}</th><th class="text-end">{{ __('Difference') }}</th><th>{{ __('Status') }}</th></tr></thead><tbody>@foreach($glReconciliation as $row)<tr><td>{{ $row['label'] }}</td><td class="text-end">{{ $row['subledger'] }}</td><td class="text-end">{{ $row['gl'] }}</td><td class="text-end">{{ $row['difference'] }}</td><td><span class="badge bg-{{ $row['status'] === 'reconciled' ? 'success' : 'danger' }}">{{ __(str($row['status'])->replace('_', ' ')->title()->toString()) }}</span></td></tr>@endforeach</tbody></table></div></div>
@elseif($glReconciliationUnavailableReason !== null)
<div class="card mb-3"><div class="card-header"><h5 class="mb-0">{{ __('Inventory / Production to General Ledger Reconciliation') }}</h5></div><div class="card-body"><div class="alert alert-warning mb-0" role="alert">{{ $glReconciliationUnavailableReason }}</div></div></div>
@endif

<div class="card mb-3"><div class="card-header"><h5 class="mb-0">{{ __('Inventory Aging by Receipt Layer') }}</h5></div><div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>{{ __('Receipt date') }}</th><th>{{ __('Age / bucket') }}</th><th>{{ __('Receipt source') }}</th><th>{{ __('Store / location') }}</th><th>{{ __('Product') }}</th><th>{{ __('Status / batch') }}</th><th class="text-end">{{ __('Remaining quantity') }}</th>@if($canViewFinancial)<th class="text-end">{{ __('Remaining value') }}</th>@endif</tr></thead><tbody>@forelse($agingLayers as $layer)<tr><td>{{ $layer->original_receipt_date?->toDateString() }}</td><td>{{ $layer->age_days }} / {{ $layer->age_bucket }}</td><td>{{ $layer->source_doc_num }}</td><td>{{ $layer->branchStore?->name }} / {{ $layer->warehouseLocation?->code }}</td><td>{{ $layer->product?->doc_num }} — {{ $layer->product?->name }}</td><td>{{ __('inventory.movements.stock_statuses.'.$layer->stock_status) }} / {{ $layer->batch_lot }}</td><td class="text-end">{{ $numbers->format($layer->remaining_quantity) }}</td>@if($canViewFinancial)<td class="text-end">{{ $layer->remaining_value }}</td>@endif</tr>@empty<tr><td colspan="{{ $canViewFinancial ? 8 : 7 }}" class="text-center text-muted">{{ __('No receipt layers match the filters.') }}</td></tr>@endforelse</tbody><tfoot><tr class="fw-bold"><td colspan="6">{{ __('Total') }}</td><td class="text-end">{{ $numbers->format($reportTotals['aging_quantity']) }}</td>@if($canViewFinancial)<td class="text-end">{{ $reportTotals['aging_value'] }}</td>@endif</tr></tfoot></table></div></div>

<div class="card mb-3"><div class="card-header"><h5 class="mb-0">{{ __('Expired and Expiring Inventory') }}</h5></div><div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>{{ __('State') }}</th><th>{{ __('Expiry date') }}</th><th>{{ __('Days to expiry') }}</th><th>{{ __('Batch') }}</th><th>{{ __('Product') }}</th><th>{{ __('Store / location') }}</th><th>{{ __('Status') }}</th><th class="text-end">{{ __('Remaining quantity') }}</th></tr></thead><tbody>@forelse($expiryLayers as $layer)<tr><td><span class="badge bg-{{ $layer->expiry_state === 'expired' ? 'danger' : 'warning' }}">{{ __($layer->expiry_state === 'expired' ? 'Expired' : 'Expiring') }}</span></td><td>{{ $layer->expiry_date?->toDateString() }}</td><td>{{ $layer->days_to_expiry }}</td><td>{{ $layer->batch_lot }}</td><td>{{ $layer->product?->doc_num }} — {{ $layer->product?->name }}</td><td>{{ $layer->branchStore?->name }} / {{ $layer->warehouseLocation?->code }}</td><td>{{ __('inventory.movements.stock_statuses.'.$layer->stock_status) }}</td><td class="text-end">{{ $numbers->format($layer->remaining_quantity) }}</td></tr>@empty<tr><td colspan="8" class="text-center text-muted">{{ __('No expired or expiring receipt layers match the selected horizon.') }}</td></tr>@endforelse</tbody><tfoot><tr class="fw-bold"><td colspan="7">{{ __('Total') }}</td><td class="text-end">{{ $numbers->format($reportTotals['expiry_quantity']) }}</td></tr></tfoot></table></div></div>
</div>
@endsection

@push('styles')<link rel="stylesheet" href="{{ app(\Modules\Core\Services\AssetVersionService::class)->url('assets/css/modules/Production/execution.css') }}">@endpush
@push('scripts')<script src="{{ app(\Modules\Core\Services\AssetVersionService::class)->url('assets/js/modules/Production/execution.js') }}"></script>@endpush
