@extends('layouts.app')

@section('title', __('Inventory Operational Reports'))

@section('content')
<div class="d-flex justify-content-between align-items-center mb-3">
    <div><h4 class="mb-1">{{ __('Inventory Operational Reports') }}</h4><div class="text-muted">{{ __('One ledger-backed dataset powers this screen, XLSX, and PDF.') }}</div></div>
    @can('inventory.reports.export')<div class="d-flex gap-2"><a class="btn btn-outline-success" href="{{ route('admin.inventory.reports.export', request()->query()) }}">{{ __('Export XLSX') }}</a><a class="btn btn-outline-secondary" target="_blank" href="{{ route('admin.inventory.reports.print', request()->query()) }}">{{ __('Print PDF') }}</a></div>@endcan
</div>

<div class="card mb-3">
    <div class="card-header"><h5 class="mb-0">{{ __('Stock Balance by Status and Location') }}</h5></div>
    <div class="table-responsive"><table class="table table-sm mb-0">
        <thead><tr><th>{{ __('Store') }}</th><th>{{ __('Location') }}</th><th>{{ __('Product') }}</th><th>{{ __('Status') }}</th><th>{{ __('Batch') }}</th><th class="text-end">{{ __('On hand') }}</th>@if($canViewFinancial)<th>{{ __('Value') }}</th><th class="text-end">{{ __('Unvalued receipt quantity') }}</th><th>{{ __('Valuation status') }}</th>@endif</tr></thead>
        <tbody>@forelse($balances as $row)<tr><td>{{ $row->branchStore?->name }}</td><td>{{ $row->warehouseLocation?->code }}</td><td>{{ $row->product?->doc_num }} — {{ $row->product?->name }}</td><td>{{ $row->stock_status }}</td><td>{{ $row->batch_lot }}</td><td class="text-end">{{ $row->on_hand }}</td>@if($canViewFinancial)<td class="text-end">{{ $row->inventory_value }}</td><td class="text-end">{{ $row->unvalued_receipt_quantity }}</td><td>{{ (float) $row->unvalued_receipt_quantity > 0 ? __('Pending Supplier Invoice valuation') : __('Valued') }}</td>@endif</tr>@empty<tr><td colspan="{{ $canViewFinancial ? 9 : 6 }}" class="text-center text-muted">{{ __('No stock balances match the filters.') }}</td></tr>@endforelse</tbody>
        <tfoot><tr class="fw-bold"><td colspan="5">{{ __('Total') }}</td><td class="text-end">{{ $reportTotals['on_hand'] }}</td>@if($canViewFinancial)<td class="text-end">{{ $reportTotals['inventory_value'] }}</td><td class="text-end">{{ $reportTotals['unvalued_receipt_quantity'] }}</td><td></td>@endif</tr></tfoot>
    </table></div>
</div>

<div class="card mb-3"><div class="card-header"><h5 class="mb-0">{{ __('Available vs Reserved and Reorder Shortage') }}</h5></div><div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>{{ __('Product') }}</th><th>{{ __('Store') }}</th><th class="text-end">{{ __('On hand') }}</th><th class="text-end">{{ __('Reserved') }}</th><th class="text-end">{{ __('Available') }}</th><th class="text-end">{{ __('Reorder point') }}</th><th class="text-end">{{ __('Shortage') }}</th><th class="text-end">{{ __('Production demand') }}</th></tr></thead><tbody>@forelse($reorder as $row)<tr><td>{{ $row->product?->doc_num }} — {{ $row->product?->name }}</td><td>{{ $row->branchStore?->name }}</td><td class="text-end">{{ $row->on_hand }}</td><td class="text-end">{{ $row->reserved }}</td><td class="text-end">{{ $row->available }}</td><td class="text-end">{{ $row->reorder_point }}</td><td class="text-end text-danger fw-bold">{{ $row->shortage }}</td><td class="text-end">{{ $row->production_demand }}</td></tr>@empty<tr><td colspan="8" class="text-center text-muted">{{ __('No reorder shortages or production demand.') }}</td></tr>@endforelse</tbody></table></div></div>

<div class="card mb-3"><div class="card-header"><h5 class="mb-0">{{ __('Active Reservations') }}</h5></div><div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>{{ __('Product') }}</th><th>{{ __('Store') }}</th><th>{{ __('Sales order') }}</th><th>{{ __('Production order') }}</th><th>{{ __('Run') }}</th><th class="text-end">{{ __('Remaining') }}</th></tr></thead><tbody>@forelse($reservations as $row)<tr><td>{{ $row->product?->name }}</td><td>{{ $row->branchStore?->name }}</td><td>{{ $row->order?->doc_num }}</td><td>{{ $row->productionOrder?->doc_num }}</td><td>{{ $row->productionRun?->run_number }}</td><td class="text-end">{{ $row->remaining_quantity }}</td></tr>@empty<tr><td colspan="6" class="text-center text-muted">{{ __('No active reservations.') }}</td></tr>@endforelse</tbody></table></div></div>

<div class="card mb-3"><div class="card-header"><h5 class="mb-0">{{ __('Inventory Movement Ledger / Stock Card') }}</h5></div><div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>{{ __('Date') }}</th><th>{{ __('Source') }}</th><th>{{ __('Type') }}</th><th>{{ __('Store / status') }}</th><th>{{ __('Product') }}</th><th class="text-end">{{ __('In') }}</th><th class="text-end">{{ __('Out') }}</th><th>{{ __('Run') }}</th></tr></thead><tbody>@forelse($movements as $row)<tr><td>{{ $row->transaction_date?->toDateString() }}</td><td>@if($row->sourceDocument instanceof \Modules\Inventory\Models\InventoryDocument) @can('inventory.documents.view')<a href="{{ route('admin.inventory.documents.show', $row->sourceDocument) }}">{{ $row->source_doc_num }}</a>@else{{ $row->source_doc_num }}@endcan @elseif($row->sourceDocument instanceof \Modules\Inventory\Models\OpeningStock) @can('inventory.opening_stocks.view')<a href="{{ route('admin.inventory.opening-stocks.show', $row->sourceDocument) }}">{{ $row->source_doc_num }}</a>@else{{ $row->source_doc_num }}@endcan @else{{ $row->source_doc_num }}@endif</td><td>{{ $row->transaction_type }}</td><td>{{ $row->branchStore?->name }} / {{ $row->stock_status }}</td><td>{{ $row->product?->doc_num }} — {{ $row->product?->name }}</td><td class="text-end">{{ $row->quantity_in }}</td><td class="text-end">{{ $row->quantity_out }}</td><td>@if($row->productionRun) @can('production.runs.view')<a href="{{ route('admin.production.runs.show', $row->productionRun) }}">{{ $row->productionRun->run_number }}</a>@else{{ $row->productionRun->run_number }}@endcan @endif</td></tr>@empty<tr><td colspan="8" class="text-center text-muted">{{ __('No movements match the filters.') }}</td></tr>@endforelse</tbody><tfoot><tr class="fw-bold"><td colspan="5">{{ __('Total') }}</td><td class="text-end">{{ $reportTotals['quantity_in'] }}</td><td class="text-end">{{ $reportTotals['quantity_out'] }}</td><td></td></tr></tfoot></table></div></div>

<div class="row g-3 mb-3">
    <div class="col-xl-6"><div class="card h-100"><div class="card-header"><h5 class="mb-0">{{ __('QC / Quarantine / Rework') }}</h5></div><div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>{{ __('Product') }}</th><th>{{ __('Store') }}</th><th>{{ __('Status') }}</th><th>{{ __('Batch') }}</th><th class="text-end">{{ __('On hand') }}</th></tr></thead><tbody>@forelse($qualityBalances as $row)<tr><td>{{ $row->product?->name }}</td><td>{{ $row->branchStore?->name }}</td><td>{{ $row->stock_status }}</td><td>{{ $row->batch_lot }}</td><td class="text-end">{{ $row->on_hand }}</td></tr>@empty<tr><td colspan="5" class="text-center text-muted">{{ __('No quality-held stock.') }}</td></tr>@endforelse</tbody></table></div></div></div>
    <div class="col-xl-6"><div class="card h-100"><div class="card-header"><h5 class="mb-0">{{ __('Damage and Scrap Movements') }}</h5></div><div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>{{ __('Date') }}</th><th>{{ __('Document') }}</th><th>{{ __('Product') }}</th><th>{{ __('Type') }}</th><th class="text-end">{{ __('Out') }}</th></tr></thead><tbody>@forelse($damageAndScrap as $row)<tr><td>{{ $row->transaction_date?->toDateString() }}</td><td>{{ $row->source_doc_num }}</td><td>{{ $row->product?->name }}</td><td>{{ $row->transaction_type }}</td><td class="text-end">{{ $row->quantity_out }}</td></tr>@empty<tr><td colspan="5" class="text-center text-muted">{{ __('No damage or scrap movements.') }}</td></tr>@endforelse</tbody></table></div></div></div>
</div>

<div class="card mb-3"><div class="card-header"><h5 class="mb-0">{{ __('Stock Count Variances') }}</h5></div><div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>{{ __('Count') }}</th><th>{{ __('Date') }}</th><th>{{ __('Store') }}</th><th>{{ __('Product') }}</th><th class="text-end">{{ __('System') }}</th><th class="text-end">{{ __('Physical') }}</th><th class="text-end">{{ __('Variance') }}</th><th>{{ __('Reason') }}</th></tr></thead><tbody>@forelse($stockCountVariances as $row)<tr><td>{{ $row->stockCount?->doc_num }}</td><td>{{ $row->stockCount?->count_date?->toDateString() }}</td><td>{{ $row->stockCount?->branchStore?->name }}</td><td>{{ $row->product?->name }}</td><td class="text-end">{{ $row->system_quantity }}</td><td class="text-end">{{ $row->physical_quantity }}</td><td class="text-end">{{ $row->variance_quantity }}</td><td>{{ $row->variance_reason }}</td></tr>@empty<tr><td colspan="8" class="text-center text-muted">{{ __('No stock count variances.') }}</td></tr>@endforelse</tbody></table></div></div>

@if($glReconciliation !== null)
<div class="card mb-3"><div class="card-header"><h5 class="mb-0">{{ __('Inventory / Production to General Ledger Reconciliation') }}</h5></div><div class="table-responsive"><table class="table table-sm table-bordered mb-0"><thead><tr><th>{{ __('Control') }}</th><th class="text-end">{{ __('Subledger') }}</th><th class="text-end">{{ __('General Ledger') }}</th><th class="text-end">{{ __('Difference') }}</th><th>{{ __('Status') }}</th></tr></thead><tbody>@foreach($glReconciliation as $row)<tr><td>{{ $row['label'] }}</td><td class="text-end">{{ $row['subledger'] }}</td><td class="text-end">{{ $row['gl'] }}</td><td class="text-end">{{ $row['difference'] }}</td><td><span class="badge bg-{{ $row['status'] === 'reconciled' ? 'success' : 'danger' }}">{{ str($row['status'])->replace('_', ' ')->title() }}</span></td></tr>@endforeach</tbody></table></div></div>
@endif

@unless($agingSupported)<div class="alert alert-info mb-2">{{ __('Inventory aging is intentionally unavailable: this ledger has valued movements but no receipt-layer consumption model, so a reliable layer-age report cannot be produced.') }}</div>@endunless
@unless($expirySupported)<div class="alert alert-info mb-0">{{ __('Expiry reporting is intentionally unavailable because inventory batches do not store an expiry date.') }}</div>@endunless
@endsection
