@extends('layouts.app')

@php($numbers = app(\Modules\Core\Services\NumericFormatService::class))
@php($dates = app(\Modules\Core\Services\DateFormatService::class))

@section('title', __('fixed_assets.lifecycle.depreciation_run').' '.$run->doc_num)

@section('content')
    @if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
    @if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
    <div class="card">
        <div class="card-header d-flex justify-content-between align-items-center"><div><h5 class="mb-1">{{ $run->doc_num }}</h5><span class="badge badge-subtle-{{ $run->status === 'posted' ? 'success' : 'danger' }}">{{ __('fixed_assets.lifecycle.statuses.'.$run->status) }}</span></div><div class="d-flex flex-wrap gap-2"><a class="btn btn-falcon-default btn-sm" href="{{ route('admin.fixed-assets.depreciation.index') }}">{{ __('common.actions.back') }}</a>@can('fixed_assets.print')<a target="_blank" class="btn btn-falcon-default btn-sm" href="{{ route('admin.fixed-assets.depreciation.print', $run) }}">{{ __('common.actions.print') }}</a>@endcan</div></div>
        <div class="card-body"><div class="row g-3 mb-4">@foreach([__('fixed_assets.lifecycle.financial_period') => $run->financialPeriod?->name, __('fixed_assets.reports.columns.period') => $dates->formatDate($run->period_start, '').' - '.$dates->formatDate($run->period_end, ''), __('fixed_assets.lifecycle.posting_date') => $dates->formatDate($run->posting_date, ''), __('fixed_assets.reports.columns.journal_entry') => $run->journalEntry?->doc_num, __('fixed_assets.reports.columns.period_depreciation') => $numbers->format($run->base_total_depreciation)] as $label => $value)<div class="col-md-4"><div class="text-600 fs-10">{{ $label }}</div><div class="fw-semibold">{{ $value }}</div></div>@endforeach</div>
            @can('journal_entries.view')<div class="d-flex flex-wrap gap-3 mb-3">@foreach([$run->journalEntry, $run->reversalJournalEntry] as $journal)@if($journal)<a href="{{ route('admin.accounting.journal-entries.show', $journal) }}">{{ $journal->doc_num }}</a>@endif @endforeach</div>@endcan
            <div class="table-responsive"><table class="table table-sm table-bordered"><thead><tr><th>{{ __('fixed_assets.reports.columns.asset') }}</th><th>{{ __('fixed_assets.reports.columns.period_depreciation') }}</th><th>{{ __('fixed_assets.reports.columns.accumulated_before') }}</th><th>{{ __('fixed_assets.reports.columns.accumulated_after') }}</th><th>{{ __('fixed_assets.reports.columns.net_book_value') }}</th><th>{{ __('fixed_assets.attributes.cost_center') }}</th></tr></thead><tbody>@foreach($run->lines as $line)<tr><td><a href="{{ route('admin.fixed-assets.lifecycle.show', $line->asset) }}">{{ $line->asset?->doc_num }} / {{ $line->asset?->asset_name }}</a></td><td dir="ltr">{{ $numbers->format($line->period_depreciation) }}</td><td dir="ltr">{{ $numbers->format($line->accumulated_before) }}</td><td dir="ltr">{{ $numbers->format($line->accumulated_after) }}</td><td dir="ltr">{{ $numbers->format($line->closing_net_book_value) }}</td><td>{{ $line->costCenter?->codeNameLabel() }}</td></tr>@endforeach</tbody></table></div>
            @if(app(\Modules\FixedAssets\Services\FixedAssetDepreciationService::class)->canReverse($run))@can('fixed_assets.depreciation.reverse')<form method="POST" action="{{ route('admin.fixed-assets.depreciation.reverse', $run) }}" class="row g-2 align-items-end mt-3">@csrf<div class="col-md-8"><label class="form-label" for="run-reason">{{ __('fixed_assets.lifecycle.reversal_reason') }}</label><textarea id="run-reason" class="form-control" name="reason" required></textarea></div><div class="col-auto"><button class="btn btn-danger" type="submit">{{ __('fixed_assets.lifecycle.reverse') }}</button></div></form>@endcan @endif
        </div>
    </div>
@endsection
