@extends('layouts.app')
@section('title', __('Sales Request'))
@php
    $lineRows = old('lines', $record ? $record->lines->map(fn($line) => [...$line->toArray(), 'product_doc_num' => $line->product?->doc_num, 'unit_doc_num' => $line->unit?->doc_num])->all() : [[]]);
    $productUnits = $products->mapWithKeys(fn($product) => [$product->doc_num => collect([$product->unit, $product->equivalentUnit])->filter()->unique('id')->map(fn($unit) => ['id' => $unit->doc_num, 'text' => $unit->name])->values()]);
    $selectedCurrencyDocNum = old('currency_doc_num', $record?->currency?->doc_num ?? $currencies->firstWhere('is_main', true)?->doc_num ?? $currencies->first()?->doc_num);
@endphp
@section('content')
@if($record?->sales_employee_id && !$record?->business_employee_id)<div class="alert alert-subtle-warning">{{ __('sales_ui.employee_unresolved') }}</div>@endif
<form class="js-sales-cycle-form" data-sales-ui data-sales-request-form data-index-url="{{ route('admin.sales.customer-requests.index') }}" data-create-url="{{ route('admin.sales.customer-requests.create') }}" data-edit-url="{{ route('admin.sales.customer-requests.edit', '__DOCUMENT__') }}" action="{{ $record ? route('admin.sales.customer-requests.update', $record) : route('admin.sales.customer-requests.store') }}" method="POST">
@csrf @if($record) @method('PUT') @endif <x-forms.line-item-cards :line-label="__('sales_ui.line')" />
<div class="alert alert-danger d-none js-sales-form-alert"></div>
<div class="card mb-3"><div class="card-header d-flex flex-wrap justify-content-between gap-2"><h5>{{ __('Sales Request') }} {{ $record?->doc_num }}</h5>@include('modules.finance.partials.form-actions', ['mode' => $record ? 'edit' : 'create', 'record' => $record, 'resource' => 'sales_requests', 'routePrefix' => 'admin.sales.customer-requests', 'canClone' => false])</div><div class="card-body row g-3">
<div class="col-md-6 col-xl-4"><x-forms.label for="request_type" :label="__('sales_ui.request_type')" required /><select id="request_type" name="request_type" class="form-select" required data-request-type><option value="customer" @selected(old('request_type', $record && !$record->customer_id ? 'internal' : 'customer') === 'customer')>{{ __('sales_ui.customer_request') }}</option><option value="internal" @selected(old('request_type', $record && !$record->customer_id ? 'internal' : 'customer') === 'internal')>{{ __('Internal request') }}</option></select></div>
<div class="col-md-6 col-xl-4"><x-forms.label for="customer_doc_num" :label="__('Customer')" required /><select class="form-select js-select2-ajax" id="customer_doc_num" name="customer_doc_num" data-url="{{ route('admin.sales.select2.customers') }}" data-allow-clear="true"><option value="">{{ __('Select customer') }}</option>@foreach($customers as $customer)<option value="{{ $customer->doc_num }}" @selected(old('customer_doc_num', $record?->customer?->doc_num) === $customer->doc_num)>{{ $customer->name }}</option>@endforeach</select></div>
@foreach(['request_date' => __('Date'), 'required_delivery_date' => __('Required date')] as $field => $label)<div class="col-md-6 col-xl-4"><x-forms.label :for="$field" :label="$label" :required="$field === 'request_date'" /><input id="{{ $field }}" class="form-control js-date-picker" name="{{ $field }}" @required($field === 'request_date') value="{{ old($field, app(\Modules\Core\Services\DateFormatService::class)->formatDate($record?->{$field}?->toDateString() ?? ($field === 'request_date' ? now()->toDateString() : null))) }}"></div>@endforeach
<div class="col-md-6 col-xl-4"><x-forms.label for="currency_doc_num" :label="__('Currency')" required /><select class="form-select js-select2-ajax" id="currency_doc_num" name="currency_doc_num" data-url="{{ route('admin.select2.currencies') }}" data-placeholder="{{ __('Currency') }}" required>@foreach($currencies as $currency)<option value="{{ $currency->doc_num }}" @selected($selectedCurrencyDocNum === $currency->doc_num)>{{ $currency->code }} — {{ $currency->name }}</option>@endforeach</select></div>
<div class="col-md-6 col-xl-4"><x-forms.label for="exchange_rate" :label="__('Exchange rate')" required /><x-forms.numeric-input id="exchange_rate" name="exchange_rate" :value="old('exchange_rate', $record?->exchange_rate ?? 1)" :scale="6" min="0.000001" step="0.000001" required /></div>
<div class="col-md-6 col-xl-4"><label class="form-label" for="sales_employee_doc_num">{{ __('Sales representative') }}</label><select class="form-select js-select2-ajax" id="sales_employee_doc_num" name="sales_employee_doc_num" data-url="{{ route('admin.sales.select2.employees') }}" data-allow-clear="true"><option value="">{{ __('Unassigned') }}</option>@foreach($salesEmployees as $employee)<option value="{{ $employee->doc_num }}" @selected(old('sales_employee_doc_num', $record?->salesEmployee?->doc_num) === $employee->doc_num)>{{ $employee->full_name ?: $employee->name }}</option>@endforeach</select><small class="text-muted">{{ __('sales_ui.employee_hint') }} @can('hr.employees.create')<a href="{{ route('admin.hr.employees.create') }}">{{ __('sales_ui.add_employee') }}</a>@endcan</small></div>
<div class="col-12"><label class="form-label" for="notes">{{ __('Notes') }}</label><textarea class="form-control" id="notes" name="notes">{{ old('notes', $record?->notes) }}</textarea></div>
</div></div>
<div class="card"><div class="card-header d-flex justify-content-between align-items-center"><h6 class="mb-0">{{ __('Items') }}</h6><button type="button" class="btn btn-falcon-default btn-sm" data-sales-add-line data-shortcut-action="line.add" title="{{ __('common.shortcuts.add_line') }}" data-bs-title="{{ __('common.shortcuts.add_line') }}"><span class="fas fa-plus me-1"></span>{{ __('Add line') }}</button></div>
<div class="table-responsive"><table class="table"><thead><tr><th>#</th><th>{{ __('Product') }} <span class="text-danger">*</span></th><th>{{ __('Unit') }} <span class="text-danger">*</span></th><th>{{ __('Requested quantity') }} <span class="text-danger">*</span></th><th>{{ __('Unit price') }} <span class="text-danger">*</span></th><th>{{ __('Total') }}</th><th></th></tr></thead><tbody data-sales-lines>@foreach($lineRows as $index => $line)@include('modules.sales.requests.line')@endforeach</tbody></table></div>
<div class="card-footer"><div class="row g-2 mb-3 sales-request-summary"><div class="col-6 col-lg-3"><div class="border rounded p-2 h-100"><div class="small text-600">{{ __('sales_ui.line_count') }}</div><div class="fw-semibold" data-sales-summary-lines>0</div></div></div><div class="col-6 col-lg-3"><div class="border rounded p-2 h-100"><div class="small text-600">{{ __('sales_ui.distinct_products') }}</div><div class="fw-semibold" data-sales-summary-products>0</div></div></div><div class="col-6 col-lg-3"><div class="border rounded p-2 h-100"><div class="small text-600">{{ __('sales_ui.total_quantity') }}</div><div class="fw-semibold" data-sales-summary-quantity>0</div></div></div><div class="col-6 col-lg-3"><div class="border rounded p-2 h-100"><div class="small text-600">{{ __('sales_ui.grand_total') }}</div><div class="fw-semibold"><span data-sales-summary-total>0</span> <span data-sales-summary-currency></span></div></div></div></div><button type="button" class="btn btn-falcon-default btn-sm" data-sales-add-line><span class="fas fa-plus me-1"></span>{{ __('Add line') }}</button></div></div>
</form><template id="sales-order-line-template">@include('modules.sales.requests.line', ['index' => '__INDEX__', 'line' => []])</template>
@endsection
@push('scripts')<script>window.salesProductUnits = @json($productUnits);</script>@include('modules.sales.cycle.partials.scripts')@endpush
