@extends('layouts.app')
@section('title', __('Sales Request'))
@php
    $lineRows = old('lines', $record ? $record->lines->map(fn($line) => [...$line->toArray(), 'product_doc_num' => $line->product?->doc_num, 'unit_doc_num' => $line->unit?->doc_num])->all() : [[]]);
    $productUnits = $products->mapWithKeys(fn($product) => [$product->doc_num => collect([$product->unit, $product->equivalentUnit])->filter()->unique('id')->map(fn($unit) => ['id' => $unit->doc_num, 'text' => $unit->name])->values()]);
@endphp
@section('content')
@if($record?->sales_employee_id && !$record?->business_employee_id)<div class="alert alert-subtle-warning">{{ __('sales_ui.employee_unresolved') }}</div>@endif
<form class="js-sales-cycle-form" data-sales-ui data-index-url="{{ route('admin.sales.customer-requests.index') }}" data-create-url="{{ route('admin.sales.customer-requests.create') }}" data-edit-url="{{ route('admin.sales.customer-requests.edit', '__DOCUMENT__') }}" action="{{ $record ? route('admin.sales.customer-requests.update', $record) : route('admin.sales.customer-requests.store') }}" method="POST">
@csrf @if($record) @method('PUT') @endif <x-forms.line-item-cards :line-label="__('sales_ui.line')" />
<div class="alert alert-danger d-none js-sales-form-alert"></div>
<div class="card mb-3"><div class="card-header d-flex flex-wrap justify-content-between gap-2"><h5>{{ __('Sales Request') }} {{ $record?->doc_num }}</h5>@include('modules.finance.partials.form-actions', ['mode' => $record ? 'edit' : 'create', 'record' => $record, 'resource' => 'sales_requests', 'routePrefix' => 'admin.sales.customer-requests', 'canClone' => false])</div><div class="card-body row g-3">
<div class="col-md-6 col-xl-4"><label class="form-label" for="request_type">{{ __('sales_ui.request_type') }}</label><select id="request_type" name="request_type" class="form-select" required data-request-type><option value="customer" @selected(old('request_type', $record && !$record->customer_id ? 'internal' : 'customer') === 'customer')>{{ __('sales_ui.customer_request') }}</option><option value="internal" @selected(old('request_type', $record && !$record->customer_id ? 'internal' : 'customer') === 'internal')>{{ __('Internal request') }}</option></select></div>
<div class="col-md-6 col-xl-4"><label class="form-label" for="customer_doc_num">{{ __('Customer') }}</label><select class="form-select js-select2-ajax" id="customer_doc_num" name="customer_doc_num" data-url="{{ route('admin.sales.select2.customers') }}" data-allow-clear="true"><option value="">{{ __('Select customer') }}</option>@foreach($customers as $customer)<option value="{{ $customer->doc_num }}" @selected(old('customer_doc_num', $record?->customer?->doc_num) === $customer->doc_num)>{{ $customer->name }}</option>@endforeach</select></div>
@foreach(['request_date' => __('Date'), 'required_delivery_date' => __('Required date')] as $field => $label)<div class="col-md-6 col-xl-4"><label class="form-label" for="{{ $field }}">{{ $label }}</label><input id="{{ $field }}" class="form-control js-date-picker" name="{{ $field }}" @required($field === 'request_date') value="{{ old($field, app(\Modules\Core\Services\DateFormatService::class)->formatDate($record?->{$field}?->toDateString() ?? now()->toDateString())) }}"></div>@endforeach
<div class="col-md-6 col-xl-4"><label class="form-label" for="branch_store_uuid">{{ __('Warehouse') }}</label><select class="form-select js-select2-ajax" id="branch_store_uuid" name="branch_store_uuid" data-url="{{ route('admin.sales.select2.stores') }}" data-allow-clear="true"><option value="">{{ __('Select store') }}</option>@foreach($stores as $store)<option value="{{ $store->public_uuid }}" @selected(old('branch_store_uuid', $record?->branchStore?->public_uuid) === $store->public_uuid)>{{ $store->name }}</option>@endforeach</select></div>
<div class="col-md-6 col-xl-4"><label class="form-label" for="currency_doc_num">{{ __('Currency') }}</label><select class="form-select" id="currency_doc_num" name="currency_doc_num">@foreach($currencies as $currency)<option value="{{ $currency->doc_num }}" @selected(old('currency_doc_num', $record?->currency?->doc_num) === $currency->doc_num)>{{ $currency->code }}</option>@endforeach</select></div>
<div class="col-md-6 col-xl-4"><label class="form-label" for="exchange_rate">{{ __('Exchange rate') }}</label><input class="form-control" id="exchange_rate" name="exchange_rate" inputmode="decimal" value="{{ app(\Modules\Core\Services\NumericFormatService::class)->formatForInput(old('exchange_rate', $record?->exchange_rate ?? 1)) }}"></div>
<div class="col-md-6 col-xl-4"><label class="form-label" for="sales_employee_doc_num">{{ __('Sales representative') }}</label><select class="form-select js-select2-ajax" id="sales_employee_doc_num" name="sales_employee_doc_num" data-url="{{ route('admin.sales.select2.employees') }}" data-allow-clear="true"><option value="">{{ __('Unassigned') }}</option>@foreach($salesEmployees as $employee)<option value="{{ $employee->doc_num }}" @selected(old('sales_employee_doc_num', $record?->salesEmployee?->doc_num) === $employee->doc_num)>{{ $employee->name }}</option>@endforeach</select></div>
<div class="col-md-6 col-xl-4"><label class="form-label" for="priority">{{ __('Priority') }}</label><select id="priority" name="priority" class="form-select">@foreach(['low','normal','high','urgent'] as $priority)<option value="{{ $priority }}" @selected(old('priority', $record?->priority ?? 'normal') === $priority)>{{ __(ucfirst($priority)) }}</option>@endforeach</select></div>
<div class="col-md-6 col-xl-4"><label class="form-label" for="customer_reference">{{ __('Customer reference / PO') }}</label><input class="form-control" id="customer_reference" name="customer_reference" value="{{ old('customer_reference', $record?->customer_reference) }}"></div>
<div class="col-12"><label class="form-label" for="notes">{{ __('Notes') }}</label><textarea class="form-control" id="notes" name="notes">{{ old('notes', $record?->notes) }}</textarea></div>
</div></div>
<div class="card"><div class="card-header d-flex justify-content-between"><h6>{{ __('Items') }}</h6><button type="button" class="btn btn-falcon-default btn-sm" data-sales-add-line>{{ __('Add line') }}</button></div>
<div class="table-responsive"><table class="table"><thead><tr><th>#</th><th>{{ __('Product') }}</th><th>{{ __('Unit') }}</th><th>{{ __('Requested quantity') }}</th><th>{{ __('Unit price') }}</th><th>{{ __('Packaging') }}</th><th>{{ __('Units per package') }}</th><th>{{ __('Notes') }}</th><th>{{ __('Total') }}</th><th></th></tr></thead><tbody data-sales-lines>@foreach($lineRows as $index => $line)@include('modules.sales.requests.line')@endforeach</tbody></table></div></div>
</form><template id="sales-order-line-template">@include('modules.sales.requests.line', ['index' => '__INDEX__', 'line' => []])</template>
@endsection
@push('scripts')<script>window.salesProductUnits = @json($productUnits);</script>@include('modules.sales.cycle.partials.scripts')@endpush
