@extends('layouts.app')
@section('title', __($warehouse ? 'production_handover.warehouse_title' : 'production_handover.title'))
@section('content')
@php($dates = app(\Modules\Core\Services\DateFormatService::class))
@if($warehouse && $handovers)
<div class="card mb-3"><div class="card-header"><h5>{{ __('production_handover.ready_handovers') }}</h5></div><div class="card-body">@forelse($handovers as $handover)<div class="d-flex justify-content-between mb-2"><a href="{{ route('admin.production.handovers.show', $handover) }}">{{ $handover->doc_num }} · {{ $handover->source_doc_num }} · {{ $dates->formatDate($handover->document_date) }}</a>@can('inventory.production_receipts.create')<a class="btn btn-outline-success btn-sm" href="{{ route('admin.inventory.production-receipts.create', $handover) }}">{{ __('production_handover.warehouse_create') }}</a>@endcan</div>@empty <p>{{ __('No records found.') }}</p>@endforelse{{ $handovers->links() }}</div></div>
@endif
<div class="card"><div class="card-header"><h5>{{ __($warehouse ? 'production_handover.warehouse_title' : 'production_handover.title') }}</h5></div><div class="table-responsive"><table class="table table-sm"><thead><tr><th>{{ __('Document Number') }}</th><th>{{ __('production_handover.date') }}</th><th>{{ __('Source') }}</th><th>{{ __('Status') }}</th><th>{{ __('common.fields.actions') }}</th></tr></thead><tbody>@forelse($documents as $document)<tr><td><a href="{{ route($warehouse ? 'admin.inventory.production-receipts.show' : 'admin.production.handovers.show', $document) }}">{{ $document->doc_num }}</a></td><td>{{ $dates->formatDate($document->document_date) }}</td><td>{{ $document->source_doc_num }}</td><td>{{ __('production_handover.statuses.'.$document->status) }}</td><td><x-document-owner-actions :record="$document" :menu="false" /></td></tr>@empty <tr><td colspan="5">{{ __('No records found.') }}</td></tr>@endforelse</tbody></table></div><div class="card-footer">{{ $documents->links() }}</div></div>
@endsection
