@extends('layouts.app')
@section('title', __('production_handover.correct_receipt'))
@section('content')
@php
    $numbers = app(\Modules\Core\Services\NumericFormatService::class);
    $dates = app(\Modules\Core\Services\DateFormatService::class);
@endphp
<div class="card mb-3"><div class="card-header d-flex justify-content-between"><h5>{{ __('production_handover.correct_receipt') }} — {{ $record->doc_num }}</h5><a href="{{ route('admin.inventory.production-receipts.show', $record) }}" class="btn btn-falcon-default btn-sm">{{ __('Back') }}</a></div><div class="card-body"><p>{{ __('production_handover.correction_help') }}</p><p>{{ __('production_handover.history_retained') }}</p></div>
<div class="table-responsive"><table class="table table-sm"><thead><tr><th>{{ __('Product') }}</th><th>{{ __('Unit') }}</th><th>{{ __('production_handover.actual_quantity') }}</th></tr></thead><tbody>@foreach($record->lines as $line)<tr><td>{{ $line->product?->name }}</td><td>{{ $line->transactionUnit?->name }}</td><td>{{ $numbers->format($line->transaction_quantity) }}</td></tr>@endforeach</tbody></table></div></div>
@if($errors->any())<div class="alert alert-danger">@foreach($errors->all() as $error)<div>{{ $error }}</div>@endforeach</div>@endif
@foreach($blockers as $blocker)<div class="alert alert-warning">{{ $blocker }}</div>@endforeach
@if($steps !== [])<div class="card mb-3"><div class="card-header">{{ __('production_run_correction.dependencies_required') }}</div><div class="card-body">@foreach($steps as $step)<div>{{ $step['document'] }} — {{ $step['status'] }} @if($step['correction_url'])<a href="{{ $step['correction_url'] }}">{{ __('production_handover.correct_receipt') }}</a>@elseif($step['source_url'])<a href="{{ $step['source_url'] }}">{{ __('Document') }}</a>@endif</div>@endforeach</div></div>@endif
@if($blockers === [])@can('inventory.production_receipts.correct_prepare')<form class="card mb-3" method="POST" action="{{ route('admin.inventory.production-receipts.corrections.store', $record) }}">@csrf<x-forms.input type="hidden" name="_submission_token" :value="(string) \Illuminate\Support\Str::uuid()" /><x-forms.input type="hidden" name="fingerprint" :value="$fingerprint" /><div class="card-body row g-3"><div class="col-md-4"><x-forms.label :label="__('Date')" /><x-forms.date-input name="posting_date" :value="now()->toDateString()" required /></div><div class="col-md-8"><x-forms.label :label="__('Cancellation reason')" /><x-forms.textarea name="reason" minlength="5" maxlength="2000" required /></div></div><div class="card-footer text-end"><button class="btn btn-outline-danger">{{ __('production_handover.prepare_correction') }}</button></div></form>@endcan @endif
@foreach($corrections as $proposal)<div class="card mb-3"><div class="card-header">#{{ $proposal->id }} — {{ __('production_run_correction.'.$proposal->status) }}</div><div class="card-body">{{ $proposal->reason }} — {{ $dates->formatDate($proposal->posting_date) }}</div>@if($proposal->status === 'prepared')@can('inventory.production_receipts.correct_approve')<form class="card-footer" method="POST" action="{{ route('admin.inventory.production-receipts.corrections.approve', [$record, $proposal->id]) }}">@csrf<x-forms.input type="hidden" name="_submission_token" :value="(string) \Illuminate\Support\Str::uuid()" /><button class="btn btn-danger">{{ __('production_handover.approve_correction') }}</button></form>@endcan @endif</div>@endforeach
@endsection
