@extends('layouts.app')

@section('title', __('Production Operational Reports'))

@section('content')
<div class="d-flex justify-content-between align-items-center mb-3">
    <div><h4 class="mb-1">{{ __('Production Operational Reports') }}</h4><div class="text-muted">{{ __('Orders, runs, consumption, yield, traceability, receipts, and supported WIP cost.') }}</div></div>
    @can('production.reports.export')<div class="d-flex gap-2"><a class="btn btn-outline-success" href="{{ route('admin.production.reports.export', request()->query()) }}">{{ __('Export XLSX') }}</a><a class="btn btn-outline-secondary" target="_blank" href="{{ route('admin.production.reports.print', request()->query()) }}">{{ __('Print PDF') }}</a></div>@endcan
</div>

<div class="row g-3 mb-3">@foreach($kpis as $label => $value)<div class="col-md-3"><div class="card"><div class="card-body"><div class="text-500">{{ str($label)->replace('_', ' ')->title() }}</div><div class="fs-5 fw-bold">{{ $value }}</div></div></div></div>@endforeach</div>

<div class="card mb-3"><div class="card-header"><h5 class="mb-0">{{ __('Production Orders and Sales Origin') }}</h5></div><div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>{{ __('Order') }}</th><th>{{ __('Date') }}</th><th>{{ __('Source') }}</th><th>{{ __('Sales order') }}</th><th>{{ __('Customer') }}</th><th class="text-end">{{ __('Planned') }}</th><th class="text-end">{{ __('Received') }}</th><th>{{ __('Status') }}</th></tr></thead><tbody>@forelse($orders as $order)<tr><td><a href="{{ route('admin.production.work-orders.show', $order) }}">{{ $order->doc_num }}</a></td><td>{{ $order->production_order_date?->toDateString() }}</td><td>{{ $order->source_type }}</td><td>{{ $order->salesOrder?->doc_num }}</td><td>{{ $order->salesOrder?->customer?->name }}</td><td class="text-end">{{ $order->lines->sum('base_quantity') }}</td><td class="text-end">{{ $order->lines->sum('received_base_quantity') }}</td><td>{{ $order->status }}</td></tr>@empty<tr><td colspan="8" class="text-center text-muted">{{ __('No production orders match the filters.') }}</td></tr>@endforelse</tbody></table></div></div>

<div class="card mb-3"><div class="card-header"><h5 class="mb-0">{{ __('Run Performance — Plan vs Actual, Waste and Yield') }}</h5></div><div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>{{ __('Run') }}</th><th>{{ __('Order / Sales / Customer') }}</th><th>{{ __('Product') }}</th><th class="text-end">{{ __('Planned') }}</th><th class="text-end">{{ __('Good') }}</th><th class="text-end">{{ __('Rejected') }}</th><th class="text-end">{{ __('Rework') }}</th><th class="text-end">{{ __('Scrap') }}</th><th class="text-end">{{ __('Yield %') }}</th><th>{{ __('Status') }}</th></tr></thead><tbody>@forelse($runs as $run)<tr><td><a href="{{ route('admin.production.runs.show', $run) }}">{{ $run->run_number }}</a></td><td>{{ $run->order?->doc_num }} / {{ $run->order?->salesOrder?->doc_num }} / {{ $run->order?->salesOrder?->customer?->name }}</td><td>{{ $run->product?->name }}</td><td class="text-end">{{ $run->planned_base_quantity }}</td><td class="text-end">{{ $run->good_base_quantity }}</td><td class="text-end">{{ $run->rejected_base_quantity }}</td><td class="text-end">{{ $run->rework_base_quantity }}</td><td class="text-end">{{ $run->scrap_base_quantity }}</td><td class="text-end">{{ $run->yield_percent }}</td><td>{{ $run->status }}</td></tr>@empty<tr><td colspan="10" class="text-center text-muted">{{ __('No runs match the filters.') }}</td></tr>@endforelse</tbody><tfoot><tr class="fw-bold"><td colspan="3">{{ __('Total') }}</td><td class="text-end">{{ $kpis['planned_base_quantity'] }}</td><td class="text-end">{{ $kpis['good_base_quantity'] }}</td><td colspan="5"></td></tr></tfoot></table></div></div>

<div class="card mb-3"><div class="card-header"><h5 class="mb-0">{{ __('Material Requirements, Consumption and Variance') }}</h5></div><div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>{{ __('Run') }}</th><th>{{ __('Material') }}</th><th class="text-end">{{ __('Planned') }}</th><th class="text-end">{{ __('Issued total') }}</th><th class="text-end">{{ __('Returned') }}</th><th class="text-end">{{ __('Consumed') }}</th><th class="text-end">{{ __('Waste') }}</th><th class="text-end">{{ __('Qty variance') }}</th><th class="text-end">{{ __('Accountability variance') }}</th>@if($canViewFinancial)<th class="text-end">{{ __('Planned cost') }}</th><th class="text-end">{{ __('Actual cost') }}</th><th class="text-end">{{ __('Waste cost') }}</th><th class="text-end">{{ __('Cost variance') }}</th>@endif</tr></thead><tbody>@forelse($materials as $line)<tr><td>{{ $line->run?->run_number }}</td><td>{{ $line->product?->doc_num }} — {{ $line->product?->name }}</td><td class="text-end">{{ $line->planned_quantity }}</td><td class="text-end">{{ $line->issued_total_quantity }}</td><td class="text-end">{{ $line->returned_quantity }}</td><td class="text-end">{{ $line->consumed_quantity }}</td><td class="text-end">{{ $line->waste_quantity }}</td><td class="text-end">{{ $line->quantity_variance }}</td><td class="text-end">{{ $line->accountability_variance }}</td>@if($canViewFinancial)<td class="text-end">{{ $line->planned_cost }}</td><td class="text-end">{{ $line->actual_cost }}</td><td class="text-end">{{ $line->waste_cost }}</td><td class="text-end">{{ $line->cost_variance }}</td>@endif</tr>@empty<tr><td colspan="{{ $canViewFinancial ? 13 : 9 }}" class="text-center text-muted">{{ __('No material requirements match the filters.') }}</td></tr>@endforelse</tbody></table></div></div>

<div class="card mb-3"><div class="card-header"><h5 class="mb-0">{{ __('Finished Goods Receipts and Traceability') }}</h5></div><div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>{{ __('Receipt') }}</th><th>{{ __('Date') }}</th><th>{{ __('Run') }}</th><th>{{ __('Order / Sales / Customer') }}</th><th>{{ __('Product') }}</th><th class="text-end">{{ __('Quantity') }}</th>@if($canViewFinancial)<th class="text-end">{{ __('Value') }}</th><th>{{ __('Journal') }}</th>@endif</tr></thead><tbody>@forelse($finishedGoodsReceipts as $document)@foreach($document->lines as $line)<tr><td>{{ $document->doc_num }}</td><td>{{ $document->document_date?->toDateString() }}</td><td>{{ $document->productionRun?->run_number }}</td><td>{{ $document->productionRun?->order?->doc_num }} / {{ $document->productionRun?->order?->salesOrder?->doc_num }} / {{ $document->productionRun?->order?->salesOrder?->customer?->name }}</td><td>{{ $line->product?->name }}</td><td class="text-end">{{ $line->base_quantity }}</td>@if($canViewFinancial)<td class="text-end">{{ $line->total_cost }}</td><td>{{ $document->journalEntry?->doc_num }}</td>@endif</tr>@endforeach@empty<tr><td colspan="{{ $canViewFinancial ? 8 : 6 }}" class="text-center text-muted">{{ __('No finished goods receipts match the filters.') }}</td></tr>@endforelse</tbody></table></div></div>

@if($canViewFinancial)<div class="card"><div class="card-header"><h5 class="mb-0">{{ __('Production Cost and Work in Process') }}</h5></div><div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>{{ __('Run') }}</th><th>{{ __('Order') }}</th><th class="text-end">{{ __('Issued') }}</th><th class="text-end">{{ __('Returned') }}</th><th class="text-end">{{ __('Waste') }}</th><th class="text-end">{{ __('Capitalizable') }}</th><th class="text-end">{{ __('Finished goods') }}</th><th class="text-end">{{ __('WIP') }}</th></tr></thead><tbody>@forelse($runCosts as $row)<tr><td>{{ $row->run?->run_number }}</td><td>{{ $row->run?->order?->doc_num }}</td><td class="text-end">{{ $row->issued }}</td><td class="text-end">{{ $row->returned }}</td><td class="text-end">{{ $row->waste }}</td><td class="text-end">{{ $row->capitalizable }}</td><td class="text-end">{{ $row->finished_goods }}</td><td class="text-end">{{ $row->wip }}</td></tr>@empty<tr><td colspan="8" class="text-center text-muted">{{ __('No production cost movements.') }}</td></tr>@endforelse</tbody></table></div></div>@endif
@endsection
