@extends('layouts.app')

@section('title', __('Production Operational Reports'))

@section('content')
<div class="row g-3 mb-3">@foreach($kpis as $label => $value)<div class="col-md-3"><div class="card"><div class="card-body"><div class="text-500">{{ str($label)->replace('_', ' ')->title() }}</div><div class="fs-5 fw-bold">{{ $value }}</div></div></div></div>@endforeach</div>
<div class="card mb-3"><div class="card-header"><h5 class="mb-0">{{ __('Run Performance') }}</h5></div><div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>{{ __('Run') }}</th><th>{{ __('Order') }}</th><th>{{ __('Product') }}</th><th>{{ __('Planned') }}</th><th>{{ __('Good') }}</th><th>{{ __('Rejected') }}</th><th>{{ __('Scrap') }}</th><th>{{ __('Status') }}</th></tr></thead><tbody>@foreach($runs as $run)<tr><td><a href="{{ route('admin.production.runs.show', $run) }}">{{ $run->run_number }}</a></td><td>{{ $run->order?->doc_num }}</td><td>{{ $run->product?->name }}</td><td>{{ $run->planned_base_quantity }}</td><td>{{ $run->good_base_quantity }}</td><td>{{ $run->rejected_base_quantity }}</td><td>{{ $run->scrap_base_quantity }}</td><td>{{ $run->status }}</td></tr>@endforeach</tbody></table></div></div>
<div class="card"><div class="card-header"><h5 class="mb-0">{{ __('Material Variance') }}</h5></div><div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>{{ __('Run') }}</th><th>{{ __('Material') }}</th><th>{{ __('Planned') }}</th><th>{{ __('Issued total') }}</th><th>{{ __('Returned') }}</th><th>{{ __('Consumed') }}</th><th>{{ __('Waste') }}</th></tr></thead><tbody>@foreach($materials as $line)<tr><td>{{ $line->run?->run_number }}</td><td>{{ $line->product?->name }}</td><td>{{ $line->planned_quantity }}</td><td>{{ bcadd($line->issued_quantity, $line->additional_issued_quantity, 8) }}</td><td>{{ $line->returned_quantity }}</td><td>{{ $line->consumed_quantity }}</td><td>{{ $line->waste_quantity }}</td></tr>@endforeach</tbody></table></div></div>
@endsection
