@extends('layouts.app')

@php($numbers = app(\Modules\Core\Services\NumericFormatService::class))

@section('title', __('Sales Cycle Operational Report'))

@section('content')
    <div class="page-print-actions d-flex justify-content-end gap-2 mb-3">@can('reports.sales.sales_orders.export')<a class="btn btn-falcon-default btn-sm" href="{{ route('admin.reports.sales.sales-orders.export', request()->only(['from', 'to'])) }}">{{ __('Excel') }}</a>@endcan @can('reports.sales.sales_orders.print')<a class="btn btn-falcon-primary btn-sm" href="{{ route('admin.reports.sales.sales-orders.print', request()->only(['from', 'to'])) }}">{{ __('Print view') }}</a>@endcan @if(request()->routeIs('admin.reports.sales.sales-orders.print'))<button class="btn btn-primary btn-sm" type="button" onclick="window.print()">{{ __('Print') }}</button>@endif</div>
    <div class="card mb-3"><div class="card-header"><h5 class="mb-0">{{ __('Sales Cycle Operational Report') }}</h5></div><div class="card-body"><form class="row g-3"><div class="col-md-4"><label class="form-label">{{ __('From') }}</label><input class="form-control datetimepicker" name="from" value="{{ request('from') }}"></div><div class="col-md-4"><label class="form-label">{{ __('To') }}</label><input class="form-control datetimepicker" name="to" value="{{ request('to') }}"></div><div class="col-md-4 d-flex align-items-end"><button class="btn btn-primary w-100">{{ __('Apply') }}</button></div></form></div></div>

    <div class="card mb-3"><div class="card-header"><h6 class="mb-0">{{ __('Open / Partially Fulfilled / Overdue Orders') }}</h6></div><div class="table-responsive"><table class="table table-sm table-bordered mb-0"><thead><tr><th>{{ __('Order') }}</th><th>{{ __('Customer') }}</th><th>{{ __('Required date') }}</th><th>{{ __('Status') }}</th><th class="text-end">{{ __('Ordered') }}</th><th class="text-end">{{ __('Delivered') }}</th><th class="text-end">{{ __('Production requested') }}</th></tr></thead><tbody>@foreach($openOrders as $order)<tr><td><a href="{{ route('admin.sales.sales-orders.show', $order) }}">{{ $order->doc_num }}</a></td><td>{{ $order->customer?->name }}</td><td>{{ $order->expected_delivery_date?->toDateString() }} @if($order->expected_delivery_date?->isBefore(today()))<span class="badge bg-danger">{{ __('Overdue') }}</span>@endif</td><td>{{ $order->status }}</td><td class="text-end">{{ $numbers->format($order->ordered_quantity) }}</td><td class="text-end">{{ $numbers->format($order->delivered_quantity) }}</td><td class="text-end">{{ $numbers->format($order->production_requested_quantity) }}</td></tr>@endforeach</tbody></table></div></div>
    <div class="card mb-3"><div class="card-header"><h6 class="mb-0">{{ __('Customer Order History') }}</h6></div><div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>{{ __('Order') }}</th><th>{{ __('Customer') }}</th><th>{{ __('Date') }}</th><th>{{ __('Status') }}</th><th class="text-end">{{ __('Ordered') }}</th><th class="text-end">{{ __('Delivered') }}</th></tr></thead><tbody>@foreach($orderHistory as $order)<tr><td><a href="{{ route('admin.sales.sales-orders.show', $order) }}">{{ $order->doc_num }}</a></td><td>{{ $order->customer?->doc_num }} / {{ $order->customer?->name }}</td><td>{{ $order->order_date?->toDateString() }}</td><td>{{ $order->status }}</td><td class="text-end">{{ $numbers->format($order->ordered_quantity) }}</td><td class="text-end">{{ $numbers->format($order->delivered_quantity) }}</td></tr>@endforeach</tbody></table></div></div>
    <div class="row g-3"><div class="col-xl-6"><div class="card h-100"><div class="card-header"><h6 class="mb-0">{{ __('Sales / Outstanding by Customer') }}</h6></div><div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>{{ __('Customer') }}</th><th class="text-end">{{ __('Sales') }}</th><th class="text-end">{{ __('Outstanding') }}</th></tr></thead><tbody>@foreach($salesByCustomer as $row)<tr><td>{{ $row->doc_num }} / {{ $row->name }}</td><td class="text-end">{{ $numbers->format($row->sales_value) }}</td><td class="text-end">{{ $numbers->format($row->outstanding) }}</td></tr>@endforeach</tbody></table></div></div></div><div class="col-xl-6"><div class="card h-100"><div class="card-header"><h6 class="mb-0">{{ __('Due / Overdue Installments') }}</h6></div><div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>{{ __('Invoice') }}</th><th>{{ __('Customer') }}</th><th>{{ __('Due') }}</th><th class="text-end">{{ __('Outstanding') }}</th></tr></thead><tbody>@foreach($installments as $row)<tr><td>{{ $row->doc_num }}</td><td>{{ $row->name }}</td><td>{{ $row->due_date }}</td><td class="text-end">{{ $numbers->format($row->outstanding) }}</td></tr>@endforeach</tbody></table></div></div></div></div>
    <div class="card mt-3"><div class="card-header"><h6 class="mb-0">{{ __('Customer Aging') }}</h6></div><div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>{{ __('Customer') }}</th><th class="text-end">{{ __('Current') }}</th><th class="text-end">1–30</th><th class="text-end">31–60</th><th class="text-end">61–90</th><th class="text-end">90+</th></tr></thead><tbody>@foreach($aging as $row)<tr><td>{{ $row['customer'] }}</td><td class="text-end">{{ $numbers->format($row['current']) }}</td><td class="text-end">{{ $numbers->format($row['1_30']) }}</td><td class="text-end">{{ $numbers->format($row['31_60']) }}</td><td class="text-end">{{ $numbers->format($row['61_90']) }}</td><td class="text-end">{{ $numbers->format($row['over_90']) }}</td></tr>@endforeach</tbody></table></div></div>
    <div class="row g-3 mt-0">
        <div class="col-xl-6"><div class="card h-100"><div class="card-header"><h6 class="mb-0">{{ __('Invoice Outstanding') }}</h6></div><div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>{{ __('Invoice') }}</th><th>{{ __('Customer') }}</th><th>{{ __('Due') }}</th><th class="text-end">{{ __('Outstanding') }}</th></tr></thead><tbody>@foreach($invoiceOutstanding as $invoice)<tr><td><a href="{{ route('admin.sales.customer-invoices.show', $invoice) }}">{{ $invoice->doc_num }}</a></td><td>{{ $invoice->customer?->name }}</td><td>{{ $invoice->due_date?->toDateString() }}</td><td class="text-end">{{ $numbers->format($invoice->remaining_amount) }}</td></tr>@endforeach</tbody></table></div></div></div>
        <div class="col-xl-6"><div class="card h-100"><div class="card-header"><h6 class="mb-0">{{ __('Upcoming Collections') }}</h6></div><div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>{{ __('Invoice') }}</th><th>{{ __('Customer') }}</th><th>{{ __('Due') }}</th><th class="text-end">{{ __('Outstanding') }}</th></tr></thead><tbody>@foreach($upcomingCollections as $row)<tr><td>{{ $row->doc_num }}</td><td>{{ $row->name }}</td><td>{{ $row->due_date }}</td><td class="text-end">{{ $numbers->format($row->outstanding) }}</td></tr>@endforeach</tbody></table></div></div></div>
    </div>
    <div class="row g-3 mt-0">
        <div class="col-xl-6"><div class="card h-100"><div class="card-header"><h6 class="mb-0">{{ __('Sales by Item') }}</h6></div><div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>{{ __('Item') }}</th><th class="text-end">{{ __('Quantity') }}</th><th class="text-end">{{ __('Value') }}</th></tr></thead><tbody>@foreach($salesByItem as $row)<tr><td>{{ $row->doc_num }} / {{ $row->name }}</td><td class="text-end">{{ $numbers->format($row->sold_quantity) }}</td><td class="text-end">{{ $numbers->format($row->sales_value) }}</td></tr>@endforeach</tbody></table></div></div></div>
        <div class="col-xl-6"><div class="card h-100"><div class="card-header"><h6 class="mb-0">{{ __('Sales by Period') }}</h6></div><div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>{{ __('Date') }}</th><th class="text-end">{{ __('Invoices') }}</th><th class="text-end">{{ __('Value') }}</th></tr></thead><tbody>@foreach($salesByPeriod as $row)<tr><td>{{ $row->invoice_date }}</td><td class="text-end">{{ $row->invoice_count }}</td><td class="text-end">{{ $numbers->format($row->sales_value) }}</td></tr>@endforeach</tbody></table></div></div></div>
    </div>
    <div class="card mt-3"><div class="card-header"><h6 class="mb-0">{{ __('Customer / Item Sales Analysis') }}</h6></div><div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>{{ __('Customer') }}</th><th>{{ __('Item') }}</th><th class="text-end">{{ __('Quantity') }}</th><th class="text-end">{{ __('Value') }}</th></tr></thead><tbody>@foreach($salesByCustomerItem as $row)<tr><td>{{ $row->customer_doc_num }} / {{ $row->customer_name }}</td><td>{{ $row->product_doc_num }} / {{ $row->product_name }}</td><td class="text-end">{{ $numbers->format($row->sold_quantity) }}</td><td class="text-end">{{ $numbers->format($row->sales_value) }}</td></tr>@endforeach</tbody></table></div></div>
    <div class="card mt-3"><div class="card-header"><h6 class="mb-0">{{ __('Returns by Reason and Quality Disposition') }}</h6></div><div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>{{ __('Reason') }}</th><th class="text-end">{{ __('Returns') }}</th><th class="text-end">{{ __('Quantity') }}</th><th class="text-end">{{ __('Saleable') }}</th><th class="text-end">{{ __('Rejected / Rework / Scrap') }}</th></tr></thead><tbody>@foreach($returns as $row)<tr><td>{{ str($row->reason_code)->replace('_', ' ')->title() }}</td><td class="text-end">{{ $row->return_count }}</td><td class="text-end">{{ $numbers->format($row->returned_quantity) }}</td><td class="text-end">{{ $numbers->format($row->saleable_quantity) }}</td><td class="text-end">{{ $numbers->format($row->rejected_quantity) }}</td></tr>@endforeach</tbody></table></div></div>
    <div class="card mt-3"><div class="card-header"><h6 class="mb-0">{{ __('Customer / Item Return Analysis') }}</h6></div><div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>{{ __('Customer') }}</th><th>{{ __('Item') }}</th><th>{{ __('Reason') }}</th><th>{{ __('Disposition') }}</th><th class="text-end">{{ __('Quantity') }}</th></tr></thead><tbody>@foreach($returnAnalysis as $row)<tr><td>{{ $row->customer_doc_num }} / {{ $row->customer_name }}</td><td>{{ $row->product_doc_num }} / {{ $row->product_name }}</td><td>{{ str($row->reason_code)->replace('_', ' ')->title() }}</td><td>{{ $row->quality_disposition ?: '—' }}</td><td class="text-end">{{ $numbers->format($row->returned_quantity) }}</td></tr>@endforeach</tbody></table></div></div>
@endsection
