@extends('layouts.app')

@section('title', __('Production Resources'))

@section('content')
<div class="row g-3 mb-3">
    <div class="col-lg-4"><form class="card h-100" method="POST" action="{{ route('admin.production.resources.machines.store') }}">@csrf<div class="card-header"><h5 class="mb-0">{{ __('New Machine') }}</h5></div><div class="card-body"><label class="form-label">{{ __('Code') }}</label><input class="form-control mb-2" name="code" required><label class="form-label">{{ __('Name') }}</label><input class="form-control mb-2" name="name" required><label class="form-label">{{ __('Status') }}</label><select class="form-select" name="status"><option value="available">{{ __('Available') }}</option><option value="maintenance">{{ __('Maintenance') }}</option><option value="unavailable">{{ __('Unavailable') }}</option></select></div><div class="card-footer text-end"><button class="btn btn-primary">{{ __('Create') }}</button></div></form></div>
    <div class="col-lg-4"><form class="card h-100" method="POST" action="{{ route('admin.production.resources.molds.store') }}">@csrf<div class="card-header"><h5 class="mb-0">{{ __('New Mold') }}</h5></div><div class="card-body"><label class="form-label">{{ __('Code') }}</label><input class="form-control mb-2" name="code" required><label class="form-label">{{ __('Name') }}</label><input class="form-control mb-2" name="name" required><input type="hidden" name="status" value="available"><label class="form-label">{{ __('Compatible machines') }}</label><select class="form-select mb-2" name="machine_ids[]" multiple required>@foreach($machines as $machine)<option value="{{ $machine->id }}">{{ $machine->code }} — {{ $machine->name }}</option>@endforeach</select><label class="form-label">{{ __('Finished products') }}</label><select class="form-select" name="product_ids[]" multiple required>@foreach($products as $product)<option value="{{ $product->id }}">{{ $product->doc_num }} — {{ $product->name }}</option>@endforeach</select></div><div class="card-footer text-end"><button class="btn btn-primary">{{ __('Create') }}</button></div></form></div>
    <div class="col-lg-4"><form class="card h-100" method="POST" action="{{ route('admin.production.resources.shifts.store') }}">@csrf<div class="card-header"><h5 class="mb-0">{{ __('New Shift') }}</h5></div><div class="card-body"><label class="form-label">{{ __('Code') }}</label><input class="form-control mb-2" name="code" required><label class="form-label">{{ __('Name') }}</label><input class="form-control mb-2" name="name" required><label class="form-label">{{ __('Starts') }}</label><input class="form-control mb-2" type="time" name="starts_at" required><label class="form-label">{{ __('Ends') }}</label><input class="form-control" type="time" name="ends_at" required></div><div class="card-footer text-end"><button class="btn btn-primary">{{ __('Create') }}</button></div></form></div>
</div>
<div class="card"><div class="card-header"><h5 class="mb-0">{{ __('Machine / Mold Compatibility') }}</h5></div><div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>{{ __('Mold') }}</th><th>{{ __('Machines') }}</th><th>{{ __('Products') }}</th><th>{{ __('Status') }}</th></tr></thead><tbody>@foreach($molds as $mold)<tr><td>{{ $mold->code }} — {{ $mold->name }}</td><td>{{ $mold->machines->pluck('name')->implode(', ') }}</td><td>{{ $mold->products->pluck('name')->implode(', ') }}</td><td>{{ __(str($mold->status)->replace('_', ' ')->title()->toString()) }}</td></tr>@endforeach</tbody></table></div></div>
@endsection
