<?php

$screen = static fn (string $slug, string $en, string $ar, string $group = 'configuration', array $extra = []): array => [
    'key' => 'core_'.str_replace('-', '_', $slug),
    'slug' => $slug,
    'title' => ['en' => $en, 'ar' => $ar],
    'group' => $group,
    'profile' => 'setup',
    ...$extra,
];

return [
    'module' => 'core',
    'title' => ['en' => 'Dashboard and Setup', 'ar' => 'لوحة التحكم والإعدادات'],
    'route_segment' => 'core',
    'route_name' => 'core',
    'permission_prefix' => 'core',
    'menu' => ['label' => 'dashboard_setup', 'title' => ['en' => 'Dashboard and Setup', 'ar' => 'لوحة التحكم والإعدادات'], 'icon' => 'cogs', 'order' => 10],
    'groups' => [
        'configuration' => ['title' => ['en' => 'General Configuration', 'ar' => 'الإعدادات العامة'], 'icon' => 'cogs', 'order' => 10],
        'commercial_policies' => ['title' => ['en' => 'Commercial Policies', 'ar' => 'السياسات التجارية'], 'icon' => 'file-contract', 'order' => 30],
        'operational_policies' => ['title' => ['en' => 'Operational Policies', 'ar' => 'السياسات التشغيلية'], 'icon' => 'sliders-h', 'order' => 40],
    ],
    'screens' => [
        $screen('erp-general-settings', 'ERP General Settings', 'الإعدادات العامة للنظام'),
        $screen('company-operational-settings', 'Company Operational Settings', 'إعدادات تشغيل الشركة'),
        $screen('branch-operational-settings', 'Branch Operational Settings', 'إعدادات تشغيل الفرع'),
        $screen('financial-period-control', 'Financial Period Control', 'التحكم في الفترات المالية'),
        $screen('tax-definitions', 'Tax Definitions', 'تعريفات الضرائب', 'commercial_policies', ['profile' => 'master']),
        $screen('currency-rate-policies', 'Currency Rate Policies', 'سياسات أسعار العملات', 'commercial_policies'),
        [
            'key' => 'core_quick_tasks',
            'slug' => 'quick-tasks',
            'title' => ['en' => 'Quick Tasks', 'ar' => 'المهام السريعة'],
            'group' => 'configuration',
            'profile' => 'setup',
            'classification' => 'OUT_OF_SCOPE',
            'shell_enabled' => false,
            'menu_visible' => false,
            'permission_prefix' => 'quick_tasks',
            'actions' => [
                'view',
                'create',
                'update',
                'delete',
                'restore',
                'change_status',
                'bulk_delete',
            ],
        ],
        [
            'key' => 'core_user_tasks',
            'slug' => 'user-tasks',
            'title' => ['en' => 'User Tasks', 'ar' => 'مهام المستخدم'],
            'group' => 'configuration',
            'profile' => 'setup',
            'classification' => 'OUT_OF_SCOPE',
            'shell_enabled' => false,
            'menu_visible' => false,
            'permission_prefix' => 'tasks',
            'actions' => [
                'view',
                'create',
                'edit',
                'update',
                'delete',
                'clone',
                'bulk_delete',
                'restore',
                'view_trashed',
                'document_number.control',
                'document_number_settings.update',
            ],
        ],
        [
            'key' => 'core_screen_data_visibility_rules',
            'slug' => 'screen-data-visibility-rules',
            'title' => ['en' => 'Data Visibility Rules', 'ar' => 'سياسات رؤية البيانات'],
            'group' => 'configuration',
            'profile' => 'setup',
            'classification' => 'OUT_OF_SCOPE',
            'shell_enabled' => false,
            'menu_visible' => false,
            'permission_prefix' => 'screen_data_visibility_rules',
            'actions' => [
                'view',
                'create',
                'clone',
                'edit',
                'delete',
                'view_trashed',
                'restore',
                'bypass',
            ],
        ],
    ],
];
