<?php

$screen = static fn (string $slug, string $en, string $ar, string $group = 'analysis', string $profile = 'document', array $extra = []): array => [
    'key' => 'costing_'.str_replace('-', '_', $slug),
    'slug' => $slug,
    'title' => ['en' => $en, 'ar' => $ar],
    'group' => $group,
    'profile' => $profile,
    ...$extra,
];

return [
    'module' => 'costing',
    'title' => ['en' => 'Costing', 'ar' => 'التكاليف'],
    'route_segment' => 'costing',
    'route_name' => 'costing',
    'permission_prefix' => 'costing',
    'menu' => ['label' => 'costing', 'title' => ['en' => 'Costing', 'ar' => 'التكاليف'], 'icon' => 'calculator', 'order' => 120],
    'groups' => [
        'setup' => ['title' => ['en' => 'Costing Setup', 'ar' => 'إعدادات التكاليف'], 'icon' => 'cogs', 'order' => 10],
        'standards' => ['title' => ['en' => 'Standard Costs', 'ar' => 'التكاليف المعيارية'], 'icon' => 'clipboard-list', 'order' => 20],
        'work_orders' => ['title' => ['en' => 'Work Order Costing', 'ar' => 'تكاليف أوامر التشغيل'], 'icon' => 'industry', 'order' => 30],
        'components' => ['title' => ['en' => 'Cost Components', 'ar' => 'مكونات التكلفة'], 'icon' => 'puzzle-piece', 'order' => 40],
        'allocation' => ['title' => ['en' => 'Overhead Allocation', 'ar' => 'توزيع التكاليف غير المباشرة'], 'icon' => 'project-diagram', 'order' => 50],
        'analysis' => ['title' => ['en' => 'Cost Analysis and Profitability', 'ar' => 'تحليل التكلفة والربحية'], 'icon' => 'chart-bar', 'order' => 60],
        'closing' => ['title' => ['en' => 'Cost Closing', 'ar' => 'إقفال التكاليف'], 'icon' => 'lock', 'order' => 70],
    ],
    'screens' => [
        $screen('costing-settings', 'Costing Settings', 'إعدادات التكاليف', 'setup', 'setup'),
        $screen('cost-elements', 'Cost Elements', 'عناصر التكلفة', 'setup', 'master'),
        $screen('cost-types', 'Cost Types', 'أنواع التكلفة', 'setup', 'master'),
        $screen('standard-material-cost', 'Standard Material Cost', 'التكلفة المعيارية للخامات', 'standards'),
        $screen('standard-labor-cost', 'Standard Labor Cost', 'التكلفة المعيارية للعمالة', 'standards'),
        $screen('standard-overhead-cost', 'Standard Overhead Cost', 'التكلفة المعيارية غير المباشرة', 'standards'),
        $screen('product-standard-cost', 'Product Standard Cost', 'التكلفة المعيارية للمنتج', 'standards'),
        $screen('product-cost-sheet', 'Product Cost Sheet', 'بطاقة تكلفة المنتج', 'standards'),
        $screen('work-order-estimated-cost', 'Work Order Estimated Cost', 'التكلفة التقديرية لأمر التشغيل', 'work_orders'),
        $screen('work-order-actual-cost', 'Work Order Actual Cost', 'التكلفة الفعلية لأمر التشغيل', 'work_orders'),
        $screen('material-cost-analysis', 'Material Cost Analysis', 'تحليل تكلفة الخامات', 'components', 'inquiry'),
        $screen('labor-cost-analysis', 'Labor Cost Analysis', 'تحليل تكلفة العمالة', 'components', 'inquiry'),
        $screen('machine-cost-analysis', 'Machine Cost Analysis', 'تحليل تكلفة الماكينات', 'components', 'inquiry'),
        $screen('external-manufacturing-cost', 'External Manufacturing Cost', 'تكلفة التصنيع الخارجي', 'components'),
        $screen('maintenance-cost', 'Maintenance Cost', 'تكلفة الصيانة', 'components'),
        $screen('scrap-cost', 'Scrap Cost', 'تكلفة الهالك', 'components'),
        $screen('waste-cost', 'Waste Cost', 'تكلفة الفاقد', 'components'),
        $screen('packaging-cost', 'Packaging Cost', 'تكلفة التعبئة', 'components'),
        $screen('delivery-cost', 'Delivery Cost', 'تكلفة التسليم', 'components'),
        $screen('overhead-allocation-rules', 'Overhead Allocation Rules', 'قواعد توزيع التكاليف غير المباشرة', 'allocation', 'setup', [
            'classification' => 'WORKING_REAL_SCREEN',
            'shell_enabled' => false,
            'actions' => ['view', 'create'],
            'modes' => ['index'],
        ]),
        $screen('overhead-allocation-run', 'Overhead Allocation Run', 'تشغيل توزيع التكاليف غير المباشرة', 'allocation', 'document', [
            'classification' => 'WORKING_REAL_SCREEN',
            'shell_enabled' => false,
            'actions' => ['view', 'create', 'approve', 'reverse'],
            'modes' => ['index'],
        ]),
        $screen('cost-variance-analysis', 'Cost Variance Analysis', 'تحليل انحرافات التكلفة', 'analysis', 'inquiry'),
        $screen('estimated-vs-actual-cost', 'Estimated vs Actual Cost', 'التكلفة التقديرية مقابل الفعلية', 'analysis', 'inquiry'),
        $screen('work-order-profitability', 'Work Order Profitability', 'ربحية أمر التشغيل', 'analysis', 'inquiry'),
        $screen('product-profitability', 'Product Profitability', 'ربحية المنتج', 'analysis', 'inquiry'),
        $screen('customer-profitability', 'Customer Profitability', 'ربحية العميل', 'analysis', 'inquiry'),
        $screen('contract-profitability', 'Contract Profitability', 'ربحية العقد', 'analysis', 'inquiry'),
        $screen('cost-closing', 'Cost Closing', 'إقفال التكاليف', 'closing', 'closing', ['shell_enabled' => false, 'menu_visible' => false]),
        [
            'key' => 'costing_work_orders_view',
            'slug' => 'work-orders-view',
            'title' => ['en' => 'Work Orders View', 'ar' => 'عرض أوامر التشغيل'],
            'group' => 'work_orders',
            'profile' => 'closing',
            'classification' => 'OUT_OF_SCOPE',
            'shell_enabled' => false,
            'menu_visible' => false,
            'permission_prefix' => 'production',
            'actions' => ['work_orders.view'],
        ],
    ],
];
