<?php

$screen = static fn (string $slug, string $en, string $ar, string $group = 'treasury', string $profile = 'document', array $extra = []): array => [
    'key' => 'finance_'.str_replace('-', '_', $slug),
    'slug' => $slug,
    'title' => ['en' => $en, 'ar' => $ar],
    'group' => $group,
    'profile' => $profile,
    ...$extra,
];

return [
    'module' => 'finance',
    'title' => ['en' => 'Finance and Treasury', 'ar' => 'المالية والخزينة'],
    'route_segment' => 'finance',
    'route_name' => 'finance',
    'permission_prefix' => 'finance',
    'menu' => ['label' => 'finance', 'title' => ['en' => 'Finance and Treasury', 'ar' => 'المالية والخزينة'], 'icon' => 'money-check-alt', 'order' => 100],
    'groups' => [
        'bank_vouchers' => ['title' => ['en' => 'Bank Vouchers', 'ar' => 'سندات البنوك'], 'icon' => 'university', 'order' => 10],
        'cheques' => ['title' => ['en' => 'Cheque Controls', 'ar' => 'إدارة الشيكات'], 'icon' => 'money-check', 'order' => 20],
        'treasury' => ['title' => ['en' => 'Treasury Operations', 'ar' => 'عمليات الخزينة'], 'icon' => 'cash-register', 'order' => 30],
        'reconciliation' => ['title' => ['en' => 'Reconciliation and Closing', 'ar' => 'التسويات والإقفالات'], 'icon' => 'balance-scale', 'order' => 40],
        'collections' => ['title' => ['en' => 'Collections and Payments', 'ar' => 'التحصيل والمدفوعات'], 'icon' => 'hand-holding-usd', 'order' => 50],
        'expenses' => ['title' => ['en' => 'Expenses and Custody', 'ar' => 'المصروفات والعهد'], 'icon' => 'wallet', 'order' => 60],
        'currency' => ['title' => ['en' => 'Currency Operations', 'ar' => 'عمليات العملات'], 'icon' => 'coins', 'order' => 70],
        'history' => ['title' => ['en' => 'Financial History', 'ar' => 'السجل المالي'], 'icon' => 'history', 'order' => 80],
    ],
    'screens' => [
        $screen('bank-receipt-vouchers', 'Bank Receipt Vouchers', 'سندات قبض بنكية', 'bank_vouchers'),
        $screen('bank-payment-vouchers', 'Bank Payment Vouchers', 'سندات صرف بنكية', 'bank_vouchers'),
        $screen('cheque-replacement', 'Cheque Replacement', 'استبدال الشيك', 'cheques'),
        $screen('cheque-movement-history', 'Cheque Movement History', 'سجل حركة الشيك', 'cheques', 'inquiry'),
        $screen('transfer-receipt', 'Transfer Receipt', 'استلام التحويل', 'treasury'),
        $screen('bank-reconciliation', 'Bank Reconciliation', 'تسوية البنك', 'reconciliation', 'document', [
            'classification' => 'DUPLICATE',
            'menu_visible' => false,
            'shell_enabled' => false,
            'canonical_route' => 'admin.reports.finance.bank-reconciliation.index',
        ]),
        $screen('bank-reconciliation-lines', 'Bank Reconciliation Lines', 'سطور تسوية البنك', 'reconciliation'),
        $screen('cashbox-count', 'Cashbox Count', 'جرد الخزينة', 'reconciliation', 'document', [
            'classification' => 'WORKING_REAL_SCREEN',
            'actions' => ['view', 'create', 'edit', 'reopen', 'print'],
            'modes' => ['index', 'data'],
        ]),
        $screen('cashbox-closing', 'Cashbox Closing', 'إغلاق الخزينة', 'reconciliation'),
        $screen('daily-treasury-closing', 'Daily Treasury Closing', 'الإغلاق اليومي للخزينة', 'reconciliation'),
        $screen('customer-advances', 'Customer Advances', 'دفعات العملاء المقدمة', 'collections'),
        $screen('supplier-advances', 'Supplier Advances', 'دفعات الموردين المقدمة', 'collections', 'document', ['classification' => 'DUPLICATE', 'menu_visible' => false, 'shell_enabled' => false, 'canonical_route' => 'admin.purchases.supplier-advances.index']),
        $screen('customer-receipts', 'Customer Receipts', 'متحصلات العملاء', 'collections', 'document', [
            'classification' => 'DUPLICATE',
            'menu_visible' => false,
            'shell_enabled' => false,
            'canonical_route' => 'admin.sales.customer-receipts.index',
        ]),
        $screen('supplier-payments', 'Supplier Payments', 'مدفوعات الموردين', 'collections', 'document', ['classification' => 'DUPLICATE', 'menu_visible' => false, 'shell_enabled' => false, 'canonical_route' => 'admin.purchases.supplier-payments.index']),
        $screen('receipt-allocations', 'Receipt Allocations', 'تخصيص المتحصلات', 'collections'),
        $screen('payment-allocations', 'Payment Allocations', 'تخصيص المدفوعات', 'collections', 'document', [
            'classification' => 'DUPLICATE',
            'menu_visible' => false,
            'shell_enabled' => false,
            'canonical_route' => 'admin.purchases.supplier-payments.index',
        ]),
        $screen('employee-custody', 'Employee Custody', 'عهد الموظفين', 'expenses', 'document', ['classification' => 'DUPLICATE', 'menu_visible' => false, 'shell_enabled' => false]),
        $screen('custody-settlement', 'Custody Settlement', 'تسوية العهدة', 'expenses'),
        $screen('expense-requests', 'Expense Requests', 'طلبات المصروفات', 'expenses'),
        $screen('expense-vouchers', 'Expense Vouchers', 'سندات المصروفات', 'expenses'),
        $screen('petty-cash-requests', 'Petty Cash Requests', 'طلبات النثرية', 'expenses'),
        $screen('petty-cash-settlement', 'Petty Cash Settlement', 'تسوية النثرية', 'expenses'),
        $screen('payment-requests', 'Payment Requests', 'طلبات الدفع', 'collections'),
        $screen('payment-approvals', 'Payment Approvals', 'اعتمادات الدفع', 'collections'),
        $screen('collection-requests', 'Collection Requests', 'طلبات التحصيل', 'collections'),
        $screen('collection-follow-up', 'Collection Follow-up', 'متابعة التحصيل', 'collections'),
        $screen('currency-exchange', 'Currency Exchange', 'تبديل العملات', 'currency'),
        $screen('currency-revaluation', 'Currency Revaluation', 'إعادة تقييم العملات', 'currency'),
        $screen('financial-document-history', 'Financial Document History', 'سجل المستندات المالية', 'history', 'inquiry'),
    ],
];
