<?php

$screen = static fn (string $slug, string $en, string $ar, string $group = 'transactions', string $profile = 'document', array $extra = []): array => [
    'key' => 'fixed_assets_'.str_replace('-', '_', $slug),
    'slug' => $slug,
    'title' => ['en' => $en, 'ar' => $ar],
    'group' => $group,
    'profile' => $profile,
    ...$extra,
];

return [
    'module' => 'fixed_assets',
    'title' => ['en' => 'Fixed Assets', 'ar' => 'الأصول الثابتة'],
    'route_segment' => 'fixed-assets',
    'route_name' => 'fixed-assets',
    'permission_prefix' => 'fixed_assets',
    'menu' => ['label' => 'fixed_assets', 'title' => ['en' => 'Fixed Assets', 'ar' => 'الأصول الثابتة'], 'icon' => 'building', 'order' => 110],
    'groups' => [
        'setup' => ['title' => ['en' => 'Asset Setup', 'ar' => 'إعدادات الأصول'], 'icon' => 'cogs', 'order' => 10],
        'transactions' => ['title' => ['en' => 'Asset Transactions', 'ar' => 'حركات الأصول'], 'icon' => 'exchange-alt', 'order' => 20],
        'depreciation' => ['title' => ['en' => 'Depreciation', 'ar' => 'الإهلاك'], 'icon' => 'chart-line', 'order' => 30],
        'valuation' => ['title' => ['en' => 'Valuation and Disposal', 'ar' => 'التقييم والاستبعاد'], 'icon' => 'balance-scale', 'order' => 40],
        'support' => ['title' => ['en' => 'Asset Support', 'ar' => 'خدمات الأصول'], 'icon' => 'folder-open', 'order' => 50],
    ],
    'screens' => [
        $screen('asset-categories', 'Asset Categories', 'فئات الأصول', 'setup', 'master'),
        $screen('asset-groups', 'Asset Groups', 'مجموعات الأصول', 'setup', 'master'),
        $screen('asset-locations', 'Asset Locations', 'مواقع الأصول', 'setup', 'master'),
        $screen('asset-acquisition', 'Asset Acquisition', 'اقتناء الأصل'),
        $screen('asset-capitalization', 'Asset Capitalization', 'رسملة الأصل'),
        $screen('asset-opening-balances', 'Asset Opening Balances', 'أرصدة الأصول الافتتاحية'),
        $screen('asset-transfer', 'Asset Transfer', 'تحويل الأصل'),
        $screen('asset-custody', 'Asset Custody', 'عهدة الأصل'),
        $screen('asset-assignment', 'Asset Assignment', 'تخصيص الأصل'),
        $screen('asset-return', 'Asset Return', 'إرجاع الأصل'),
        $screen('asset-improvement', 'Asset Improvement', 'تحسين الأصل'),
        $screen('asset-component-replacement', 'Asset Component Replacement', 'استبدال مكون الأصل'),
        $screen('asset-depreciation-setup', 'Asset Depreciation Setup', 'إعداد إهلاك الأصل', 'depreciation', 'setup'),
        $screen('depreciation-run', 'Depreciation Run', 'تشغيل الإهلاك', 'depreciation'),
        $screen('depreciation-review', 'Depreciation Review', 'مراجعة الإهلاك', 'depreciation', 'inquiry'),
        $screen('asset-revaluation', 'Asset Revaluation', 'إعادة تقييم الأصل', 'valuation'),
        $screen('asset-impairment', 'Asset Impairment', 'اضمحلال الأصل', 'valuation'),
        $screen('asset-disposal', 'Asset Disposal', 'استبعاد الأصل', 'valuation'),
        $screen('asset-sale', 'Asset Sale', 'بيع الأصل', 'valuation'),
        $screen('asset-retirement', 'Asset Retirement', 'تكهين الأصل', 'valuation'),
        $screen('asset-maintenance-schedule', 'Asset Maintenance Schedule', 'جدول صيانة الأصل', 'support'),
        $screen('asset-inspection', 'Asset Inspection', 'فحص الأصل', 'support'),
        $screen('asset-documents', 'Asset Documents', 'مستندات الأصل', 'support'),
        $screen('asset-insurance', 'Asset Insurance', 'تأمين الأصل', 'support'),
        $screen('asset-history', 'Asset History', 'سجل الأصل', 'support', 'inquiry'),
    ],
];
