<?php

$screen = static fn (string $slug, string $en, string $ar, string $group = 'employee_relations', string $profile = 'document', array $extra = []): array => [
    'key' => 'hr_'.str_replace('-', '_', $slug),
    'slug' => $slug,
    'title' => ['en' => $en, 'ar' => $ar],
    'group' => $group,
    'profile' => $profile,
    'menu_visible' => false,
    ...$extra,
];

return [
    'module' => 'hr',
    'title' => ['en' => 'Human Resources', 'ar' => 'الموارد البشرية'],
    'route_segment' => 'hr',
    'route_name' => 'hr',
    'permission_prefix' => 'hr',
    'menu' => ['label' => 'human_resources', 'title' => ['en' => 'Human Resources', 'ar' => 'الموارد البشرية'], 'icon' => 'users', 'order' => 130],
    'groups' => [
        'contracts' => ['title' => ['en' => 'Contracts', 'ar' => 'العقود'], 'icon' => 'file-contract', 'order' => 10],
        'attendance' => ['title' => ['en' => 'Attendance and Time', 'ar' => 'الحضور والوقت'], 'icon' => 'clock', 'order' => 20],
        'leave' => ['title' => ['en' => 'Leave and Permissions', 'ar' => 'الإجازات والأذونات'], 'icon' => 'calendar-check', 'order' => 30],
        'employee_relations' => ['title' => ['en' => 'Employee Relations', 'ar' => 'شؤون العاملين'], 'icon' => 'user-tie', 'order' => 40],
        'development' => ['title' => ['en' => 'Performance and Development', 'ar' => 'الأداء والتطوير'], 'icon' => 'graduation-cap', 'order' => 50],
        'payroll' => ['title' => ['en' => 'Payroll', 'ar' => 'الرواتب'], 'icon' => 'money-bill-wave', 'order' => 60],
        'requests' => ['title' => ['en' => 'HR Requests and History', 'ar' => 'طلبات وسجل الموارد البشرية'], 'icon' => 'folder-open', 'order' => 70],
    ],
    'screens' => [
        $screen('employee-contracts', 'Employee Contracts', 'عقود الموظفين', 'contracts'),
        $screen('employee-contract-renewals', 'Employee Contract Renewals', 'تجديدات عقود الموظفين', 'contracts'),
        $screen('employee-attendance', 'Employee Attendance', 'حضور الموظفين', 'attendance', 'document', ['shell_enabled' => false, 'classification' => 'CANONICAL', 'actions' => ['view', 'manage', 'correct', 'export']]),
        $screen('attendance-import', 'Attendance Import', 'استيراد الحضور', 'attendance'),
        $screen('attendance-corrections', 'Attendance Corrections', 'تصحيحات الحضور', 'attendance'),
        $screen('shift-assignments', 'Shift Assignments', 'تخصيص الورديات', 'attendance', 'document', ['shell_enabled' => false, 'classification' => 'CANONICAL', 'actions' => ['view', 'manage']]),
        $screen('employee-leave-requests', 'Employee Leave Requests', 'طلبات إجازات الموظفين', 'leave'),
        $screen('leave-approvals', 'Leave Approvals', 'اعتمادات الإجازات', 'leave'),
        $screen('employee-permissions', 'Employee Permissions', 'أذونات الموظفين', 'leave'),
        $screen('overtime-requests', 'Overtime Requests', 'طلبات العمل الإضافي', 'attendance'),
        $screen('overtime-approvals', 'Overtime Approvals', 'اعتمادات العمل الإضافي', 'attendance'),
        $screen('employee-advances', 'Employee Advances', 'سلف الموظفين'),
        $screen('employee-custody', 'Employee Custody', 'عهد الموظفين'),
        $screen('employee-evaluations', 'Employee Evaluations', 'تقييمات الموظفين', 'development'),
        $screen('training-requests', 'Training Requests', 'طلبات التدريب', 'development'),
        $screen('training-courses', 'Training Courses', 'الدورات التدريبية', 'development'),
        $screen('disciplinary-actions', 'Disciplinary Actions', 'الإجراءات التأديبية'),
        $screen('employee-complaints', 'Employee Complaints', 'شكاوى الموظفين'),
        $screen('employee-documents', 'Employee Documents', 'مستندات الموظفين'),
        $screen('employee-medical-records', 'Employee Medical Records UI', 'واجهة السجلات الطبية للموظفين'),
        $screen('employee-insurance', 'Employee Insurance UI', 'واجهة تأمينات الموظفين'),
        $screen('payroll-periods', 'Payroll Periods', 'فترات الرواتب', 'payroll', 'master'),
        $screen('payroll-preparation', 'Payroll Preparation', 'إعداد الرواتب', 'payroll', 'document', [
            'shell_enabled' => false,
            'menu_visible' => false,
            'classification' => 'CANONICAL',
            'actions' => ['view', 'calculate'],
        ]),
        $screen('payroll-review', 'Payroll Review', 'مراجعة الرواتب', 'payroll'),
        $screen('payroll-approval', 'Payroll Approval', 'اعتماد الرواتب', 'payroll'),
        $screen('payroll-payment', 'Payroll Payment', 'صرف الرواتب', 'payroll'),
        $screen('employee-settlement', 'Employee Settlement', 'تسوية الموظف', 'payroll'),
        $screen('end-of-service', 'End of Service', 'نهاية الخدمة', 'payroll'),
        $screen('hr-requests', 'HR Requests', 'طلبات الموارد البشرية', 'requests', 'document', ['shell_enabled' => false, 'classification' => 'CANONICAL', 'actions' => ['view', 'manage']]),
        $screen('hr-attachments', 'HR Attachments', 'مرفقات الموارد البشرية', 'requests'),
        $screen('hr-history', 'HR History', 'سجل الموارد البشرية', 'requests', 'inquiry'),
    ],
];
