<?php

$screen = static fn (string $slug, string $en, string $ar, string $group = 'transactions', string $profile = 'document', array $extra = []): array => [
    'key' => 'inventory_'.str_replace('-', '_', $slug),
    'slug' => $slug,
    'title' => ['en' => $en, 'ar' => $ar],
    'group' => $group,
    'profile' => $profile,
    'shell_enabled' => true,
    'menu_visible' => true,
    'classification' => 'UI_SURFACE_PENDING_DEEP_WORKFLOW',
    ...$extra,
];

return [
    'module' => 'inventory',
    'title' => ['en' => 'Inventory and Warehouses', 'ar' => 'المخزون والمخازن'],
    'route_segment' => 'inventory',
    'route_name' => 'inventory',
    'permission_prefix' => 'inventory',
    'menu' => ['label' => 'inventory', 'title' => ['en' => 'Inventory and Warehouses', 'ar' => 'المخزون والمخازن'], 'icon' => 'warehouse', 'order' => 60],
    'groups' => [
        'structure' => ['title' => ['en' => 'Warehouse Structure', 'ar' => 'هيكل المخازن'], 'icon' => 'warehouse', 'order' => 10],
        'transactions' => ['title' => ['en' => 'Inventory Transactions', 'ar' => 'حركات المخزون'], 'icon' => 'exchange-alt', 'order' => 20],
        'counting' => ['title' => ['en' => 'Stock Counting', 'ar' => 'جرد المخزون'], 'icon' => 'clipboard-check', 'order' => 30],
        'tracking' => ['title' => ['en' => 'Tracking and Stock Status', 'ar' => 'التتبع وحالة المخزون'], 'icon' => 'barcode', 'order' => 40],
        'operations' => ['title' => ['en' => 'Operational Issues and Receipts', 'ar' => 'الصرف والاستلام التشغيلي'], 'icon' => 'dolly', 'order' => 50],
        'inquiries' => ['title' => ['en' => 'Inventory Inquiries', 'ar' => 'استعلامات المخزون'], 'icon' => 'search', 'order' => 60],
        'planning' => ['title' => ['en' => 'Inventory Planning', 'ar' => 'تخطيط المخزون'], 'icon' => 'chart-line', 'order' => 70],
    ],
    'screens' => [
        $screen('warehouses', 'Warehouses', 'المستودعات', 'structure', 'master'),
        $screen('warehouse-locations', 'Warehouse Locations', 'مواقع المخازن', 'structure', 'master'),
        $screen('warehouse-zones', 'Warehouse Zones', 'مناطق المخازن', 'structure', 'master'),
        $screen('warehouse-bins', 'Warehouse Bins', 'خانات المخازن', 'structure', 'master'),
        $screen('stock-receipts', 'Stock Receipts', 'إيصالات المخزون'),
        $screen('goods-receipt-posting', 'Goods Receipt Posting', 'ترحيل استلام البضاعة'),
        $screen('material-issue-vouchers', 'Material Issue Vouchers', 'أذون صرف الخامات'),
        $screen('material-return-vouchers', 'Material Return Vouchers', 'أذون مرتجع الخامات'),
        $screen('inventory-transfer-requests', 'Inventory Transfer Requests', 'طلبات تحويل المخزون'),
        $screen('inventory-transfer-vouchers', 'Inventory Transfer Vouchers', 'أذون تحويل المخزون'),
        $screen('store-to-store-transfers', 'Store-to-Store Transfers', 'تحويلات مخزن إلى مخزن'),
        $screen('branch-to-branch-transfers', 'Branch-to-Branch Transfers', 'تحويلات فرع إلى فرع'),
        $screen('hall-transfers', 'Hall Transfers', 'تحويلات الصالات'),
        $screen('location-transfers', 'Location Transfers', 'تحويلات المواقع'),
        $screen('stock-adjustments', 'Stock Adjustments', 'تسويات المخزون'),
        $screen('adjustment-in', 'Adjustment In', 'تسوية بالزيادة'),
        $screen('adjustment-out', 'Adjustment Out', 'تسوية بالنقص'),
        $screen('stock-count-plans', 'Stock Count Plans', 'خطط الجرد', 'counting'),
        $screen('stock-count-sheets', 'Stock Count Sheets', 'أوراق الجرد', 'counting'),
        $screen('stock-count-entry', 'Stock Count Entry', 'إدخال الجرد', 'counting'),
        $screen('stock-count-differences', 'Stock Count Differences', 'فروق الجرد', 'counting'),
        $screen('stock-count-approval', 'Stock Count Approval', 'اعتماد الجرد', 'counting'),
        $screen('inventory-reservations', 'Inventory Reservations', 'حجوزات المخزون', 'tracking'),
        $screen('reservation-release', 'Reservation Release', 'فك حجز المخزون', 'tracking'),
        $screen('batch-lot-definitions', 'Batch / Lot Definitions', 'تعريفات التشغيلات / اللوطات', 'tracking', 'master'),
        $screen('batch-receipt', 'Batch Receipt', 'استلام التشغيلات', 'tracking'),
        $screen('batch-issue', 'Batch Issue', 'صرف التشغيلات', 'tracking'),
        $screen('serial-number-tracking', 'Serial Number Tracking', 'تتبع الأرقام المسلسلة', 'tracking'),
        $screen('expiry-tracking', 'Expiry Tracking', 'تتبع الصلاحية', 'tracking'),
        $screen('quarantine-stock', 'Quarantine Stock', 'مخزون الحجر', 'tracking', 'inquiry'),
        $screen('quality-hold-stock', 'Quality Hold Stock', 'مخزون موقوف للجودة', 'tracking', 'inquiry'),
        $screen('released-stock', 'Released Stock', 'المخزون المفرج عنه', 'tracking', 'inquiry'),
        $screen('damaged-stock', 'Damaged Stock', 'المخزون التالف', 'tracking', 'inquiry'),
        $screen('scrap-stock', 'Scrap Stock', 'مخزون الهالك', 'tracking', 'inquiry'),
        $screen('waste-stock', 'Waste Stock', 'مخزون الفاقد', 'tracking', 'inquiry'),
        $screen('packaging-issue', 'Packaging Issue', 'صرف مواد التعبئة', 'operations'),
        $screen('packaging-return', 'Packaging Return', 'مرتجع مواد التعبئة', 'operations'),
        $screen('finished-goods-receipt', 'Finished Goods Receipt', 'استلام الإنتاج التام', 'operations'),
        $screen('production-material-issue', 'Production Material Issue', 'صرف خامات الإنتاج', 'operations'),
        $screen('production-material-return', 'Production Material Return', 'مرتجع خامات الإنتاج', 'operations'),
        $screen('sales-delivery-issue', 'Sales Delivery Issue', 'صرف تسليم المبيعات', 'operations'),
        $screen('purchase-return-issue', 'Purchase Return Issue', 'صرف مردود المشتريات', 'operations'),
        $screen('inventory-transaction-viewer', 'Inventory Transaction Viewer', 'عارض حركات المخزون', 'inquiries', 'inquiry'),
        $screen('stock-balance-inquiry', 'Stock Balance Inquiry', 'استعلام رصيد المخزون', 'inquiries', 'inquiry'),
        $screen('stock-card-inquiry', 'Stock Card Inquiry', 'استعلام كارت الصنف', 'inquiries', 'inquiry'),
        $screen('negative-stock-review', 'Negative Stock Review', 'مراجعة المخزون السالب', 'inquiries', 'inquiry'),
        $screen('reorder-suggestions', 'Reorder Suggestions', 'مقترحات إعادة الطلب', 'planning', 'inquiry'),
        $screen('slow-moving-stock', 'Slow Moving Stock', 'المخزون بطيء الحركة', 'planning', 'inquiry'),
        $screen('dead-stock', 'Dead Stock', 'المخزون الراكد', 'planning', 'inquiry'),
        $screen('stock-aging', 'Stock Aging', 'أعمار المخزون', 'planning', 'inquiry'),
    ],
];
