<?php

$screen = static fn (string $slug, string $en, string $ar, string $group = 'work_orders', string $profile = 'document', array $extra = []): array => [
    'key' => 'maintenance_'.str_replace('-', '_', $slug),
    'slug' => $slug,
    'title' => ['en' => $en, 'ar' => $ar],
    'group' => $group,
    'profile' => $profile,
    ...$extra,
];

return [
    'module' => 'maintenance',
    'title' => ['en' => 'Maintenance', 'ar' => 'الصيانة'],
    'route_segment' => 'maintenance',
    'route_name' => 'maintenance',
    'permission_prefix' => 'maintenance',
    'menu' => ['label' => 'maintenance', 'title' => ['en' => 'Maintenance', 'ar' => 'الصيانة'], 'icon' => 'tools', 'order' => 90],
    'groups' => [
        'setup' => ['title' => ['en' => 'Maintenance Setup', 'ar' => 'إعدادات الصيانة'], 'icon' => 'cogs', 'order' => 10],
        'registers' => ['title' => ['en' => 'Asset Registers', 'ar' => 'سجلات الأصول'], 'icon' => 'industry', 'order' => 20],
        'requests' => ['title' => ['en' => 'Maintenance Requests', 'ar' => 'طلبات الصيانة'], 'icon' => 'clipboard', 'order' => 30],
        'work_orders' => ['title' => ['en' => 'Maintenance Work Orders', 'ar' => 'أوامر الصيانة'], 'icon' => 'wrench', 'order' => 40],
        'preventive' => ['title' => ['en' => 'Preventive Maintenance', 'ar' => 'الصيانة الوقائية'], 'icon' => 'calendar-check', 'order' => 50],
        'inspections' => ['title' => ['en' => 'Inspection and Metering', 'ar' => 'الفحص والقياسات'], 'icon' => 'tachometer-alt', 'order' => 60],
        'history' => ['title' => ['en' => 'Maintenance History', 'ar' => 'سجل الصيانة'], 'icon' => 'history', 'order' => 70],
        'external' => ['title' => ['en' => 'External Maintenance', 'ar' => 'الصيانة الخارجية'], 'icon' => 'truck', 'order' => 80],
    ],
    'screens' => [
        $screen('maintenance-settings', 'Maintenance Settings', 'إعدادات الصيانة', 'setup', 'setup'),
        $screen('maintenance-asset-types', 'Maintenance Asset Types', 'أنواع أصول الصيانة', 'setup', 'master'),
        $screen('machine-register', 'Machine Register', 'سجل الماكينات', 'registers', 'master'),
        $screen('mold-register', 'Mold Register', 'سجل الاسطمبات', 'registers', 'master'),
        $screen('tool-register', 'Tool Register', 'سجل العدد', 'registers', 'master'),
        $screen('spare-parts-register', 'Spare Parts Register', 'سجل قطع الغيار', 'registers', 'master'),
        $screen('maintenance-departments', 'Maintenance Departments', 'إدارات الصيانة', 'setup', 'master'),
        $screen('maintenance-teams', 'Maintenance Teams', 'فرق الصيانة', 'setup', 'master'),
        $screen('technicians', 'Technicians', 'الفنيون', 'setup', 'master'),
        $screen('maintenance-priorities', 'Maintenance Priorities', 'أولويات الصيانة', 'setup', 'master'),
        $screen('failure-types', 'Failure Types', 'أنواع الأعطال', 'setup', 'master'),
        $screen('failure-causes', 'Failure Causes', 'أسباب الأعطال', 'setup', 'master'),
        $screen('maintenance-request', 'Maintenance Request', 'طلب صيانة', 'requests'),
        $screen('breakdown-request', 'Breakdown Request', 'طلب عطل', 'requests'),
        $screen('preventive-maintenance-request', 'Preventive Maintenance Request', 'طلب صيانة وقائية', 'requests'),
        $screen('corrective-maintenance-request', 'Corrective Maintenance Request', 'طلب صيانة تصحيحية', 'requests'),
        $screen('emergency-maintenance-request', 'Emergency Maintenance Request', 'طلب صيانة طارئة', 'requests'),
        $screen('maintenance-work-orders', 'Maintenance Work Orders', 'أوامر عمل الصيانة'),
        $screen('maintenance-work-order-lines', 'Maintenance Work Order Lines', 'سطور أوامر عمل الصيانة'),
        $screen('maintenance-tasks', 'Maintenance Tasks', 'مهام الصيانة'),
        $screen('maintenance-checklists', 'Maintenance Checklists', 'قوائم فحص الصيانة'),
        $screen('maintenance-labor', 'Maintenance Labor', 'عمالة الصيانة'),
        $screen('maintenance-spare-parts', 'Maintenance Spare Parts', 'قطع غيار الصيانة'),
        $screen('spare-part-issue', 'Spare Part Issue', 'صرف قطع الغيار'),
        $screen('spare-part-return', 'Spare Part Return', 'مرتجع قطع الغيار'),
        $screen('preventive-maintenance-plans', 'Preventive Maintenance Plans', 'خطط الصيانة الوقائية', 'preventive'),
        $screen('preventive-maintenance-schedule', 'Preventive Maintenance Schedule', 'جدول الصيانة الوقائية', 'preventive'),
        $screen('daily-maintenance-schedule', 'Daily Maintenance Schedule', 'جدول الصيانة اليومي', 'preventive'),
        $screen('weekly-maintenance-schedule', 'Weekly Maintenance Schedule', 'جدول الصيانة الأسبوعي', 'preventive'),
        $screen('monthly-maintenance-schedule', 'Monthly Maintenance Schedule', 'جدول الصيانة الشهري', 'preventive'),
        $screen('machine-inspection', 'Machine Inspection', 'فحص الماكينة', 'inspections'),
        $screen('mold-inspection', 'Mold Inspection', 'فحص الاسطمبة', 'inspections'),
        $screen('tool-inspection', 'Tool Inspection', 'فحص العدد', 'inspections'),
        $screen('meter-readings', 'Meter Readings', 'قراءات العدادات', 'inspections'),
        $screen('operating-hours', 'Operating Hours', 'ساعات التشغيل', 'inspections'),
        $screen('maintenance-downtime', 'Maintenance Downtime', 'توقفات الصيانة', 'inspections'),
        $screen('machine-breakdown-history', 'Machine Breakdown History', 'سجل أعطال الماكينات', 'history', 'inquiry'),
        $screen('mold-maintenance-history', 'Mold Maintenance History', 'سجل صيانة الاسطمبات', 'history', 'inquiry'),
        $screen('tool-maintenance-history', 'Tool Maintenance History', 'سجل صيانة العدد', 'history', 'inquiry'),
        $screen('calibration-schedule', 'Calibration Schedule', 'جدول المعايرة', 'inspections'),
        $screen('calibration-entry', 'Calibration Entry', 'إدخال المعايرة', 'inspections'),
        $screen('maintenance-completion', 'Maintenance Completion', 'إتمام الصيانة'),
        $screen('maintenance-approval', 'Maintenance Approval', 'اعتماد الصيانة'),
        $screen('maintenance-closing', 'Maintenance Closing', 'إغلاق الصيانة'),
        $screen('external-maintenance', 'External Maintenance', 'الصيانة الخارجية', 'external'),
        $screen('maintenance-supplier-invoice-link', 'Maintenance Supplier Invoice Link', 'ربط فاتورة مورد الصيانة', 'external'),
        $screen('maintenance-attachments', 'Maintenance Attachments', 'مرفقات الصيانة', 'history'),
        $screen('maintenance-history', 'Maintenance History', 'سجل الصيانة', 'history', 'inquiry'),
    ],
];
