<?php

$screen = static fn (string $slug, string $en, string $ar, string $group = 'execution', string $profile = 'document', array $extra = []): array => [
    'key' => 'production_'.str_replace('-', '_', $slug),
    'slug' => $slug,
    'title' => ['en' => $en, 'ar' => $ar],
    'group' => $group,
    'profile' => $profile,
    'shell_enabled' => false,
    'menu_visible' => false,
    ...$extra,
];

return [
    'module' => 'production',
    'title' => ['en' => 'Planning and Production', 'ar' => 'التخطيط والإنتاج'],
    'route_segment' => 'production',
    'route_name' => 'production',
    'permission_prefix' => 'production',
    'menu' => ['label' => 'planning_production', 'title' => ['en' => 'Planning and Production', 'ar' => 'التخطيط والإنتاج'], 'icon' => 'industry', 'order' => 70],
    'groups' => [
        'setup' => ['title' => ['en' => 'Production Setup', 'ar' => 'إعدادات الإنتاج'], 'icon' => 'cogs', 'order' => 10],
        'engineering' => ['title' => ['en' => 'Production Engineering', 'ar' => 'هندسة الإنتاج'], 'icon' => 'drafting-compass', 'order' => 20],
        'planning' => ['title' => ['en' => 'Production Planning', 'ar' => 'تخطيط الإنتاج'], 'icon' => 'calendar-alt', 'order' => 30],
        'work_orders' => ['title' => ['en' => 'Work Orders', 'ar' => 'أوامر التشغيل'], 'icon' => 'clipboard-list', 'order' => 40],
        'materials' => ['title' => ['en' => 'Materials', 'ar' => 'الخامات'], 'icon' => 'boxes', 'order' => 50],
        'execution' => ['title' => ['en' => 'Production Execution', 'ar' => 'تنفيذ الإنتاج'], 'icon' => 'play-circle', 'order' => 60],
        'monitoring' => ['title' => ['en' => 'Monitoring and Allocation', 'ar' => 'المتابعة والتخصيص'], 'icon' => 'chart-line', 'order' => 70],
        'external' => ['title' => ['en' => 'External Manufacturing', 'ar' => 'التصنيع الخارجي'], 'icon' => 'truck-loading', 'order' => 80],
    ],
    'screens' => [
        $screen('production-settings', 'Production Settings', 'إعدادات الإنتاج', 'setup', 'setup'),
        $screen('production-calendars', 'Production Calendars', 'تقويمات الإنتاج', 'setup', 'master'),
        $screen('production-shifts', 'Production Shifts', 'ورديات الإنتاج', 'setup', 'master'),
        $screen('production-lines', 'Production Lines', 'خطوط الإنتاج', 'setup', 'master'),
        $screen('production-departments', 'Production Departments', 'إدارات الإنتاج', 'setup', 'master'),
        $screen('production-work-centers', 'Production Work Centers', 'مراكز عمل الإنتاج', 'setup', 'master'),
        $screen('machines', 'Machines', 'الماكينات', 'engineering', 'master'),
        $screen('molds', 'Molds', 'الاسطمبات', 'engineering', 'master'),
        $screen('tools', 'Tools', 'العدد والأدوات', 'engineering', 'master'),
        $screen('production-stages', 'Production Stages', 'مراحل الإنتاج', 'engineering', 'master'),
        $screen('production-routing', 'Production Routing', 'مسارات الإنتاج', 'engineering'),
        $screen('bom-versions', 'BOM Versions', 'إصدارات قوائم المكونات', 'engineering'),
        $screen('bom-approval', 'BOM Approval', 'اعتماد قوائم المكونات', 'engineering'),
        $screen('master-production-schedule', 'Master Production Schedule', 'الجدول الرئيسي للإنتاج', 'planning'),
        $screen('production-forecast', 'Production Forecast', 'توقعات الإنتاج', 'planning'),
        $screen('production-plan', 'Production Plan', 'خطة الإنتاج', 'planning'),
        $screen('weekly-production-plan', 'Weekly Production Plan', 'خطة الإنتاج الأسبوعية', 'planning'),
        $screen('daily-production-plan', 'Daily Production Plan', 'خطة الإنتاج اليومية', 'planning'),
        $screen('material-requirements-planning', 'Material Requirements Planning', 'تخطيط احتياجات الخامات', 'planning'),
        $screen('capacity-requirements-planning', 'Capacity Requirements Planning', 'تخطيط احتياجات الطاقة', 'planning'),
        $screen('machine-loading-plan', 'Machine Loading Plan', 'خطة تحميل الماكينات', 'planning'),
        $screen('mold-loading-plan', 'Mold Loading Plan', 'خطة تحميل الاسطمبات', 'planning'),
        $screen('work-orders', 'Work Orders', 'أوامر التشغيل', 'work_orders', 'document', [
            'shell_enabled' => false,
            'permission_prefix' => 'production.work_orders',
            'actions' => ['view', 'complete', 'print'],
            'modes' => ['index', 'view'],
        ]),
        $screen('work-order-lines', 'Work Order Lines', 'سطور أوامر التشغيل', 'work_orders'),
        $screen('work-order-materials', 'Work Order Materials', 'خامات أوامر التشغيل', 'work_orders'),
        $screen('work-order-operations', 'Work Order Operations', 'عمليات أوامر التشغيل', 'work_orders'),
        $screen('work-order-specifications', 'Work Order Specifications', 'مواصفات أوامر التشغيل', 'work_orders'),
        $screen('work-order-attachments', 'Work Order Attachments', 'مرفقات أوامر التشغيل', 'work_orders'),
        $screen('work-order-approval', 'Work Order Approval', 'اعتماد أمر التشغيل', 'work_orders'),
        $screen('work-order-release', 'Work Order Release', 'إطلاق أمر التشغيل', 'work_orders'),
        $screen('work-order-start', 'Work Order Start', 'بدء أمر التشغيل', 'work_orders'),
        $screen('work-order-pause', 'Work Order Pause', 'إيقاف أمر التشغيل مؤقتا', 'work_orders'),
        $screen('work-order-resume', 'Work Order Resume', 'استئناف أمر التشغيل', 'work_orders'),
        $screen('work-order-completion', 'Work Order Completion', 'إتمام أمر التشغيل', 'work_orders'),
        $screen('work-order-closing', 'Work Order Closing', 'إغلاق أمر التشغيل', 'work_orders'),
        $screen('production-batch-orders', 'Production Batch Orders', 'أوامر تشغيل الدفعات', 'work_orders'),
        $screen('batch-material-requirements', 'Batch Material Requirements', 'احتياجات خامات الدفعات', 'materials'),
        $screen('material-requests', 'Material Requests', 'طلبات الخامات', 'materials'),
        $screen('material-request-lines', 'Material Request Lines', 'سطور طلبات الخامات', 'materials'),
        $screen('material-issue-request', 'Material Issue Request', 'طلب صرف الخامات', 'materials'),
        $screen('material-consumption', 'Material Consumption', 'استهلاك الخامات', 'materials'),
        $screen('production-output-receipt', 'Production Output Receipt', 'استلام ناتج الإنتاج'),
        $screen('production-output-lines', 'Production Output Lines', 'سطور ناتج الإنتاج'),
        $screen('semi-finished-output', 'Semi-Finished Output', 'ناتج نصف مصنع'),
        $screen('finished-goods-output', 'Finished Goods Output', 'ناتج تام الصنع'),
        $screen('production-scrap', 'Production Scrap', 'هالك الإنتاج'),
        $screen('production-waste', 'Production Waste', 'فاقد الإنتاج'),
        $screen('production-rework', 'Production Rework', 'إعادة تشغيل الإنتاج'),
        $screen('rework-orders', 'Rework Orders', 'أوامر إعادة التشغيل'),
        $screen('shift-production-entry', 'Shift Production Entry', 'إدخال إنتاج الوردية'),
        $screen('machine-production-entry', 'Machine Production Entry', 'إدخال إنتاج الماكينة'),
        $screen('mold-change-entry', 'Mold Change Entry', 'إدخال تغيير الاسطمبة'),
        $screen('production-downtime', 'Production Downtime', 'توقف الإنتاج', 'monitoring'),
        $screen('production-stops', 'Production Stops', 'توقفات الإنتاج', 'monitoring'),
        $screen('production-delays', 'Production Delays', 'تأخيرات الإنتاج', 'monitoring'),
        $screen('production-employee-allocation', 'Production Employee Allocation', 'تخصيص موظفي الإنتاج', 'monitoring'),
        $screen('production-notes', 'Production Notes', 'ملاحظات الإنتاج', 'monitoring'),
        $screen('production-checklist', 'Production Checklist', 'قائمة فحص الإنتاج', 'monitoring'),
        $screen('project-allocation', 'Project Allocation', 'تخصيص المشروع', 'monitoring'),
        $screen('contract-identifier-allocation', 'Contract Identifier Allocation', 'تخصيص معرفات العقد', 'monitoring'),
        $screen('material-requirements-summary', 'Material Requirements Summary', 'ملخص احتياجات الخامات', 'monitoring', 'inquiry'),
        $screen('external-manufacturing-orders', 'External Manufacturing Orders', 'أوامر التصنيع الخارجي', 'external'),
        $screen('external-manufacturing-materials', 'External Manufacturing Materials', 'خامات التصنيع الخارجي', 'external'),
        $screen('external-manufacturing-receipts', 'External Manufacturing Receipts', 'استلامات التصنيع الخارجي', 'external'),
        $screen('supplier-custody', 'Supplier Custody', 'عهدة المورد', 'external'),
        $screen('production-status-history', 'Production Status History', 'سجل حالات الإنتاج', 'monitoring', 'inquiry'),
    ],
];
