<?php

$screen = static fn (string $slug, string $en, string $ar, string $group = 'orders', string $profile = 'document', array $extra = []): array => [
    'key' => 'purchases_'.str_replace('-', '_', $slug),
    'slug' => $slug,
    'title' => ['en' => $en, 'ar' => $ar],
    'group' => $group,
    'profile' => $profile,
    ...$extra,
];

return [
    'module' => 'purchases',
    'title' => ['en' => 'Purchases', 'ar' => 'المشتريات'],
    'route_segment' => 'purchases',
    'route_name' => 'purchases',
    'permission_prefix' => 'purchases',
    'menu' => ['label' => 'purchases', 'title' => ['en' => 'Purchases', 'ar' => 'المشتريات'], 'icon' => 'shopping-bag', 'order' => 50],
    'groups' => [
        'requisitions' => ['title' => ['en' => 'Requisitions', 'ar' => 'طلبات الشراء'], 'icon' => 'clipboard', 'order' => 10],
        'sourcing' => ['title' => ['en' => 'Sourcing and Quotations', 'ar' => 'التوريد وعروض الموردين'], 'icon' => 'search-dollar', 'order' => 20],
        'orders' => ['title' => ['en' => 'Purchase Orders', 'ar' => 'أوامر الشراء'], 'icon' => 'clipboard-list', 'order' => 30],
        'receiving' => ['title' => ['en' => 'Receiving', 'ar' => 'الاستلام'], 'icon' => 'dolly', 'order' => 40],
        'billing' => ['title' => ['en' => 'Invoices and Payments', 'ar' => 'الفواتير والمدفوعات'], 'icon' => 'file-invoice-dollar', 'order' => 50],
        'supplier_management' => ['title' => ['en' => 'Supplier Management', 'ar' => 'إدارة الموردين'], 'icon' => 'truck', 'order' => 60],
        'special' => ['title' => ['en' => 'Special Purchases', 'ar' => 'المشتريات الخاصة'], 'icon' => 'bolt', 'order' => 70],
    ],
    'screens' => [
        $screen('purchase-requisitions', 'Purchase Requisitions', 'طلبات الشراء', 'requisitions'),
        $screen('purchase-requisition-lines', 'Purchase Requisition Lines', 'سطور طلبات الشراء', 'requisitions'),
        $screen('purchase-requisition-approvals', 'Purchase Requisition Approvals', 'اعتمادات طلبات الشراء', 'requisitions'),
        $screen('request-for-quotations', 'Request for Quotations', 'طلبات عروض الأسعار', 'sourcing'),
        $screen('supplier-quotation-entry', 'Supplier Quotation Entry', 'إدخال عرض المورد', 'sourcing'),
        $screen('supplier-quotation-lines', 'Supplier Quotation Lines', 'سطور عرض المورد', 'sourcing'),
        $screen('supplier-quotation-comparison', 'Supplier Quotation Comparison', 'مقارنة عروض الموردين', 'sourcing', 'inquiry'),
        $screen('supplier-selection', 'Supplier Selection', 'اختيار المورد', 'sourcing'),
        $screen('purchase-order-lines', 'Purchase Order Lines', 'سطور أوامر الشراء'),
        $screen('purchase-order-approvals', 'Purchase Order Approvals', 'اعتمادات أوامر الشراء'),
        $screen('purchase-order-change-requests', 'Purchase Order Change Requests', 'طلبات تغيير أوامر الشراء'),
        $screen('purchase-order-delivery-schedule', 'Purchase Order Delivery Schedule', 'جدول تسليم أمر الشراء'),
        $screen('goods-receipt-notes', 'Goods Receipt Notes', 'أذون استلام البضاعة', 'receiving'),
        $screen('goods-receipt-lines', 'Goods Receipt Lines', 'سطور أذون الاستلام', 'receiving'),
        $screen('goods-receipt-inspection', 'Goods Receipt Inspection', 'فحص استلام البضاعة', 'receiving'),
        $screen('purchase-invoice-lines', 'Purchase Invoice Lines', 'سطور فواتير المشتريات', 'billing'),
        $screen('purchase-invoice-payments', 'Purchase Invoice Payments', 'مدفوعات فواتير المشتريات', 'billing'),
        $screen('purchase-invoice-allocations', 'Purchase Invoice Allocations', 'تخصيص فواتير المشتريات', 'billing'),
        $screen('purchase-returns', 'Purchase Returns', 'مردودات المشتريات', 'billing'),
        $screen('purchase-return-lines', 'Purchase Return Lines', 'سطور مردودات المشتريات', 'billing'),
        $screen('supplier-advances', 'Supplier Advances', 'دفعات الموردين المقدمة', 'billing'),
        $screen('supplier-payments', 'Supplier Payments', 'مدفوعات الموردين', 'billing', 'document', ['permission_prefix' => 'supplier_payments']),
        $screen('supplier-payment-allocations', 'Supplier Payment Allocations', 'تخصيص مدفوعات الموردين', 'billing'),
        $screen('supplier-debit-notes', 'Supplier Debit Notes', 'إشعارات خصم الموردين', 'billing'),
        $screen('supplier-credit-notes', 'Supplier Credit Notes', 'إشعارات إضافة الموردين', 'billing'),
        $screen('supplier-contracts', 'Supplier Contracts', 'عقود الموردين', 'supplier_management'),
        $screen('supplier-contract-milestones', 'Supplier Contract Milestones', 'مراحل عقود الموردين', 'supplier_management'),
        $screen('supplier-evaluation', 'Supplier Evaluation', 'تقييم الموردين', 'supplier_management'),
        $screen('supplier-price-lists', 'Supplier Price Lists', 'قوائم أسعار الموردين', 'supplier_management'),
        $screen('supplier-product-catalog', 'Supplier Product Catalog', 'دليل منتجات الموردين', 'supplier_management'),
        $screen('supplier-attachments', 'Supplier Attachments', 'مرفقات الموردين', 'supplier_management'),
        $screen('supplier-complaints', 'Supplier Complaints', 'شكاوى الموردين', 'supplier_management'),
        $screen('external-service-purchase-orders', 'External Service Purchase Orders', 'أوامر شراء الخدمات الخارجية', 'special'),
        $screen('direct-production-purchases', 'Direct Production Purchases', 'مشتريات الإنتاج المباشرة', 'special'),
        $screen('emergency-purchases', 'Emergency Purchases', 'المشتريات الطارئة', 'special'),
    ],
];
