<?php

$screen = static fn (string $slug, string $en, string $ar, string $group = 'inspections', string $profile = 'document', array $extra = []): array => [
    'key' => 'quality_'.str_replace('-', '_', $slug),
    'slug' => $slug,
    'title' => ['en' => $en, 'ar' => $ar],
    'group' => $group,
    'profile' => $profile,
    ...$extra,
];

return [
    'module' => 'quality',
    'title' => ['en' => 'Quality', 'ar' => 'الجودة'],
    'route_segment' => 'quality',
    'route_name' => 'quality',
    'permission_prefix' => 'quality',
    'menu' => ['label' => 'quality', 'title' => ['en' => 'Quality', 'ar' => 'الجودة'], 'icon' => 'clipboard-check', 'order' => 80],
    'groups' => [
        'setup' => ['title' => ['en' => 'Quality Setup', 'ar' => 'إعدادات الجودة'], 'icon' => 'cogs', 'order' => 10],
        'plans' => ['title' => ['en' => 'Inspection Planning', 'ar' => 'تخطيط الفحص'], 'icon' => 'clipboard-list', 'order' => 20],
        'inspections' => ['title' => ['en' => 'Inspections', 'ar' => 'الفحوصات'], 'icon' => 'microscope', 'order' => 30],
        'decisions' => ['title' => ['en' => 'Quality Decisions', 'ar' => 'قرارات الجودة'], 'icon' => 'gavel', 'order' => 40],
        'capa' => ['title' => ['en' => 'Non-Conformance and CAPA', 'ar' => 'عدم المطابقة والإجراءات التصحيحية'], 'icon' => 'exclamation-triangle', 'order' => 50],
        'certificates' => ['title' => ['en' => 'Certificates and Results', 'ar' => 'الشهادات والنتائج'], 'icon' => 'certificate', 'order' => 60],
        'audits' => ['title' => ['en' => 'Audits and Calibration', 'ar' => 'المراجعات والمعايرة'], 'icon' => 'search', 'order' => 70],
    ],
    'screens' => [
        $screen('quality-settings', 'Quality Settings', 'إعدادات الجودة', 'setup', 'setup'),
        $screen('quality-standards', 'Quality Standards', 'معايير الجودة', 'setup', 'master'),
        $screen('quality-parameters', 'Quality Parameters', 'معاملات الجودة', 'setup', 'master'),
        $screen('quality-characteristics', 'Quality Characteristics', 'خصائص الجودة', 'setup', 'master'),
        $screen('inspection-types', 'Inspection Types', 'أنواع الفحص', 'setup', 'master'),
        $screen('inspection-plans', 'Inspection Plans', 'خطط الفحص', 'plans'),
        $screen('sampling-plans', 'Sampling Plans', 'خطط أخذ العينات', 'plans'),
        $screen('test-methods', 'Test Methods', 'طرق الاختبار', 'plans', 'master'),
        $screen('laboratory-tests', 'Laboratory Tests', 'اختبارات المعمل', 'plans'),
        $screen('incoming-material-inspection', 'Incoming Material Inspection', 'فحص الخامات الواردة'),
        $screen('incoming-inspection-lines', 'Incoming Inspection Lines', 'سطور فحص الوارد'),
        $screen('goods-receipt-quality-inspection', 'Goods Receipt Quality Inspection', 'فحص جودة استلام البضاعة'),
        $screen('in-process-inspection', 'In-Process Inspection', 'الفحص أثناء التشغيل'),
        $screen('production-stage-inspection', 'Production Stage Inspection', 'فحص مرحلة الإنتاج'),
        $screen('finished-goods-inspection', 'Finished Goods Inspection', 'فحص الإنتاج التام'),
        $screen('packaging-inspection', 'Packaging Inspection', 'فحص التعبئة'),
        $screen('pre-delivery-inspection', 'Pre-Delivery Inspection', 'الفحص قبل التسليم'),
        $screen('quality-hold', 'Quality Hold', 'إيقاف الجودة', 'decisions'),
        $screen('quality-release', 'Quality Release', 'إفراج الجودة', 'decisions'),
        $screen('quality-rejection', 'Quality Rejection', 'رفض الجودة', 'decisions'),
        $screen('non-conformance-reports', 'Non-Conformance Reports', 'تقارير عدم المطابقة', 'capa'),
        $screen('non-conformance-lines', 'Non-Conformance Lines', 'سطور عدم المطابقة', 'capa'),
        $screen('corrective-actions', 'Corrective Actions', 'الإجراءات التصحيحية', 'capa'),
        $screen('preventive-actions', 'Preventive Actions', 'الإجراءات الوقائية', 'capa'),
        $screen('capa-follow-up', 'CAPA Follow-up', 'متابعة الإجراءات التصحيحية والوقائية', 'capa'),
        $screen('rework-approval', 'Rework Approval', 'اعتماد إعادة التشغيل', 'decisions'),
        $screen('scrap-approval', 'Scrap Approval', 'اعتماد الهالك', 'decisions'),
        $screen('customer-quality-complaint', 'Customer Quality Complaint', 'شكوى جودة من العميل', 'capa'),
        $screen('supplier-quality-complaint', 'Supplier Quality Complaint', 'شكوى جودة للمورد', 'capa'),
        $screen('quality-certificates', 'Quality Certificates', 'شهادات الجودة', 'certificates'),
        $screen('certificate-of-analysis', 'Certificate of Analysis', 'شهادة التحليل', 'certificates'),
        $screen('test-result-entry', 'Test Result Entry', 'إدخال نتائج الاختبار', 'certificates'),
        $screen('inspection-result-entry', 'Inspection Result Entry', 'إدخال نتائج الفحص', 'certificates'),
        $screen('quality-audit-plans', 'Quality Audit Plans', 'خطط مراجعة الجودة', 'audits'),
        $screen('internal-quality-audits', 'Internal Quality Audits', 'مراجعات الجودة الداخلية', 'audits'),
        $screen('quality-audit-findings', 'Quality Audit Findings', 'ملاحظات مراجعة الجودة', 'audits'),
        $screen('calibration-requirements', 'Calibration Requirements', 'متطلبات المعايرة', 'audits'),
        $screen('calibration-certificates', 'Calibration Certificates', 'شهادات المعايرة', 'audits'),
        $screen('quality-history', 'Quality History', 'سجل الجودة', 'audits', 'inquiry'),
    ],
];
