<?php

$screen = static fn (string $domain, string $slug, string $en, string $ar, array $extra = []): array => [
    'key' => 'reports_'.$domain.'_'.str_replace('-', '_', $slug),
    'slug' => $domain.'/'.$slug,
    'permission_prefix' => 'reports.'.$domain.'.'.str_replace('-', '_', $slug),
    'title' => ['en' => $en, 'ar' => $ar],
    'group' => $domain,
    'profile' => 'report',
    'kind' => 'report',
    'shell_enabled' => false,
    'menu_visible' => false,
    ...$extra,
];
$financeScreen = static fn (string $slug, string $en, string $ar): array => [
    ...$screen('finance', $slug, $en, $ar),
    'actions' => ['view', 'export', 'pdf'],
    'shell_enabled' => false,
    'menu_visible' => true,
    'classification' => 'WORKING_REAL_SCREEN',
    'canonical_route' => 'admin.reports.finance.'.$slug.'.index',
    'subgroup' => 'finance_reports',
    'group' => 'finance',
    'menu_title' => ['en' => $en, 'ar' => $ar],
];
$costingScreen = static fn (string $slug, string $en, string $ar): array => [
    ...$screen('costing', $slug, $en, $ar),
    'actions' => ['view', 'print', 'export'],
    'classification' => 'WORKING_REAL_SCREEN',
    'menu_visible' => true,
];

return [
    'module' => 'reports',
    'title' => ['en' => 'Reports', 'ar' => 'التقارير'],
    'route_segment' => 'reports',
    'route_name' => 'reports',
    'permission_prefix' => 'reports',
    'menu' => ['label' => 'reports', 'title' => ['en' => 'Reports', 'ar' => 'التقارير'], 'icon' => 'chart-bar', 'order' => 140],
    'groups' => [
        'finance' => ['title' => ['en' => 'Finance Reports', 'ar' => 'تقارير المالية'], 'icon' => 'money-check-alt', 'order' => 10],
        'sales' => ['title' => ['en' => 'Sales Reports', 'ar' => 'تقارير المبيعات'], 'icon' => 'shopping-cart', 'order' => 20],
        'purchases' => ['title' => ['en' => 'Purchases Reports', 'ar' => 'تقارير المشتريات'], 'icon' => 'shopping-bag', 'order' => 30],
        'costing' => ['title' => ['en' => 'Costing Reports', 'ar' => 'تقارير التكاليف'], 'icon' => 'calculator', 'order' => 80],
    ],
    'screens' => [
        $financeScreen('cashbox-balances', 'Cashbox Balances', 'أرصدة الخزائن'),
        $financeScreen('cashbox-statement', 'Cashbox Statement', 'كشف حساب الخزينة'),
        $financeScreen('cash-vouchers', 'Receipt and Payment Vouchers', 'سندات القبض والصرف'),
        $financeScreen('bank-account-balances', 'Bank Account Balances', 'أرصدة الحسابات البنكية'),
        $financeScreen('bank-account-statement', 'Bank Account Statement', 'كشف الحساب البنكي'),
        $financeScreen('bank-reconciliation', 'Bank Reconciliation', 'المطابقة البنكية'),
        $financeScreen('treasury-transfers', 'Treasury Transfers', 'تحويلات الخزينة'),
        $financeScreen('received-cheques', 'Incoming Cheques', 'الشيكات الواردة'),
        $financeScreen('issued-cheques', 'Outgoing Cheques', 'الشيكات الصادرة'),
        $financeScreen('cleared-cheques', 'Cleared and Paid Cheques', 'الشيكات المحصلة والمصروفة'),
        $financeScreen('returned-cheques', 'Returned and Rejected Cheques', 'الشيكات المرتدة والمرفوضة'),
        $financeScreen('cancelled-cheques', 'Cancelled Cheques', 'الشيكات الملغاة'),
        $financeScreen('cheque-transit', 'Due and Upcoming Cheques', 'الشيكات المستحقة والقادمة'),
        $financeScreen('advances-allocations', 'Allocations and Unallocated Payments', 'التخصيصات والمدفوعات غير المخصصة'),
        $financeScreen('unapproved-documents', 'Unapproved Financial Documents', 'المستندات المالية غير المعتمدة'),
        $financeScreen('customer-aging', 'Customer Aging', 'أعمار ديون العملاء'),
        $financeScreen('supplier-aging', 'Supplier Aging', 'أعمار ديون الموردين'),
        [
            'key' => 'reports_finance_overview',
            'slug' => 'finance-overview',
            'title' => ['en' => 'Financial Reports Overview', 'ar' => 'نظرة عامة على التقارير المالية'],
            'group' => 'finance',
            'profile' => 'report',
            'kind' => 'report',
            'classification' => 'WORKING_REAL_SCREEN',
            'shell_enabled' => false,
            'menu_visible' => false,
            'permission_prefix' => 'reports.finance',
            'canonical_route' => 'admin.reports.finance.finance-overview.index',
            'subgroup' => 'finance_reports',
            'menu_title' => ['en' => 'Financial Reports Overview', 'ar' => 'نظرة عامة على التقارير المالية'],
            'actions' => ['view'],
        ],
        [...$screen('sales', 'sales-orders', 'Sales Orders', 'أوامر البيع'), 'shell_enabled' => false],
        [...$screen('purchases', 'purchases-by-supplier', 'Purchases by Supplier', 'المشتريات حسب المورد'), 'menu_visible' => false, 'shell_enabled' => false],
        [...$screen('purchases', 'purchase-orders', 'Purchase Orders', 'أوامر الشراء'), 'menu_visible' => false, 'shell_enabled' => false],
        [...$screen('purchases', 'purchase-invoice-details', 'Purchase Invoice Details', 'تفاصيل فواتير المشتريات'), 'menu_visible' => false, 'shell_enabled' => false],
        [...$screen('purchases', 'goods-receipts', 'Goods Receipts', 'استلامات البضاعة'), 'menu_visible' => false, 'shell_enabled' => false],
        [...$screen('purchases', 'purchase-returns', 'Purchase Returns', 'مردودات المشتريات'), 'menu_visible' => false, 'shell_enabled' => false],
        $costingScreen('product-cost', 'Product Cost', 'تكلفة المنتج'),
        $costingScreen('work-order-cost', 'Work Order Cost', 'تكلفة أمر التشغيل'),
        $costingScreen('estimated-vs-actual', 'Estimated vs Actual', 'التقديري مقابل الفعلي'),
        $costingScreen('cost-variance', 'Cost Variance', 'انحراف التكلفة'),
        $costingScreen('profitability', 'Profitability', 'الربحية'),
        $costingScreen('work-in-progress', 'Work in Progress', 'الإنتاج تحت التشغيل'),
        $costingScreen('finished-goods-cost', 'Finished Goods Cost', 'تكلفة الإنتاج التام'),
        $costingScreen('allocation-analysis', 'Allocation Analysis', 'تحليل التحميل'),
    ],
];
