<?php

$screen = static fn (string $domain, string $slug, string $en, string $ar): array => [
    'key' => 'reports_'.$domain.'_'.str_replace('-', '_', $slug),
    'slug' => $domain.'/'.$slug,
    'permission_prefix' => 'reports.'.$domain.'.'.str_replace('-', '_', $slug),
    'title' => ['en' => $en, 'ar' => $ar],
    'group' => $domain,
    'profile' => 'report',
    'kind' => 'report',
];

return [
    'module' => 'reports',
    'title' => ['en' => 'Reports', 'ar' => 'التقارير'],
    'route_segment' => 'reports',
    'route_name' => 'reports',
    'permission_prefix' => 'reports',
    'menu' => ['label' => 'reports', 'title' => ['en' => 'Reports', 'ar' => 'التقارير'], 'icon' => 'chart-bar', 'order' => 140],
    'groups' => [
        'finance' => ['title' => ['en' => 'Finance Reports', 'ar' => 'تقارير المالية'], 'icon' => 'money-check-alt', 'order' => 10],
        'sales' => ['title' => ['en' => 'Sales Reports', 'ar' => 'تقارير المبيعات'], 'icon' => 'shopping-cart', 'order' => 20],
        'purchases' => ['title' => ['en' => 'Purchases Reports', 'ar' => 'تقارير المشتريات'], 'icon' => 'shopping-bag', 'order' => 30],
        'inventory' => ['title' => ['en' => 'Inventory Reports', 'ar' => 'تقارير المخزون'], 'icon' => 'warehouse', 'order' => 40],
        'production' => ['title' => ['en' => 'Production Reports', 'ar' => 'تقارير الإنتاج'], 'icon' => 'industry', 'order' => 50],
        'quality' => ['title' => ['en' => 'Quality Reports', 'ar' => 'تقارير الجودة'], 'icon' => 'clipboard-check', 'order' => 60],
        'maintenance' => ['title' => ['en' => 'Maintenance Reports', 'ar' => 'تقارير الصيانة'], 'icon' => 'tools', 'order' => 70],
        'costing' => ['title' => ['en' => 'Costing Reports', 'ar' => 'تقارير التكاليف'], 'icon' => 'calculator', 'order' => 80],
    ],
    'screens' => [
        $screen('finance', 'cashbox-balances', 'Cashbox Balances', 'أرصدة الخزائن'),
        $screen('finance', 'cashbox-statement', 'Cashbox Statement', 'كشف حساب الخزينة'),
        $screen('finance', 'bank-account-balances', 'Bank Account Balances', 'أرصدة الحسابات البنكية'),
        $screen('finance', 'bank-account-statement', 'Bank Account Statement', 'كشف الحساب البنكي'),
        $screen('finance', 'cheque-transit', 'Cheque Transit', 'الشيكات بالطريق'),
        $screen('finance', 'treasury-transfers', 'Treasury Transfers', 'تحويلات الخزينة'),
        $screen('finance', 'customer-aging', 'Customer Aging', 'أعمار ديون العملاء'),
        $screen('finance', 'supplier-aging', 'Supplier Aging', 'أعمار ديون الموردين'),
        [...$screen('sales', 'sales-orders', 'Sales Orders', 'أوامر البيع'), 'shell_enabled' => false],
        $screen('purchases', 'purchases-by-supplier', 'Purchases by Supplier', 'المشتريات حسب المورد'),
        $screen('purchases', 'purchase-orders', 'Purchase Orders', 'أوامر الشراء'),
        $screen('purchases', 'purchase-invoice-details', 'Purchase Invoice Details', 'تفاصيل فواتير المشتريات'),
        $screen('purchases', 'goods-receipts', 'Goods Receipts', 'استلامات البضاعة'),
        $screen('purchases', 'purchase-returns', 'Purchase Returns', 'مردودات المشتريات'),
        $screen('inventory', 'inventory-balances', 'Inventory Balances', 'أرصدة المخزون'),
        $screen('inventory', 'stock-card', 'Stock Card', 'كارت الصنف'),
        $screen('inventory', 'inventory-movements', 'Inventory Movements', 'حركات المخزون'),
        $screen('inventory', 'stock-aging', 'Stock Aging', 'أعمار المخزون'),
        $screen('inventory', 'slow-moving-stock', 'Slow Moving Stock', 'المخزون بطيء الحركة'),
        $screen('inventory', 'negative-stock', 'Negative Stock', 'المخزون السالب'),
        $screen('inventory', 'material-outside-company', 'Material Outside Company', 'الخامات خارج الشركة'),
        $screen('inventory', 'supplier-custody', 'Supplier Custody', 'عهدة المورد'),
        $screen('production', 'work-orders-by-status', 'Work Orders by Status', 'أوامر التشغيل حسب الحالة'),
        $screen('production', 'production-plan', 'Production Plan', 'خطة الإنتاج'),
        $screen('production', 'production-output', 'Production Output', 'ناتج الإنتاج'),
        $screen('production', 'material-consumption', 'Material Consumption', 'استهلاك الخامات'),
        $screen('production', 'production-efficiency', 'Production Efficiency', 'كفاءة الإنتاج'),
        $screen('production', 'machine-utilization', 'Machine Utilization', 'استغلال الماكينات'),
        $screen('production', 'downtime', 'Downtime', 'التوقفات'),
        $screen('production', 'scrap-and-waste', 'Scrap and Waste', 'الهالك والفاقد'),
        $screen('production', 'external-manufacturing', 'External Manufacturing', 'التصنيع الخارجي'),
        $screen('quality', 'inspection-results', 'Inspection Results', 'نتائج الفحص'),
        $screen('quality', 'rejection-report', 'Rejection Report', 'تقرير الرفض'),
        $screen('quality', 'non-conformance', 'Non-Conformance', 'عدم المطابقة'),
        $screen('quality', 'capa', 'CAPA', 'الإجراءات التصحيحية والوقائية'),
        $screen('quality', 'supplier-quality', 'Supplier Quality', 'جودة المورد'),
        $screen('quality', 'customer-complaints', 'Customer Complaints', 'شكاوى العملاء'),
        $screen('maintenance', 'maintenance-requests', 'Maintenance Requests', 'طلبات الصيانة'),
        $screen('maintenance', 'maintenance-work-orders', 'Maintenance Work Orders', 'أوامر عمل الصيانة'),
        $screen('maintenance', 'preventive-maintenance-compliance', 'Preventive Maintenance Compliance', 'الالتزام بالصيانة الوقائية'),
        $screen('maintenance', 'breakdown-history', 'Breakdown History', 'سجل الأعطال'),
        $screen('maintenance', 'machine-downtime', 'Machine Downtime', 'توقف الماكينات'),
        $screen('maintenance', 'spare-parts-usage', 'Spare Parts Usage', 'استخدام قطع الغيار'),
        $screen('costing', 'product-cost', 'Product Cost', 'تكلفة المنتج'),
        $screen('costing', 'work-order-cost', 'Work Order Cost', 'تكلفة أمر التشغيل'),
        $screen('costing', 'estimated-vs-actual', 'Estimated vs Actual', 'التقديري مقابل الفعلي'),
        $screen('costing', 'cost-variance', 'Cost Variance', 'انحراف التكلفة'),
        $screen('costing', 'profitability', 'Profitability', 'الربحية'),
    ],
];
