<?php

$screen = static fn (string $slug, string $en, string $ar, string $group = 'orders', string $profile = 'document', array $extra = []): array => [
    'key' => 'sales_'.str_replace('-', '_', $slug),
    'slug' => $slug,
    'title' => ['en' => $en, 'ar' => $ar],
    'group' => $group,
    'profile' => $profile,
    'shell_enabled' => false,
    ...$extra,
];

return [
    'module' => 'sales',
    'title' => ['en' => 'Sales', 'ar' => 'المبيعات'],
    'route_segment' => 'sales',
    'route_name' => 'sales',
    'permission_prefix' => 'sales',
    'menu' => ['label' => 'sales', 'title' => ['en' => 'Sales', 'ar' => 'المبيعات'], 'icon' => 'shopping-cart', 'order' => 40],
    'groups' => [
        'crm' => ['title' => ['en' => 'CRM and Customer Activity', 'ar' => 'إدارة علاقات العملاء'], 'icon' => 'users', 'order' => 10],
        'customer_data' => ['title' => ['en' => 'Customer Commercial Data', 'ar' => 'بيانات العميل التجارية'], 'icon' => 'address-card', 'order' => 20],
        'quotations' => ['title' => ['en' => 'Quotations', 'ar' => 'عروض الأسعار'], 'icon' => 'file-invoice-dollar', 'order' => 30],
        'orders' => ['title' => ['en' => 'Sales Orders', 'ar' => 'أوامر البيع'], 'icon' => 'clipboard-list', 'order' => 40],
        'contracts' => ['title' => ['en' => 'Sales Contracts', 'ar' => 'عقود المبيعات'], 'icon' => 'file-contract', 'order' => 50],
        'billing' => ['title' => ['en' => 'Billing and Collections', 'ar' => 'الفواتير والتحصيل'], 'icon' => 'money-check-alt', 'order' => 60],
        'delivery' => ['title' => ['en' => 'Delivery', 'ar' => 'التسليم'], 'icon' => 'truck', 'order' => 70],
        'controls' => ['title' => ['en' => 'Sales Controls', 'ar' => 'ضوابط المبيعات'], 'icon' => 'user-shield', 'order' => 80],
    ],
    'screens' => [
        $screen('leads', 'Leads', 'العملاء المحتملون', 'crm'),
        $screen('opportunities', 'Opportunities', 'الفرص البيعية', 'crm'),
        $screen('customer-inquiries', 'Customer Inquiries', 'استفسارات العملاء', 'crm'),
        $screen('customer-requests', 'Customer Requests', 'طلبات العملاء', 'crm'),
        $screen('customer-visits', 'Customer Visits', 'زيارات العملاء', 'crm'),
        $screen('customer-follow-ups', 'Customer Follow-ups', 'متابعات العملاء', 'crm'),
        $screen('customer-contacts', 'Customer Contacts', 'جهات اتصال العملاء', 'customer_data'),
        $screen('customer-addresses', 'Customer Addresses', 'عناوين العملاء', 'customer_data'),
        $screen('customer-sites', 'Customer Sites', 'مواقع العملاء', 'customer_data'),
        $screen('customer-credit-limits', 'Customer Credit Limits', 'حدود ائتمان العملاء', 'customer_data'),
        $screen('customer-price-lists', 'Customer Price Lists', 'قوائم أسعار العملاء', 'customer_data'),
        $screen('customer-contracts', 'Customer Contracts', 'عقود العملاء', 'customer_data'),
        $screen('customer-contract-amendments', 'Customer Contract Amendments', 'تعديلات عقود العملاء', 'customer_data'),
        $screen('customer-specifications', 'Customer Specifications', 'مواصفات العملاء', 'customer_data'),
        $screen('customer-attachments', 'Customer Attachments', 'مرفقات العملاء', 'customer_data'),
        $screen('quotation-comparison', 'Quotation Comparison', 'مقارنة عروض الأسعار', 'quotations', 'inquiry'),
        $screen('sales-orders', 'Sales Orders', 'أوامر البيع', 'orders', 'document', [
            'shell_enabled' => false,
            'permission_prefix' => 'sales_orders',
            'actions' => ['view', 'create', 'edit', 'delete', 'approve', 'reject', 'cancel', 'reopen', 'print', 'view_prices', 'credit_override', 'reserve', 'deliver', 'invoice', 'production'],
        ]),
        $screen('sales-order-lines', 'Sales Order Lines', 'سطور أوامر البيع'),
        $screen('sales-order-specifications', 'Sales Order Specifications', 'مواصفات أوامر البيع'),
        $screen('sales-order-change-requests', 'Sales Order Change Requests', 'طلبات تغيير أوامر البيع'),
        $screen('sales-order-approvals', 'Sales Order Approvals', 'اعتمادات أوامر البيع'),
        $screen('sales-order-payment-schedule', 'Sales Order Payment Schedule', 'جدول دفعات أمر البيع'),
        $screen('sales-order-delivery-schedule', 'Sales Order Delivery Schedule', 'جدول تسليم أمر البيع'),
        $screen('sales-order-status-history', 'Sales Order Status History', 'سجل حالات أمر البيع', 'orders', 'inquiry'),
        $screen('sales-contracts', 'Sales Contracts', 'عقود المبيعات', 'contracts'),
        $screen('contract-milestones', 'Contract Milestones', 'مراحل العقود', 'contracts'),
        $screen('contract-delivery-schedule', 'Contract Delivery Schedule', 'جدول تسليم العقد', 'contracts'),
        $screen('contract-payment-schedule', 'Contract Payment Schedule', 'جدول دفعات العقد', 'contracts'),
        $screen('contract-execution-schedule', 'Contract Execution Schedule', 'جدول تنفيذ العقد', 'contracts'),
        $screen('contract-terms', 'Contract Terms', 'شروط العقد', 'contracts'),
        $screen('sales-invoices', 'Sales Invoices', 'فواتير المبيعات', 'billing', 'document', [
            'shell_enabled' => false,
            'permission_prefix' => 'customer_invoices',
            'actions' => ['view', 'create', 'edit', 'post', 'cancel', 'reopen', 'print', 'view_prices'],
        ]),
        $screen('sales-invoice-lines', 'Sales Invoice Lines', 'سطور فواتير المبيعات', 'billing'),
        $screen('sales-returns', 'Sales Returns', 'مردودات المبيعات', 'billing', 'document', [
            'shell_enabled' => false,
            'permission_prefix' => 'sales_returns',
            'actions' => ['view', 'create', 'authorize', 'receive', 'inspect', 'close', 'cancel', 'print'],
        ]),
        $screen('customer-advances', 'Customer Advances', 'دفعات العملاء المقدمة', 'billing', 'document', ['permission_prefix' => 'customer_advances']),
        $screen('customer-receipts', 'Customer Receipts', 'متحصلات العملاء', 'billing', 'document', [
            'shell_enabled' => false,
            'permission_prefix' => 'customer_receipts',
            'actions' => ['view', 'create', 'cancel', 'reopen', 'print', 'allocate'],
        ]),
        $screen('customer-receipt-allocations', 'Customer Receipt Allocations', 'تخصيص متحصلات العملاء', 'billing', 'document', ['permission_prefix' => 'customer_receipt_allocations']),
        $screen('delivery-notes', 'Delivery Notes', 'أذون التسليم', 'delivery', 'document', [
            'shell_enabled' => false,
            'permission_prefix' => 'sales_deliveries',
            'actions' => ['view', 'create', 'post', 'cancel', 'reopen', 'print'],
        ]),
        $screen('customer-delivery-confirmation', 'Customer Delivery Confirmation', 'تأكيد استلام العميل', 'delivery'),
        $screen('trip-sheets', 'Trip Sheets', 'أوراق الرحلات', 'delivery', 'document', ['permission_prefix' => 'trip_sheets']),
        $screen('customer-complaints', 'Customer Complaints', 'شكاوى العملاء', 'crm'),
        $screen('sales-commission-definitions', 'Sales Commission Definitions', 'تعريفات عمولات المبيعات', 'controls', 'master'),
        $screen('sales-employee-targets', 'Sales Employee Targets', 'أهداف موظفي المبيعات', 'controls'),
        $screen('sales-price-approvals', 'Sales Price Approvals', 'اعتمادات أسعار البيع', 'controls'),
        $screen('discount-approval-requests', 'Discount Approval Requests', 'طلبات اعتماد الخصومات', 'controls'),
    ],
];
