<?php

$screen = static fn (string $slug, string $en, string $ar, string $group = 'system', string $profile = 'setup', array $extra = []): array => [
    'key' => 'tools_'.str_replace('-', '_', $slug),
    'slug' => $slug,
    'title' => ['en' => $en, 'ar' => $ar],
    'group' => $group,
    'profile' => $profile,
    ...$extra,
];

return [
    'module' => 'tools',
    'title' => ['en' => 'Tools and Settings', 'ar' => 'الأدوات والإعدادات'],
    'route_segment' => 'tools',
    'route_name' => 'tools',
    'permission_prefix' => 'tools',
    'menu' => ['label' => 'tools', 'title' => ['en' => 'Tools and Settings', 'ar' => 'الأدوات والإعدادات'], 'icon' => 'tools', 'order' => 150],
    'groups' => [
        'workflow' => ['title' => ['en' => 'Workflow and Approvals', 'ar' => 'مسارات العمل والاعتمادات'], 'icon' => 'project-diagram', 'order' => 10],
        'communications' => ['title' => ['en' => 'Communication Templates', 'ar' => 'قوالب الاتصالات'], 'icon' => 'envelope', 'order' => 20],
        'data' => ['title' => ['en' => 'Data Exchange', 'ar' => 'تبادل البيانات'], 'icon' => 'exchange-alt', 'order' => 30],
        'integrations' => ['title' => ['en' => 'Integrations', 'ar' => 'التكاملات'], 'icon' => 'plug', 'order' => 40],
        'printing' => ['title' => ['en' => 'Barcode and Printing', 'ar' => 'الباركود والطباعة'], 'icon' => 'print', 'order' => 50],
        'system' => ['title' => ['en' => 'System Operations', 'ar' => 'عمليات النظام'], 'icon' => 'server', 'order' => 60],
        'review' => ['title' => ['en' => 'Configuration Review', 'ar' => 'مراجعة الإعدادات'], 'icon' => 'search', 'order' => 70],
    ],
    'screens' => [
        $screen('workflow-designer', 'Workflow Designer', 'مصمم مسارات العمل', 'workflow', 'document'),
        $screen('approval-matrix', 'Approval Matrix', 'مصفوفة الاعتمادات', 'workflow', 'document'),
        $screen('notification-center-settings', 'Notification Center Settings', 'إعدادات مركز الإشعارات', 'communications'),
        $screen('email-template-settings', 'Email Template Settings', 'إعدادات قوالب البريد الإلكتروني', 'communications'),
        $screen('sms-template-settings', 'SMS Template Settings', 'إعدادات قوالب الرسائل القصيرة', 'communications'),
        $screen('whatsapp-template-settings', 'WhatsApp Template Settings', 'إعدادات قوالب واتساب', 'communications'),
        $screen('import-templates', 'Import Templates', 'قوالب الاستيراد', 'data'),
        $screen('data-import', 'Data Import', 'استيراد البيانات', 'data', 'document'),
        $screen('data-export', 'Data Export', 'تصدير البيانات', 'data', 'document'),
        $screen('integration-settings', 'Integration Settings', 'إعدادات التكامل', 'integrations'),
        $screen('api-settings', 'API Settings', 'إعدادات واجهة البرمجة', 'integrations'),
        $screen('barcode-settings', 'Barcode Settings', 'إعدادات الباركود', 'printing'),
        $screen('label-templates', 'Label Templates', 'قوالب الملصقات', 'printing'),
        $screen('print-template-designer', 'Print Template Designer', 'مصمم قوالب الطباعة', 'printing', 'document'),
        $screen('integration-logs', 'Integration Logs', 'سجلات التكامل', 'integrations', 'inquiry'),
        $screen('background-job-monitor', 'Background Job Monitor UI', 'واجهة مراقبة المهام الخلفية', 'system', 'inquiry'),
        $screen('system-health', 'System Health UI', 'واجهة صحة النظام', 'system', 'inquiry'),
        $screen('backup-settings', 'Backup Settings UI', 'واجهة إعدادات النسخ الاحتياطي', 'system'),
        $screen('numbering-review', 'Numbering Review', 'مراجعة الترقيم', 'review', 'inquiry'),
        $screen('permission-review', 'Permission Review', 'مراجعة الصلاحيات', 'review', 'inquiry'),
        $screen('menu-review', 'Menu Review', 'مراجعة القوائم', 'review', 'inquiry'),
    ],
];
