<?php

return [
    'roles' => [
        'prefix' => 'Role-',
        'padding' => 5,
        'column' => 'doc_num',
        'number_column' => 'doc_number',
    ],
    'users' => [
        'prefix' => 'User-',
        'padding' => 5,
        'column' => 'doc_num',
        'number_column' => 'doc_number',
    ],
    'companies' => [
        'prefix' => 'Company-',
        'padding' => 5,
        'column' => 'doc_num',
        'number_column' => 'doc_number',
    ],
    'archive_files' => [
        'prefix' => 'File-',
        'padding' => 5,
        'column' => 'doc_num',
        'number_column' => 'doc_number',
    ],
    'archive_folders' => [
        'prefix' => 'Folder-',
        'padding' => 5,
        'column' => 'doc_num',
        'number_column' => 'doc_number',
    ],
    'hr_countries' => [
        'prefix' => 'Country-',
        'padding' => 5,
        'column' => 'doc_num',
        'number_column' => 'doc_number',
    ],
    'hr_governorates' => [
        'prefix' => 'Governorate-',
        'padding' => 5,
        'column' => 'doc_num',
        'number_column' => 'doc_number',
    ],
    'hr_cities' => [
        'prefix' => 'City-',
        'padding' => 5,
        'column' => 'doc_num',
        'number_column' => 'doc_number',
    ],
    'hr_areas' => [
        'prefix' => 'Area-',
        'padding' => 5,
        'column' => 'doc_num',
        'number_column' => 'doc_number',
    ],
    'hr_nationalities' => [
        'prefix' => 'Nationality-',
        'padding' => 5,
        'column' => 'doc_num',
        'number_column' => 'doc_number',
    ],
    'hr_religions' => [
        'prefix' => 'Religion-',
        'padding' => 5,
        'column' => 'doc_num',
        'number_column' => 'doc_number',
    ],
    'hr_qualifications' => [
        'prefix' => 'Qualification-',
        'padding' => 5,
        'column' => 'doc_num',
        'number_column' => 'doc_number',
    ],
    'hr_universities' => [
        'prefix' => 'University-',
        'padding' => 5,
        'column' => 'doc_num',
        'number_column' => 'doc_number',
    ],
    'hr_faculties' => [
        'prefix' => 'Faculty-',
        'padding' => 5,
        'column' => 'doc_num',
        'number_column' => 'doc_number',
    ],
    'hr_specializations' => [
        'prefix' => 'Specialization-',
        'padding' => 5,
        'column' => 'doc_num',
        'number_column' => 'doc_number',
    ],
    'hr_military_services' => [
        'prefix' => 'MilitaryService-',
        'padding' => 5,
        'column' => 'doc_num',
        'number_column' => 'doc_number',
    ],
    'hr_allowances' => [
        'prefix' => 'Allowance-',
        'padding' => 5,
        'column' => 'doc_num',
        'number_column' => 'doc_number',
    ],
    'hr_hiring_statuses' => [
        'prefix' => 'HiringStatus-',
        'padding' => 5,
        'column' => 'doc_num',
        'number_column' => 'doc_number',
    ],
    'hr_identifications' => [
        'prefix' => 'Identification-',
        'padding' => 5,
        'column' => 'doc_num',
        'number_column' => 'doc_number',
    ],
    'hr_employees' => [
        'prefix' => 'Emp-',
        'padding' => 5,
        'column' => 'doc_num',
        'number_column' => 'doc_number',
    ],
    'hr_departments' => [
        'prefix' => 'Dept-',
        'padding' => 5,
        'column' => 'doc_num',
        'number_column' => 'doc_number',
    ],
    'hr_sections' => [
        'prefix' => 'Sect-',
        'padding' => 5,
        'column' => 'doc_num',
        'number_column' => 'doc_number',
    ],
    'hr_jobs' => [
        'prefix' => 'HrJob-',
        'padding' => 5,
        'column' => 'doc_num',
        'number_column' => 'doc_number',
    ],
    'hr_document_types' => [
        'prefix' => 'DocType-',
        'padding' => 5,
        'column' => 'doc_num',
        'number_column' => 'doc_number',
    ],
    'hr_shifts' => [
        'prefix' => 'Shift-',
        'padding' => 5,
        'column' => 'doc_num',
        'number_column' => 'doc_number',
    ],
    'hr_biometric_devices' => [
        'prefix' => 'BioDev-',
        'padding' => 5,
        'column' => 'doc_num',
        'number_column' => 'doc_number',
    ],
    'hr_grades' => [
        'prefix' => 'Grd-',
        'padding' => 5,
        'column' => 'doc_num',
        'number_column' => 'doc_number',
    ],
    'hr_employment_types' => [
        'prefix' => 'ETyp-',
        'padding' => 5,
        'column' => 'doc_num',
        'number_column' => 'doc_number',
    ],
    'hr_insurance_offices' => [
        'prefix' => 'InsOffice-',
        'padding' => 5,
        'column' => 'doc_num',
        'number_column' => 'doc_number',
    ],
    'hr_employee_documents' => [
        'prefix' => 'EmpDoc-',
        'padding' => 5,
        'column' => 'doc_num',
        'number_column' => 'doc_number',
    ],
    'branches' => [
        'prefix' => 'Branch-',
        'padding' => 5,
        'column' => 'doc_num',
        'number_column' => 'doc_number',
    ],
    'financial_periods' => [
        'prefix' => 'Period-',
        'padding' => 5,
        'column' => 'doc_num',
        'number_column' => 'doc_number',
        'scope' => 'company',
    ],
    'item_units' => [
        'prefix' => 'Unit-',
        'padding' => 5,
        'column' => 'doc_num',
        'number_column' => 'doc_number',
        'scope' => 'company',
    ],
    'item_sizes' => [
        'prefix' => 'Size-',
        'padding' => 5,
        'column' => 'doc_num',
        'number_column' => 'doc_number',
        'scope' => 'company',
    ],
    'item_colors' => [
        'prefix' => 'Color-',
        'padding' => 5,
        'column' => 'doc_num',
        'number_column' => 'doc_number',
        'scope' => 'company',
    ],
    'item_decals' => [
        'prefix' => 'Decal-',
        'padding' => 5,
        'column' => 'doc_num',
        'number_column' => 'doc_number',
        'scope' => 'company',
    ],
    'item_models' => [
        'prefix' => 'Model-',
        'padding' => 5,
        'column' => 'doc_num',
        'number_column' => 'doc_number',
        'scope' => 'company',
    ],
    'item_categories' => [
        'prefix' => 'Category-',
        'padding' => 5,
        'column' => 'doc_num',
        'number_column' => 'doc_number',
        'scope' => 'company',
    ],
    'item_groups' => [
        'prefix' => 'Group-',
        'padding' => 5,
        'column' => 'doc_num',
        'number_column' => 'doc_number',
        'scope' => 'company',
    ],
    'item_origin_countries' => [
        'prefix' => 'Origin-',
        'padding' => 5,
        'column' => 'doc_num',
        'number_column' => 'doc_number',
        'scope' => 'company',
    ],
    'products' => [
        'prefix' => 'Product-',
        'padding' => 5,
        'column' => 'doc_num',
        'number_column' => 'doc_number',
        'scope' => 'company',
    ],
    'raw_materials' => [
        'prefix' => 'RAW-',
        'padding' => 5,
        'column' => 'doc_num',
        'number_column' => 'doc_number',
        'scope' => 'company',
    ],
    'account_classifications' => [
        'prefix' => 'ACLS-',
        'padding' => 5,
        'column' => 'doc_num',
        'number_column' => 'doc_number',
    ],
    'accounts' => [
        'prefix' => 'ACC-',
        'padding' => 5,
        'column' => 'doc_num',
        'number_column' => 'doc_number',
        'scope' => 'company',
    ],
    'cost_centers' => [
        'prefix' => 'CC-',
        'padding' => 5,
        'column' => 'doc_num',
        'number_column' => 'doc_number',
        'scope' => 'company',
    ],
    'production_identifier_types' => [
        'prefix' => 'IDT-',
        'padding' => 5,
        'column' => 'doc_num',
        'number_column' => 'doc_number',
        'scope' => 'company',
    ],
    'production_identifiers' => [
        'prefix' => 'ID-',
        'padding' => 5,
        'column' => 'doc_num',
        'number_column' => 'doc_number',
        'scope' => 'company',
    ],
    'currencies' => [
        'prefix' => 'CUR-',
        'padding' => 5,
        'column' => 'doc_num',
        'number_column' => 'doc_number',
        'scope' => 'company',
    ],
    'bank_accounts' => [
        'prefix' => 'BANK-',
        'padding' => 5,
        'column' => 'doc_num',
        'number_column' => 'doc_number',
        'scope' => 'company',
    ],
    'cashboxes' => [
        'prefix' => 'CASH-',
        'padding' => 5,
        'column' => 'doc_num',
        'number_column' => 'doc_number',
        'scope' => 'company',
    ],
    'cash_receipt_vouchers' => [
        'prefix' => 'CRV-',
        'padding' => 5,
        'column' => 'doc_num',
        'number_column' => 'doc_number',
        'scope' => 'company',
    ],
    'cash_payment_vouchers' => [
        'prefix' => 'CPV-',
        'padding' => 5,
        'column' => 'doc_num',
        'number_column' => 'doc_number',
        'scope' => 'company',
    ],
    'received_cheques' => [
        'prefix' => 'RCH-',
        'padding' => 5,
        'column' => 'doc_num',
        'number_column' => 'doc_number',
        'scope' => 'company',
    ],
    'issued_cheques' => [
        'prefix' => 'ICH-',
        'padding' => 5,
        'column' => 'doc_num',
        'number_column' => 'doc_number',
        'scope' => 'company',
    ],
    'fund_transfers' => [
        'prefix' => 'FTR-',
        'padding' => 5,
        'column' => 'doc_num',
        'number_column' => 'doc_number',
        'scope' => 'company',
    ],
    'customers' => [
        'prefix' => 'Customer-',
        'padding' => 5,
        'column' => 'doc_num',
        'number_column' => 'doc_number',
        'scope' => 'company',
    ],
    'quotations' => [
        'prefix' => 'QT-',
        'padding' => 5,
        'column' => 'doc_num',
        'number_column' => 'doc_number',
        'scope' => 'company',
    ],
    'project_structures' => [
        'prefix' => 'PST-',
        'padding' => 5,
        'column' => 'doc_num',
        'number_column' => 'doc_number',
        'scope' => 'company',
    ],
    'project_structure_models' => [
        'prefix' => 'PSM-',
        'padding' => 5,
        'column' => 'doc_num',
        'number_column' => 'doc_number',
        'scope' => 'company',
    ],
    'suppliers' => [
        'prefix' => 'Supplier-',
        'padding' => 5,
        'column' => 'doc_num',
        'number_column' => 'doc_number',
        'scope' => 'company',
    ],
    'purchase_orders' => [
        'prefix' => 'PO-',
        'padding' => 5,
        'column' => 'doc_num',
        'number_column' => 'doc_number',
        'scope' => 'company_period',
    ],
    'purchase_invoices' => [
        'prefix' => 'PINV-',
        'padding' => 5,
        'column' => 'doc_num',
        'number_column' => 'doc_number',
        'scope' => 'company_period',
    ],
    'fixed_assets' => [
        'prefix' => 'FA-',
        'padding' => 5,
        'column' => 'doc_num',
        'number_column' => 'doc_number',
        'scope' => 'company',
    ],
    'opening_balances' => [
        'prefix' => 'OB-',
        'padding' => 5,
        'column' => 'doc_num',
        'number_column' => 'doc_number',
    ],
    'inventory_opening_stocks' => [
        'prefix' => 'OS-',
        'padding' => 5,
        'column' => 'doc_num',
        'number_column' => 'doc_number',
    ],
    'unpriced_inventory_receipts' => [
        'prefix' => 'UIR-',
        'padding' => 5,
        'column' => 'doc_num',
        'number_column' => 'doc_number',
    ],
    'inventory_opening_stock_pricings' => [
        'prefix' => 'OSP-',
        'padding' => 5,
        'column' => 'doc_num',
        'number_column' => 'doc_number',
    ],
    'journal_entries' => [
        'prefix' => 'JE-',
        'padding' => 5,
        'column' => 'doc_num',
        'number_column' => 'doc_number',
    ],
    'user_tasks' => [
        'prefix' => 'Task-',
        'padding' => 5,
        'column' => 'doc_num',
        'number_column' => 'doc_number',
    ],
    'quick_tasks' => [
        'prefix' => 'QT-',
        'padding' => 5,
        'column' => 'doc_num',
        'number_column' => 'doc_number',
        'scope' => 'company',
    ],
    'task_boards' => [
        'prefix' => 'TB-',
        'padding' => 5,
        'column' => 'doc_num',
        'number_column' => 'doc_number',
        'scope' => 'company',
    ],
    'board_lists' => [
        'prefix' => 'BoardList-',
        'padding' => 5,
        'column' => 'doc_num',
        'number_column' => 'doc_number',
    ],
    'my_board_labels' => [
        'prefix' => 'BoardLabel-',
        'padding' => 5,
        'column' => 'doc_num',
        'number_column' => 'doc_number',
    ],
];
