<?php

return [
    'modules' => [
        'dashboard' => [
            'label' => 'erp_expanded_screens.modules.dashboard',
            'order' => 10,
            'icon' => 'home',
        ],
        'basic_data' => [
            'label' => 'erp_expanded_screens.modules.basic_data',
            'order' => 20,
            'icon' => 'database',
        ],
        'item_data' => [
            'label' => 'erp_expanded_screens.modules.item_data',
            'order' => 30,
            'icon' => 'tags',
        ],
        'general_accounting' => [
            'label' => 'erp_expanded_screens.modules.general_accounting',
            'order' => 40,
            'icon' => 'calculator',
        ],
        'costing' => [
            'label' => 'erp_expanded_screens.modules.costing',
            'order' => 50,
            'icon' => 'calculator',
        ],
        'sales' => [
            'label' => 'erp_expanded_screens.modules.sales',
            'order' => 60,
            'icon' => 'shopping-cart',
        ],
        'purchases' => [
            'label' => 'erp_expanded_screens.modules.purchases',
            'order' => 70,
            'icon' => 'shopping-bag',
        ],
        'planning_production' => [
            'label' => 'erp_expanded_screens.modules.planning_production',
            'order' => 80,
            'icon' => 'industry',
        ],
        'quality' => [
            'label' => 'erp_expanded_screens.modules.quality',
            'order' => 90,
            'icon' => 'clipboard-check',
        ],
        'maintenance' => [
            'label' => 'erp_expanded_screens.modules.maintenance',
            'order' => 100,
            'icon' => 'tools',
        ],
        'finance' => [
            'label' => 'erp_expanded_screens.modules.finance',
            'order' => 110,
            'icon' => 'money-check-alt',
        ],
        'fixed_assets' => [
            'label' => 'erp_expanded_screens.modules.fixed_assets',
            'order' => 120,
            'icon' => 'building',
        ],
        'inventory' => [
            'label' => 'erp_expanded_screens.modules.inventory',
            'order' => 130,
            'icon' => 'warehouse',
        ],
        'human_resources' => [
            'label' => 'erp_expanded_screens.modules.human_resources',
            'order' => 140,
            'icon' => 'users',
        ],
        'reports' => [
            'label' => 'erp_expanded_screens.modules.reports',
            'order' => 150,
            'icon' => 'chart-bar',
        ],
        'tools' => [
            'label' => 'erp_expanded_screens.modules.tools',
            'order' => 160,
            'icon' => 'tools',
        ],
    ],

    'screens' => [
        ['module' => 'dashboard', 'key' => 'dashboard', 'label' => 'erp_expanded_screens.screens.dashboard', 'status' => 'live', 'route' => 'dashboard', 'path' => 'dashboard', 'permission' => null, 'icon' => 'home'],

        ['module' => 'basic_data', 'key' => 'roles', 'label' => 'erp_expanded_screens.screens.roles', 'status' => 'live', 'route' => 'admin.roles.index', 'path' => 'admin/roles', 'permission' => 'roles.view', 'icon' => 'shield'],
        ['module' => 'basic_data', 'key' => 'users', 'label' => 'erp_expanded_screens.screens.users', 'status' => 'live', 'route' => 'admin.users.index', 'path' => 'admin/users', 'permission' => 'users.view', 'icon' => 'users'],
        ['module' => 'basic_data', 'key' => 'companies', 'label' => 'erp_expanded_screens.screens.companies', 'status' => 'live', 'route' => 'admin.companies.index', 'path' => 'admin/companies', 'permission' => 'companies.view', 'icon' => 'building'],
        ['module' => 'basic_data', 'key' => 'branches', 'label' => 'erp_expanded_screens.screens.branches', 'status' => 'live', 'route' => 'admin.branches.index', 'path' => 'admin/branches', 'permission' => 'branches.view', 'icon' => 'code-branch'],
        ['module' => 'basic_data', 'key' => 'financial_periods', 'label' => 'erp_expanded_screens.screens.financial_periods', 'status' => 'live', 'route' => 'admin.financial-periods.index', 'path' => 'admin/financial-periods', 'permission' => 'financial_periods.view', 'icon' => 'calendar-check'],
        ['module' => 'basic_data', 'key' => 'activity_logs', 'label' => 'erp_expanded_screens.screens.activity_logs', 'status' => 'live', 'route' => 'admin.activity-logs.index', 'path' => 'admin/activity-logs', 'permission' => 'activity.logs.view', 'icon' => 'clipboard-list'],
        ['module' => 'basic_data', 'key' => 'auth_logs', 'label' => 'erp_expanded_screens.screens.auth_logs', 'status' => 'live', 'route' => 'admin.auth-logs.index', 'path' => 'admin/auth-logs', 'permission' => 'auth.logs.view', 'icon' => 'clipboard-list'],
        ['module' => 'basic_data', 'key' => 'auth_sessions', 'label' => 'erp_expanded_screens.screens.auth_sessions', 'status' => 'live', 'route' => 'admin.auth-sessions.index', 'path' => 'admin/auth-sessions', 'permission' => 'auth.sessions.view', 'icon' => 'clock'],
        ['module' => 'basic_data', 'key' => 'profile', 'label' => 'erp_expanded_screens.screens.profile', 'status' => 'live', 'route' => 'profile.show', 'path' => 'profile', 'permission' => 'profile.view', 'icon' => 'user-circle'],

        ['module' => 'item_data', 'key' => 'products', 'label' => 'erp_expanded_screens.screens.products', 'status' => 'live', 'route' => 'admin.products.index', 'path' => 'admin/products', 'permission' => 'products.view', 'icon' => 'box'],
        ['module' => 'item_data', 'key' => 'raw_materials', 'label' => 'erp_expanded_screens.screens.raw_materials', 'status' => 'live', 'route' => 'admin.raw-materials.index', 'path' => 'admin/raw-materials', 'permission' => 'raw_materials.view', 'icon' => 'cubes'],
        ['module' => 'item_data', 'key' => 'item_categories', 'label' => 'erp_expanded_screens.screens.item_categories', 'status' => 'live', 'route' => 'admin.item-categories.index', 'path' => 'admin/item-categories', 'permission' => 'item_categories.view', 'icon' => 'layer-group'],
        ['module' => 'item_data', 'key' => 'item_units', 'label' => 'erp_expanded_screens.screens.item_units', 'status' => 'live', 'route' => 'admin.item-units.index', 'path' => 'admin/item-units', 'permission' => 'item_units.view', 'icon' => 'balance-scale'],
        ['module' => 'item_data', 'key' => 'item_sizes', 'label' => 'erp_expanded_screens.screens.item_sizes', 'status' => 'live', 'route' => 'admin.item-sizes.index', 'path' => 'admin/item-sizes', 'permission' => 'item_sizes.view', 'icon' => 'expand-arrows-alt'],
        ['module' => 'item_data', 'key' => 'item_colors', 'label' => 'erp_expanded_screens.screens.item_colors', 'status' => 'live', 'route' => 'admin.item-colors.index', 'path' => 'admin/item-colors', 'permission' => 'item_colors.view', 'icon' => 'palette'],
        ['module' => 'item_data', 'key' => 'item_decals', 'label' => 'erp_expanded_screens.screens.item_decals', 'status' => 'live', 'route' => 'admin.item-decals.index', 'path' => 'admin/item-decals', 'permission' => 'item_decals.view', 'icon' => 'stamp'],
        ['module' => 'item_data', 'key' => 'item_models', 'label' => 'erp_expanded_screens.screens.item_models', 'status' => 'live', 'route' => 'admin.item-models.index', 'path' => 'admin/item-models', 'permission' => 'item_models.view', 'icon' => 'cube'],
        ['module' => 'item_data', 'key' => 'item_groups', 'label' => 'erp_expanded_screens.screens.item_groups', 'status' => 'live', 'route' => 'admin.item-groups.index', 'path' => 'admin/item-groups', 'permission' => 'item_groups.view', 'icon' => 'object-group'],
        ['module' => 'item_data', 'key' => 'item_origin_countries', 'label' => 'erp_expanded_screens.screens.item_origin_countries', 'status' => 'live', 'route' => 'admin.item-origin-countries.index', 'path' => 'admin/item-origin-countries', 'permission' => 'item_origin_countries.view', 'icon' => 'globe-africa'],

        ['module' => 'general_accounting', 'key' => 'chart_of_accounts', 'label' => 'erp_expanded_screens.screens.chart_of_accounts', 'status' => 'live', 'route' => 'admin.accounting.accounts.index', 'path' => 'admin/accounting/accounts', 'permission' => 'accounts.view', 'icon' => 'sitemap'],
        ['module' => 'general_accounting', 'key' => 'cost_centers', 'label' => 'erp_expanded_screens.screens.cost_centers', 'status' => 'live', 'route' => 'admin.accounting.cost-centers.index', 'path' => 'admin/accounting/cost-centers', 'permission' => 'cost_centers.view', 'icon' => 'project-diagram'],
        ['module' => 'general_accounting', 'key' => 'journal_entries', 'label' => 'erp_expanded_screens.screens.journal_entries', 'status' => 'live', 'route' => 'admin.accounting.journal-entries.index', 'path' => 'admin/accounting/journal-entries', 'permission' => 'journal_entries.view', 'icon' => 'book-open'],
        ['module' => 'general_accounting', 'key' => 'account_ledger', 'label' => 'erp_expanded_screens.screens.account_ledger', 'status' => 'live', 'route' => 'admin.accounting.reports.account-ledger', 'path' => 'admin/accounting/reports/account-ledger', 'permission' => 'reports.account_ledger.view', 'icon' => 'list-alt'],
        ['module' => 'general_accounting', 'key' => 'customer_statement', 'label' => 'erp_expanded_screens.screens.customer_statement', 'status' => 'live', 'route' => 'admin.accounting.reports.customer-statement', 'path' => 'admin/accounting/reports/customer-statement', 'permission' => 'reports.customer_statement.view', 'icon' => 'file-invoice-dollar'],
        ['module' => 'general_accounting', 'key' => 'supplier_statement', 'label' => 'erp_expanded_screens.screens.supplier_statement', 'status' => 'live', 'route' => 'admin.accounting.reports.supplier-statement', 'path' => 'admin/accounting/reports/supplier-statement', 'permission' => 'reports.supplier_statement.view', 'icon' => 'file-invoice'],

        ['module' => 'costing', 'key' => 'estimated_cost_sheets', 'label' => 'erp_expanded_screens.screens.estimated_cost_sheets', 'status' => 'placeholder', 'route' => 'admin.costing.estimated-cost-sheets.index', 'path' => 'admin/costing/estimated-cost-sheets', 'permission' => 'costing.estimated_cost_sheets.view', 'icon' => 'file-invoice-dollar'],
        ['module' => 'costing', 'key' => 'actual_cost_sheets', 'label' => 'erp_expanded_screens.screens.actual_cost_sheets', 'status' => 'placeholder', 'route' => 'admin.costing.actual-cost-sheets.index', 'path' => 'admin/costing/actual-cost-sheets', 'permission' => 'costing.actual_cost_sheets.view', 'icon' => 'receipt'],
        ['module' => 'costing', 'key' => 'cost_variance_analysis', 'label' => 'erp_expanded_screens.screens.cost_variance_analysis', 'status' => 'placeholder', 'route' => 'admin.costing.variance-analysis.index', 'path' => 'admin/costing/variance-analysis', 'permission' => 'costing.variance_analysis.view', 'icon' => 'chart-line'],
        ['module' => 'costing', 'key' => 'job_closing', 'label' => 'erp_expanded_screens.screens.job_closing', 'status' => 'placeholder', 'route' => 'admin.costing.job-closing.index', 'path' => 'admin/costing/job-closing', 'permission' => 'costing.job_closing.view', 'icon' => 'check-circle'],
        ['module' => 'costing', 'key' => 'costing_settings', 'label' => 'erp_expanded_screens.screens.costing_settings', 'status' => 'placeholder', 'route' => 'admin.costing.settings.index', 'path' => 'admin/costing/settings', 'permission' => 'costing.settings.view', 'icon' => 'cog'],

        ['module' => 'sales', 'key' => 'customers', 'label' => 'erp_expanded_screens.screens.customers', 'status' => 'live', 'route' => 'admin.sales.customers.index', 'path' => 'admin/sales/customers', 'permission' => 'customers.view', 'icon' => 'user-tie'],
        ['module' => 'sales', 'key' => 'quotations', 'label' => 'erp_expanded_screens.screens.quotations', 'status' => 'live', 'route' => 'admin.sales.quotations.index', 'path' => 'admin/sales/quotations', 'permission' => 'quotations.view', 'icon' => 'file-invoice-dollar'],
        ['module' => 'sales', 'key' => 'sales_orders', 'label' => 'erp_expanded_screens.screens.sales_orders', 'status' => 'implemented', 'route' => 'admin.sales.sales-orders.index', 'path' => 'admin/sales/sales-orders', 'permission' => 'sales_orders.view', 'icon' => 'clipboard-list'],
        ['module' => 'sales', 'key' => 'customer_invoices', 'label' => 'erp_expanded_screens.screens.customer_invoices', 'status' => 'implemented', 'route' => 'admin.sales.sales-invoices.index', 'path' => 'admin/sales/sales-invoices', 'permission' => 'customer_invoices.view', 'icon' => 'file-invoice-dollar'],
        ['module' => 'sales', 'key' => 'customer_receipts', 'label' => 'erp_expanded_screens.screens.customer_receipts', 'status' => 'implemented', 'route' => 'admin.sales.customer-receipts.index', 'path' => 'admin/sales/customer-receipts', 'permission' => 'customer_receipts.view', 'icon' => 'hand-holding-usd'],
        ['module' => 'sales', 'key' => 'delivery_notes', 'label' => 'erp_expanded_screens.screens.delivery_notes', 'status' => 'implemented', 'route' => 'admin.sales.delivery-notes.index', 'path' => 'admin/sales/delivery-notes', 'permission' => 'sales_deliveries.view', 'icon' => 'truck-loading'],
        ['module' => 'sales', 'key' => 'sales_returns', 'label' => 'erp_expanded_screens.screens.sales_returns', 'status' => 'implemented', 'route' => 'admin.sales.sales-returns.index', 'path' => 'admin/sales/sales-returns', 'permission' => 'sales_returns.view', 'icon' => 'undo-alt'],

        ['module' => 'purchases', 'key' => 'suppliers', 'label' => 'erp_expanded_screens.screens.suppliers', 'status' => 'live', 'route' => 'admin.purchases.suppliers.index', 'path' => 'admin/purchases/suppliers', 'permission' => 'suppliers.view', 'icon' => 'truck'],
        ['module' => 'purchases', 'key' => 'purchase_orders', 'label' => 'erp_expanded_screens.screens.purchase_orders', 'status' => 'live', 'route' => 'admin.purchases.purchase-orders.index', 'path' => 'admin/purchases/purchase-orders', 'permission' => 'purchase_orders.view', 'icon' => 'clipboard-list', 'expanded_required' => true],
        ['module' => 'purchases', 'key' => 'purchase_invoices', 'label' => 'erp_expanded_screens.screens.purchase_invoices', 'status' => 'live', 'route' => 'admin.purchases.purchase-invoices.index', 'path' => 'admin/purchases/purchase-invoices', 'permission' => 'purchase_invoices.view', 'icon' => 'file-invoice-dollar'],
        ['module' => 'purchases', 'key' => 'goods_receipts', 'label' => 'erp_expanded_screens.screens.goods_receipts', 'status' => 'placeholder', 'route' => 'admin.purchases.goods-receipts.index', 'path' => 'admin/purchases/goods-receipts', 'permission' => 'goods_receipts.view', 'icon' => 'dolly'],
        ['module' => 'purchases', 'key' => 'purchase_order_receiving', 'label' => 'erp_expanded_screens.screens.purchase_order_receiving', 'status' => 'placeholder', 'route' => 'admin.purchases.purchase-order-receiving.index', 'path' => 'admin/purchases/purchase-order-receiving', 'permission' => 'purchase_order_receiving.view', 'icon' => 'clipboard-check'],
        ['module' => 'purchases', 'key' => 'supplier_payments', 'label' => 'erp_expanded_screens.screens.supplier_payments', 'status' => 'placeholder', 'route' => 'admin.purchases.supplier-payments.index', 'path' => 'admin/purchases/supplier-payments', 'permission' => 'supplier_payments.view', 'icon' => 'money-check-alt'],
        ['module' => 'purchases', 'key' => 'supplier_invoice_allocations', 'label' => 'erp_expanded_screens.screens.supplier_invoice_allocations', 'status' => 'placeholder', 'route' => 'admin.purchases.supplier-invoice-allocations.index', 'path' => 'admin/purchases/supplier-invoice-allocations', 'permission' => 'supplier_invoice_allocations.view', 'icon' => 'tasks'],

        ['module' => 'planning_production', 'key' => 'production_identifier_types', 'label' => 'erp_expanded_screens.screens.production_identifier_types', 'status' => 'live', 'route' => 'admin.production.identifier-types.index', 'path' => 'admin/production/identifier-types', 'permission' => 'production.identifier_types.view', 'icon' => 'tags'],
        ['module' => 'planning_production', 'key' => 'production_identifiers', 'label' => 'erp_expanded_screens.screens.production_identifiers', 'status' => 'live', 'route' => 'admin.production.identifiers.index', 'path' => 'admin/production/identifiers', 'permission' => 'production.identifiers.view', 'icon' => 'sitemap'],
        ['module' => 'planning_production', 'key' => 'production_identifier_assignments', 'label' => 'erp_expanded_screens.screens.production_identifier_assignments', 'status' => 'retired', 'route' => 'admin.production.identifier-assignments.index', 'path' => 'admin/production/identifier-assignments', 'permission' => 'production.identifier_assignments.view', 'icon' => 'project-diagram'],
        ['module' => 'planning_production', 'key' => 'production_work_orders', 'label' => 'erp_expanded_screens.screens.production_work_orders', 'status' => 'implemented', 'route' => 'admin.production.work-orders.index', 'path' => 'admin/production/work-orders', 'permission' => 'production.work_orders.view', 'icon' => 'clipboard-list'],
        ['module' => 'planning_production', 'key' => 'technical_office_reviews', 'label' => 'erp_expanded_screens.screens.technical_office_reviews', 'status' => 'retired', 'route' => 'admin.production.technical-office-reviews.index', 'path' => 'admin/production/technical-office-reviews', 'permission' => 'production.technical_office_reviews.view', 'icon' => 'drafting-compass'],
        ['module' => 'planning_production', 'key' => 'production_stages', 'label' => 'erp_expanded_screens.screens.production_stages', 'status' => 'retired', 'route' => 'admin.production.stages.index', 'path' => 'admin/production/stages', 'permission' => 'production.stages.view', 'icon' => 'stream'],
        ['module' => 'planning_production', 'key' => 'production_material_requests', 'label' => 'erp_expanded_screens.screens.production_material_requests', 'status' => 'retired', 'route' => 'admin.production.material-requests.index', 'path' => 'admin/production/material-requests', 'permission' => 'production.material_requests.view', 'icon' => 'clipboard'],
        ['module' => 'planning_production', 'key' => 'production_material_issues', 'label' => 'erp_expanded_screens.screens.production_material_issues', 'status' => 'retired', 'route' => 'admin.production.material-issues.index', 'path' => 'admin/production/material-issues', 'permission' => 'production.material_issues.view', 'icon' => 'share-square'],
        ['module' => 'planning_production', 'key' => 'production_material_returns', 'label' => 'erp_expanded_screens.screens.production_material_returns', 'status' => 'retired', 'route' => 'admin.production.material-returns.index', 'path' => 'admin/production/material-returns', 'permission' => 'production.material_returns.view', 'icon' => 'undo-alt'],
        ['module' => 'planning_production', 'key' => 'production_output_receipts', 'label' => 'erp_expanded_screens.screens.production_output_receipts', 'status' => 'retired', 'route' => 'admin.production.output-receipts.index', 'path' => 'admin/production/output-receipts', 'permission' => 'production.output_receipts.view', 'icon' => 'boxes'],
        ['module' => 'planning_production', 'key' => 'external_manufacturing_orders', 'label' => 'erp_expanded_screens.screens.external_manufacturing_orders', 'status' => 'retired', 'route' => 'admin.production.external-manufacturing-orders.index', 'path' => 'admin/production/external-manufacturing-orders', 'permission' => 'production.external_manufacturing_orders.view', 'icon' => 'industry'],
        ['module' => 'planning_production', 'key' => 'supplier_custodies', 'label' => 'erp_expanded_screens.screens.supplier_custodies', 'status' => 'retired', 'route' => 'admin.production.supplier-custodies.index', 'path' => 'admin/production/supplier-custodies', 'permission' => 'production.supplier_custodies.view', 'icon' => 'people-carry'],

        ['module' => 'quality', 'key' => 'quality_inspection_types', 'label' => 'erp_expanded_screens.screens.quality_inspection_types', 'status' => 'retired', 'route' => 'admin.quality.inspection-types.index', 'path' => 'admin/quality/inspection-types', 'permission' => 'quality.inspection_types.view', 'icon' => 'tags'],
        ['module' => 'quality', 'key' => 'quality_checkpoints', 'label' => 'erp_expanded_screens.screens.quality_checkpoints', 'status' => 'retired', 'route' => 'admin.quality.checkpoints.index', 'path' => 'admin/quality/checkpoints', 'permission' => 'quality.checkpoints.view', 'icon' => 'tasks'],
        ['module' => 'quality', 'key' => 'quality_inspections', 'label' => 'erp_expanded_screens.screens.quality_inspections', 'status' => 'retired', 'route' => 'admin.quality.inspections.index', 'path' => 'admin/quality/inspections', 'permission' => 'quality.inspections.view', 'icon' => 'clipboard-check'],
        ['module' => 'quality', 'key' => 'quality_results', 'label' => 'erp_expanded_screens.screens.quality_results', 'status' => 'retired', 'route' => 'admin.quality.results.index', 'path' => 'admin/quality/results', 'permission' => 'quality.results.view', 'icon' => 'poll'],
        ['module' => 'quality', 'key' => 'quality_reports', 'label' => 'erp_expanded_screens.screens.quality_reports', 'status' => 'retired', 'route' => 'admin.quality.reports.index', 'path' => 'admin/quality/reports', 'permission' => 'quality.reports.view', 'icon' => 'chart-bar'],

        ['module' => 'maintenance', 'key' => 'maintenance_requests', 'label' => 'erp_expanded_screens.screens.maintenance_requests', 'status' => 'placeholder', 'route' => 'admin.maintenance.requests.index', 'path' => 'admin/maintenance/requests', 'permission' => 'maintenance.requests.view', 'icon' => 'clipboard-list'],
        ['module' => 'maintenance', 'key' => 'maintenance_work_orders', 'label' => 'erp_expanded_screens.screens.maintenance_work_orders', 'status' => 'placeholder', 'route' => 'admin.maintenance.work-orders.index', 'path' => 'admin/maintenance/work-orders', 'permission' => 'maintenance.work_orders.view', 'icon' => 'tools'],
        ['module' => 'maintenance', 'key' => 'preventive_maintenance_plans', 'label' => 'erp_expanded_screens.screens.preventive_maintenance_plans', 'status' => 'placeholder', 'route' => 'admin.maintenance.preventive-plans.index', 'path' => 'admin/maintenance/preventive-plans', 'permission' => 'maintenance.preventive_plans.view', 'icon' => 'calendar-check'],
        ['module' => 'maintenance', 'key' => 'maintenance_execution', 'label' => 'erp_expanded_screens.screens.maintenance_execution', 'status' => 'placeholder', 'route' => 'admin.maintenance.execution.index', 'path' => 'admin/maintenance/execution', 'permission' => 'maintenance.execution.view', 'icon' => 'wrench'],
        ['module' => 'maintenance', 'key' => 'maintenance_history', 'label' => 'erp_expanded_screens.screens.maintenance_history', 'status' => 'placeholder', 'route' => 'admin.maintenance.history.index', 'path' => 'admin/maintenance/history', 'permission' => 'maintenance.history.view', 'icon' => 'history'],
        ['module' => 'maintenance', 'key' => 'maintenance_reports', 'label' => 'erp_expanded_screens.screens.maintenance_reports', 'status' => 'placeholder', 'route' => 'admin.maintenance.reports.index', 'path' => 'admin/maintenance/reports', 'permission' => 'maintenance.reports.view', 'icon' => 'chart-bar'],

        ['module' => 'finance', 'key' => 'currencies', 'label' => 'erp_expanded_screens.screens.currencies', 'status' => 'live', 'route' => 'admin.currencies.index', 'path' => 'admin/currencies', 'permission' => 'currencies.view', 'icon' => 'coins'],
        ['module' => 'finance', 'key' => 'bank_accounts', 'label' => 'erp_expanded_screens.screens.bank_accounts', 'status' => 'live', 'route' => 'admin.finance.bank-accounts.index', 'path' => 'admin/finance/bank-accounts', 'permission' => 'bank_accounts.view', 'icon' => 'university'],
        ['module' => 'finance', 'key' => 'cashboxes', 'label' => 'erp_expanded_screens.screens.cashboxes', 'status' => 'live', 'route' => 'admin.finance.cashboxes.index', 'path' => 'admin/finance/cashboxes', 'permission' => 'cashboxes.view', 'icon' => 'cash-register'],
        ['module' => 'finance', 'key' => 'cash_receipt_vouchers', 'label' => 'erp_expanded_screens.screens.cash_receipt_vouchers', 'status' => 'live', 'route' => 'admin.finance.cash-receipt-vouchers.index', 'path' => 'admin/finance/cash-receipt-vouchers', 'permission' => 'cash_receipt_vouchers.view', 'icon' => 'file-invoice-dollar'],
        ['module' => 'finance', 'key' => 'cash_payment_vouchers', 'label' => 'erp_expanded_screens.screens.cash_payment_vouchers', 'status' => 'live', 'route' => 'admin.finance.cash-payment-vouchers.index', 'path' => 'admin/finance/cash-payment-vouchers', 'permission' => 'cash_payment_vouchers.view', 'icon' => 'file-invoice'],
        ['module' => 'finance', 'key' => 'cheques', 'label' => 'erp_expanded_screens.screens.cheques', 'status' => 'live', 'route' => 'admin.finance.cheques.index', 'path' => 'admin/finance/cheques', 'permission' => 'cheques.view', 'icon' => 'money-check'],
        ['module' => 'finance', 'key' => 'fund_transfers', 'label' => 'erp_expanded_screens.screens.fund_transfers', 'status' => 'live', 'route' => 'admin.finance.fund-transfers.index', 'path' => 'admin/finance/fund-transfers', 'permission' => 'fund_transfers.view', 'icon' => 'exchange-alt'],
        ['module' => 'finance', 'key' => 'opening_balances', 'label' => 'erp_expanded_screens.screens.opening_balances', 'status' => 'live', 'route' => 'admin.finance.opening-balances.index', 'path' => 'admin/finance/opening-balances', 'permission' => 'opening_balances.view', 'icon' => 'balance-scale'],

        ['module' => 'fixed_assets', 'key' => 'fixed_assets_register', 'label' => 'erp_expanded_screens.screens.fixed_assets_register', 'status' => 'live', 'route' => 'admin.fixed-assets.assets.index', 'path' => 'admin/fixed-assets/assets', 'permission' => 'fixed_assets.view', 'icon' => 'clipboard-list'],

        ['module' => 'inventory', 'key' => 'opening_stocks', 'label' => 'erp_expanded_screens.screens.opening_stocks', 'status' => 'live', 'route' => 'admin.inventory.opening-stocks.index', 'path' => 'admin/inventory/opening-stocks', 'permission' => 'inventory.opening_stocks.view', 'icon' => 'boxes'],
        ['module' => 'inventory', 'key' => 'unpriced_inventory_receipts', 'label' => 'erp_expanded_screens.screens.unpriced_inventory_receipts', 'status' => 'live', 'route' => 'admin.inventory.unpriced-inventory-receipts.index', 'path' => 'admin/inventory/unpriced-inventory-receipts', 'permission' => 'inventory.unpriced_inventory_receipts.view', 'icon' => 'dolly'],
        ['module' => 'inventory', 'key' => 'opening_stock_pricings', 'label' => 'erp_expanded_screens.screens.opening_stock_pricings', 'status' => 'live', 'route' => 'admin.inventory.opening-stock-pricings.index', 'path' => 'admin/inventory/opening-stock-pricings', 'permission' => 'inventory.opening_stock_pricings.view', 'icon' => 'tags'],
        ['module' => 'inventory', 'key' => 'inventory_material_requests', 'label' => 'erp_expanded_screens.screens.inventory_material_requests', 'status' => 'retired', 'route' => 'admin.inventory.material-requests.index', 'path' => 'admin/inventory/material-requests', 'permission' => 'inventory.material_requests.view', 'icon' => 'clipboard'],
        ['module' => 'inventory', 'key' => 'inventory_material_issues', 'label' => 'erp_expanded_screens.screens.inventory_material_issues', 'status' => 'retired', 'route' => 'admin.inventory.material-issues.index', 'path' => 'admin/inventory/material-issues', 'permission' => 'inventory.material_issues.view', 'icon' => 'share-square'],
        ['module' => 'inventory', 'key' => 'inventory_material_returns', 'label' => 'erp_expanded_screens.screens.inventory_material_returns', 'status' => 'retired', 'route' => 'admin.inventory.material-returns.index', 'path' => 'admin/inventory/material-returns', 'permission' => 'inventory.material_returns.view', 'icon' => 'undo-alt'],
        ['module' => 'inventory', 'key' => 'inventory_transfers', 'label' => 'erp_expanded_screens.screens.inventory_transfers', 'status' => 'retired', 'route' => 'admin.inventory.transfers.index', 'path' => 'admin/inventory/transfers', 'permission' => 'inventory.transfers.view', 'icon' => 'exchange-alt'],

        ['module' => 'human_resources', 'key' => 'hr_employees', 'label' => 'erp_expanded_screens.screens.hr_employees', 'status' => 'live', 'route' => 'admin.hr.employees.index', 'path' => 'admin/hr/employees', 'permission' => 'hr.employees.view', 'icon' => 'user-tie'],
        ['module' => 'human_resources', 'key' => 'hr_departments', 'label' => 'erp_expanded_screens.screens.hr_departments', 'status' => 'live', 'route' => 'admin.hr.departments.index', 'path' => 'admin/hr/departments', 'permission' => 'hr.departments.view', 'icon' => 'building'],
        ['module' => 'human_resources', 'key' => 'hr_sections', 'label' => 'erp_expanded_screens.screens.hr_sections', 'status' => 'live', 'route' => 'admin.hr.sections.index', 'path' => 'admin/hr/sections', 'permission' => 'hr.sections.view', 'icon' => 'sitemap'],
        ['module' => 'human_resources', 'key' => 'hr_jobs', 'label' => 'erp_expanded_screens.screens.hr_jobs', 'status' => 'live', 'route' => 'admin.hr.jobs.index', 'path' => 'admin/hr/jobs', 'permission' => 'hr.jobs.view', 'icon' => 'briefcase'],
        ['module' => 'human_resources', 'key' => 'hr_employment_types', 'label' => 'erp_expanded_screens.screens.hr_employment_types', 'status' => 'live', 'route' => 'admin.hr.employment-types.index', 'path' => 'admin/hr/employment-types', 'permission' => 'hr.employment_types.view', 'icon' => 'id-badge'],
        ['module' => 'human_resources', 'key' => 'hr_biometric_devices', 'label' => 'erp_expanded_screens.screens.hr_biometric_devices', 'status' => 'live', 'route' => 'admin.hr.biometric-devices.index', 'path' => 'admin/hr/biometric-devices', 'permission' => 'hr.biometric_devices.view', 'icon' => 'fingerprint'],
        ['module' => 'human_resources', 'key' => 'hr_shifts', 'label' => 'erp_expanded_screens.screens.hr_shifts', 'status' => 'live', 'route' => 'admin.hr.shifts.index', 'path' => 'admin/hr/shifts', 'permission' => 'hr.shifts.view', 'icon' => 'clock'],
        ['module' => 'human_resources', 'key' => 'hr_document_types', 'label' => 'erp_expanded_screens.screens.hr_document_types', 'status' => 'live', 'route' => 'admin.hr.document-types.index', 'path' => 'admin/hr/document-types', 'permission' => 'hr.document_types.view', 'icon' => 'file-alt'],
        ['module' => 'human_resources', 'key' => 'hr_insurance_offices', 'label' => 'erp_expanded_screens.screens.hr_insurance_offices', 'status' => 'live', 'route' => 'admin.hr.insurance-offices.index', 'path' => 'admin/hr/insurance-offices', 'permission' => 'hr.insurance_offices.view', 'icon' => 'shield-alt'],
        ['module' => 'human_resources', 'key' => 'hr_allowances', 'label' => 'erp_expanded_screens.screens.hr_allowances', 'status' => 'live', 'route' => 'admin.hr.allowances.index', 'path' => 'admin/hr/allowances', 'permission' => 'hr.allowances.view', 'icon' => 'plus-circle'],
        ['module' => 'human_resources', 'key' => 'hr_areas', 'label' => 'erp_expanded_screens.screens.hr_areas', 'status' => 'live', 'route' => 'admin.hr.areas.index', 'path' => 'admin/hr/areas', 'permission' => 'hr.areas.view', 'icon' => 'map-marker-alt'],
        ['module' => 'human_resources', 'key' => 'hr_cities', 'label' => 'erp_expanded_screens.screens.hr_cities', 'status' => 'live', 'route' => 'admin.hr.cities.index', 'path' => 'admin/hr/cities', 'permission' => 'hr.cities.view', 'icon' => 'city'],
        ['module' => 'human_resources', 'key' => 'hr_countries', 'label' => 'erp_expanded_screens.screens.hr_countries', 'status' => 'live', 'route' => 'admin.hr.countries.index', 'path' => 'admin/hr/countries', 'permission' => 'hr.countries.view', 'icon' => 'globe'],
        ['module' => 'human_resources', 'key' => 'hr_faculties', 'label' => 'erp_expanded_screens.screens.hr_faculties', 'status' => 'live', 'route' => 'admin.hr.faculties.index', 'path' => 'admin/hr/faculties', 'permission' => 'hr.faculties.view', 'icon' => 'university'],
        ['module' => 'human_resources', 'key' => 'hr_governorates', 'label' => 'erp_expanded_screens.screens.hr_governorates', 'status' => 'live', 'route' => 'admin.hr.governorates.index', 'path' => 'admin/hr/governorates', 'permission' => 'hr.governorates.view', 'icon' => 'map'],
        ['module' => 'human_resources', 'key' => 'hr_grades', 'label' => 'erp_expanded_screens.screens.hr_grades', 'status' => 'live', 'route' => 'admin.hr.grades.index', 'path' => 'admin/hr/grades', 'permission' => 'hr.grades.view', 'icon' => 'layer-group'],
        ['module' => 'human_resources', 'key' => 'hr_hiring_statuses', 'label' => 'erp_expanded_screens.screens.hr_hiring_statuses', 'status' => 'live', 'route' => 'admin.hr.hiring-statuses.index', 'path' => 'admin/hr/hiring-statuses', 'permission' => 'hr.hiring_statuses.view', 'icon' => 'user-check'],
        ['module' => 'human_resources', 'key' => 'hr_identifications', 'label' => 'erp_expanded_screens.screens.hr_identifications', 'status' => 'live', 'route' => 'admin.hr.identifications.index', 'path' => 'admin/hr/identifications', 'permission' => 'hr.identifications.view', 'icon' => 'id-card'],
        ['module' => 'human_resources', 'key' => 'hr_military_services', 'label' => 'erp_expanded_screens.screens.hr_military_services', 'status' => 'live', 'route' => 'admin.hr.military-services.index', 'path' => 'admin/hr/military-services', 'permission' => 'hr.military_services.view', 'icon' => 'medal'],
        ['module' => 'human_resources', 'key' => 'hr_nationalities', 'label' => 'erp_expanded_screens.screens.hr_nationalities', 'status' => 'live', 'route' => 'admin.hr.nationalities.index', 'path' => 'admin/hr/nationalities', 'permission' => 'hr.nationalities.view', 'icon' => 'flag'],
        ['module' => 'human_resources', 'key' => 'hr_qualifications', 'label' => 'erp_expanded_screens.screens.hr_qualifications', 'status' => 'live', 'route' => 'admin.hr.qualifications.index', 'path' => 'admin/hr/qualifications', 'permission' => 'hr.qualifications.view', 'icon' => 'graduation-cap'],
        ['module' => 'human_resources', 'key' => 'hr_religions', 'label' => 'erp_expanded_screens.screens.hr_religions', 'status' => 'live', 'route' => 'admin.hr.religions.index', 'path' => 'admin/hr/religions', 'permission' => 'hr.religions.view', 'icon' => 'star-and-crescent'],
        ['module' => 'human_resources', 'key' => 'hr_specializations', 'label' => 'erp_expanded_screens.screens.hr_specializations', 'status' => 'live', 'route' => 'admin.hr.specializations.index', 'path' => 'admin/hr/specializations', 'permission' => 'hr.specializations.view', 'icon' => 'certificate'],
        ['module' => 'human_resources', 'key' => 'hr_universities', 'label' => 'erp_expanded_screens.screens.hr_universities', 'status' => 'live', 'route' => 'admin.hr.universities.index', 'path' => 'admin/hr/universities', 'permission' => 'hr.universities.view', 'icon' => 'university'],

        ['module' => 'reports', 'key' => 'inventory_reports', 'label' => 'erp_expanded_screens.screens.inventory_reports', 'status' => 'placeholder', 'route' => 'admin.reports.inventory.index', 'path' => 'admin/reports/inventory', 'permission' => 'reports.inventory.view', 'icon' => 'warehouse'],
        ['module' => 'reports', 'key' => 'purchases_reports', 'label' => 'erp_expanded_screens.screens.purchases_reports', 'status' => 'placeholder', 'route' => 'admin.reports.purchases.index', 'path' => 'admin/reports/purchases', 'permission' => 'reports.purchases.view', 'icon' => 'shopping-bag'],
        ['module' => 'reports', 'key' => 'sales_reports', 'label' => 'erp_expanded_screens.screens.sales_reports', 'status' => 'placeholder', 'route' => 'admin.reports.sales.index', 'path' => 'admin/reports/sales', 'permission' => 'reports.sales.view', 'icon' => 'shopping-cart'],
        ['module' => 'reports', 'key' => 'production_reports', 'label' => 'erp_expanded_screens.screens.production_reports', 'status' => 'placeholder', 'route' => 'admin.reports.production.index', 'path' => 'admin/reports/production', 'permission' => 'reports.production.view', 'icon' => 'industry'],
        ['module' => 'reports', 'key' => 'quality_domain_reports', 'label' => 'erp_expanded_screens.screens.quality_domain_reports', 'status' => 'placeholder', 'route' => 'admin.reports.quality.index', 'path' => 'admin/reports/quality', 'permission' => 'reports.quality.view', 'icon' => 'clipboard-check'],
        ['module' => 'reports', 'key' => 'finance_reports', 'label' => 'erp_expanded_screens.screens.finance_reports', 'status' => 'placeholder', 'route' => 'admin.reports.finance.index', 'path' => 'admin/reports/finance', 'permission' => 'reports.finance.view', 'icon' => 'money-check-alt'],
        ['module' => 'reports', 'key' => 'costing_reports', 'label' => 'erp_expanded_screens.screens.costing_reports', 'status' => 'placeholder', 'route' => 'admin.reports.costing.index', 'path' => 'admin/reports/costing', 'permission' => 'reports.costing.view', 'icon' => 'calculator'],
        ['module' => 'reports', 'key' => 'maintenance_domain_reports', 'label' => 'erp_expanded_screens.screens.maintenance_domain_reports', 'status' => 'placeholder', 'route' => 'admin.reports.maintenance.index', 'path' => 'admin/reports/maintenance', 'permission' => 'reports.maintenance.view', 'icon' => 'tools'],
        ['module' => 'reports', 'key' => 'human_resources_reports', 'label' => 'erp_expanded_screens.screens.human_resources_reports', 'status' => 'placeholder', 'route' => 'admin.reports.human-resources.index', 'path' => 'admin/reports/human-resources', 'permission' => 'reports.human_resources.view', 'icon' => 'users'],
        ['module' => 'reports', 'key' => 'fixed_assets_reports', 'label' => 'erp_expanded_screens.screens.fixed_assets_reports', 'status' => 'live', 'route' => 'admin.fixed-assets.reports.index', 'path' => 'admin/fixed-assets/reports', 'permission' => 'fixed_assets.reports', 'icon' => 'building'],

        ['module' => 'tools', 'key' => 'open_documents', 'label' => 'erp_expanded_screens.screens.open_documents', 'status' => 'live', 'route' => 'admin.tools.open-documents.index', 'path' => 'admin/tools/open-documents', 'permission' => 'tools.open_documents.view', 'icon' => 'unlock'],
        ['module' => 'tools', 'key' => 'file_manager', 'label' => 'erp_expanded_screens.screens.file_manager', 'status' => 'live', 'route' => 'admin.file-manager.index', 'path' => 'admin/file-manager', 'permission' => 'file_manager.view', 'icon' => 'folder'],
        ['module' => 'tools', 'key' => 'calendar', 'label' => 'erp_expanded_screens.screens.calendar', 'status' => 'live', 'route' => 'admin.calendar.index', 'path' => 'admin/calendar', 'permission' => 'calendar.view', 'icon' => 'calendar-alt'],
        ['module' => 'tools', 'key' => 'my_board', 'label' => 'erp_expanded_screens.screens.my_board', 'status' => 'live', 'route' => 'admin.my-board.index', 'path' => 'admin/my-board', 'permission' => 'my_board.view', 'icon' => 'columns'],
        ['module' => 'tools', 'key' => 'task_boards', 'label' => 'erp_expanded_screens.screens.task_boards', 'status' => 'live', 'route' => 'admin.task-boards.index', 'path' => 'admin/task-boards', 'permission' => 'task_boards.view', 'icon' => 'columns'],
        ['module' => 'tools', 'key' => 'team_board', 'label' => 'erp_expanded_screens.screens.team_board', 'status' => 'live', 'route' => 'admin.tools.team-board.index', 'path' => 'admin/tools/team-board', 'permission' => ['my_board.tasks.view_all', 'my_board.notes.view_all'], 'icon' => 'table'],
        ['module' => 'tools', 'key' => 'chat', 'label' => 'erp_expanded_screens.screens.chat', 'status' => 'live', 'route' => 'admin.chat.index', 'path' => 'admin/chat', 'permission' => 'chat.view', 'icon' => 'comments'],
        ['module' => 'tools', 'key' => 'pwa_settings', 'label' => 'erp_expanded_screens.screens.pwa_settings', 'status' => 'live', 'route' => 'admin.settings.pwa', 'path' => 'admin/settings/pwa', 'permission' => 'settings.pwa.view', 'icon' => 'mobile-alt'],
    ],
];
