<?php

return [
    'order' => [
        'dashboard',
        'basic_data',
        'sales',
        'purchases',
        'inventory',
        'production',
        'accounting_costing',
        'human_resources',
        'tools',
    ],

    'sections' => [
        'basic_data' => ['icon' => 'database'],
        'sales' => ['icon' => 'shopping-cart'],
        'purchases' => ['icon' => 'shopping-bag'],
        'inventory' => ['icon' => 'warehouse'],
        'production' => ['icon' => 'industry'],
        'accounting_costing' => ['icon' => 'calculator'],
        'human_resources' => ['icon' => 'user-tie'],
        'tools' => ['icon' => 'tools'],
    ],

    'source_sections' => [
        'dashboard' => 'dashboard',
        'basic_data' => 'basic_data',
        'dashboard_setup' => 'basic_data',
        'master_data_settings' => 'basic_data',
        'item_data' => 'inventory',
        'sales' => 'sales',
        'purchases' => 'purchases',
        'inventory' => 'inventory',
        'inventory_operations' => 'inventory',
        'planning_production' => 'production',
        'production' => 'production',
        'quality' => 'production',
        'maintenance' => 'production',
        'general_ledger' => 'accounting_costing',
        'accounting' => 'accounting_costing',
        'accounting_costing' => 'accounting_costing',
        'finance' => 'accounting_costing',
        'fixed_assets' => 'accounting_costing',
        'costing' => 'accounting_costing',
        'human_resources' => 'human_resources',
        'reports' => null,
        'tools' => 'tools',
    ],

    'container_sections' => [
        'product_data_classification' => 'basic_data',
        'product_data_relationships' => 'production',
        'reports_finance' => 'accounting_costing',
        'reports_sales' => 'sales',
        'reports_purchases' => 'purchases',
        'reports_inventory' => 'inventory',
        'reports_production' => 'production',
        'reports_quality' => 'production',
        'reports_maintenance' => 'production',
        'reports_costing' => 'accounting_costing',
    ],

    'leaf_sections' => [
        'item_units' => 'basic_data',
        'item_sizes' => 'basic_data',
        'item_colors' => 'basic_data',
        'item_decals' => 'basic_data',
        'item_models' => 'basic_data',
        'item_categories' => 'basic_data',
        'item_groups' => 'basic_data',
        'item_origin_countries' => 'basic_data',
        'core_tax_definitions' => 'accounting_costing',
        'core_currency_rate_policies' => 'accounting_costing',
        'core_warehouse_policies' => 'inventory',
        'core_production_policies' => 'production',
        'core_quality_policies' => 'production',
        'core_maintenance_policies' => 'production',
        'product_data_product_specifications' => 'basic_data',
        'product_data_product_technical_properties' => 'basic_data',
        'product_data_product_units' => 'basic_data',
        'product_data_product_equivalent_units' => 'basic_data',
        'product_data_product_bom' => 'production',
        'product_data_product_routing' => 'production',
        'product_data_product_quality_specifications' => 'production',
        'inventory_finished_goods_receipt' => 'production',
        'inventory_production_material_issue' => 'production',
        'inventory_production_material_return' => 'production',
        'activity_logs' => 'tools',
        'auth_logs' => 'tools',
        'auth_sessions' => 'tools',
        'products_data_report' => 'inventory',
        'customers_report' => 'sales',
        'suppliers_report' => 'purchases',
    ],
];
