<?php

return [
    'order' => [
        'dashboard',
        'basic_data',
        'sales',
        'purchases',
        'inventory',
        'production',
        'accounting_costing',
        'fixed_assets',
        'maintenance',
        'human_resources',
        'reports',
        'tools',
    ],

    'sections' => [
        'basic_data' => ['icon' => 'database'],
        'sales' => ['icon' => 'shopping-cart'],
        'purchases' => ['icon' => 'shopping-bag'],
        'inventory' => ['icon' => 'warehouse'],
        'production' => ['icon' => 'industry'],
        'accounting_costing' => ['icon' => 'calculator'],
        'fixed_assets' => ['icon' => 'building'],
        'maintenance' => ['icon' => 'tools'],
        'human_resources' => ['icon' => 'user-tie'],
        'reports' => ['icon' => 'chart-bar'],
        'tools' => ['icon' => 'tools'],
    ],

    'source_sections' => [
        'dashboard' => 'dashboard',
        'basic_data' => 'basic_data',
        'dashboard_setup' => 'basic_data',
        'master_data_settings' => 'basic_data',
        'item_data' => 'inventory',
        'sales' => 'sales',
        'purchases' => 'purchases',
        'inventory' => 'inventory',
        'inventory_operations' => 'inventory',
        'planning_production' => 'production',
        'production' => 'production',
        'quality' => 'production',
        'maintenance' => 'maintenance',
        'general_ledger' => 'accounting_costing',
        'accounting' => 'accounting_costing',
        'accounting_costing' => 'accounting_costing',
        'finance' => 'accounting_costing',
        'fixed_assets' => 'fixed_assets',
        'costing' => 'accounting_costing',
        'human_resources' => 'human_resources',
        'reports' => 'reports',
        'tools' => 'tools',
    ],

    'leaf_sections' => [
        'core_tax_definitions' => 'accounting_costing',
        'core_currency_rate_policies' => 'accounting_costing',
        'core_warehouse_policies' => 'inventory',
        'core_production_policies' => 'production',
        'core_quality_policies' => 'production',
        'core_maintenance_policies' => 'maintenance',
        'product_data_product_bom' => 'production',
        'product_data_product_routing' => 'production',
        'product_data_product_quality_specifications' => 'production',
        'product_data_mold_product_relationships' => 'production',
        'product_data_machine_product_relationships' => 'production',
        'product_data_raw_material_substitution_rules' => 'production',
        'product_data_scrap_definitions' => 'production',
        'product_data_waste_definitions' => 'production',
        'inventory_finished_goods_receipt' => 'production',
        'inventory_production_material_issue' => 'production',
        'inventory_production_material_return' => 'production',
        'activity_logs' => 'tools',
        'auth_logs' => 'tools',
        'auth_sessions' => 'tools',
        'fixed_assets_register' => 'fixed_assets',
        'products_data_report' => 'reports',
        'customers_report' => 'reports',
        'suppliers_report' => 'reports',
    ],

    'leaf_subgroups' => [
        'roles' => 'users_permissions',
        'users' => 'users_permissions',
        'screen_data_visibility_rules' => 'users_permissions',
        'profile' => 'users_permissions',
        'companies' => 'organization_setup',
        'branches' => 'organization_setup',
        'financial_periods' => 'organization_setup',
        'activity_logs' => 'application_tools',
        'auth_logs' => 'application_tools',
        'auth_sessions' => 'application_tools',
        'customers' => 'customer_data',
        'quotations' => 'sales_cycle',
        'project_structures' => 'sales_setup',
        'project_structure_models' => 'sales_setup',
        'suppliers' => 'supplier_data',
        'purchase_orders' => 'purchase_cycle',
        'purchase_invoices' => 'purchase_cycle',
        'products' => 'item_data',
        'raw_materials' => 'item_data',
        'packaging_materials' => 'item_data',
        'item_units' => 'item_data',
        'item_sizes' => 'item_data',
        'item_colors' => 'item_data',
        'item_decals' => 'item_data',
        'item_models' => 'item_data',
        'item_categories' => 'item_data',
        'item_groups' => 'item_data',
        'item_origin_countries' => 'item_data',
        'opening_stocks' => 'opening_inventory',
        'unpriced_inventory_receipts' => 'opening_inventory',
        'opening_stock_pricings' => 'opening_inventory',
        'production_identifier_types' => 'production_setup',
        'production_identifiers' => 'production_setup',
        'chart_of_accounts' => 'general_accounting',
        'opening_balances' => 'general_accounting',
        'journal_entries' => 'general_accounting',
        'account_ledger' => 'general_accounting',
        'customer_statement' => 'general_accounting',
        'supplier_statement' => 'general_accounting',
        'currencies' => 'treasury_banks',
        'bank_accounts' => 'treasury_banks',
        'cashboxes' => 'treasury_banks',
        'cash_receipt_vouchers' => 'treasury_banks',
        'cash_payment_vouchers' => 'treasury_banks',
        'cheques' => 'treasury_banks',
        'fund_transfers' => 'treasury_banks',
        'cost_centers' => 'cost_accounting',
        'fixed_assets_register' => 'asset_data',
        'hr_employees' => 'employee_data',
        'hr_departments' => 'hr_setup',
        'hr_sections' => 'hr_setup',
        'hr_jobs' => 'hr_setup',
        'hr_employment_types' => 'hr_setup',
        'hr_biometric_devices' => 'attendance_leave',
        'hr_shifts' => 'attendance_leave',
        'hr_document_types' => 'hr_setup',
        'hr_insurance_offices' => 'hr_setup',
        'hr_allowances' => 'hr_setup',
        'hr_areas' => 'hr_setup',
        'hr_cities' => 'hr_setup',
        'hr_countries' => 'hr_setup',
        'hr_faculties' => 'hr_setup',
        'hr_governorates' => 'hr_setup',
        'hr_grades' => 'hr_setup',
        'hr_hiring_statuses' => 'hr_setup',
        'hr_identifications' => 'hr_setup',
        'hr_military_services' => 'hr_setup',
        'hr_nationalities' => 'hr_setup',
        'hr_qualifications' => 'hr_setup',
        'hr_religions' => 'hr_setup',
        'hr_specializations' => 'hr_setup',
        'hr_universities' => 'hr_setup',
        'products_data_report' => 'inventory_reports',
        'customers_report' => 'sales_reports',
        'suppliers_report' => 'purchase_reports',
        'open_documents' => 'files_documents',
        'file_manager' => 'files_documents',
        'calendar' => 'work_management',
        'my_board' => 'work_management',
        'task_boards' => 'work_management',
        'team_board' => 'work_management',
        'chat' => 'communication',
        'pwa_settings' => 'application_tools',
        'core_tax_definitions' => 'general_accounting',
        'core_currency_rate_policies' => 'treasury_banks',
        'core_warehouse_policies' => 'warehouse_setup',
        'core_production_policies' => 'production_setup',
        'core_quality_policies' => 'quality_management',
        'core_maintenance_policies' => 'maintenance_setup',
        'product_data_product_bom' => 'product_structures',
        'product_data_product_routing' => 'product_structures',
        'product_data_product_quality_specifications' => 'quality_management',
        'product_data_mold_product_relationships' => 'product_structures',
        'product_data_machine_product_relationships' => 'product_structures',
        'product_data_raw_material_substitution_rules' => 'product_structures',
        'product_data_scrap_definitions' => 'product_structures',
        'product_data_waste_definitions' => 'product_structures',
        'inventory_finished_goods_receipt' => 'production_operations',
        'inventory_production_material_issue' => 'production_operations',
        'inventory_production_material_return' => 'production_operations',
    ],

    'source_subgroups' => [
        'core_configuration' => 'organization_setup',
        'core_document_governance' => 'shared_setup',
        'core_commercial_policies' => 'shared_setup',
        'core_operational_policies' => 'shared_setup',
        'product_data_classification' => 'item_data',
        'product_data_technical' => 'item_data',
        'product_data_logistics' => 'item_data',
        'product_data_planning' => 'item_data',
        'product_data_relationships' => 'product_structures',
        'sales_crm' => 'customer_transactions',
        'sales_customer_data' => 'customer_data',
        'sales_quotations' => 'sales_cycle',
        'sales_orders' => 'sales_cycle',
        'sales_contracts' => 'sales_cycle',
        'sales_billing' => 'sales_cycle',
        'sales_delivery' => 'sales_cycle',
        'sales_controls' => 'sales_setup',
        'purchases_requisitions' => 'purchase_cycle',
        'purchases_sourcing' => 'purchase_cycle',
        'purchases_orders' => 'purchase_cycle',
        'purchases_receiving' => 'purchase_cycle',
        'purchases_billing' => 'purchase_cycle',
        'purchases_supplier_management' => 'supplier_data',
        'purchases_special' => 'purchase_cycle',
        'inventory_structure' => 'warehouse_setup',
        'inventory_transactions' => 'inventory_transactions',
        'inventory_counting' => 'inventory_transactions',
        'inventory_tracking' => 'inventory_transactions',
        'inventory_operations' => 'inventory_transactions',
        'inventory_inquiries' => 'inventory_inquiries',
        'inventory_planning' => 'inventory_planning',
        'production_setup' => 'production_setup',
        'production_engineering' => 'product_structures',
        'production_planning' => 'production_planning',
        'production_work_orders' => 'production_operations',
        'production_materials' => 'production_operations',
        'production_execution' => 'production_operations',
        'production_monitoring' => 'production_operations',
        'production_external' => 'production_operations',
        'quality_setup' => 'quality_management',
        'quality_plans' => 'quality_management',
        'quality_inspections' => 'quality_management',
        'quality_decisions' => 'quality_management',
        'quality_capa' => 'quality_management',
        'quality_certificates' => 'quality_management',
        'quality_audits' => 'quality_management',
        'maintenance_setup' => 'maintenance_setup',
        'maintenance_registers' => 'maintenance_setup',
        'maintenance_requests' => 'maintenance_operations',
        'maintenance_work_orders' => 'maintenance_operations',
        'maintenance_preventive' => 'maintenance_planning',
        'maintenance_inspections' => 'maintenance_operations',
        'maintenance_history' => 'maintenance_operations',
        'maintenance_external' => 'maintenance_operations',
        'finance_bank_vouchers' => 'treasury_banks',
        'finance_cheques' => 'treasury_banks',
        'finance_treasury' => 'treasury_banks',
        'finance_reconciliation' => 'treasury_banks',
        'finance_collections' => 'treasury_banks',
        'finance_expenses' => 'treasury_banks',
        'finance_currency' => 'treasury_banks',
        'finance_history' => 'treasury_banks',
        'fixed_assets_setup' => 'asset_data',
        'fixed_assets_transactions' => 'asset_transactions',
        'fixed_assets_depreciation' => 'depreciation',
        'fixed_assets_valuation' => 'asset_transactions',
        'fixed_assets_support' => 'asset_transactions',
        'costing_setup' => 'cost_accounting',
        'costing_standards' => 'cost_accounting',
        'costing_work_orders' => 'costing_operations',
        'costing_components' => 'costing_operations',
        'costing_allocation' => 'costing_operations',
        'costing_analysis' => 'costing_analysis',
        'costing_closing' => 'costing_operations',
        'hr_contracts' => 'employee_data',
        'hr_attendance' => 'attendance_leave',
        'hr_leave' => 'attendance_leave',
        'hr_employee_relations' => 'employee_transactions',
        'hr_development' => 'hr_setup',
        'hr_payroll' => 'payroll',
        'hr_requests' => 'employee_transactions',
        'reports_finance' => 'accounting_costing_reports',
        'reports_sales' => 'sales_reports',
        'reports_purchases' => 'purchase_reports',
        'reports_inventory' => 'inventory_reports',
        'reports_production' => 'production_reports',
        'reports_quality' => 'production_reports',
        'reports_maintenance' => 'maintenance_reports',
        'reports_costing' => 'accounting_costing_reports',
        'tools_workflow' => 'application_tools',
        'tools_communications' => 'communication',
        'tools_data' => 'application_tools',
        'tools_integrations' => 'application_tools',
        'tools_printing' => 'application_tools',
        'tools_system' => 'application_tools',
        'tools_review' => 'application_tools',
    ],

    'subgroups' => [
        'organization_setup' => ['domain' => 'basic_data', 'icon' => 'building', 'order' => 10],
        'users_permissions' => ['domain' => 'basic_data', 'icon' => 'user-shield', 'order' => 20],
        'shared_setup' => ['domain' => 'basic_data', 'icon' => 'cogs', 'order' => 30],
        'customer_data' => ['domain' => 'sales', 'icon' => 'user-tie', 'order' => 10],
        'sales_cycle' => ['domain' => 'sales', 'icon' => 'file-invoice-dollar', 'order' => 20],
        'customer_transactions' => ['domain' => 'sales', 'icon' => 'exchange-alt', 'order' => 30],
        'sales_setup' => ['domain' => 'sales', 'icon' => 'sitemap', 'order' => 40],
        'supplier_data' => ['domain' => 'purchases', 'icon' => 'truck', 'order' => 10],
        'purchase_cycle' => ['domain' => 'purchases', 'icon' => 'shopping-bag', 'order' => 20],
        'item_data' => ['domain' => 'inventory', 'icon' => 'boxes', 'order' => 10],
        'warehouse_setup' => ['domain' => 'inventory', 'icon' => 'warehouse', 'order' => 20],
        'opening_inventory' => ['domain' => 'inventory', 'icon' => 'boxes', 'order' => 30],
        'inventory_transactions' => ['domain' => 'inventory', 'icon' => 'exchange-alt', 'order' => 40],
        'inventory_inquiries' => ['domain' => 'inventory', 'icon' => 'search', 'order' => 50],
        'inventory_planning' => ['domain' => 'inventory', 'icon' => 'clipboard-list', 'order' => 60],
        'production_setup' => ['domain' => 'production', 'icon' => 'cogs', 'order' => 10],
        'product_structures' => ['domain' => 'production', 'icon' => 'sitemap', 'order' => 20],
        'production_planning' => ['domain' => 'production', 'icon' => 'calendar-alt', 'order' => 30],
        'production_operations' => ['domain' => 'production', 'icon' => 'industry', 'order' => 40],
        'quality_management' => ['domain' => 'production', 'icon' => 'check-circle', 'order' => 50],
        'general_accounting' => ['domain' => 'accounting_costing', 'icon' => 'book', 'order' => 10],
        'treasury_banks' => ['domain' => 'accounting_costing', 'icon' => 'university', 'order' => 20],
        'cost_accounting' => ['domain' => 'accounting_costing', 'icon' => 'project-diagram', 'order' => 30],
        'costing_operations' => ['domain' => 'accounting_costing', 'icon' => 'calculator', 'order' => 40],
        'costing_analysis' => ['domain' => 'accounting_costing', 'icon' => 'chart-line', 'order' => 50],
        'asset_data' => ['domain' => 'fixed_assets', 'icon' => 'building', 'order' => 10],
        'asset_transactions' => ['domain' => 'fixed_assets', 'icon' => 'exchange-alt', 'order' => 20],
        'depreciation' => ['domain' => 'fixed_assets', 'icon' => 'chart-line', 'order' => 30],
        'maintenance_setup' => ['domain' => 'maintenance', 'icon' => 'cogs', 'order' => 10],
        'maintenance_planning' => ['domain' => 'maintenance', 'icon' => 'calendar-alt', 'order' => 20],
        'maintenance_operations' => ['domain' => 'maintenance', 'icon' => 'tools', 'order' => 30],
        'employee_data' => ['domain' => 'human_resources', 'icon' => 'users', 'order' => 10],
        'hr_setup' => ['domain' => 'human_resources', 'icon' => 'cogs', 'order' => 20],
        'attendance_leave' => ['domain' => 'human_resources', 'icon' => 'calendar-check', 'order' => 30],
        'payroll' => ['domain' => 'human_resources', 'icon' => 'money-check-alt', 'order' => 40],
        'employee_transactions' => ['domain' => 'human_resources', 'icon' => 'exchange-alt', 'order' => 50],
        'sales_reports' => ['domain' => 'reports', 'icon' => 'shopping-cart', 'order' => 10],
        'purchase_reports' => ['domain' => 'reports', 'icon' => 'shopping-bag', 'order' => 20],
        'inventory_reports' => ['domain' => 'reports', 'icon' => 'warehouse', 'order' => 30],
        'production_reports' => ['domain' => 'reports', 'icon' => 'industry', 'order' => 40],
        'accounting_costing_reports' => ['domain' => 'reports', 'icon' => 'calculator', 'order' => 50],
        'maintenance_reports' => ['domain' => 'reports', 'icon' => 'tools', 'order' => 60],
        'human_resources_reports' => ['domain' => 'reports', 'icon' => 'user-tie', 'order' => 70],
        'files_documents' => ['domain' => 'tools', 'icon' => 'folder', 'order' => 10],
        'work_management' => ['domain' => 'tools', 'icon' => 'columns', 'order' => 20],
        'communication' => ['domain' => 'tools', 'icon' => 'comments', 'order' => 30],
        'application_tools' => ['domain' => 'tools', 'icon' => 'tools', 'order' => 40],
    ],
];
