<?php

return [
    'leaf_order' => [
        'purchases' => ['suppliers', 'purchase_requisitions', 'purchase_orders', 'supplier_quotations', 'supply_orders', 'purchase_inspections', 'goods_receipts', 'purchase_invoices', 'supplier_payments', 'purchase_returns'],
        'sales' => ['customers', 'customer_terms', 'price_lists', 'sales_requests', 'quotations', 'sales_orders', 'sales_invoices', 'deliveries', 'customer_collections', 'sales_returns'],
        'human_resources' => [
            'hr_employees',
            'hr_departments',
            'hr_sections',
            'hr_jobs',
            'hr_employment_types',
            'hr_biometric_devices',
            'hr_shifts',
            'hr_employee_attendance',
            'hr_requests',
            'employee_self_service',
            'hr_document_types',
            'hr_insurance_offices',
            'hr_social_insurance_policies',
            'hr_employment_tax_policies',
            'hr_allowances',
            'hr_areas',
            'hr_cities',
            'hr_countries',
            'hr_faculties',
            'hr_governorates',
            'hr_grades',
            'hr_hiring_statuses',
            'hr_identifications',
            'hr_military_services',
            'hr_nationalities',
            'hr_qualifications',
            'hr_religions',
            'hr_specializations',
            'hr_universities',
        ],
    ],
    'subgroup_leaf_order' => [
        'general_accounting' => [
            'chart_of_accounts',
            'core_tax_definitions',
            'opening_balances',
            'journal_entries',
            'financial_periods',
            'period_closing',
        ],
        'accounting_costing_reports' => [
            'general_journal',
            'account_ledger',
            'trial_balance',
            'financial_statements',
        ],
    ],
    'navigation_children' => [
        'production' => ['quality', 'maintenance'],
        'accounting_costing' => ['finance', 'fixed_assets'],
    ],
    'navigation_content_groups' => [
        'production' => [
            'label' => 'production_management',
            'icon' => 'industry',
        ],
    ],
    'navigation_child_order' => [
        'accounting_costing' => [
            'general_accounting',
            'accounting_costing_reports',
            'finance',
            'fixed_assets',
            'costing',
            'costing_reports',
            'financial_analysis_reports',
        ],
    ],

    'order' => [
        'dashboard',
        'basic_data',
        'sales',
        'purchases',
        'inventory',
        'production',
        'quality',
        'maintenance',
        'finance',
        'accounting_costing',
        'fixed_assets',
        'human_resources',
        'reports',
        'tools',
    ],

    'sections' => [
        'basic_data' => ['icon' => 'database'],
        'sales' => ['icon' => 'shopping-cart'],
        'purchases' => ['icon' => 'shopping-bag'],
        'inventory' => ['icon' => 'warehouse'],
        'production' => ['icon' => 'industry'],
        'quality' => ['icon' => 'check-circle'],
        'maintenance' => ['icon' => 'tools'],
        'finance' => ['icon' => 'money-check-alt'],
        'accounting_costing' => ['icon' => 'calculator'],
        'fixed_assets' => ['icon' => 'building'],
        'human_resources' => ['icon' => 'user-tie'],
        'reports' => ['icon' => 'chart-bar'],
        'tools' => ['icon' => 'tools'],
    ],

    'source_sections' => [
        'dashboard' => 'dashboard',
        'basic_data' => 'basic_data',
        'dashboard_setup' => 'basic_data',
        'master_data_settings' => 'basic_data',
        'item_data' => 'inventory',
        'sales' => 'sales',
        'purchases' => 'purchases',
        'inventory' => 'inventory',
        'inventory_operations' => 'inventory',
        'planning_production' => 'production',
        'production' => 'production',
        'quality' => 'quality',
        'maintenance' => 'maintenance',
        'general_ledger' => 'accounting_costing',
        'accounting' => 'accounting_costing',
        'accounting_costing' => 'accounting_costing',
        'finance' => 'finance',
        'fixed_assets' => 'fixed_assets',
        'costing' => 'accounting_costing',
        'reports_finance' => 'finance',
        'reports_costing' => 'accounting_costing',
        'human_resources' => 'human_resources',
        'reports' => 'reports',
        'tools' => 'tools',
    ],

    'leaf_sections' => [
        'core_tax_definitions' => 'accounting_costing',
        'core_currency_rate_policies' => 'finance',
        'financial_periods' => 'accounting_costing',
        'opening_balances' => 'accounting_costing',
        'product_data_product_bom' => 'production',
        'product_data_product_routing' => 'production',
        'product_data_product_quality_specifications' => 'quality',
        'product_data_mold_product_relationships' => 'production',
        'product_data_machine_product_relationships' => 'production',
        'product_data_raw_material_substitution_rules' => 'production',
        'product_data_scrap_definitions' => 'production',
        'product_data_waste_definitions' => 'production',
        'inventory_finished_goods_receipt' => 'inventory',
        'inventory_production_material_issue' => 'inventory',
        'inventory_production_material_return' => 'inventory',
        'activity_logs' => 'tools',
        'auth_logs' => 'tools',
        'auth_sessions' => 'tools',
        'fixed_assets_register' => 'fixed_assets',
        'sales_report_invoices' => 'sales',
        'sales_report_quotations' => 'sales',
        'sales_report_fulfillment' => 'sales',
        'sales_report_pricing' => 'sales',
        'sales_report_operational' => 'sales',
        'sales_report_financial' => 'accounting_costing',
        'sales_report_period' => 'accounting_costing',
        'sales_report_customer' => 'accounting_costing',
        'sales_report_product' => 'accounting_costing',
        'sales_report_receivables' => 'accounting_costing',
        'sales_report_collections' => 'accounting_costing',
        'sales_report_returns' => 'accounting_costing',
        'report_purchases_by_supplier' => 'accounting_costing',
        'report_purchases_by_item' => 'accounting_costing',
        'report_purchases_by_category' => 'accounting_costing',
        'report_purchases_by_warehouse' => 'accounting_costing',
        'report_purchases_by_period' => 'accounting_costing',
        'report_price_history' => 'accounting_costing',
        'report_supplier_outstanding' => 'accounting_costing',
        'report_due_supplier_installments' => 'accounting_costing',
        'report_supplier_aging' => 'accounting_costing',
        'report_upcoming_supplier_payments' => 'accounting_costing',
        'procurement_cycle_report' => 'purchases',
        'inventory_operational_reports' => 'inventory',
        'inventory_stock_balance_inquiry' => 'inventory',
        'production_operational_reports' => 'production',
        'production_reports_quality' => 'quality',
        'production_reports_receipts' => 'inventory',
        'account_ledger' => 'accounting_costing',
        'general_journal' => 'accounting_costing',
        'trial_balance' => 'accounting_costing',
        'financial_statements' => 'accounting_costing',
        'period_closing' => 'accounting_costing',
        'customer_statement' => 'sales',
        'supplier_statement' => 'purchases',
        'fixed_asset_reports' => 'fixed_assets',
        'finance_reports' => 'finance',
        'costing_reports' => 'accounting_costing',
        'human_resources_reports' => 'human_resources',
        'fixed_assets_reports' => 'fixed_assets',
        'purchases_reports' => 'purchases',
        'products_data_report' => 'inventory',
        'customers_report' => 'sales',
        'suppliers_report' => 'purchases',
    ],

    'leaf_subgroups' => [
        'purchases_purchase_returns' => null,
        'purchases_goods_receipt_inspection' => null,
        'purchases_goods_receipt_notes' => null,
        'purchases_supplier_selection' => null,
        'purchases_supplier_quotation_comparison' => null,
        'purchases_supplier_quotation_entry' => null,
        'purchases_request_for_quotations' => null,
        'sales_requests' => null,
        'sales_orders' => null,
        'deliveries' => null,
        'sales_invoices' => null,
        'sales_returns' => null,
        'sales_customer_receipts' => null,
        'customer_collections' => null,
        'purchase_requisitions' => null,
        'supplier_quotations' => null,
        'supply_orders' => null,
        'purchase_inspections' => null,
        'goods_receipts' => null,
        'supplier_payments' => null,
        'purchase_returns' => null,
        'roles' => 'users_permissions',
        'users' => 'users_permissions',
        'screen_data_visibility_rules' => 'users_permissions',
        'profile' => 'users_permissions',
        'companies' => 'organization_setup',
        'branches' => 'organization_setup',
        'financial_periods' => 'general_accounting',
        'activity_logs' => 'application_tools',
        'auth_logs' => 'application_tools',
        'auth_sessions' => 'application_tools',
        'customers' => null,
        'customer_terms' => null,
        'price_lists' => null,
        'quotations' => null,
        'suppliers' => null,
        'purchase_orders' => null,
        'purchase_invoices' => null,
        'products' => null,
        'raw_materials' => null,
        'packaging_materials' => null,
        'item_units' => null,
        'item_sizes' => null,
        'item_colors' => null,
        'item_decals' => null,
        'item_models' => null,
        'item_categories' => null,
        'item_groups' => null,
        'item_origin_countries' => null,
        'opening_stocks' => null,
        'unpriced_inventory_receipts' => null,
        'opening_stock_pricings' => null,
        'inventory_movements' => null,
        'inventory_operational_reports' => 'inventory_module_reports',
        'inventory_stock_balance_inquiry' => 'inventory_module_reports',
        'inventory_stock_counts' => null,
        'production_stages' => null,
        'product_production_stages' => null,
        'production_work_orders' => null,
        'production_runs' => null,
        'production_material_requests' => null,
        'production_expenses' => null,
        'production_quality' => null,
        'production_quality_active' => null,
        'production_quality_reports' => 'quality_reports',
        'production_operational_reports' => 'production_reports_operations',
        'production_reports_quality' => 'quality_reports',
        'production_reports_receipts' => 'inventory_module_reports',
        'maintenance_plans' => null,
        'maintenance_requests' => null,
        'maintenance_orders' => null,
        'maintenance_material_requests' => null,
        'maintenance_expenses' => null,
        'maintenance_reports' => 'maintenance_report_group',
        'chart_of_accounts' => 'general_accounting',
        'opening_balances' => 'general_accounting',
        'journal_entries' => 'general_accounting',
        'account_ledger' => 'accounting_costing_reports',
        'general_journal' => 'accounting_costing_reports',
        'trial_balance' => 'accounting_costing_reports',
        'financial_statements' => 'accounting_costing_reports',
        'reports_costing_profitability' => 'financial_analysis_reports',
        'reports_costing_allocation_analysis' => 'financial_analysis_reports',
        'period_closing' => 'general_accounting',
        'customer_statement' => null,
        'supplier_statement' => 'purchase_reports',
        'currencies' => null,
        'bank_accounts' => null,
        'cashboxes' => null,
        'cash_receipt_vouchers' => null,
        'cash_payment_vouchers' => null,
        'cheques' => null,
        'fund_transfers' => null,
        'cost_centers' => 'costing',
        'fixed_assets_register' => null,
        'fixed_asset_movements' => null,
        'fixed_asset_depreciation' => null,
        'fixed_asset_reports' => 'asset_reports',
        'hr_employees' => null,
        'hr_departments' => null,
        'hr_sections' => null,
        'hr_jobs' => null,
        'hr_employment_types' => null,
        'hr_biometric_devices' => null,
        'hr_shifts' => null,
        'hr_employee_attendance' => null,
        'hr_requests' => null,
        'employee_self_service' => null,
        'hr_document_types' => null,
        'hr_insurance_offices' => null,
        'hr_social_insurance_policies' => null,
        'hr_employment_tax_policies' => null,
        'hr_allowances' => null,
        'hr_areas' => null,
        'hr_cities' => null,
        'hr_countries' => null,
        'hr_faculties' => null,
        'hr_governorates' => null,
        'hr_grades' => null,
        'hr_hiring_statuses' => null,
        'hr_identifications' => null,
        'hr_military_services' => null,
        'hr_nationalities' => null,
        'hr_qualifications' => null,
        'hr_religions' => null,
        'hr_specializations' => null,
        'hr_universities' => null,
        'products_data_report' => 'inventory_module_reports',
        'customers_report' => 'sales_cycle_reports',
        'suppliers_report' => 'purchase_reports',
        'customer_statement' => 'sales_cycle_reports',
        'sales_report_financial' => 'sales_cycle_reports',
        'sales_report_period' => 'sales_cycle_reports',
        'sales_report_customer' => 'sales_cycle_reports',
        'sales_report_product' => 'sales_cycle_reports',
        'sales_report_invoices' => 'sales_cycle_reports',
        'sales_report_receivables' => 'sales_cycle_reports',
        'sales_report_collections' => 'sales_cycle_reports',
        'sales_report_returns' => 'sales_cycle_reports',
        'sales_report_quotations' => 'sales_cycle_reports',
        'sales_report_fulfillment' => 'sales_cycle_reports',
        'sales_report_operational' => 'sales_cycle_reports',
        'procurement_cycle_report' => 'purchase_reports',
        'open_documents' => 'files_documents',
        'file_manager' => 'files_documents',
        'calendar' => 'work_management',
        'my_board' => 'work_management',
        'task_boards' => 'work_management',
        'team_board' => 'work_management',
        'chat' => 'communication',
        'chat_report' => 'communication',
        'pwa_settings' => 'application_tools',
        'core_tax_definitions' => 'general_accounting',
        'core_currency_rate_policies' => null,
        'product_data_product_bom' => null,
        'product_data_product_routing' => null,
        'product_data_product_quality_specifications' => null,
        'product_data_mold_product_relationships' => null,
        'product_data_machine_product_relationships' => null,
        'product_data_raw_material_substitution_rules' => null,
        'product_data_scrap_definitions' => null,
        'product_data_waste_definitions' => null,
        'inventory_finished_goods_receipt' => null,
        'inventory_production_material_issue' => null,
        'inventory_production_material_return' => null,
    ],

    'source_subgroups' => [
        'core_configuration' => 'organization_setup',
        'product_data_classification' => null,
        'product_data_technical' => null,
        'product_data_logistics' => null,
        'product_data_planning' => null,
        'product_data_relationships' => null,
        'sales_crm' => null,
        'sales_customer_data' => null,
        'sales_quotations' => null,
        'sales_orders' => null,
        'sales_contracts' => null,
        'sales_billing' => null,
        'sales_delivery' => null,
        'sales_controls' => null,
        'purchases_requisitions' => null,
        'purchases_sourcing' => null,
        'purchases_orders' => null,
        'purchases_receiving' => null,
        'purchases_billing' => null,
        'purchases_supplier_management' => null,
        'purchases_special' => null,
        'inventory_structure' => null,
        'inventory_transactions' => null,
        'inventory_counting' => null,
        'inventory_tracking' => null,
        'inventory_operations' => null,
        'inventory_inquiries' => 'inventory_module_reports',
        'inventory_planning' => null,
        'production_setup' => null,
        'production_engineering' => null,
        'production_planning' => null,
        'production_work_orders' => null,
        'production_materials' => null,
        'production_execution' => null,
        'production_monitoring' => null,
        'production_external' => null,
        'production_operational_reports' => 'production_reports_operations',
        'quality_setup' => null,
        'quality_plans' => null,
        'quality_inspections' => null,
        'quality_decisions' => null,
        'quality_capa' => null,
        'quality_certificates' => null,
        'quality_audits' => null,
        'maintenance_setup' => null,
        'maintenance_registers' => null,
        'maintenance_requests' => null,
        'maintenance_work_orders' => null,
        'maintenance_preventive' => null,
        'maintenance_inspections' => null,
        'maintenance_history' => null,
        'maintenance_external' => null,
        'finance_bank_vouchers' => null,
        'finance_cheques' => null,
        'finance_treasury' => null,
        'finance_reconciliation' => null,
        'finance_collections' => null,
        'finance_expenses' => null,
        'finance_currency' => null,
        'finance_history' => null,
        'fixed_assets_setup' => null,
        'fixed_assets_transactions' => null,
        'fixed_assets_depreciation' => null,
        'fixed_assets_valuation' => null,
        'fixed_assets_support' => null,
        'costing_setup' => 'costing',
        'costing_standards' => 'costing',
        'costing_work_orders' => 'costing',
        'costing_components' => 'costing',
        'costing_allocation' => 'costing',
        'costing_analysis' => 'costing',
        'costing_closing' => 'costing',
        'hr_contracts' => null,
        'hr_attendance' => null,
        'hr_leave' => null,
        'hr_employee_relations' => null,
        'hr_development' => null,
        'hr_payroll' => null,
        'hr_requests' => null,
        'reports_finance' => 'finance_reports',
        'reports_sales' => 'sales_reports',
        'reports_purchases' => null,
        'reports_inventory' => 'inventory_reports',
        'reports_production' => 'production_reports',
        'reports_quality' => 'production_reports',
        'reports_maintenance' => 'maintenance_report_group',
        'reports_costing' => 'costing_reports',
        'tools_workflow' => 'application_tools',
        'tools_communications' => 'communication',
        'tools_data' => 'application_tools',
        'tools_integrations' => 'application_tools',
        'tools_printing' => 'application_tools',
        'tools_system' => 'application_tools',
        'tools_review' => 'application_tools',
    ],

    'subgroups' => [
        'organization_setup' => ['domain' => 'basic_data', 'icon' => 'building', 'order' => 10],
        'users_permissions' => ['domain' => 'basic_data', 'icon' => 'user-shield', 'order' => 20],
        'customer_data' => ['domain' => 'sales', 'icon' => 'user-tie', 'order' => 10],
        'sales_cycle' => ['domain' => 'sales', 'icon' => 'file-invoice-dollar', 'order' => 20],
        'customer_transactions' => ['domain' => 'sales', 'icon' => 'exchange-alt', 'order' => 30],
        'sales_setup' => ['domain' => 'sales', 'icon' => 'sitemap', 'order' => 40],
        'supplier_data' => ['domain' => 'purchases', 'icon' => 'truck', 'order' => 10],
        'purchase_cycle' => ['domain' => 'purchases', 'icon' => 'shopping-bag', 'order' => 20],
        'item_data' => ['domain' => 'inventory', 'icon' => 'boxes', 'order' => 10],
        'warehouse_setup' => ['domain' => 'inventory', 'icon' => 'warehouse', 'order' => 20],
        'opening_inventory' => ['domain' => 'inventory', 'icon' => 'boxes', 'order' => 30],
        'inventory_transactions' => ['domain' => 'inventory', 'icon' => 'exchange-alt', 'order' => 40],
        'inventory_inquiries' => ['domain' => 'inventory', 'icon' => 'search', 'order' => 50],
        'inventory_planning' => ['domain' => 'inventory', 'icon' => 'clipboard-list', 'order' => 60],
        'production_setup' => ['domain' => 'production', 'icon' => 'cogs', 'order' => 10],
        'product_structures' => ['domain' => 'production', 'icon' => 'sitemap', 'order' => 20],
        'production_planning' => ['domain' => 'production', 'icon' => 'calendar-alt', 'order' => 30],
        'production_operations' => ['domain' => 'production', 'icon' => 'industry', 'order' => 10],
        'production_reports_operations' => ['domain' => 'production', 'icon' => 'chart-line', 'order' => 50],
        'quality_management' => ['domain' => 'quality', 'icon' => 'check-circle', 'order' => 10],
        'quality_reports' => ['domain' => 'quality', 'icon' => 'chart-bar', 'order' => 90],
        'general_accounting' => ['domain' => 'accounting_costing', 'icon' => 'book', 'order' => 10],
        'treasury_banks' => ['domain' => 'finance', 'icon' => 'university', 'order' => 10],
        'finance_reports' => ['domain' => 'finance', 'icon' => 'chart-line', 'order' => 90],
        'costing' => ['domain' => 'accounting_costing', 'icon' => 'calculator', 'order' => 30],
        'asset_data' => ['domain' => 'fixed_assets', 'icon' => 'building', 'order' => 10],
        'asset_transactions' => ['domain' => 'fixed_assets', 'icon' => 'exchange-alt', 'order' => 20],
        'depreciation' => ['domain' => 'fixed_assets', 'icon' => 'chart-line', 'order' => 30],
        'asset_reports' => ['domain' => 'fixed_assets', 'icon' => 'chart-bar', 'order' => 90],
        'maintenance_setup' => ['domain' => 'maintenance', 'icon' => 'cogs', 'order' => 10],
        'maintenance_planning' => ['domain' => 'maintenance', 'icon' => 'calendar-alt', 'order' => 20],
        'maintenance_operations' => ['domain' => 'maintenance', 'icon' => 'tools', 'order' => 30],
        'employee_data' => ['domain' => 'human_resources', 'icon' => 'users', 'order' => 10],
        'hr_setup' => ['domain' => 'human_resources', 'icon' => 'cogs', 'order' => 20],
        'attendance_leave' => ['domain' => 'human_resources', 'icon' => 'calendar-check', 'order' => 30],
        'payroll' => ['domain' => 'human_resources', 'icon' => 'money-check-alt', 'order' => 40],
        'employee_transactions' => ['domain' => 'human_resources', 'icon' => 'exchange-alt', 'order' => 50],
        'sales_reports' => ['domain' => 'reports', 'icon' => 'shopping-cart', 'order' => 10],
        'sales_cycle_reports' => ['domain' => 'sales', 'icon' => 'chart-pie', 'order' => 90],
        'purchase_reports' => ['domain' => 'purchases', 'icon' => 'shopping-bag', 'order' => 90],
        'inventory_module_reports' => ['domain' => 'inventory', 'icon' => 'warehouse', 'order' => 90],
        'inventory_reports' => ['domain' => 'reports', 'icon' => 'warehouse', 'order' => 30],
        'production_reports' => ['domain' => 'reports', 'icon' => 'industry', 'order' => 40],
        'accounting_costing_reports' => ['domain' => 'accounting_costing', 'icon' => 'calculator', 'order' => 20],
        'costing_reports' => ['domain' => 'accounting_costing', 'icon' => 'chart-bar', 'order' => 70],
        'financial_analysis_reports' => ['domain' => 'accounting_costing', 'icon' => 'chart-line', 'order' => 80],
        'maintenance_report_group' => ['domain' => 'maintenance', 'icon' => 'tools', 'order' => 90],
        'human_resources_reports' => ['domain' => 'human_resources', 'icon' => 'user-tie', 'order' => 90],
        'files_documents' => ['domain' => 'tools', 'icon' => 'folder', 'order' => 10],
        'work_management' => ['domain' => 'tools', 'icon' => 'columns', 'order' => 20],
        'communication' => ['domain' => 'tools', 'icon' => 'comments', 'order' => 30],
        'application_tools' => ['domain' => 'tools', 'icon' => 'tools', 'order' => 40],
    ],
];
