@extends('layouts.app')
@section('title', __('Purchase Return'))
@section('content')
@php($dates = app(\Modules\Core\Services\DateFormatService::class))
@php($numbers = app(\Modules\Core\Services\NumericFormatService::class))
@php($draft = $draft ?? null)
@unless($draft)
<div class="card mb-3"><div class="card-header"><h5 class="mb-0">{{ __('Purchase Return') }}</h5></div><div class="card-body"><form class="row g-3 align-items-end" method="GET"><div class="col-md-8"><label class="form-label">{{ __('Source Goods Receipt') }}</label><select class="form-select js-select2-ajax" name="receipt" data-url="{{ route('admin.purchases.select2.receipts', ['purpose' => 'return']) }}" data-placeholder="{{ __('Select') }}" required>@if($sourceReceipt)<option selected value="{{ $sourceReceipt->doc_num }}">{{ $sourceReceipt->doc_num }}</option>@endif</select></div><div class="col-md-4"><button class="btn btn-falcon-primary">{{ __('Load returnable receipts') }}</button></div></form></div></div>
@endunless
@if($record)
<form method="POST" action="{{ $draft ? route('admin.purchases.purchase-returns.update', $draft->doc_num) : route('admin.purchases.purchase-returns.store') }}">
    @csrf
        <x-forms.line-item-cards /> @if($draft) @method('PUT') @endif<input type="hidden" name="purchase_order_doc_num" value="{{ $record->doc_num }}">
    <div class="card mb-3">@include('modules.purchases.procurement.partials.form-toolbar', ['toolbarTitle' => __('Purchase Return'), 'toolbarPermission' => 'purchases.purchase_returns', 'toolbarRoute' => 'purchase-returns'])<div class="card-body">
        @if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
        <div class="row g-3"><div class="col-md-3"><label class="form-label">{{ __('Return date') }}</label><input class="form-control js-date-picker" type="text" data-date-format="{{ $dates->jsDateFormat() }}" data-locale="{{ app()->getLocale() }}" dir="ltr" name="return_date" value="{{ old('return_date', $dates->formatDate($draft?->return_date, '') ?? $dates->formatDate(now())) }}" required></div><div class="col-md-3"><label class="form-label">{{ __('Reason code') }}</label><select class="form-select" name="reason_code" required>@php($selectedReason = old('reason_code', $draft?->reason_code))@if(filled($selectedReason) && ! in_array($selectedReason, ['quality_rejection', 'latent_defect', 'wrong_specification', 'excess_delivery', 'wrong_item', 'damaged', 'commercial_return'], true))<option value="{{ $selectedReason }}" selected>{{ $selectedReason }}</option>@endif<option value="quality_rejection" @selected(old('reason_code', $draft?->reason_code) === 'quality_rejection')>{{ __('Quality rejection') }}</option><option value="latent_defect" @selected(old('reason_code', $draft?->reason_code) === 'latent_defect')>{{ __('Latent defect') }}</option><option value="wrong_specification" @selected(old('reason_code', $draft?->reason_code) === 'wrong_specification')>{{ __('Wrong specification') }}</option><option value="excess_delivery" @selected(old('reason_code', $draft?->reason_code) === 'excess_delivery')>{{ __('Excess delivery') }}</option><option value="wrong_item" @selected(old('reason_code', $draft?->reason_code) === 'wrong_item')>{{ __('Wrong item') }}</option><option value="damaged" @selected(old('reason_code', $draft?->reason_code) === 'damaged')>{{ __('Damaged') }}</option><option value="commercial_return" @selected(old('reason_code', $draft?->reason_code) === 'commercial_return')>{{ __('Commercial return') }}</option></select></div><div class="col-md-3"><label class="form-label">{{ __('Source invoice') }}</label><select class="form-select js-select2-ajax" name="purchase_invoice_doc_num" data-url="{{ route('admin.purchases.select2.invoices', ['purchase_order' => $record->doc_num, 'receipt' => $sourceReceipt?->doc_num]) }}" data-placeholder="{{ __('Operational return only') }}" data-allow-clear="true"><option value="">{{ __('Operational return only') }}</option>@foreach($invoices as $invoice)<option value="{{ $invoice->doc_num }}" @selected(old('purchase_invoice_doc_num', $draft?->purchaseInvoice?->doc_num ?? ($invoices->count() === 1 ? $invoice->doc_num : null)) === $invoice->doc_num)>{{ $invoice->doc_num }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label">{{ __('Notes') }}</label><input class="form-control" name="notes" value="{{ old('notes', $draft?->notes) }}"></div></div>
    </div></div>
    <div class="card mb-3"><div class="card-body p-0"><div class="table-responsive procurement-lines-scroll"><table class="table table-sm align-middle mb-0 procurement-lines-table"><thead class="bg-100"><tr><th>{{ __('Receipt') }}</th><th>{{ __('Item') }}</th><th>{{ __('Unit') }}</th><th class="text-end">{{ __('Accepted') }}</th><th class="text-end">{{ __('Rejected') }}</th><th>{{ __('Previously returned') }}</th><th>{{ __('Returnable quantity') }}</th><th>{{ __('Return quantity') }}</th><th>{{ __('From quarantine') }}</th><th>{{ __('Reason') }}</th></tr></thead><tbody>
        @foreach($receiptLines as $index => $line) @php($draftLine = $draft?->lines->firstWhere('receipt_line_id', $line->getKey()))<tr><td dir="ltr">{{ $line->receipt?->doc_num }}<input type="hidden" name="lines[{{ $index }}][receipt_line_public_id]" value="{{ $line->public_id }}"></td><td>{{ $line->product?->doc_num }} / {{ $line->product?->name }}</td><td>{{ $line->unit?->name }}</td><td class="text-end" dir="ltr">{{ $numbers->format($line->accepted_quantity) }}</td><td class="text-end" dir="ltr">{{ $numbers->format($line->rejected_quantity) }}</td><td>{{ $numbers->format($line->previously_returned_quantity) }}</td><td>{{ $numbers->format($line->returnable_quantity) }} / {{ $numbers->format($line->returnable_quarantine_quantity) }}</td><td><x-forms.numeric-input name="lines[{{ $index }}][quantity]" :scale="8" min="0" :value="old('lines.'.$index.'.quantity', $draftLine?->quantity ?? 0)" step="0.00000001" /></td><td><select class="form-select" name="lines[{{ $index }}][from_quarantine]"><option value="0">{{ __('Usable stock') }}</option><option value="1" @selected($draftLine?->from_quarantine)>{{ __('Rejected / quarantine') }}</option></select></td><td><input class="form-control" name="lines[{{ $index }}][reason]" value="{{ old('lines.'.$index.'.reason', $draftLine?->reason) }}"></td></tr>@endforeach
    </tbody></table></div></div></div>
</form>
@endif
@endsection
