@extends('layouts.app')
@section('title', __('Purchase Return'))
@section('content')
<div class="card mb-3"><div class="card-header"><h5 class="mb-0">{{ __('Select Purchase Order for Return') }}</h5></div><div class="card-body"><form class="row g-3 align-items-end" method="GET"><div class="col-md-8"><label class="form-label">{{ __('Purchase Order') }}</label><select class="form-select" name="purchase_order" required>@foreach($orders as $order)<option value="{{ $order->doc_num }}" @selected($record?->is($order))>{{ $order->doc_num }} / {{ $order->supplier?->name }}</option>@endforeach</select></div><div class="col-md-4"><button class="btn btn-falcon-primary">{{ __('Load returnable receipts') }}</button></div></form></div></div>
@if($record)
<form method="POST" action="{{ route('admin.purchases.purchase-returns.store') }}">
    @csrf<input type="hidden" name="purchase_order_doc_num" value="{{ $record->doc_num }}">
    <div class="card mb-3"><div class="card-body">
        @if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
        <div class="row g-3"><div class="col-md-3"><label class="form-label">{{ __('Return date') }}</label><input class="form-control" type="date" name="return_date" value="{{ now()->toDateString() }}" required></div><div class="col-md-3"><label class="form-label">{{ __('Reason code') }}</label><select class="form-select" name="reason_code" required><option value="quality_rejection">{{ __('Quality rejection') }}</option><option value="latent_defect">{{ __('Latent defect') }}</option><option value="wrong_specification">{{ __('Wrong specification') }}</option><option value="excess_delivery">{{ __('Excess delivery') }}</option><option value="wrong_item">{{ __('Wrong item') }}</option><option value="damaged">{{ __('Damaged') }}</option><option value="commercial_return">{{ __('Commercial return') }}</option></select></div><div class="col-md-3"><label class="form-label">{{ __('Source invoice') }}</label><select class="form-select" name="purchase_invoice_doc_num"><option value="">{{ __('Operational return only') }}</option>@foreach($invoices as $invoice)<option value="{{ $invoice->doc_num }}">{{ $invoice->doc_num }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label">{{ __('Notes') }}</label><input class="form-control" name="notes"></div></div>
    </div></div>
    <div class="card mb-3"><div class="card-body p-0"><div class="table-responsive procurement-lines-scroll"><table class="table table-sm align-middle mb-0 procurement-lines-table"><thead class="bg-100"><tr><th>{{ __('Receipt') }}</th><th>{{ __('Item') }}</th><th class="text-end">{{ __('Accepted') }}</th><th class="text-end">{{ __('Rejected') }}</th><th>{{ __('Return quantity') }}</th><th>{{ __('From quarantine') }}</th><th>{{ __('Reason') }}</th></tr></thead><tbody>
        @foreach($receiptLines as $index => $line)<tr><td dir="ltr">{{ $line->receipt?->doc_num }}<input type="hidden" name="lines[{{ $index }}][receipt_line_public_id]" value="{{ $line->public_id }}"></td><td>{{ $line->product?->name }}</td><td class="text-end" dir="ltr">{{ $line->accepted_quantity }}</td><td class="text-end" dir="ltr">{{ $line->rejected_quantity }}</td><td><x-forms.numeric-input name="lines[{{ $index }}][quantity]" :scale="8" min="0.00000001" step="0.00000001" /></td><td><select class="form-select" name="lines[{{ $index }}][from_quarantine]"><option value="0">{{ __('Usable stock') }}</option><option value="1">{{ __('Rejected / quarantine') }}</option></select></td><td><input class="form-control" name="lines[{{ $index }}][reason]"></td></tr>@endforeach
    </tbody></table></div></div></div>
    <div class="d-flex justify-content-end"><button class="btn btn-primary">{{ __('Save return draft') }}</button></div>
</form>
@endif
@endsection
