<?php

return [
    [
        'label' => 'accounting_costing',
        'title' => 'Accounting & Costing',
        'icon' => 'calculator',
        'route' => null,
        'permission' => null,
        'keywords' => ['general ledger', 'accounting', 'accounts', 'chart of accounts', 'journal entries', 'ledger', 'statements', 'cost centers', 'الحسابات', 'شجرة الحسابات', 'قيود اليومية', 'الأستاذ', 'كشوف الحسابات', 'مراكز التكلفة'],
        'active' => [
            'admin.accounting.*',
        ],
        'children' => [
            [
                'label' => 'journal_entries',
                'title' => 'Journal Entries',
                'icon' => 'book-open',
                'route' => 'admin.accounting.journal-entries.index',
                'permission' => 'journal_entries.view',
                'keywords' => ['journal entries', 'manual entries', 'general journal', 'قيود اليومية', 'قيد يومية'],
                'actions' => [
                    'view' => 'journal_entries.view',
                    'create' => 'journal_entries.create',
                    'edit' => 'journal_entries.edit',
                    'delete' => 'journal_entries.delete',
                    'post' => 'journal_entries.post',
                    'view_trashed' => 'journal_entries.view_trashed',
                    'restore' => 'journal_entries.restore',
                ],
                'active' => ['admin.accounting.journal-entries.*'],
                'children' => [],
            ],
            [
                'label' => 'chart_of_accounts',
                'title' => 'Chart of Accounts',
                'icon' => 'sitemap',
                'route' => 'admin.accounting.accounts.index',
                'permission' => 'accounts.view',
                'keywords' => ['chart of accounts', 'accounts', 'ledger', 'شجرة الحسابات', 'الحسابات'],
                'actions' => [
                    'view' => 'accounts.view',
                    'create' => 'accounts.create',
                    'clone' => 'accounts.clone',
                    'edit' => 'accounts.edit',
                    'delete' => 'accounts.delete',
                    'view_trashed' => 'accounts.view_trashed',
                    'restore' => 'accounts.restore',
                    'export' => 'accounts.export',
                    'document_number_control' => 'accounts.document_number.control',
                    'document_number_settings_update' => 'accounts.document_number_settings.update',
                    'account_code_control' => 'accounts.account_code.control',
                ],
                'active' => [
                    'admin.accounting.accounts.*',
                ],
                'children' => [],
            ],
            [
                'label' => 'cost_centers',
                'title' => 'Cost Centers',
                'icon' => 'project-diagram',
                'route' => 'admin.accounting.cost-centers.index',
                'permission' => 'cost_centers.view',
                'keywords' => ['cost centers', 'cost center tree', 'مراكز التكلفة', 'مركز تكلفة'],
                'actions' => [
                    'view' => 'cost_centers.view',
                    'create' => 'cost_centers.create',
                    'clone' => 'cost_centers.clone',
                    'edit' => 'cost_centers.edit',
                    'delete' => 'cost_centers.delete',
                    'view_trashed' => 'cost_centers.view_trashed',
                    'restore' => 'cost_centers.restore',
                    'print' => 'cost_centers.print',
                    'export' => 'cost_centers.export',
                    'document_number_control' => 'cost_centers.document_number.control',
                    'document_number_settings_update' => 'cost_centers.document_number_settings.update',
                ],
                'active' => [
                    'admin.accounting.cost-centers.*',
                ],
                'children' => [],
            ],
            [
                'label' => 'period_closing',
                'title' => 'Period Closing & Carry Forward',
                'icon' => 'lock',
                'route' => 'admin.financial-periods.closing',
                'permission' => 'financial_periods.view',
                'keywords' => ['period close', 'carry forward', 'reopen period', 'إقفال الفترة', 'ترحيل الأرصدة', 'إعادة فتح الفترة'],
                'actions' => [
                    'view' => 'financial_periods.view',
                    'close' => 'financial_periods.close',
                    'reopen' => 'financial_periods.reopen',
                ],
                'active' => ['admin.financial-periods.closing'],
                'children' => [],
            ],
            [
                'label' => 'account_ledger',
                'title' => 'Account Ledger',
                'icon' => 'list-alt',
                'route' => 'admin.accounting.reports.account-ledger',
                'permission' => 'reports.account_ledger.view',
                'keywords' => ['account ledger', 'general ledger', 'كشف الأستاذ', 'حركة الحساب'],
                'actions' => [
                    'view' => 'reports.account_ledger.view',
                    'export' => 'reports.account_ledger.export',
                ],
                'active' => ['admin.accounting.reports.account-ledger'],
                'children' => [],
            ],
            [
                'label' => 'trial_balance',
                'title' => 'Trial Balance',
                'icon' => 'balance-scale',
                'route' => 'admin.accounting.reports.trial-balance',
                'permission' => 'reports.trial_balance.view',
                'keywords' => ['trial balance', 'opening balance', 'ending balance', 'ميزان المراجعة', 'أرصدة الحسابات'],
                'actions' => [
                    'view' => 'reports.trial_balance.view',
                    'export' => 'reports.trial_balance.export',
                ],
                'active' => ['admin.accounting.reports.trial-balance*'],
                'children' => [],
            ],
            [
                'label' => 'reconciliation_center',
                'title' => 'Reconciliation Center',
                'icon' => 'check-double',
                'route' => 'admin.accounting.reports.reconciliation-center',
                'permission' => 'reports.account_ledger.view',
                'keywords' => ['reconciliation', 'subledger', 'general ledger', 'مطابقة', 'فروقات'],
                'actions' => [
                    'view' => 'reports.account_ledger.view',
                    'export' => 'reports.account_ledger.export',
                ],
                'active' => ['admin.accounting.reports.reconciliation-center*'],
                'children' => [],
            ],
            [
                'label' => 'financial_statements',
                'title' => 'Financial Statements',
                'icon' => 'file-invoice-dollar',
                'route' => 'admin.accounting.reports.financial-statements',
                'permission' => 'reports.financial_statements.view',
                'keywords' => ['income statement', 'financial position', 'balance sheet', 'equity changes', 'قائمة الدخل', 'المركز المالي', 'حقوق الملكية'],
                'actions' => [
                    'view' => 'reports.financial_statements.view',
                    'export' => 'reports.financial_statements.export',
                ],
                'active' => ['admin.accounting.reports.financial-statements*'],
                'children' => [],
            ],
            [
                'label' => 'customer_statement',
                'title' => 'Customer Statement',
                'icon' => 'file-invoice-dollar',
                'route' => 'admin.accounting.reports.customer-statement',
                'permission' => 'reports.customer_statement.view',
                'keywords' => ['customer statement', 'customer ledger', 'كشف حساب عميل'],
                'actions' => [
                    'view' => 'reports.customer_statement.view',
                    'export' => 'reports.customer_statement.export',
                ],
                'active' => ['admin.accounting.reports.customer-statement'],
                'children' => [],
            ],
            [
                'label' => 'supplier_statement',
                'title' => 'Supplier Statement',
                'icon' => 'file-invoice',
                'route' => 'admin.accounting.reports.supplier-statement',
                'permission' => 'reports.supplier_statement.view',
                'keywords' => ['supplier statement', 'supplier ledger', 'كشف حساب مورد'],
                'actions' => [
                    'view' => 'reports.supplier_statement.view',
                    'export' => 'reports.supplier_statement.export',
                ],
                'active' => ['admin.accounting.reports.supplier-statement'],
                'children' => [],
            ],
        ],
    ],
];
