<?php

$screenDataVisibilityRulesEnabled = (bool) config('erp_features.screen_data_visibility_rules.enabled', false);

return [
    [
        'label' => 'dashboard',
        'title' => 'Dashboard',
        'icon' => 'home',
        'route' => 'dashboard',
        'permission' => null,
        'keywords' => ['home', 'start', 'لوحة', 'الرئيسية'],
        'actions' => [
            'view' => 'dashboard.view',
            'sales_summary' => 'dashboard.summaries.sales.view',
            'purchases_summary' => 'dashboard.summaries.purchases.view',
        ],
        'active' => [
            'dashboard',
        ],
        'children' => [],
    ],
    [
        'label' => 'basic_data',
        'title' => 'Basic Data',
        'icon' => 'database',
        'route' => null,
        'permission' => null,
        'active' => [
            'admin.roles.*',
            'admin.users.*',
            ...($screenDataVisibilityRulesEnabled ? ['admin.screen-data-visibility-rules.*'] : []),
            'admin.companies.*',
            'admin.branches.*',
            'admin.financial-periods.*',
            'admin.permissions.*',
            'admin.activity-logs.*',
            'admin.auth-logs.*',
            'admin.auth-sessions.*',
        ],
        'children' => [
            [
                'label' => 'roles',
                'title' => 'User Groups',
                'icon' => 'shield',
                'route' => 'admin.roles.index',
                'permission' => 'roles.view',
                'keywords' => ['user groups', 'groups', 'group', 'permissions', 'مجموعات المستخدمين', 'مجموعة المستخدمين', 'المجموعة', 'الصلاحيات'],
                'active' => [
                    'admin.roles.*',
                ],
                'actions' => [
                    'view' => 'roles.view',
                    'view_trashed' => 'roles.view_trashed',
                    'create' => 'roles.create',
                    'clone' => 'roles.clone',
                    'edit' => 'roles.edit',
                    'delete' => 'roles.delete',
                    'restore' => 'roles.restore',
                    'operating_scope_manage' => 'roles.operating_scope.manage',
                    'document_number_control' => 'roles.document_number.control',
                    'document_number_settings_update' => 'roles.document_number_settings.update',
                ],
                'children' => [],
            ],
            [
                'label' => 'users',
                'title' => 'Users',
                'icon' => 'users',
                'route' => 'admin.users.index',
                'permission' => 'users.view',
                'keywords' => ['user', 'users', 'accounts', 'المستخدمين', 'المستخدمون', 'الحسابات'],
                'active' => [
                    'admin.users.*',
                ],
                'actions' => [
                    'view' => 'users.view',
                    'create' => 'users.create',
                    'clone' => 'users.clone',
                    'edit' => 'users.edit',
                    'delete' => 'users.delete',
                    'view_trashed' => 'users.view_trashed',
                    'restore' => 'users.restore',
                    'document_number_control' => 'users.document_number.control',
                    'document_number_settings_update' => 'users.document_number_settings.update',
                    'roles_manage' => 'users.roles.manage',
                ],
                'children' => [],
            ],
            ...($screenDataVisibilityRulesEnabled ? [[
                'label' => 'screen_data_visibility_rules',
                'title' => 'Data Visibility Rules',
                'icon' => 'user-shield',
                'route' => 'admin.screen-data-visibility-rules.index',
                'permission' => 'screen_data_visibility_rules.view',
                'keywords' => ['data visibility', 'record visibility', 'user restrictions', 'سياسات رؤية البيانات', 'تقييد السجلات'],
                'actions' => [
                    'view' => 'screen_data_visibility_rules.view',
                    'create' => 'screen_data_visibility_rules.create',
                    'clone' => 'screen_data_visibility_rules.clone',
                    'edit' => 'screen_data_visibility_rules.edit',
                    'delete' => 'screen_data_visibility_rules.delete',
                    'view_trashed' => 'screen_data_visibility_rules.view_trashed',
                    'restore' => 'screen_data_visibility_rules.restore',
                    'bypass' => 'screen_data_visibility_rules.bypass',
                ],
                'active' => [
                    'admin.screen-data-visibility-rules.*',
                ],
                'children' => [],
            ]] : []),
            [
                'label' => 'companies',
                'title' => 'Companies',
                'icon' => 'building',
                'route' => 'admin.companies.index',
                'permission' => 'companies.view',
                'keywords' => ['company', 'companies', 'الشركات', 'شركة'],
                'actions' => [
                    'view' => 'companies.view',
                    'create' => 'companies.create',
                    'clone' => 'companies.clone',
                    'edit' => 'companies.edit',
                    'delete' => 'companies.delete',
                    'view_trashed' => 'companies.view_trashed',
                    'restore' => 'companies.restore',
                    'document_number_control' => 'companies.document_number.control',
                    'document_number_settings_update' => 'companies.document_number_settings.update',
                    'main_control' => 'companies.main.control',
                ],
                'active' => [
                    'admin.companies.*',
                ],
                'children' => [],
            ],
            [
                'label' => 'branches',
                'title' => 'Branches',
                'icon' => 'code-branch',
                'route' => 'admin.branches.index',
                'permission' => 'branches.view',
                'keywords' => ['branch', 'branches', 'locations', 'الفروع', 'فرع'],
                'actions' => [
                    'view' => 'branches.view',
                    'create' => 'branches.create',
                    'clone' => 'branches.clone',
                    'edit' => 'branches.edit',
                    'delete' => 'branches.delete',
                    'view_trashed' => 'branches.view_trashed',
                    'restore' => 'branches.restore',
                    'document_number_control' => 'branches.document_number.control',
                    'document_number_settings_update' => 'branches.document_number_settings.update',
                ],
                'active' => [
                    'admin.branches.*',
                ],
                'children' => [],
            ],
            [
                'label' => 'financial_periods',
                'title' => 'Financial Periods',
                'icon' => 'calendar-check',
                'route' => 'admin.financial-periods.index',
                'permission' => 'financial_periods.view',
                'keywords' => ['financial periods', 'periods', 'fiscal year', 'fiscal periods', 'الفترات المالية', 'فترة مالية'],
                'actions' => [
                    'view' => 'financial_periods.view',
                    'create' => 'financial_periods.create',
                    'clone' => 'financial_periods.clone',
                    'edit' => 'financial_periods.edit',
                    'delete' => 'financial_periods.delete',
                    'view_trashed' => 'financial_periods.view_trashed',
                    'restore' => 'financial_periods.restore',
                    'close' => 'financial_periods.close',
                    'reopen' => 'financial_periods.reopen',
                    'document_number_control' => 'financial_periods.document_number.control',
                    'document_number_settings_update' => 'financial_periods.document_number_settings.update',
                ],
                'active' => [
                    'admin.financial-periods.*',
                ],
                'children' => [],
            ],
            [
                'label' => 'activity_logs',
                'title' => 'Activity Log',
                'icon' => 'clipboard-list',
                'route' => 'admin.activity-logs.index',
                'permission' => 'activity.logs.view',
                'keywords' => ['activity', 'logs', 'audit', 'سجل', 'النشاط'],
                'actions' => [
                    'view' => 'activity.logs.view',
                    'details' => 'activity.logs.details',
                    'export' => 'activity.logs.export',
                    'pdf' => 'activity.logs.pdf',
                ],
                'active' => [
                    'admin.activity-logs.*',
                ],
                'children' => [],
            ],
            [
                'label' => 'auth_logs',
                'title' => 'Auth Logs',
                'icon' => 'clipboard-list',
                'route' => 'admin.auth-logs.index',
                'permission' => 'auth.logs.view',
                'keywords' => ['login', 'auth', 'logs', 'دخول', 'تسجيل الدخول'],
                'actions' => [
                    'view' => 'auth.logs.view',
                    'details' => 'auth.logs.details',
                    'export' => 'auth.logs.export',
                    'pdf' => 'auth.logs.pdf',
                ],
                'active' => [
                    'admin.auth-logs.*',
                ],
                'children' => [],
            ],
            [
                'label' => 'auth_sessions',
                'title' => 'Active Sessions',
                'icon' => 'clock',
                'route' => 'admin.auth-sessions.index',
                'permission' => 'auth.sessions.view',
                'keywords' => ['sessions', 'active sessions', 'logged in', 'الجلسات', 'النشطة'],
                'actions' => [
                    'view' => 'auth.sessions.view',
                    'details' => 'auth.sessions.details',
                    'export' => 'auth.sessions.export',
                    'pdf' => 'auth.sessions.pdf',
                    'force_logout' => 'auth.sessions.force_logout',
                ],
                'active' => [
                    'admin.auth-sessions.*',
                ],
                'children' => [],
            ],
            [
                'label' => 'profile',
                'title' => 'Profile',
                'icon' => 'user-circle',
                'route' => 'profile.show',
                'permission' => 'profile.view',
                'hidden' => true,
                'actions' => [
                    'view_profile' => 'profile.view',
                    'edit_profile' => 'profile.edit',
                    'password_update' => 'profile.password.update',
                    'sessions_view' => 'profile.sessions.view',
                    'auth_logs_view' => 'profile.auth_logs.view',
                    'delete_account' => 'profile.delete',
                ],
                'active' => [
                    'profile.*',
                ],
                'children' => [],
            ],
        ],
    ],
    [
        'label' => 'inventory',
        'title' => 'Inventory',
        'icon' => 'warehouse',
        'route' => null,
        'permission' => null,
        'keywords' => ['items', 'item data', 'units', 'sizes', 'colors', 'patterns', 'decals', 'origin countries', 'models', 'categories', 'groups', 'الأصناف', 'الوحدات', 'المقاسات', 'الألوان', 'النقشات', 'الديكالات', 'بلد المنشأ'],
        'active' => [
            'admin.products.*',
            'admin.raw-materials.*',
            'admin.packaging-materials.*',
            'admin.item-units.*',
            'admin.item-sizes.*',
            'admin.item-colors.*',
            'admin.item-decals.*',
            'admin.item-origin-countries.*',
            'admin.item-models.*',
            'admin.item-categories.*',
            'admin.item-groups.*',
        ],
        'children' => [
            [
                'label' => 'products',
                'title' => 'Products',
                'icon' => 'box',
                'route' => 'admin.products.index',
                'permission' => 'products.view',
                'keywords' => ['product', 'products', 'items', 'raw material', 'finished product', 'المنتجات', 'منتج', 'خام', 'تام'],
                'actions' => [
                    'view' => 'products.view',
                    'create' => 'products.create',
                    'clone' => 'products.clone',
                    'edit' => 'products.edit',
                    'delete' => 'products.delete',
                    'view_trashed' => 'products.view_trashed',
                    'restore' => 'products.restore',
                    'import' => 'products.import',
                    'document_number_control' => 'products.document_number.control',
                    'document_number_settings_update' => 'products.document_number_settings.update',
                ],
                'active' => [
                    'admin.products.*',
                ],
                'children' => [],
            ],
            [
                'label' => 'raw_materials',
                'title' => 'Raw Materials',
                'icon' => 'cubes',
                'route' => 'admin.raw-materials.index',
                'permission' => 'raw_materials.view',
                'keywords' => ['raw material', 'raw materials', 'materials', 'خامات', 'خامة', 'مواد خام'],
                'actions' => [
                    'view' => 'raw_materials.view',
                    'create' => 'raw_materials.create',
                    'clone' => 'raw_materials.clone',
                    'edit' => 'raw_materials.edit',
                    'delete' => 'raw_materials.delete',
                    'view_trashed' => 'raw_materials.view_trashed',
                    'restore' => 'raw_materials.restore',
                    'document_number_control' => 'raw_materials.document_number.control',
                    'document_number_settings_update' => 'raw_materials.document_number_settings.update',
                ],
                'active' => [
                    'admin.raw-materials.*',
                ],
                'children' => [],
            ],
            [
                'label' => 'packaging_materials',
                'title' => 'Packaging Materials',
                'icon' => 'boxes',
                'route' => 'admin.packaging-materials.index',
                'permission' => 'packaging_materials.view',
                'keywords' => ['packaging material', 'packaging materials', 'packaging', 'materials', 'مواد التعبئة والتغليف', 'تعبئة وتغليف'],
                'actions' => [
                    'view' => 'packaging_materials.view',
                    'create' => 'packaging_materials.create',
                    'clone' => 'packaging_materials.clone',
                    'edit' => 'packaging_materials.edit',
                    'delete' => 'packaging_materials.delete',
                    'view_trashed' => 'packaging_materials.view_trashed',
                    'restore' => 'packaging_materials.restore',
                    'document_number_control' => 'packaging_materials.document_number.control',
                    'document_number_settings_update' => 'packaging_materials.document_number_settings.update',
                ],
                'active' => [
                    'admin.packaging-materials.*',
                ],
                'children' => [],
            ],
            [
                'label' => 'item_categories',
                'title' => 'Categories',
                'icon' => 'layer-group',
                'route' => 'admin.item-categories.index',
                'permission' => 'item_categories.view',
                'keywords' => ['category', 'categories', 'الفئات', 'فئة'],
                'actions' => [
                    'view' => 'item_categories.view',
                    'create' => 'item_categories.create',
                    'clone' => 'item_categories.clone',
                    'edit' => 'item_categories.edit',
                    'delete' => 'item_categories.delete',
                    'view_trashed' => 'item_categories.view_trashed',
                    'restore' => 'item_categories.restore',
                    'document_number_control' => 'item_categories.document_number.control',
                    'document_number_settings_update' => 'item_categories.document_number_settings.update',
                ],
                'active' => [
                    'admin.item-categories.*',
                ],
                'children' => [],
            ],
            [
                'label' => 'item_units',
                'title' => 'Units',
                'icon' => 'balance-scale',
                'route' => 'admin.item-units.index',
                'permission' => 'item_units.view',
                'keywords' => ['unit', 'units', 'measure', 'الوحدات', 'وحدة'],
                'actions' => [
                    'view' => 'item_units.view',
                    'create' => 'item_units.create',
                    'clone' => 'item_units.clone',
                    'edit' => 'item_units.edit',
                    'delete' => 'item_units.delete',
                    'view_trashed' => 'item_units.view_trashed',
                    'restore' => 'item_units.restore',
                    'document_number_control' => 'item_units.document_number.control',
                    'document_number_settings_update' => 'item_units.document_number_settings.update',
                ],
                'active' => [
                    'admin.item-units.*',
                ],
                'children' => [],
            ],
            [
                'label' => 'item_sizes',
                'title' => 'Sizes',
                'icon' => 'expand-arrows-alt',
                'route' => 'admin.item-sizes.index',
                'permission' => 'item_sizes.view',
                'keywords' => ['size', 'sizes', 'المقاسات', 'مقاس'],
                'actions' => [
                    'view' => 'item_sizes.view',
                    'create' => 'item_sizes.create',
                    'clone' => 'item_sizes.clone',
                    'edit' => 'item_sizes.edit',
                    'delete' => 'item_sizes.delete',
                    'view_trashed' => 'item_sizes.view_trashed',
                    'restore' => 'item_sizes.restore',
                    'document_number_control' => 'item_sizes.document_number.control',
                    'document_number_settings_update' => 'item_sizes.document_number_settings.update',
                ],
                'active' => [
                    'admin.item-sizes.*',
                ],
                'children' => [],
            ],
            [
                'label' => 'item_colors',
                'title' => 'Colors',
                'icon' => 'palette',
                'route' => 'admin.item-colors.index',
                'permission' => 'item_colors.view',
                'keywords' => ['color', 'colors', 'الألوان', 'لون'],
                'actions' => [
                    'view' => 'item_colors.view',
                    'create' => 'item_colors.create',
                    'clone' => 'item_colors.clone',
                    'edit' => 'item_colors.edit',
                    'delete' => 'item_colors.delete',
                    'view_trashed' => 'item_colors.view_trashed',
                    'restore' => 'item_colors.restore',
                    'document_number_control' => 'item_colors.document_number.control',
                    'document_number_settings_update' => 'item_colors.document_number_settings.update',
                ],
                'active' => [
                    'admin.item-colors.*',
                ],
                'children' => [],
            ],
            [
                'label' => 'item_decals',
                'title' => 'Patterns / Decals',
                'icon' => 'stamp',
                'route' => 'admin.item-decals.index',
                'permission' => 'item_decals.view',
                'keywords' => ['pattern', 'patterns', 'decal', 'decals', 'النقشات', 'النقشة', 'الديكالات', 'ديكال'],
                'actions' => [
                    'view' => 'item_decals.view',
                    'create' => 'item_decals.create',
                    'clone' => 'item_decals.clone',
                    'edit' => 'item_decals.edit',
                    'delete' => 'item_decals.delete',
                    'view_trashed' => 'item_decals.view_trashed',
                    'restore' => 'item_decals.restore',
                    'document_number_control' => 'item_decals.document_number.control',
                    'document_number_settings_update' => 'item_decals.document_number_settings.update',
                ],
                'active' => [
                    'admin.item-decals.*',
                ],
                'children' => [],
            ],
            [
                'label' => 'item_models',
                'title' => 'Models',
                'icon' => 'cube',
                'route' => 'admin.item-models.index',
                'permission' => 'item_models.view',
                'keywords' => ['model', 'models', 'الموديلات', 'موديل'],
                'actions' => [
                    'view' => 'item_models.view',
                    'create' => 'item_models.create',
                    'clone' => 'item_models.clone',
                    'edit' => 'item_models.edit',
                    'delete' => 'item_models.delete',
                    'view_trashed' => 'item_models.view_trashed',
                    'restore' => 'item_models.restore',
                    'document_number_control' => 'item_models.document_number.control',
                    'document_number_settings_update' => 'item_models.document_number_settings.update',
                ],
                'active' => [
                    'admin.item-models.*',
                ],
                'children' => [],
            ],
            [
                'label' => 'item_groups',
                'title' => 'Groups',
                'icon' => 'object-group',
                'route' => 'admin.item-groups.index',
                'permission' => 'item_groups.view',
                'keywords' => ['group', 'groups', 'المجموعات', 'مجموعة'],
                'actions' => [
                    'view' => 'item_groups.view',
                    'create' => 'item_groups.create',
                    'clone' => 'item_groups.clone',
                    'edit' => 'item_groups.edit',
                    'delete' => 'item_groups.delete',
                    'view_trashed' => 'item_groups.view_trashed',
                    'restore' => 'item_groups.restore',
                    'document_number_control' => 'item_groups.document_number.control',
                    'document_number_settings_update' => 'item_groups.document_number_settings.update',
                ],
                'active' => [
                    'admin.item-groups.*',
                ],
                'children' => [],
            ],
            [
                'label' => 'item_origin_countries',
                'title' => 'Country of Origin',
                'icon' => 'globe-africa',
                'route' => 'admin.item-origin-countries.index',
                'permission' => 'item_origin_countries.view',
                'keywords' => ['country of origin', 'origin country', 'origin countries', 'بلد المنشأ', 'بلاد المنشأ', 'منشأ'],
                'actions' => [
                    'view' => 'item_origin_countries.view',
                    'create' => 'item_origin_countries.create',
                    'clone' => 'item_origin_countries.clone',
                    'edit' => 'item_origin_countries.edit',
                    'delete' => 'item_origin_countries.delete',
                    'view_trashed' => 'item_origin_countries.view_trashed',
                    'restore' => 'item_origin_countries.restore',
                    'document_number_control' => 'item_origin_countries.document_number.control',
                    'document_number_settings_update' => 'item_origin_countries.document_number_settings.update',
                ],
                'active' => [
                    'admin.item-origin-countries.*',
                ],
                'children' => [],
            ],
        ],
    ],
];
