<?php

return [
    [
        'label' => 'finance',
        'title' => 'Finance',
        'icon' => 'money-check-alt',
        'route' => null,
        'permission' => null,
        'keywords' => ['finance', 'currencies', 'bank accounts', 'cashboxes', 'opening balances', 'المالية', 'العملات', 'البنوك', 'الخزائن'],
        'active' => ['admin.currencies.*', 'admin.finance.*'],
        'children' => [
            [
                'label' => 'currencies',
                'title' => 'Currencies',
                'icon' => 'coins',
                'route' => 'admin.currencies.index',
                'permission' => 'currencies.view',
                'keywords' => ['currencies', 'currency', 'العملات', 'عملة'],
                'actions' => [
                    'view' => 'currencies.view',
                    'create' => 'currencies.create',
                    'clone' => 'currencies.clone',
                    'edit' => 'currencies.edit',
                    'delete' => 'currencies.delete',
                    'view_trashed' => 'currencies.view_trashed',
                    'restore' => 'currencies.restore',
                    'document_number_control' => 'currencies.document_number.control',
                    'document_number_settings_update' => 'currencies.document_number_settings.update',
                ],
                'active' => ['admin.currencies.*'],
                'children' => [],
            ],
            [
                'label' => 'bank_accounts',
                'title' => 'Bank Accounts',
                'icon' => 'university',
                'route' => 'admin.finance.bank-accounts.index',
                'permission' => 'bank_accounts.view',
                'actions' => [
                    'view' => 'bank_accounts.view', 'create' => 'bank_accounts.create', 'clone' => 'bank_accounts.clone',
                    'edit' => 'bank_accounts.edit', 'delete' => 'bank_accounts.delete', 'view_trashed' => 'bank_accounts.view_trashed',
                    'restore' => 'bank_accounts.restore', 'document_number_control' => 'bank_accounts.document_number.control',
                    'document_number_settings_update' => 'bank_accounts.document_number_settings.update',
                ],
                'active' => ['admin.finance.bank-accounts.*'],
                'children' => [],
            ],
            [
                'label' => 'cashboxes',
                'title' => 'Cashboxes',
                'icon' => 'cash-register',
                'route' => 'admin.finance.cashboxes.index',
                'permission' => 'cashboxes.view',
                'actions' => [
                    'view' => 'cashboxes.view', 'create' => 'cashboxes.create', 'clone' => 'cashboxes.clone',
                    'edit' => 'cashboxes.edit', 'delete' => 'cashboxes.delete', 'view_trashed' => 'cashboxes.view_trashed',
                    'restore' => 'cashboxes.restore', 'document_number_control' => 'cashboxes.document_number.control',
                    'document_number_settings_update' => 'cashboxes.document_number_settings.update',
                ],
                'active' => ['admin.finance.cashboxes.*'],
                'children' => [],
            ],
            [
                'label' => 'cash_receipt_vouchers',
                'title' => 'Cash Receipt Vouchers',
                'icon' => 'file-invoice-dollar',
                'route' => 'admin.finance.cash-receipt-vouchers.index',
                'permission' => 'cash_receipt_vouchers.view',
                'actions' => [
                    'view' => 'cash_receipt_vouchers.view', 'create' => 'cash_receipt_vouchers.create', 'clone' => 'cash_receipt_vouchers.clone',
                    'edit' => 'cash_receipt_vouchers.edit', 'delete' => 'cash_receipt_vouchers.delete', 'view_trashed' => 'cash_receipt_vouchers.view_trashed',
                    'restore' => 'cash_receipt_vouchers.restore', 'approve' => 'cash_receipt_vouchers.approve',
                    'cancel' => 'cash_receipt_vouchers.cancel', 'print' => 'cash_receipt_vouchers.print',
                    'document_number_control' => 'cash_receipt_vouchers.document_number.control',
                    'document_number_settings_update' => 'cash_receipt_vouchers.document_number_settings.update',
                ],
                'active' => ['admin.finance.cash-receipt-vouchers.*'],
                'children' => [],
            ],
            [
                'label' => 'cash_payment_vouchers',
                'title' => 'Cash Payment Vouchers',
                'icon' => 'file-invoice',
                'route' => 'admin.finance.cash-payment-vouchers.index',
                'permission' => 'cash_payment_vouchers.view',
                'actions' => [
                    'view' => 'cash_payment_vouchers.view', 'create' => 'cash_payment_vouchers.create', 'clone' => 'cash_payment_vouchers.clone',
                    'edit' => 'cash_payment_vouchers.edit', 'delete' => 'cash_payment_vouchers.delete', 'view_trashed' => 'cash_payment_vouchers.view_trashed',
                    'restore' => 'cash_payment_vouchers.restore', 'approve' => 'cash_payment_vouchers.approve',
                    'cancel' => 'cash_payment_vouchers.cancel', 'print' => 'cash_payment_vouchers.print',
                    'document_number_control' => 'cash_payment_vouchers.document_number.control',
                    'document_number_settings_update' => 'cash_payment_vouchers.document_number_settings.update',
                ],
                'active' => ['admin.finance.cash-payment-vouchers.*'],
                'children' => [],
            ],
            [
                'label' => 'cheques',
                'title' => 'Cheques',
                'icon' => 'money-check',
                'route' => 'admin.finance.cheques.index',
                'permission' => 'cheques.view',
                'actions' => [
                    'view' => 'cheques.view', 'create' => 'cheques.create', 'clone' => 'cheques.clone',
                    'edit' => 'cheques.edit', 'delete' => 'cheques.delete', 'view_trashed' => 'cheques.view_trashed',
                    'restore' => 'cheques.restore', 'mark_deposited' => 'cheques.mark_deposited',
                    'mark_collected' => 'cheques.mark_collected', 'mark_returned' => 'cheques.mark_returned',
                    'mark_issued' => 'cheques.mark_issued', 'mark_delivered' => 'cheques.mark_delivered',
                    'mark_cleared' => 'cheques.mark_cleared', 'cancel' => 'cheques.cancel',
                    'print' => 'cheques.print', 'document_number_control' => 'cheques.document_number.control',
                    'document_number_settings_update' => 'cheques.document_number_settings.update',
                ],
                'active' => ['admin.finance.cheques.*'],
                'children' => [],
            ],
            [
                'label' => 'fund_transfers',
                'title' => 'Fund Transfers',
                'icon' => 'exchange-alt',
                'route' => 'admin.finance.fund-transfers.index',
                'permission' => 'fund_transfers.view',
                'actions' => [
                    'view' => 'fund_transfers.view', 'create' => 'fund_transfers.create', 'clone' => 'fund_transfers.clone',
                    'edit' => 'fund_transfers.edit', 'delete' => 'fund_transfers.delete', 'view_trashed' => 'fund_transfers.view_trashed',
                    'restore' => 'fund_transfers.restore', 'approve' => 'fund_transfers.approve',
                    'cancel' => 'fund_transfers.cancel', 'print' => 'fund_transfers.print',
                    'document_number_control' => 'fund_transfers.document_number.control',
                    'document_number_settings_update' => 'fund_transfers.document_number_settings.update',
                ],
                'active' => ['admin.finance.fund-transfers.*'],
                'children' => [],
            ],
            [
                'label' => 'opening_balances',
                'title' => 'Opening Balances',
                'icon' => 'balance-scale',
                'route' => 'admin.finance.opening-balances.index',
                'permission' => 'opening_balances.view',
                'actions' => [
                    'view' => 'opening_balances.view', 'create' => 'opening_balances.create', 'clone' => 'opening_balances.clone',
                    'edit' => 'opening_balances.edit', 'delete' => 'opening_balances.delete', 'view_trashed' => 'opening_balances.view_trashed',
                    'restore' => 'opening_balances.restore', 'approve' => 'opening_balances.approve',
                    'cancel' => 'opening_balances.cancel', 'document_number_control' => 'opening_balances.document_number.control',
                    'document_number_settings_update' => 'opening_balances.document_number_settings.update',
                ],
                'active' => ['admin.finance.opening-balances.*'],
                'children' => [],
            ],
            [
                'label' => 'finance_report_overview',
                'title' => 'Financial Reports Overview',
                'icon' => 'chart-line',
                'route' => 'admin.reports.finance.index',
                'permission' => 'reports.finance.view',
                'actions' => ['view' => 'reports.finance.view'],
                'active' => ['admin.reports.finance.index'],
                'children' => [],
            ],
        ],
    ],
];
