<?php

return [
    [
        'label' => 'fixed_assets',
        'title' => 'Fixed Assets',
        'icon' => 'building',
        'route' => null,
        'permission' => null,
        'keywords' => ['fixed assets', 'assets', 'register', 'الأصول الثابتة', 'دليل الأصول'],
        'active' => ['admin.fixed-assets.*'],
        'children' => [
            [
                'label' => 'fixed_assets_register',
                'title' => 'Fixed Assets Register',
                'icon' => 'clipboard-list',
                'route' => 'admin.fixed-assets.assets.index',
                'permission' => 'fixed_assets.view',
                'keywords' => ['fixed assets register', 'fixed assets directory', 'assets', 'دليل الأصول الثابتة'],
                'actions' => [
                    'view' => 'fixed_assets.view',
                    'create' => 'fixed_assets.create',
                    'clone' => 'fixed_assets.clone',
                    'edit' => 'fixed_assets.edit',
                    'delete' => 'fixed_assets.delete',
                    'view_trashed' => 'fixed_assets.view_trashed',
                    'restore' => 'fixed_assets.restore',
                    'import' => 'fixed_assets.import',
                    'document_number_control' => 'fixed_assets.document_number.control',
                    'document_number_settings_update' => 'fixed_assets.document_number_settings.update',
                    'activate' => 'fixed_assets.activate',
                    'accounting_configure' => 'fixed_assets.accounting.configure',
                    'improvement_post' => 'fixed_assets.improvement.post',
                    'improvement_reverse' => 'fixed_assets.improvement.reverse',
                    'recognition_reverse' => 'fixed_assets.recognition.reverse',
                    'custody_post' => 'fixed_assets.custody.post',
                    'transfer' => 'fixed_assets.transfer',
                    'dispose' => 'fixed_assets.dispose',
                    'disposal_reverse' => 'fixed_assets.disposal.reverse',
                    'print' => 'fixed_assets.print',
                ],
                'active' => ['admin.fixed-assets.assets.*'],
                'children' => [],
            ],
            [
                'label' => 'fixed_asset_movements',
                'title' => 'Asset Movements',
                'icon' => 'exchange-alt',
                'route' => 'admin.fixed-assets.movements.index',
                'permission' => 'fixed_assets.view',
                'active' => ['admin.fixed-assets.movements.*'],
                'children' => [],
            ],
            [
                'label' => 'fixed_asset_depreciation',
                'title' => 'Fixed Asset Depreciation',
                'icon' => 'calculator',
                'route' => 'admin.fixed-assets.depreciation.index',
                'permission' => 'fixed_assets.depreciation.preview',
                'actions' => [
                    'preview' => 'fixed_assets.depreciation.preview',
                    'post' => 'fixed_assets.depreciation.post',
                    'reverse' => 'fixed_assets.depreciation.reverse',
                ],
                'active' => ['admin.fixed-assets.depreciation.*'],
                'children' => [],
            ],
            [
                'label' => 'fixed_asset_reports',
                'title' => 'Fixed Asset Reports',
                'icon' => 'chart-bar',
                'route' => 'admin.fixed-assets.reports.index',
                'permission' => 'fixed_assets.reports',
                'actions' => [
                    'view' => 'fixed_assets.reports',
                    'export' => 'fixed_assets.export',
                ],
                'active' => ['admin.fixed-assets.reports.*'],
                'children' => [],
            ],
        ],
    ],
];
