<?php

return [
    [
        'label' => 'inventory',
        'title' => 'Inventory / Warehouses',
        'icon' => 'warehouse',
        'route' => null,
        'permission' => null,
        'keywords' => ['inventory', 'warehouses', 'opening stock', 'opening inventory', 'المخازن', 'مخزون أول المدة'],
        'active' => [
            'admin.inventory.*',
        ],
        'children' => [
            [
                'label' => 'inventory_stock_balance_inquiry',
                'title' => 'Stock Balance Inquiry',
                'icon' => 'search',
                'route' => 'admin.inventory.stock-balances.index',
                'permission' => 'inventory.reports.stock_balances.view',
                'keywords' => ['stock balance inquiry', 'inventory availability', 'استعلام الأرصدة', 'أرصدة المخزون'],
                'actions' => [
                    'view' => 'inventory.reports.stock_balances.view',
                    'export' => 'inventory.reports.stock_balances.export',
                    'print' => 'inventory.reports.stock_balances.print',
                ],
                'active' => ['admin.inventory.stock-balances.*'],
                'children' => [],
            ],
            [
                'label' => 'inventory_movements',
                'title' => 'Inventory Movements',
                'icon' => 'exchange-alt',
                'route' => 'admin.inventory.documents.index',
                'permission' => 'inventory.documents.view',
                'keywords' => ['inventory movements', 'transfers', 'adjustments', 'damage', 'scrap'],
                'actions' => [
                    'view' => 'inventory.documents.view',
                    'create' => 'inventory.documents.create',
                    'edit' => 'inventory.documents.edit',
                    'clone' => 'inventory.documents.clone',
                    'delete' => 'inventory.documents.delete',
                    'view_trashed' => 'inventory.documents.view_trashed',
                    'restore' => 'inventory.documents.restore',
                    'post' => 'inventory.documents.post',
                    'receive' => 'inventory.documents.receive',
                    'issue' => 'inventory.documents.issue',
                    'return' => 'inventory.documents.return',
                    'transfer' => 'inventory.documents.transfer',
                    'adjust' => 'inventory.documents.adjust',
                    'damage_scrap' => 'inventory.documents.damage_scrap',
                    'reverse' => 'inventory.documents.reverse',
                    'print' => 'inventory.documents.print',
                ],
                'active' => ['admin.inventory.documents.*'],
                'children' => [],
            ],
            [
                'label' => 'inventory_operational_reports',
                'title' => 'Inventory Operational Reports',
                'icon' => 'chart-bar',
                'route' => 'admin.inventory.reports.index',
                'permission' => 'inventory.reports.operations.view',
                'keywords' => ['inventory reports', 'stock balance', 'stock card', 'reservations'],
                'actions' => [
                    'view' => 'inventory.reports.operations.view',
                    'export' => 'inventory.reports.operations.export',
                    'print' => 'inventory.reports.operations.print',
                ],
                'active' => ['admin.inventory.reports.*'],
                'children' => [],
            ],
            [
                'label' => 'inventory_valuation_report',
                'title' => 'Inventory Valuation Comparison',
                'icon' => 'balance-scale',
                'route' => 'admin.inventory.reports.valuation',
                'permission' => 'inventory.reports.valuation.view',
                'keywords' => ['inventory valuation', 'moving average', 'periodic average', 'fifo', 'تقييم المخزون'],
                'actions' => [
                    'view' => 'inventory.reports.valuation.view',
                    'export' => 'inventory.reports.valuation.export',
                ],
                'active' => ['admin.inventory.reports.valuation'],
                'children' => [],
            ],
            [
                'label' => 'inventory_sales_valuation_report',
                'title' => 'Inventory Sales Valuation',
                'icon' => 'tags',
                'route' => 'admin.inventory.sales-valuation',
                'permission' => 'inventory.reports.sales_valuation.view',
                'keywords' => ['inventory sales valuation', 'price list valuation', 'sales value', 'تقييم المخزون بسعر البيع'],
                'actions' => [
                    'view' => 'inventory.reports.sales_valuation.view',
                    'export' => 'inventory.reports.sales_valuation.export',
                    'print' => 'inventory.reports.sales_valuation.print',
                ],
                'active' => ['admin.inventory.sales-valuation*'],
                'children' => [],
            ],
            [
                'label' => 'production_reports_receipts',
                'title' => 'Finished Goods Receipts Report',
                'icon' => 'dolly-flatbed',
                'route' => 'admin.production.reports.receipts',
                'permission' => 'production.reports.receipts.view',
                'keywords' => ['finished goods receipts', 'warehouse receipt', 'استلام الإنتاج التام'],
                'actions' => [
                    'view' => 'production.reports.receipts.view',
                    'export' => 'production.reports.receipts.export',
                    'print' => 'production.reports.receipts.print',
                ],
                'active' => ['admin.production.reports.receipts'],
                'children' => [],
            ],
            [
                'label' => 'inventory_stock_counts',
                'title' => 'Physical Stock Counts',
                'icon' => 'clipboard-check',
                'route' => 'admin.inventory.stock-counts.index',
                'permission' => 'inventory.stock_counts.view',
                'keywords' => ['stock count', 'physical inventory', 'variance', 'adjustment'],
                'actions' => [
                    'view' => 'inventory.stock_counts.view',
                    'create' => 'inventory.stock_counts.create',
                    'clone' => 'inventory.stock_counts.clone',
                    'edit' => 'inventory.stock_counts.edit',
                    'delete' => 'inventory.stock_counts.delete',
                    'view_trashed' => 'inventory.stock_counts.view_trashed',
                    'restore' => 'inventory.stock_counts.restore',
                    'approve' => 'inventory.stock_counts.approve',
                    'print' => 'inventory.stock_counts.print',
                    'export' => 'inventory.stock_counts.export',
                    'document_number_control' => 'inventory.stock_counts.document_number.control',
                    'document_number_settings_update' => 'inventory.stock_counts.document_number_settings.update',
                ],
                'active' => ['admin.inventory.stock-counts.*'],
                'children' => [],
            ],
            [
                'label' => 'opening_stocks',
                'title' => 'Opening Stock',
                'icon' => 'boxes',
                'route' => 'admin.inventory.opening-stocks.index',
                'permission' => 'inventory.opening_stocks.view',
                'keywords' => ['opening stock', 'opening inventory', 'inventory opening', 'مخزون أول المدة'],
                'actions' => [
                    'view' => 'inventory.opening_stocks.view',
                    'create' => 'inventory.opening_stocks.create',
                    'clone' => 'inventory.opening_stocks.clone',
                    'edit' => 'inventory.opening_stocks.edit',
                    'delete' => 'inventory.opening_stocks.delete',
                    'view_trashed' => 'inventory.opening_stocks.view_trashed',
                    'restore' => 'inventory.opening_stocks.restore',
                    'approve' => 'inventory.opening_stocks.approve',
                    'document_number_control' => 'inventory.opening_stocks.document_number.control',
                    'document_number_settings_update' => 'inventory.opening_stocks.document_number_settings.update',
                ],
                'active' => [
                    'admin.inventory.opening-stocks.*',
                ],
                'children' => [],
            ],
            [
                'label' => 'unpriced_inventory_receipts',
                'title' => 'Unpriced Inventory Receipts',
                'icon' => 'dolly',
                'route' => 'admin.inventory.unpriced-inventory-receipts.index',
                'permission' => 'inventory.unpriced_inventory_receipts.view',
                'keywords' => ['unpriced inventory receipts', 'quantity only receipt', 'warehouse receipt without prices', 'توريد مخزني بدون أسعار'],
                'actions' => [
                    'view' => 'inventory.unpriced_inventory_receipts.view',
                    'create' => 'inventory.unpriced_inventory_receipts.create',
                    'edit' => 'inventory.unpriced_inventory_receipts.edit',
                    'delete' => 'inventory.unpriced_inventory_receipts.delete',
                    'view_trashed' => 'inventory.unpriced_inventory_receipts.view_trashed',
                    'restore' => 'inventory.unpriced_inventory_receipts.restore',
                    'approve' => 'inventory.unpriced_inventory_receipts.approve',
                    'close' => 'inventory.unpriced_inventory_receipts.close',
                    'cancel' => 'inventory.unpriced_inventory_receipts.cancel',
                    'document_number_control' => 'inventory.unpriced_inventory_receipts.document_number.control',
                    'document_number_settings_update' => 'inventory.unpriced_inventory_receipts.document_number_settings.update',
                ],
                'active' => [
                    'admin.inventory.unpriced-inventory-receipts.*',
                ],
                'children' => [],
            ],
            [
                'label' => 'opening_stock_pricings',
                'title' => 'Opening Stock Pricing',
                'icon' => 'tags',
                'route' => 'admin.inventory.opening-stock-pricings.index',
                'permission' => 'inventory.opening_stock_pricings.view',
                'keywords' => ['opening stock pricing', 'opening inventory pricing', 'inventory pricing', 'تسعير مخزون أول المدة'],
                'actions' => [
                    'view' => 'inventory.opening_stock_pricings.view',
                    'create' => 'inventory.opening_stock_pricings.create',
                    'clone' => 'inventory.opening_stock_pricings.clone',
                    'edit' => 'inventory.opening_stock_pricings.edit',
                    'delete' => 'inventory.opening_stock_pricings.delete',
                    'view_trashed' => 'inventory.opening_stock_pricings.view_trashed',
                    'restore' => 'inventory.opening_stock_pricings.restore',
                    'document_number_control' => 'inventory.opening_stock_pricings.document_number.control',
                    'document_number_settings_update' => 'inventory.opening_stock_pricings.document_number_settings.update',
                ],
                'active' => [
                    'admin.inventory.opening-stock-pricings.*',
                ],
                'children' => [],
            ],
        ],
    ],
];
