<?php

return [
    [
        'label' => 'inventory',
        'title' => 'Inventory / Warehouses',
        'icon' => 'warehouse',
        'route' => null,
        'permission' => null,
        'keywords' => ['inventory', 'warehouses', 'opening stock', 'opening inventory', 'المخازن', 'مخزون أول المدة'],
        'active' => [
            'admin.inventory.*',
        ],
        'children' => [
            [
                'label' => 'inventory_accounting',
                'title' => 'Inventory & Manufacturing Accounting',
                'icon' => 'balance-scale',
                'route' => 'admin.inventory.accounting.index',
                'permission' => 'inventory.accounting.view',
                'keywords' => ['inventory accounting', 'wip', 'manufacturing accounts', 'حسابات المخزون', 'تحت التشغيل'],
                'actions' => [
                    'view' => 'inventory.accounting.view',
                    'configure' => 'inventory.accounting.configure',
                ],
                'active' => ['admin.inventory.accounting.*'],
                'children' => [],
            ],
            [
                'label' => 'warehouse_locations',
                'title' => 'Warehouse Locations',
                'icon' => 'map-marker-alt',
                'route' => 'admin.inventory.warehouse-locations.index',
                'permission' => 'inventory.locations.view',
                'keywords' => ['warehouse locations', 'zones', 'bins'],
                'actions' => ['view' => 'inventory.locations.view', 'manage' => 'inventory.locations.manage'],
                'active' => ['admin.inventory.warehouse-locations.*'],
                'children' => [],
            ],
            [
                'label' => 'inventory_movements',
                'title' => 'Inventory Movements',
                'icon' => 'exchange-alt',
                'route' => 'admin.inventory.documents.index',
                'permission' => 'inventory.documents.view',
                'keywords' => ['inventory movements', 'transfers', 'adjustments', 'damage', 'scrap'],
                'actions' => [
                    'view' => 'inventory.documents.view',
                    'create' => 'inventory.documents.create',
                    'transfer' => 'inventory.documents.transfer',
                    'adjust' => 'inventory.documents.adjust',
                    'damage_scrap' => 'inventory.documents.damage_scrap',
                    'reverse' => 'inventory.documents.reverse',
                    'print' => 'inventory.documents.print',
                ],
                'active' => ['admin.inventory.documents.*'],
                'children' => [],
            ],
            [
                'label' => 'inventory_operational_reports',
                'title' => 'Inventory Operational Reports',
                'icon' => 'chart-bar',
                'route' => 'admin.inventory.reports.index',
                'permission' => 'inventory.reports.operational',
                'keywords' => ['inventory reports', 'stock balance', 'stock card', 'reservations'],
                'actions' => [
                    'view' => 'inventory.reports.operational',
                    'financial' => 'inventory.reports.financial',
                    'export' => 'inventory.reports.export',
                ],
                'active' => ['admin.inventory.reports.*'],
                'children' => [],
            ],
            [
                'label' => 'inventory_stock_counts',
                'title' => 'Physical Stock Counts',
                'icon' => 'clipboard-check',
                'route' => 'admin.inventory.stock-counts.index',
                'permission' => 'inventory.stock_counts.view',
                'keywords' => ['stock count', 'physical inventory', 'variance', 'adjustment'],
                'actions' => [
                    'view' => 'inventory.stock_counts.view',
                    'create' => 'inventory.stock_counts.create',
                    'record' => 'inventory.stock_counts.record',
                    'approve' => 'inventory.stock_counts.approve',
                    'print' => 'inventory.stock_counts.print',
                ],
                'active' => ['admin.inventory.stock-counts.*'],
                'children' => [],
            ],
            [
                'label' => 'opening_stocks',
                'title' => 'Opening Stock',
                'icon' => 'boxes',
                'route' => 'admin.inventory.opening-stocks.index',
                'permission' => 'inventory.opening_stocks.view',
                'keywords' => ['opening stock', 'opening inventory', 'inventory opening', 'مخزون أول المدة'],
                'actions' => [
                    'view' => 'inventory.opening_stocks.view',
                    'create' => 'inventory.opening_stocks.create',
                    'clone' => 'inventory.opening_stocks.clone',
                    'edit' => 'inventory.opening_stocks.edit',
                    'delete' => 'inventory.opening_stocks.delete',
                    'view_trashed' => 'inventory.opening_stocks.view_trashed',
                    'restore' => 'inventory.opening_stocks.restore',
                    'approve' => 'inventory.opening_stocks.approve',
                    'document_number_control' => 'inventory.opening_stocks.document_number.control',
                    'document_number_settings_update' => 'inventory.opening_stocks.document_number_settings.update',
                ],
                'active' => [
                    'admin.inventory.opening-stocks.*',
                ],
                'children' => [],
            ],
            [
                'label' => 'unpriced_inventory_receipts',
                'title' => 'Unpriced Inventory Receipts',
                'icon' => 'dolly',
                'route' => 'admin.inventory.unpriced-inventory-receipts.index',
                'permission' => 'inventory.unpriced_inventory_receipts.view',
                'keywords' => ['unpriced inventory receipts', 'quantity only receipt', 'warehouse receipt without prices', 'توريد مخزني بدون أسعار'],
                'actions' => [
                    'view' => 'inventory.unpriced_inventory_receipts.view',
                    'create' => 'inventory.unpriced_inventory_receipts.create',
                    'edit' => 'inventory.unpriced_inventory_receipts.edit',
                    'delete' => 'inventory.unpriced_inventory_receipts.delete',
                    'view_trashed' => 'inventory.unpriced_inventory_receipts.view_trashed',
                    'restore' => 'inventory.unpriced_inventory_receipts.restore',
                    'approve' => 'inventory.unpriced_inventory_receipts.approve',
                    'close' => 'inventory.unpriced_inventory_receipts.close',
                    'cancel' => 'inventory.unpriced_inventory_receipts.cancel',
                    'document_number_control' => 'inventory.unpriced_inventory_receipts.document_number.control',
                    'document_number_settings_update' => 'inventory.unpriced_inventory_receipts.document_number_settings.update',
                ],
                'active' => [
                    'admin.inventory.unpriced-inventory-receipts.*',
                ],
                'children' => [],
            ],
            [
                'label' => 'opening_stock_pricings',
                'title' => 'Opening Stock Pricing',
                'icon' => 'tags',
                'route' => 'admin.inventory.opening-stock-pricings.index',
                'permission' => 'inventory.opening_stock_pricings.view',
                'keywords' => ['opening stock pricing', 'opening inventory pricing', 'inventory pricing', 'تسعير مخزون أول المدة'],
                'actions' => [
                    'view' => 'inventory.opening_stock_pricings.view',
                    'create' => 'inventory.opening_stock_pricings.create',
                    'clone' => 'inventory.opening_stock_pricings.clone',
                    'edit' => 'inventory.opening_stock_pricings.edit',
                    'delete' => 'inventory.opening_stock_pricings.delete',
                    'view_trashed' => 'inventory.opening_stock_pricings.view_trashed',
                    'restore' => 'inventory.opening_stock_pricings.restore',
                    'document_number_control' => 'inventory.opening_stock_pricings.document_number.control',
                    'document_number_settings_update' => 'inventory.opening_stock_pricings.document_number_settings.update',
                ],
                'active' => [
                    'admin.inventory.opening-stock-pricings.*',
                ],
                'children' => [],
            ],
        ],
    ],
];
