<?php

return [
    [
        'label' => 'maintenance',
        'title' => 'Maintenance',
        'icon' => 'tools',
        'route' => null,
        'permission' => null,
        'keywords' => ['maintenance', 'breakdown', 'preventive', 'الصيانة', 'الأعطال'],
        'active' => ['admin.maintenance.*'],
        'children' => [
            [
                'label' => 'maintenance_requests',
                'title' => 'Breakdown Reports',
                'icon' => 'exclamation-triangle',
                'route' => 'admin.maintenance.requests.index',
                'permission' => 'maintenance.requests.view',
                'keywords' => ['breakdown reports', 'إبلاغ عطل'],
                'actions' => [
                    'view' => 'maintenance.requests.view',
                    'create' => 'maintenance.requests.create',
                    'delete' => 'maintenance.requests.delete',
                    'view_trashed' => 'maintenance.requests.view_trashed',
                    'restore' => 'maintenance.requests.restore',
                ],
                'active' => ['admin.maintenance.requests.*'],
                'children' => [],
            ],
            [
                'label' => 'maintenance_orders',
                'title' => 'Maintenance Work Orders',
                'icon' => 'clipboard-check',
                'route' => 'admin.maintenance.orders.index',
                'permission' => 'maintenance.orders.view',
                'keywords' => ['preventive', 'corrective', 'external maintenance', 'أمر صيانة'],
                'actions' => [
                    'view' => 'maintenance.orders.view',
                    'create' => 'maintenance.orders.create',
                    'approve' => 'maintenance.orders.approve',
                    'start' => 'maintenance.orders.start',
                    'complete' => 'maintenance.orders.complete',
                    'close' => 'maintenance.orders.close',
                    'print' => 'maintenance.orders.print',
                    'export' => 'maintenance.orders.export',
                ],
                'active' => ['admin.maintenance.orders.*'],
                'children' => [],
            ],
            [
                'label' => 'maintenance_material_requests',
                'title' => 'Maintenance Materials',
                'icon' => 'oil-can',
                'route' => 'admin.maintenance.material-requests.index',
                'permission' => 'maintenance.material_requests.view',
                'keywords' => ['spare parts', 'oil', 'inventory issue', 'قطع غيار', 'زيوت'],
                'actions' => [
                    'view' => 'maintenance.material_requests.view',
                    'create' => 'maintenance.material_requests.create',
                    'approve' => 'maintenance.material_requests.approve',
                    'issue' => 'maintenance.material_requests.issue',
                    'return' => 'maintenance.material_requests.return',
                ],
                'active' => ['admin.maintenance.material-requests.*'],
                'children' => [],
            ],
            [
                'label' => 'maintenance_expenses',
                'title' => 'Maintenance Expenses',
                'icon' => 'money-check-alt',
                'route' => 'admin.maintenance.expenses.index',
                'permission' => 'maintenance.expenses.view',
                'keywords' => ['maintenance expense', 'approval', 'payment', 'مصروفات الصيانة'],
                'actions' => [
                    'view' => 'maintenance.expenses.view',
                    'create' => 'maintenance.expenses.create',
                    'approve' => 'maintenance.expenses.approve',
                    'pay' => 'maintenance.expenses.pay',
                    'reverse' => 'maintenance.expenses.reverse',
                ],
                'active' => ['admin.maintenance.expenses.*'],
                'children' => [],
            ],
        ],
    ],
];
