<?php

return [
    [
        'label' => 'maintenance',
        'title' => 'Maintenance',
        'icon' => 'tools',
        'route' => null,
        'permission' => null,
        'keywords' => ['maintenance', 'breakdown', 'preventive', 'الصيانة', 'الأعطال'],
        'active' => ['admin.maintenance.*'],
        'children' => [
            [
                'label' => 'maintenance_plans',
                'title' => 'Preventive Maintenance Plans',
                'icon' => 'calendar-check',
                'route' => 'admin.maintenance.plans.index',
                'permission' => 'maintenance.plans.view',
                'keywords' => ['preventive maintenance plans', 'meters', 'due maintenance', 'خطط الصيانة', 'العدادات'],
                'actions' => [
                    'view' => 'maintenance.plans.view',
                    'create' => 'maintenance.plans.create',
                    'approve' => 'maintenance.plans.approve',
                    'generate' => 'maintenance.plans.generate',
                    'execute' => 'maintenance.plans.execute',
                    'readings' => 'maintenance.plans.readings',
                ],
                'active' => ['admin.maintenance.plans.*'],
                'children' => [],
            ],
            [
                'label' => 'maintenance_requests',
                'title' => 'Breakdown Reports',
                'icon' => 'exclamation-triangle',
                'route' => 'admin.maintenance.requests.index',
                'permission' => 'maintenance.requests.view',
                'keywords' => ['breakdown reports', 'إبلاغ عطل'],
                'actions' => [
                    'view' => 'maintenance.requests.view',
                    'create' => 'maintenance.requests.create',
                    'edit' => 'maintenance.requests.edit',
                    'delete' => 'maintenance.requests.delete',
                    'view_trashed' => 'maintenance.requests.view_trashed',
                    'restore' => 'maintenance.requests.restore',
                ],
                'active' => ['admin.maintenance.requests.*'],
                'children' => [],
            ],
            [
                'label' => 'maintenance_orders',
                'title' => 'Maintenance Work Orders',
                'icon' => 'clipboard-check',
                'route' => 'admin.maintenance.orders.index',
                'permission' => 'maintenance.orders.view',
                'keywords' => ['preventive', 'corrective', 'external maintenance', 'أمر صيانة'],
                'actions' => [
                    'view' => 'maintenance.orders.view',
                    'create' => 'maintenance.orders.create',
                    'edit' => 'maintenance.orders.edit',
                    'delete' => 'maintenance.orders.delete',
                    'view_trashed' => 'maintenance.orders.view_trashed',
                    'restore' => 'maintenance.orders.restore',
                    'approve' => 'maintenance.orders.approve',
                    'start' => 'maintenance.orders.start',
                    'pause' => 'maintenance.orders.pause',
                    'external' => 'maintenance.orders.external',
                    'complete' => 'maintenance.orders.complete',
                    'close' => 'maintenance.orders.close',
                    'print' => 'maintenance.orders.print',
                    'export' => 'maintenance.orders.export',
                ],
                'active' => ['admin.maintenance.orders.*'],
                'children' => [],
            ],
            [
                'label' => 'maintenance_material_requests',
                'title' => 'Maintenance Materials',
                'icon' => 'oil-can',
                'route' => 'admin.maintenance.material-requests.index',
                'permission' => 'maintenance.material_requests.view',
                'keywords' => ['spare parts', 'oil', 'inventory issue', 'قطع غيار', 'زيوت'],
                'actions' => [
                    'view' => 'maintenance.material_requests.view',
                    'create' => 'maintenance.material_requests.create',
                    'edit' => 'maintenance.material_requests.edit',
                    'delete' => 'maintenance.material_requests.delete',
                    'view_trashed' => 'maintenance.material_requests.view_trashed',
                    'restore' => 'maintenance.material_requests.restore',
                    'approve' => 'maintenance.material_requests.approve',
                    'issue' => 'maintenance.material_requests.issue',
                    'return' => 'maintenance.material_requests.return',
                ],
                'active' => ['admin.maintenance.material-requests.*'],
                'children' => [],
            ],
            [
                'label' => 'maintenance_expenses',
                'title' => 'Maintenance Expenses',
                'icon' => 'money-check-alt',
                'route' => 'admin.maintenance.expenses.index',
                'permission' => 'maintenance.expenses.view',
                'keywords' => ['maintenance expense', 'approval', 'payment', 'مصروفات الصيانة'],
                'actions' => [
                    'view' => 'maintenance.expenses.view',
                    'create' => 'maintenance.expenses.create',
                    'edit' => 'maintenance.expenses.edit',
                    'delete' => 'maintenance.expenses.delete',
                    'view_trashed' => 'maintenance.expenses.view_trashed',
                    'restore' => 'maintenance.expenses.restore',
                    'approve' => 'maintenance.expenses.approve',
                    'pay' => 'maintenance.expenses.pay',
                    'reverse' => 'maintenance.expenses.reverse',
                ],
                'active' => ['admin.maintenance.expenses.*'],
                'children' => [],
            ],
            [
                'label' => 'maintenance_reports',
                'title' => 'Maintenance Reports',
                'icon' => 'chart-line',
                'route' => 'admin.maintenance.reports.index',
                'permission' => 'maintenance.reports.view',
                'keywords' => ['maintenance reports', 'downtime', 'material usage', 'تقارير الصيانة', 'وقت التوقف'],
                'actions' => [
                    'view' => 'maintenance.reports.view',
                    'export' => 'maintenance.reports.export',
                    'financial' => 'maintenance.reports.financial',
                ],
                'active' => ['admin.maintenance.reports.*'],
                'children' => [],
            ],
        ],
    ],
];
