<?php

return [
    [
        'label' => 'production',
        'title' => 'Production',
        'icon' => 'industry',
        'route' => null,
        'permission' => null,
        'keywords' => ['planning', 'production', 'identifiers', 'identifier types', 'التخطيط', 'الإنتاج', 'المعرفات', 'أنواع المعرفات'],
        'active' => [
            'admin.production.*',
        ],
        'children' => [
            [
                'label' => 'production_resources',
                'title' => 'Production Resources',
                'icon' => 'cogs',
                'route' => 'admin.production.resources.index',
                'permission' => 'production.resources.view',
                'keywords' => ['machines', 'molds', 'shifts', 'compatibility'],
                'actions' => ['view' => 'production.resources.view', 'manage' => 'production.resources.manage'],
                'active' => ['admin.production.resources.*'],
                'children' => [],
            ],
            [
                'label' => 'production_work_orders',
                'title' => 'Production Work Orders',
                'icon' => 'clipboard-list',
                'route' => 'admin.production.work-orders.index',
                'permission' => 'production.orders.view',
                'keywords' => ['production orders', 'work orders', 'make to order', 'make to stock'],
                'actions' => [
                    'view' => 'production.orders.view',
                    'plan' => 'production.orders.plan',
                    'release' => 'production.orders.release',
                    'short_close' => 'production.orders.short_close',
                    'print' => 'production.orders.print',
                ],
                'active' => ['admin.production.work-orders.*'],
                'children' => [],
            ],
            [
                'label' => 'production_runs',
                'title' => 'Production Runs',
                'icon' => 'play-circle',
                'route' => 'admin.production.runs.index',
                'permission' => 'production.runs.view',
                'keywords' => ['production runs', 'machine scheduling', 'mold scheduling', 'materials', 'quality'],
                'actions' => [
                    'view' => 'production.runs.view',
                    'plan' => 'production.runs.plan',
                    'reserve' => 'production.runs.reserve',
                    'issue' => 'production.runs.issue',
                    'setup' => 'production.runs.setup',
                    'progress' => 'production.runs.progress',
                    'qc' => 'production.runs.qc',
                    'account_materials' => 'production.runs.account_materials',
                    'receive' => 'production.runs.receive',
                    'complete' => 'production.runs.complete',
                    'cancel' => 'production.runs.cancel',
                    'print' => 'production.runs.print',
                ],
                'active' => ['admin.production.runs.*'],
                'children' => [],
            ],
            [
                'label' => 'production_operational_reports',
                'title' => 'Production Operational Reports',
                'icon' => 'chart-line',
                'route' => 'admin.production.reports.index',
                'permission' => 'production.reports.operational',
                'keywords' => ['production reports', 'performance', 'material variance', 'wip'],
                'actions' => [
                    'view' => 'production.reports.operational',
                    'financial' => 'production.reports.financial',
                    'export' => 'production.reports.export',
                ],
                'active' => ['admin.production.reports.*'],
                'children' => [],
            ],
            [
                'label' => 'production_identifier_types',
                'title' => 'Identifier Types',
                'icon' => 'tags',
                'route' => 'admin.production.identifier-types.index',
                'permission' => 'production.identifier_types.view',
                'keywords' => ['identifier types', 'identifier type', 'أنواع المعرفات', 'نوع معرف'],
                'actions' => [
                    'view' => 'production.identifier_types.view',
                    'create' => 'production.identifier_types.create',
                    'clone' => 'production.identifier_types.clone',
                    'edit' => 'production.identifier_types.edit',
                    'delete' => 'production.identifier_types.delete',
                    'view_trashed' => 'production.identifier_types.view_trashed',
                    'restore' => 'production.identifier_types.restore',
                    'document_number_control' => 'production.identifier_types.document_number.control',
                    'document_number_settings_update' => 'production.identifier_types.document_number_settings.update',
                ],
                'active' => [
                    'admin.production.identifier-types.*',
                ],
                'children' => [],
            ],
            [
                'label' => 'production_identifiers',
                'title' => 'Identifiers',
                'icon' => 'sitemap',
                'route' => 'admin.production.identifiers.index',
                'permission' => 'production.identifiers.view',
                'keywords' => ['identifiers', 'identifier tree', 'المعرفات', 'معرف'],
                'actions' => [
                    'view' => 'production.identifiers.view',
                    'create' => 'production.identifiers.create',
                    'clone' => 'production.identifiers.clone',
                    'edit' => 'production.identifiers.edit',
                    'delete' => 'production.identifiers.delete',
                    'view_trashed' => 'production.identifiers.view_trashed',
                    'restore' => 'production.identifiers.restore',
                    'document_number_control' => 'production.identifiers.document_number.control',
                    'document_number_settings_update' => 'production.identifiers.document_number_settings.update',
                ],
                'active' => [
                    'admin.production.identifiers.*',
                ],
                'children' => [],
            ],
        ],
    ],
];
