<?php

return [
    [
        'label' => 'production',
        'title' => 'Production',
        'icon' => 'industry',
        'route' => null,
        'permission' => null,
        'keywords' => ['planning', 'production', 'التخطيط', 'الإنتاج'],
        'active' => [
            'admin.production.*',
        ],
        'children' => [
            [
                'label' => 'production_stages',
                'title' => 'Production Stages',
                'icon' => 'list-ol',
                'route' => 'admin.production.stages.index',
                'permission' => 'production.stages.view',
                'keywords' => ['production stages', 'routing', 'مراحل الإنتاج'],
                'actions' => [
                    'view' => 'production.stages.view',
                    'create' => 'production.stages.create',
                    'edit' => 'production.stages.edit',
                    'delete' => 'production.stages.delete',
                    'view_trashed' => 'production.stages.view_trashed',
                    'restore' => 'production.stages.restore',
                ],
                'active' => ['admin.production.stages.*'],
                'children' => [],
            ],
            [
                'label' => 'product_production_stages',
                'title' => 'Product Production Stages',
                'icon' => 'route',
                'route' => 'admin.production.product-stages.index',
                'permission' => 'production.product_stages.view',
                'keywords' => ['product routing', 'product stages', 'مراحل إنتاج الأصناف'],
                'actions' => [
                    'view' => 'production.product_stages.view',
                    'manage' => 'production.product_stages.manage',
                ],
                'active' => ['admin.production.product-stages.*'],
                'children' => [],
            ],
            [
                'label' => 'production_work_orders',
                'title' => 'Production Work Orders',
                'icon' => 'clipboard-list',
                'route' => 'admin.production.work-orders.index',
                'permission' => 'production.orders.view',
                'keywords' => ['production orders', 'work orders', 'sales driven production', 'أوامر الإنتاج', 'أوامر التشغيل'],
                'actions' => [
                    'view' => 'production.orders.view',
                    'create' => 'production.orders.create',
                    'edit' => 'production.orders.edit',
                    'clone' => 'production.orders.clone',
                    'delete' => 'production.orders.delete',
                    'view_trashed' => 'production.orders.view_trashed',
                    'restore' => 'production.orders.restore',
                    'plan' => 'production.orders.plan',
                    'release' => 'production.orders.release',
                    'short_close' => 'production.orders.short_close',
                    'print' => 'production.orders.print',
                    'document_number_settings_update' => 'production.orders.document_number_settings.update',
                ],
                'active' => ['admin.production.work-orders.*'],
                'children' => [],
            ],
            [
                'label' => 'production_runs',
                'title' => 'Production Runs',
                'icon' => 'play-circle',
                'route' => 'admin.production.runs.index',
                'permission' => 'production.runs.view',
                'keywords' => ['production runs', 'machine scheduling', 'mold scheduling', 'materials', 'quality'],
                'actions' => [
                    'view' => 'production.runs.view',
                    'plan' => 'production.runs.plan',
                    'edit' => 'production.runs.edit',
                    'clone' => 'production.runs.clone',
                    'delete' => 'production.runs.delete',
                    'view_trashed' => 'production.runs.view_trashed',
                    'restore' => 'production.runs.restore',
                    'reserve' => 'production.runs.reserve',
                    'issue' => 'production.runs.issue',
                    'setup' => 'production.runs.setup',
                    'progress' => 'production.runs.progress',
                    'labor' => 'production.runs.labor',
                    'qc' => 'production.runs.qc',
                    'account_materials' => 'production.runs.account_materials',
                    'receive' => 'production.runs.receive',
                    'complete' => 'production.runs.complete',
                    'cancel' => 'production.runs.cancel',
                    'print' => 'production.runs.print',
                ],
                'active' => ['admin.production.runs.*'],
                'children' => [],
            ],
            [
                'label' => 'production_material_requests',
                'title' => 'Production Material Requests',
                'icon' => 'dolly',
                'route' => 'admin.production.material-requests.index',
                'permission' => 'production.material_requests.view',
                'keywords' => ['materials request', 'warehouse issue', 'طلب خامات'],
                'actions' => [
                    'view' => 'production.material_requests.view',
                    'create' => 'production.material_requests.create',
                    'edit' => 'production.material_requests.edit',
                    'clone' => 'production.material_requests.clone',
                    'delete' => 'production.material_requests.delete',
                    'view_trashed' => 'production.material_requests.view_trashed',
                    'restore' => 'production.material_requests.restore',
                    'approve' => 'production.material_requests.approve',
                    'issue' => 'production.material_requests.issue',
                    'print' => 'production.material_requests.print',
                ],
                'active' => ['admin.production.material-requests.*'],
                'children' => [],
            ],
            [
                'label' => 'production_expenses',
                'title' => 'Production Expense Requests',
                'icon' => 'money-bill-wave',
                'route' => 'admin.production.expenses.index',
                'permission' => 'production.expenses.view',
                'keywords' => ['expense request', 'payment voucher', 'مصروفات تشغيل'],
                'actions' => [
                    'view' => 'production.expenses.view',
                    'create' => 'production.expenses.create',
                    'edit' => 'production.expenses.edit',
                    'clone' => 'production.expenses.clone',
                    'delete' => 'production.expenses.delete',
                    'view_trashed' => 'production.expenses.view_trashed',
                    'restore' => 'production.expenses.restore',
                    'approve' => 'production.expenses.approve',
                    'pay' => 'production.expenses.pay',
                    'reverse' => 'production.expenses.reverse',
                    'print' => 'production.expenses.print',
                ],
                'active' => ['admin.production.expenses.*'],
                'children' => [],
            ],
            [
                'label' => 'production_operational_reports',
                'title' => 'Production Operational Reports',
                'icon' => 'chart-line',
                'route' => null,
                'permission' => 'production.reports.operational',
                'keywords' => ['production reports', 'performance', 'material variance', 'wip'],
                'actions' => [
                    'view' => 'production.reports.operational',
                    'financial' => 'production.reports.financial',
                    'export' => 'production.reports.export',
                ],
                'active' => ['admin.production.reports.*'],
                'children' => [
                    [
                        'label' => 'production_reports_overview',
                        'title' => 'Production Reports Overview',
                        'icon' => 'chart-pie',
                        'route' => 'admin.production.reports.index',
                        'permission' => 'production.reports.operational',
                        'keywords' => ['production overview', 'production kpis', 'ملخص الإنتاج'],
                        'actions' => [
                            'view' => 'production.reports.operational',
                            'financial' => 'production.reports.financial',
                            'export' => 'production.reports.export',
                        ],
                        'active' => ['admin.production.reports.index'],
                        'children' => [],
                    ],
                    [
                        'label' => 'production_reports_orders',
                        'title' => 'Production Order Status Report',
                        'icon' => 'clipboard-list',
                        'route' => 'admin.production.reports.orders',
                        'permission' => 'production.reports.operational',
                        'keywords' => ['production order report', 'موقف أوامر الإنتاج'],
                        'actions' => [],
                        'active' => ['admin.production.reports.orders'],
                        'children' => [],
                    ],
                    [
                        'label' => 'production_reports_runs',
                        'title' => 'Production Run Performance Report',
                        'icon' => 'stopwatch',
                        'route' => 'admin.production.reports.runs',
                        'permission' => 'production.reports.operational',
                        'keywords' => ['run performance', 'وردية', 'التشغيلات'],
                        'actions' => [],
                        'active' => ['admin.production.reports.runs'],
                        'children' => [],
                    ],
                    [
                        'label' => 'production_reports_materials',
                        'title' => 'Production Material Reconciliation Report',
                        'icon' => 'boxes',
                        'route' => 'admin.production.reports.materials',
                        'permission' => 'production.reports.operational',
                        'keywords' => ['materials', 'consumption', 'variance', 'الخامات'],
                        'actions' => [],
                        'active' => ['admin.production.reports.materials'],
                        'children' => [],
                    ],
                ],
            ],
        ],
    ],
];
