<?php

$procurementReport = static function (string $label, string $title, string $reportType, string $icon = 'chart-bar'): array {
    $financialAnalysisTypes = [
        'purchases_by_supplier',
        'purchases_by_product',
        'purchases_by_category',
        'purchases_by_warehouse',
        'purchases_by_period',
        'price_history',
        'outstanding_supplier_invoices',
        'due_supplier_installments',
        'supplier_aging',
        'upcoming_supplier_payments',
    ];

    return [
        'label' => $label,
        'title' => $title,
        'icon' => $icon,
        'route' => 'admin.purchases.procurement-cycle-report.index',
        'route_params' => ['report_type' => $reportType],
        'permission' => 'reports.purchases.view',
        'subgroup' => in_array($reportType, $financialAnalysisTypes, true) ? 'financial_analysis_reports' : 'purchase_reports',
        'actions' => ['view' => 'reports.purchases.view', 'export' => 'reports.purchases.export'],
        'active' => ['admin.purchases.procurement-cycle-report.*'],
        'children' => [],
    ];
};

return [
    [
        'label' => 'purchases',
        'title' => 'Purchases',
        'icon' => 'shopping-bag',
        'route' => null,
        'permission' => null,
        'keywords' => ['purchases', 'suppliers', 'procurement', 'المشتريات', 'الموردين'],
        'active' => ['admin.purchases.*'],
        'children' => [
            [
                'label' => 'suppliers', 'title' => 'Suppliers', 'icon' => 'truck',
                'route' => 'admin.purchases.suppliers.index', 'permission' => 'suppliers.view',
                'keywords' => ['suppliers', 'vendors', 'الموردين'],
                'actions' => [
                    'view' => 'suppliers.view', 'create' => 'suppliers.create', 'clone' => 'suppliers.clone',
                    'edit' => 'suppliers.edit', 'delete' => 'suppliers.delete',
                    'view_trashed' => 'suppliers.view_trashed', 'restore' => 'suppliers.restore',
                    'document_number_control' => 'suppliers.document_number.control',
                    'document_number_settings_update' => 'suppliers.document_number_settings.update',
                ],
                'active' => ['admin.purchases.suppliers.*'], 'children' => [],
            ],
            [
                'label' => 'purchase_requisitions', 'title' => 'Purchase Requisitions', 'icon' => 'clipboard-list',
                'route' => 'admin.purchases.purchase-requisitions.index', 'permission' => 'purchases.purchase_requisitions.view',
                'keywords' => ['purchase requests', 'purchase requisitions', 'طلبات الشراء'],
                'actions' => [
                    'view' => 'purchases.purchase_requisitions.view', 'create' => 'purchases.purchase_requisitions.create',
                    'edit' => 'purchases.purchase_requisitions.edit', 'delete' => 'purchases.purchase_requisitions.delete',
                    'view_trashed' => 'purchases.purchase_requisitions.view_trashed', 'restore' => 'purchases.purchase_requisitions.restore',
                    'submit' => 'purchases.purchase_requisitions.submit', 'approve' => 'purchases.purchase_requisition_approvals.approve',
                    'reject' => 'purchases.purchase_requisition_approvals.reject', 'cancel' => 'purchases.purchase_requisitions.cancel',
                    'close' => 'purchases.purchase_requisitions.close', 'print' => 'purchases.purchase_requisitions.print',
                ],
                'active' => ['admin.purchases.purchase-requisitions.*'], 'children' => [],
            ],
            [
                'label' => 'supplier_quotations', 'title' => 'Supplier Quotations', 'icon' => 'file-signature',
                'route' => 'admin.purchases.supplier-quotation-entry.index', 'permission' => 'purchases.supplier_quotation_entry.view',
                'keywords' => ['supplier quotations', 'supplier offers', 'عروض أسعار الموردين'],
                'actions' => [
                    'view' => 'purchases.supplier_quotation_entry.view', 'create' => 'purchases.supplier_quotation_entry.create',
                    'edit' => 'purchases.supplier_quotation_entry.edit', 'delete' => 'purchases.supplier_quotation_entry.delete',
                    'view_trashed' => 'purchases.supplier_quotation_entry.view_trashed', 'restore' => 'purchases.supplier_quotation_entry.restore',
                    'print' => 'purchases.supplier_quotation_entry.print', 'view_prices' => 'purchases.prices.view',
                ],
                'active' => ['admin.purchases.supplier-quotation-entry.*'], 'children' => [],
            ],
            [
                'label' => 'purchase_orders', 'title' => 'Purchase Orders', 'icon' => 'file-contract',
                'route' => 'admin.purchases.purchase-orders.index', 'permission' => 'purchase_orders.view', 'phase_modes' => ['expanded'],
                'keywords' => ['purchase orders', 'procurement', 'أوامر الشراء'],
                'actions' => [
                    'view' => 'purchase_orders.view', 'create' => 'purchase_orders.create', 'edit' => 'purchase_orders.edit',
                    'delete' => 'purchase_orders.delete', 'view_trashed' => 'purchase_orders.view_trashed', 'restore' => 'purchase_orders.restore',
                    'submit' => 'purchase_orders.submit', 'approve' => 'purchase_orders.approve', 'reject' => 'purchase_orders.reject',
                    'send' => 'purchase_orders.send', 'close' => 'purchase_orders.close', 'cancel' => 'purchase_orders.cancel',
                    'print' => 'purchase_orders.print', 'view_prices' => 'purchases.prices.view',
                    'direct_procurement_override' => 'purchases.direct_procurement.override',
                    'document_number_control' => 'purchase_orders.document_number.control',
                    'document_number_settings_update' => 'purchase_orders.document_number_settings.update',
                ],
                'active' => ['admin.purchases.purchase-orders.*'], 'children' => [],
            ],
            [
                'label' => 'supply_orders', 'title' => 'Supply Orders', 'icon' => 'truck-loading',
                'route' => 'admin.purchases.supply-orders.index', 'permission' => 'purchases.supply_orders.view',
                'keywords' => ['supply orders', 'supplier dispatch', 'أوامر التوريد'],
                'actions' => [
                    'view' => 'purchases.supply_orders.view', 'create' => 'purchases.supply_orders.create',
                    'edit' => 'purchases.supply_orders.edit', 'delete' => 'purchases.supply_orders.delete',
                    'issue' => 'purchases.supply_orders.issue', 'cancel' => 'purchases.supply_orders.cancel',
                    'print' => 'purchases.supply_orders.print',
                ],
                'active' => ['admin.purchases.supply-orders.*'], 'children' => [],
            ],
            [
                'label' => 'purchase_inspections', 'title' => 'Purchase Inspections', 'icon' => 'clipboard-check',
                'route' => 'admin.purchases.goods-receipt-inspection.index', 'permission' => 'purchases.goods_receipt_inspection.view',
                'keywords' => ['purchase inspection', 'quality inspection', 'فحص المشتريات', 'الجودة'],
                'actions' => [
                    'view' => 'purchases.goods_receipt_inspection.view',
                    'create' => 'purchases.goods_receipt_inspection.create',
                    'print' => 'purchases.goods_receipt_inspection.print',
                ],
                'active' => ['admin.purchases.goods-receipt-inspection.*'], 'children' => [],
            ],
            [
                'label' => 'goods_receipts', 'title' => 'Goods Receipt Notes', 'icon' => 'dolly-flatbed',
                'route' => 'admin.purchases.goods-receipt-notes.index', 'permission' => 'purchases.goods_receipt_notes.view',
                'keywords' => ['goods receipts', 'warehouse receipt', 'أذون الاستلام', 'إذن استلام'],
                'actions' => [
                    'view' => 'purchases.goods_receipt_notes.view', 'create' => 'purchases.goods_receipt_notes.create',
                    'edit' => 'purchases.goods_receipt_notes.edit', 'delete' => 'purchases.goods_receipt_notes.delete',
                    'view_trashed' => 'purchases.goods_receipt_notes.view_trashed', 'restore' => 'purchases.goods_receipt_notes.restore',
                    'post' => 'purchases.goods_receipt_notes.post', 'reverse' => 'purchases.goods_receipt_notes.reverse',
                    'print' => 'purchases.goods_receipt_notes.print',
                ],
                'active' => ['admin.purchases.goods-receipt-notes.*'], 'children' => [],
            ],
            [
                'label' => 'purchase_invoices', 'title' => 'Purchase Invoices', 'icon' => 'file-invoice-dollar',
                'route' => 'admin.purchases.purchase-invoices.index', 'permission' => 'purchase_invoices.view',
                'keywords' => ['purchase invoices', 'supplier invoices', 'فواتير المشتريات'],
                'actions' => [
                    'view' => 'purchase_invoices.view', 'create' => 'purchase_invoices.create', 'clone' => 'purchase_invoices.clone',
                    'edit' => 'purchase_invoices.edit', 'delete' => 'purchase_invoices.delete',
                    'view_trashed' => 'purchase_invoices.view_trashed', 'restore' => 'purchase_invoices.restore',
                    'approve' => 'purchase_invoices.approve', 'close' => 'purchase_invoices.close',
                    'cancel' => 'purchase_invoices.cancel', 'reverse' => 'purchase_invoices.reverse', 'print' => 'purchase_invoices.print',
                    'direct_procurement_override' => 'purchases.direct_procurement.override',
                    'view_prices' => 'purchases.prices.view', 'document_number_control' => 'purchase_invoices.document_number.control',
                    'document_number_settings_update' => 'purchase_invoices.document_number_settings.update',
                ],
                'active' => ['admin.purchases.purchase-invoices.*'], 'children' => [],
            ],
            [
                'label' => 'purchase_returns', 'title' => 'Purchase Returns', 'icon' => 'undo-alt',
                'route' => 'admin.purchases.purchase-returns.index', 'permission' => 'purchases.purchase_returns.view',
                'keywords' => ['purchase returns', 'supplier returns', 'مرتجعات المشتريات'],
                'actions' => [
                    'view' => 'purchases.purchase_returns.view', 'create' => 'purchases.purchase_returns.create',
                    'edit' => 'purchases.purchase_returns.edit', 'delete' => 'purchases.purchase_returns.delete',
                    'view_trashed' => 'purchases.purchase_returns.view_trashed', 'restore' => 'purchases.purchase_returns.restore',
                    'post' => 'purchases.purchase_returns.post', 'reverse' => 'purchases.purchase_returns.reverse',
                    'print' => 'purchases.purchase_returns.print',
                ],
                'active' => ['admin.purchases.purchase-returns.*'], 'children' => [],
            ],
            [
                'label' => 'supplier_payments', 'title' => 'Supplier Payments', 'icon' => 'money-check-alt',
                'route' => 'admin.purchases.supplier-payments.index', 'permission' => 'supplier_payments.view',
                'keywords' => ['supplier payments', 'cash bank cheque', 'مدفوعات الموردين'],
                'actions' => [
                    'view' => 'supplier_payments.view', 'create' => 'supplier_payments.create',
                    'approve' => 'supplier_payments.approve', 'cancel' => 'supplier_payments.cancel', 'print' => 'supplier_payments.print',
                ],
                'active' => ['admin.purchases.supplier-payments.*'], 'children' => [],
            ],
            [
                'label' => 'purchase_reports', 'title' => 'Purchase Reports', 'icon' => 'chart-pie',
                'route' => null, 'permission' => null,
                'active' => ['admin.purchases.procurement-cycle-report.*', 'admin.reports.suppliers.*', 'admin.accounting.reports.supplier-statement*'],
                'children' => [
                    [
                        'label' => 'supplier_statement', 'title' => 'Supplier Statement', 'icon' => 'file-invoice',
                        'route' => 'admin.accounting.reports.supplier-statement', 'permission' => 'reports.supplier_statement.view',
                        'keywords' => ['supplier statement', 'supplier ledger', 'كشف حساب مورد'],
                        'actions' => ['view' => 'reports.supplier_statement.view', 'export' => 'reports.supplier_statement.export'],
                        'active' => ['admin.accounting.reports.supplier-statement'], 'children' => [],
                    ],
                    [
                        'label' => 'suppliers_report', 'title' => 'Suppliers Report', 'icon' => 'address-book',
                        'route' => 'admin.reports.suppliers.index', 'permission' => 'reports.suppliers.view',
                        'actions' => ['view' => 'reports.suppliers.view', 'export' => 'reports.suppliers.export', 'pdf' => 'reports.suppliers.pdf'],
                        'active' => ['admin.reports.suppliers.*'], 'children' => [],
                    ],
                    $procurementReport('report_purchase_ledger', 'Purchase Ledger', 'purchase_ledger', 'book'),
                    $procurementReport('report_open_requirements', 'Open Purchase Requirements', 'open_requirements', 'tasks'),
                    $procurementReport('report_purchase_requests', 'Purchase Requests Report', 'purchase_requests'),
                    $procurementReport('report_pending_purchase_requests', 'Pending Purchase Requests', 'pending_purchase_requests'),
                    $procurementReport('report_requested_vs_ordered', 'Requested vs Ordered', 'requested_vs_ordered'),
                    $procurementReport('report_rfq_quotation_status', 'RFQ / Quotation Status', 'rfq_quotation_status'),
                    $procurementReport('report_pending_sourcing_actions', 'Pending RFQ / Quotation / Selection Actions', 'pending_sourcing_actions'),
                    $procurementReport('report_open_purchase_orders', 'Open Purchase Orders', 'open_purchase_orders'),
                    $procurementReport('report_purchase_order_status', 'Purchase Order Status', 'purchase_order_status'),
                    $procurementReport('report_partially_received_orders', 'Partially Received Orders', 'partially_received_orders'),
                    $procurementReport('report_overdue_po_deliveries', 'Overdue PO Deliveries', 'overdue_po_deliveries'),
                    $procurementReport('report_supply_orders', 'Supply Orders Report', 'supply_orders'),
                    $procurementReport('report_delivery_schedule', 'Delivery Schedule', 'delivery_schedule'),
                    $procurementReport('report_ordered_vs_received', 'Ordered vs Received', 'ordered_vs_received'),
                    $procurementReport('report_supplier_deliveries', 'Supplier Deliveries', 'supplier_deliveries'),
                    $procurementReport('report_receipt_quality_status', 'Purchase Inspection Results', 'receipt_quality_status'),
                    $procurementReport('report_incoming_qc_pending', 'Accepted Inspections Pending Receipt', 'incoming_qc_pending'),
                    $procurementReport('report_qc_rejection', 'Purchase Inspection Rejections', 'qc_rejection'),
                    $procurementReport('report_purchase_receipts', 'Purchase Receipts', 'purchase_receipts'),
                    $procurementReport('report_purchase_invoices', 'Purchase Invoices Report', 'purchase_invoices'),
                    $procurementReport('report_received_vs_invoiced', 'Received vs Invoiced', 'received_vs_invoiced'),
                    $procurementReport('report_purchase_returns', 'Purchase Returns Report', 'returns'),
                    $procurementReport('report_purchases_by_supplier', 'Purchases by Supplier', 'purchases_by_supplier'),
                    $procurementReport('report_purchases_by_item', 'Purchases by Item', 'purchases_by_product'),
                    $procurementReport('report_purchases_by_category', 'Purchases by Category', 'purchases_by_category'),
                    $procurementReport('report_purchases_by_warehouse', 'Purchases by Warehouse', 'purchases_by_warehouse'),
                    $procurementReport('report_purchases_by_period', 'Purchases by Period', 'purchases_by_period'),
                    $procurementReport('report_price_history', 'Supplier / Item Price History', 'price_history'),
                    $procurementReport('report_supplier_outstanding', 'Supplier Outstanding', 'outstanding_supplier_invoices'),
                    $procurementReport('report_due_supplier_installments', 'Due Supplier Installments', 'due_supplier_installments'),
                    $procurementReport('report_supplier_aging', 'Supplier Aging', 'supplier_aging'),
                    $procurementReport('report_upcoming_supplier_payments', 'Upcoming Supplier Payments', 'upcoming_supplier_payments'),
                    $procurementReport('report_grni', 'Goods Received Not Invoiced', 'goods_received_not_invoiced'),
                    $procurementReport('report_production_analysis', 'Production-linked Procurement Analysis', 'production_analysis'),
                ],
            ],
        ],
    ],
];
