<?php

return [
    [
        'label' => 'purchases',
        'title' => 'Purchases',
        'icon' => 'shopping-bag',
        'route' => null,
        'permission' => null,
        'keywords' => ['purchases', 'suppliers', 'procurement', 'المشتريات', 'الموردين'],
        'active' => [
            'admin.purchases.*',
        ],
        'children' => [
            [
                'label' => 'suppliers',
                'title' => 'Suppliers',
                'icon' => 'truck',
                'route' => 'admin.purchases.suppliers.index',
                'permission' => 'suppliers.view',
                'keywords' => ['suppliers', 'supplier', 'vendors', 'الموردين', 'مورد'],
                'actions' => [
                    'view' => 'suppliers.view',
                    'create' => 'suppliers.create',
                    'clone' => 'suppliers.clone',
                    'edit' => 'suppliers.edit',
                    'delete' => 'suppliers.delete',
                    'view_trashed' => 'suppliers.view_trashed',
                    'restore' => 'suppliers.restore',
                    'document_number_control' => 'suppliers.document_number.control',
                    'document_number_settings_update' => 'suppliers.document_number_settings.update',
                ],
                'active' => [
                    'admin.purchases.suppliers.*',
                ],
                'children' => [],
            ],
            [
                'label' => 'purchase_orders',
                'title' => 'Purchase Orders',
                'icon' => 'clipboard-list',
                'route' => 'admin.purchases.purchase-orders.index',
                'permission' => 'purchase_orders.view',
                'phase_modes' => ['expanded'],
                'keywords' => ['purchase orders', 'supplier orders', 'procurement', 'أوامر الشراء', 'امر شراء'],
                'actions' => [
                    'view' => 'purchase_orders.view',
                    'create' => 'purchase_orders.create',
                    'edit' => 'purchase_orders.edit',
                    'delete' => 'purchase_orders.delete',
                    'view_trashed' => 'purchase_orders.view_trashed',
                    'restore' => 'purchase_orders.restore',
                    'approve' => 'purchase_orders.approve',
                    'close' => 'purchase_orders.close',
                    'cancel' => 'purchase_orders.cancel',
                    'print' => 'purchase_orders.print',
                    'view_prices' => 'purchases.prices.view',
                    'direct_procurement_override' => 'purchases.direct_procurement.override',
                    'document_number_control' => 'purchase_orders.document_number.control',
                    'document_number_settings_update' => 'purchase_orders.document_number_settings.update',
                ],
                'active' => [
                    'admin.purchases.purchase-orders.*',
                ],
                'children' => [],
            ],
            [
                'label' => 'purchase_invoices',
                'title' => 'Purchase Invoices',
                'icon' => 'file-invoice-dollar',
                'route' => 'admin.purchases.purchase-invoices.index',
                'permission' => 'purchase_invoices.view',
                'keywords' => ['purchase invoices', 'supplier invoices', 'purchases', 'فواتير المشتريات', 'فاتورة مشتريات'],
                'actions' => [
                    'view' => 'purchase_invoices.view',
                    'create' => 'purchase_invoices.create',
                    'clone' => 'purchase_invoices.clone',
                    'edit' => 'purchase_invoices.edit',
                    'delete' => 'purchase_invoices.delete',
                    'view_trashed' => 'purchase_invoices.view_trashed',
                    'restore' => 'purchase_invoices.restore',
                    'approve' => 'purchase_invoices.approve',
                    'close' => 'purchase_invoices.close',
                    'cancel' => 'purchase_invoices.cancel',
                    'print' => 'purchase_invoices.print',
                    'view_prices' => 'purchases.prices.view',
                    'direct_procurement_override' => 'purchases.direct_procurement.override',
                    'document_number_control' => 'purchase_invoices.document_number.control',
                    'document_number_settings_update' => 'purchase_invoices.document_number_settings.update',
                ],
                'active' => [
                    'admin.purchases.purchase-invoices.*',
                ],
                'children' => [],
            ],
        ],
    ],
];
