<?php

return [
    [
        'label' => 'quality',
        'title' => 'Quality',
        'icon' => 'check-circle',
        'route' => null,
        'permission' => null,
        'keywords' => ['quality', 'inspection', 'الجودة', 'الفحص'],
        'active' => [
            'admin.production.quality.*',
            'admin.production.reports.quality',
        ],
        'children' => [
            [
                'label' => 'production_quality',
                'title' => 'Production Quality Management',
                'icon' => 'check-double',
                'route' => 'admin.production.quality.index',
                'permission' => 'production.quality.view',
                'keywords' => ['quality management', 'stage inspection', 'جودة الإنتاج'],
                'actions' => [
                    'view' => 'production.quality.view',
                    'create' => 'production.quality.create',
                    'edit' => 'production.quality.edit',
                    'delete' => 'production.quality.delete',
                    'view_trashed' => 'production.quality.view_trashed',
                    'restore' => 'production.quality.restore',
                    'receive' => 'production.quality.receive',
                    'start' => 'production.quality.start',
                    'report' => 'production.quality.report',
                    'submit' => 'production.quality.submit',
                    'release_normal' => 'production.quality.release_normal',
                    'review' => 'production.quality.review',
                    'close' => 'production.quality.close',
                    'reinspect' => 'production.quality.reinspect',
                    'print' => 'production.quality.print',
                    'export' => 'production.quality.export',
                ],
                'active' => [
                    'admin.production.quality.index',
                    'admin.production.quality.create',
                    'admin.production.quality.show',
                    'admin.production.quality.edit',
                    'admin.production.quality.inspection.print',
                    'admin.production.quality.evidence',
                ],
                'children' => [],
            ],
            [
                'label' => 'production_quality_active',
                'title' => 'Open Quality Inspections',
                'icon' => 'hourglass-half',
                'route' => 'admin.production.quality.active',
                'permission' => 'production.quality.view',
                'keywords' => ['open inspections', 'active quality', 'فحوص مفتوحة'],
                'actions' => [],
                'active' => ['admin.production.quality.active'],
                'children' => [],
            ],
            [
                'label' => 'production_quality_reports',
                'title' => 'Quality Reports',
                'icon' => 'chart-bar',
                'route' => 'admin.production.quality.reports.index',
                'permission' => 'production.quality.view',
                'keywords' => ['inspection reports', 'quality analysis', 'تقارير الجودة'],
                'actions' => [],
                'active' => ['admin.production.quality.reports.*'],
                'children' => [],
            ],
            [
                'label' => 'production_reports_quality',
                'title' => 'Production Quality Report',
                'icon' => 'chart-line',
                'route' => 'admin.production.reports.quality',
                'permission' => 'production.reports.operational',
                'keywords' => ['production quality report', 'فحوص الإنتاج'],
                'actions' => [],
                'active' => ['admin.production.reports.quality'],
                'children' => [],
            ],
        ],
    ],
];
