<?php

return [
    [
        'label' => 'sales',
        'title' => 'Sales',
        'icon' => 'shopping-cart',
        'route' => null,
        'permission' => null,
        'keywords' => ['sales', 'customers', 'project structures', 'project structure models', 'المبيعات', 'العملاء', 'هياكل المشاريع', 'نماذج الهيكل'],
        'active' => [
            'admin.sales.*',
        ],
        'children' => [
            [
                'label' => 'customers',
                'title' => 'Customers',
                'icon' => 'user-tie',
                'route' => 'admin.sales.customers.index',
                'permission' => 'customers.view',
                'keywords' => ['customers', 'customer', 'clients', 'العملاء', 'عميل'],
                'actions' => [
                    'view' => 'customers.view',
                    'create' => 'customers.create',
                    'clone' => 'customers.clone',
                    'edit' => 'customers.edit',
                    'delete' => 'customers.delete',
                    'view_trashed' => 'customers.view_trashed',
                    'restore' => 'customers.restore',
                    'document_number_control' => 'customers.document_number.control',
                    'document_number_settings_update' => 'customers.document_number_settings.update',
                ],
                'active' => [
                    'admin.sales.customers.*',
                ],
                'children' => [],
            ],
            [
                'label' => 'quotations',
                'title' => 'Quotations',
                'icon' => 'file-invoice-dollar',
                'route' => 'admin.sales.quotations.index',
                'permission' => 'quotations.view',
                'keywords' => ['quotations', 'quotation', 'offers', 'sales offers', 'عروض الأسعار', 'عرض سعر'],
                'actions' => [
                    'view' => 'quotations.view',
                    'create' => 'quotations.create',
                    'clone' => 'quotations.clone',
                    'edit' => 'quotations.edit',
                    'delete' => 'quotations.delete',
                    'view_trashed' => 'quotations.view_trashed',
                    'restore' => 'quotations.restore',
                    'document_number_control' => 'quotations.document_number.control',
                    'document_number_settings_update' => 'quotations.document_number_settings.update',
                    'revisions_view' => 'quotations.revisions.view',
                    'revisions_create' => 'quotations.revisions.create',
                    'mark_sent' => 'quotations.mark_sent',
                    'accept' => 'quotations.accept',
                    'reject' => 'quotations.reject',
                    'cancel' => 'quotations.cancel',
                    'print' => 'quotations.print',
                    'attachments_manage' => 'quotations.attachments.manage',
                ],
                'active' => [
                    'admin.sales.quotations.*',
                ],
                'children' => [],
            ],
            [
                'label' => 'project_structures',
                'title' => 'Project Structures',
                'icon' => 'sitemap',
                'route' => 'admin.sales.project-structures.index',
                'permission' => 'project_structures.view',
                'keywords' => ['project structures', 'project structure', 'structures', 'project tree', 'هياكل المشاريع', 'هيكل مشروع', 'شجرة المشاريع'],
                'actions' => [
                    'view' => 'project_structures.view',
                    'create' => 'project_structures.create',
                    'clone' => 'project_structures.clone',
                    'edit' => 'project_structures.edit',
                    'delete' => 'project_structures.delete',
                    'view_trashed' => 'project_structures.view_trashed',
                    'restore' => 'project_structures.restore',
                    'document_number_control' => 'project_structures.document_number.control',
                    'document_number_settings_update' => 'project_structures.document_number_settings.update',
                    'tree_view' => 'project_structures.tree.view',
                    'tree_manage' => 'project_structures.tree.manage',
                ],
                'active' => [
                    'admin.sales.project-structures.*',
                ],
                'children' => [],
            ],
            [
                'label' => 'project_structure_models',
                'title' => 'Project Structure Models',
                'icon' => 'layer-group',
                'route' => 'admin.sales.project-structure-models.index',
                'permission' => 'project_structure_models.view',
                'keywords' => ['project structure models', 'structure models', 'models', 'room models', 'نماذج الهيكل', 'نموذج هيكل', 'نماذج الغرف'],
                'actions' => [
                    'view' => 'project_structure_models.view',
                    'create' => 'project_structure_models.create',
                    'clone' => 'project_structure_models.clone',
                    'edit' => 'project_structure_models.edit',
                    'delete' => 'project_structure_models.delete',
                    'view_trashed' => 'project_structure_models.view_trashed',
                    'restore' => 'project_structure_models.restore',
                    'document_number_control' => 'project_structure_models.document_number.control',
                    'document_number_settings_update' => 'project_structure_models.document_number_settings.update',
                ],
                'active' => [
                    'admin.sales.project-structure-models.*',
                ],
                'children' => [],
            ],
        ],
    ],
];
