<?php

return [
    [
        'label' => 'sales',
        'title' => 'Sales',
        'icon' => 'shopping-cart',
        'route' => null,
        'permission' => null,
        'keywords' => ['sales', 'quotations', 'orders', 'deliveries', 'invoices', 'collections', 'returns', 'reports', 'المبيعات', 'عروض الأسعار', 'أوامر البيع', 'التسليم', 'الفواتير', 'التحصيل', 'المرتجعات'],
        'active' => [
            'admin.sales.*',
            'admin.reports.sales.*',
        ],
        'children' => [
            [
                'label' => 'customers',
                'title' => 'Customers',
                'icon' => 'user-tie',
                'route' => 'admin.sales.customers.index',
                'permission' => 'customers.view',
                'keywords' => ['customers', 'customer', 'clients', 'العملاء', 'عميل'],
                'actions' => [
                    'view' => 'customers.view',
                    'create' => 'customers.create',
                    'clone' => 'customers.clone',
                    'edit' => 'customers.edit',
                    'delete' => 'customers.delete',
                    'view_trashed' => 'customers.view_trashed',
                    'restore' => 'customers.restore',
                    'document_number_control' => 'customers.document_number.control',
                    'document_number_settings_update' => 'customers.document_number_settings.update',
                ],
                'active' => [
                    'admin.sales.customers.*',
                ],
                'children' => [],
            ],
            [
                'label' => 'quotations',
                'title' => 'Quotations',
                'icon' => 'file-invoice-dollar',
                'route' => 'admin.sales.quotations.index',
                'permission' => 'quotations.view',
                'keywords' => ['quotations', 'quotation', 'offers', 'sales offers', 'عروض الأسعار', 'عرض سعر'],
                'actions' => [
                    'view' => 'quotations.view',
                    'create' => 'quotations.create',
                    'clone' => 'quotations.clone',
                    'edit' => 'quotations.edit',
                    'delete' => 'quotations.delete',
                    'view_trashed' => 'quotations.view_trashed',
                    'restore' => 'quotations.restore',
                    'document_number_control' => 'quotations.document_number.control',
                    'document_number_settings_update' => 'quotations.document_number_settings.update',
                    'revisions_view' => 'quotations.revisions.view',
                    'revisions_create' => 'quotations.revisions.create',
                    'mark_sent' => 'quotations.mark_sent',
                    'accept' => 'quotations.accept',
                    'reject' => 'quotations.reject',
                    'cancel' => 'quotations.cancel',
                    'print' => 'quotations.print',
                    'attachments_manage' => 'quotations.attachments.manage',
                ],
                'active' => [
                    'admin.sales.quotations.*',
                ],
                'children' => [],
            ],
            [
                'label' => 'sales_orders',
                'title' => 'Sales Orders',
                'icon' => 'clipboard-list',
                'route' => 'admin.sales.sales-orders.index',
                'permission' => 'sales_orders.view',
                'keywords' => ['sales orders', 'order', 'أوامر البيع', 'أمر بيع'],
                'active' => ['admin.sales.sales-orders.*', 'admin.sales.production-requests.*'],
                'children' => [],
            ],
            [
                'label' => 'deliveries',
                'title' => 'Deliveries',
                'icon' => 'truck-loading',
                'route' => 'admin.sales.delivery-notes.index',
                'permission' => 'sales_deliveries.view',
                'keywords' => ['delivery notes', 'deliveries', 'أذون التسليم', 'التسليم'],
                'active' => ['admin.sales.delivery-notes.*', 'admin.sales.sales-deliveries.*'],
                'children' => [],
            ],
            [
                'label' => 'sales_invoices',
                'title' => 'Sales Invoices',
                'icon' => 'file-invoice-dollar',
                'route' => 'admin.sales.sales-invoices.index',
                'permission' => 'customer_invoices.view',
                'actions' => [
                    'credit_allocate' => 'customer_credits.allocate',
                    'credit_refund' => 'customer_credits.refund',
                    'electronic_invoice_submit' => 'customer_invoices.electronic_invoice.submit',
                ],
                'keywords' => ['sales invoices', 'credit notes', 'فواتير المبيعات', 'إشعارات الدائن'],
                'active' => ['admin.sales.sales-invoices.*', 'admin.sales.customer-invoices.*'],
                'children' => [],
            ],
            [
                'label' => 'customer_collections',
                'title' => 'Customer Collections',
                'icon' => 'hand-holding-usd',
                'route' => 'admin.sales.customer-receipts.index',
                'permission' => 'customer_receipts.view',
                'keywords' => ['customer collections', 'receipts', 'تحصيلات العملاء', 'متحصلات'],
                'active' => ['admin.sales.customer-receipts.*'],
                'children' => [],
            ],
            [
                'label' => 'sales_returns',
                'title' => 'Sales Returns',
                'icon' => 'undo-alt',
                'route' => 'admin.sales.sales-returns.index',
                'permission' => 'sales_returns.view',
                'keywords' => ['sales returns', 'returns', 'مردودات المبيعات', 'مرتجعات'],
                'active' => ['admin.sales.sales-returns.*'],
                'children' => [],
            ],
            [
                'label' => 'sales_reports',
                'title' => 'Sales Reports',
                'icon' => 'chart-line',
                'route' => 'admin.reports.sales.sales-orders.index',
                'permission' => 'reports.sales.sales_orders.view',
                'keywords' => ['sales reports', 'fulfillment', 'aging', 'تقارير المبيعات', 'التنفيذ', 'الأعمار'],
                'active' => ['admin.reports.sales.*'],
                'children' => [],
            ],
        ],
    ],
];
