<?php

$salesReport = static function (string $label, string $title, string $reportType, string $icon = 'chart-bar'): array {
    $financialAnalysisTypes = [
        'financial',
        'period',
        'customers',
        'products',
        'receivables',
        'collections',
        'returns',
    ];

    return [
        'label' => $label,
        'title' => $title,
        'icon' => $icon,
        'route' => 'admin.reports.sales.sales-orders.index',
        'route_params' => ['report' => $reportType],
        'permission' => 'reports.sales.sales_orders.view',
        'subgroup' => in_array($reportType, $financialAnalysisTypes, true) ? 'financial_analysis_reports' : 'sales_cycle_reports',
        'actions' => [
            'view' => 'reports.sales.sales_orders.view',
            'export' => 'reports.sales.sales_orders.export',
            'print' => 'reports.sales.sales_orders.print',
        ],
        'active' => ['admin.reports.sales.*'],
        'children' => [],
    ];
};

return [
    [
        'label' => 'sales',
        'title' => 'Sales',
        'icon' => 'shopping-cart',
        'route' => null,
        'permission' => null,
        'keywords' => ['sales', 'quotations', 'orders', 'deliveries', 'invoices', 'collections', 'returns', 'reports', 'المبيعات', 'عروض الأسعار', 'أوامر البيع', 'التسليم', 'الفواتير', 'التحصيل', 'المرتجعات'],
        'active' => [
            'admin.sales.*',
            'admin.reports.sales.*',
        ],
        'children' => [
            [
                'label' => 'customers',
                'title' => 'Customers',
                'icon' => 'user-tie',
                'route' => 'admin.sales.customers.index',
                'permission' => 'customers.view',
                'keywords' => ['customers', 'customer', 'clients', 'العملاء', 'عميل'],
                'actions' => [
                    'view' => 'customers.view',
                    'create' => 'customers.create',
                    'clone' => 'customers.clone',
                    'edit' => 'customers.edit',
                    'delete' => 'customers.delete',
                    'view_trashed' => 'customers.view_trashed',
                    'restore' => 'customers.restore',
                    'document_number_control' => 'customers.document_number.control',
                    'document_number_settings_update' => 'customers.document_number_settings.update',
                ],
                'active' => [
                    'admin.sales.customers.*',
                ],
                'children' => [],
            ],
            [
                'label' => 'customer_terms',
                'title' => 'Customer Terms and Conditions',
                'icon' => 'file-contract',
                'route' => 'admin.sales.customer-terms.index',
                'permission' => 'customers.view',
                'keywords' => ['customer terms', 'quotation defaults', 'الشروط والأحكام', 'شروط العملاء'],
                'actions' => [
                    'view' => 'customers.view',
                    'edit' => 'customers.edit',
                ],
                'active' => ['admin.sales.customer-terms.*'],
                'children' => [],
            ],
            [
                'label' => 'price_lists',
                'title' => 'Price Lists',
                'icon' => 'tags',
                'route' => 'admin.sales.price-lists.index',
                'permission' => 'price_lists.view',
                'keywords' => ['price lists', 'pricing', 'قوائم الأسعار', 'التسعير'],
                'actions' => [
                    'view' => 'price_lists.view',
                    'create' => 'price_lists.create',
                    'clone' => 'price_lists.clone',
                    'edit' => 'price_lists.edit',
                    'delete' => 'price_lists.delete',
                    'view_trashed' => 'price_lists.view_trashed',
                    'restore' => 'price_lists.restore',
                ],
                'active' => ['admin.sales.price-lists.*'],
                'children' => [],
            ],
            ['label' => 'sales_requests', 'title' => 'Sales Requests', 'icon' => 'file-alt', 'route' => 'admin.sales.customer-requests.index', 'permission' => 'sales_requests.view', 'active' => ['admin.sales.customer-requests.*'], 'children' => []],
            [
                'label' => 'quotations',
                'title' => 'Quotations',
                'icon' => 'file-invoice-dollar',
                'route' => 'admin.sales.quotations.index',
                'permission' => 'quotations.view',
                'keywords' => ['quotations', 'quotation', 'offers', 'sales offers', 'عروض الأسعار', 'عرض سعر'],
                'actions' => [
                    'view' => 'quotations.view',
                    'create' => 'quotations.create',
                    'clone' => 'quotations.clone',
                    'edit' => 'quotations.edit',
                    'delete' => 'quotations.delete',
                    'view_trashed' => 'quotations.view_trashed',
                    'restore' => 'quotations.restore',
                    'document_number_control' => 'quotations.document_number.control',
                    'document_number_settings_update' => 'quotations.document_number_settings.update',
                    'revisions_view' => 'quotations.revisions.view',
                    'revisions_create' => 'quotations.revisions.create',
                    'mark_sent' => 'quotations.mark_sent',
                    'accept' => 'quotations.accept',
                    'reject' => 'quotations.reject',
                    'cancel' => 'quotations.cancel',
                    'print' => 'quotations.print',
                    'attachments_manage' => 'quotations.attachments.manage',
                ],
                'active' => [
                    'admin.sales.quotations.*',
                ],
                'children' => [],
            ],
            [
                'label' => 'sales_orders',
                'title' => 'Sales Orders',
                'icon' => 'clipboard-list',
                'route' => 'admin.sales.sales-orders.index',
                'permission' => 'sales_orders.view',
                'keywords' => ['sales orders', 'order', 'أوامر البيع', 'أمر بيع'],
                'active' => ['admin.sales.sales-orders.*', 'admin.sales.production-requests.*'],
                'children' => [],
            ],
            [
                'label' => 'sales_invoices',
                'title' => 'Sales Invoices',
                'icon' => 'file-invoice-dollar',
                'route' => 'admin.sales.sales-invoices.index',
                'permission' => 'customer_invoices.view',
                'actions' => [
                    'delete' => 'customer_invoices.delete',
                    'credit_allocate' => 'customer_credits.allocate',
                    'credit_refund' => 'customer_credits.refund',
                    'electronic_invoice_submit' => 'customer_invoices.electronic_invoice.submit',
                ],
                'keywords' => ['sales invoices', 'credit notes', 'فواتير المبيعات', 'إشعارات الدائن'],
                'active' => ['admin.sales.sales-invoices.*', 'admin.sales.customer-invoices.*'],
                'children' => [],
            ],
            [
                'label' => 'deliveries',
                'title' => 'Issue Orders',
                'icon' => 'truck-loading',
                'route' => 'admin.sales.delivery-notes.index',
                'permission' => 'sales_deliveries.view',
                'keywords' => ['issue orders', 'stock issue', 'أوامر الصرف', 'أمر صرف'],
                'active' => ['admin.sales.delivery-notes.*', 'admin.sales.sales-deliveries.*'],
                'children' => [],
            ],
            ['label' => 'customer_collections', 'title' => 'Customer Collections', 'icon' => 'hand-holding-usd', 'route' => 'admin.sales.customer-receipts.index', 'permission' => 'customer_receipts.view', 'children' => []],
            [
                'label' => 'sales_returns',
                'title' => 'Sales Returns',
                'icon' => 'undo-alt',
                'route' => 'admin.sales.sales-returns.index',
                'permission' => 'sales_returns.view',
                'keywords' => ['sales returns', 'returns', 'مردودات المبيعات', 'مرتجعات'],
                'active' => ['admin.sales.sales-returns.*'],
                'children' => [],
            ],
            [
                'label' => 'sales_reports',
                'title' => 'Sales Reports',
                'icon' => 'chart-pie',
                'route' => null,
                'permission' => null,
                'keywords' => ['sales reports', 'fulfillment', 'aging', 'تقارير المبيعات', 'التنفيذ', 'الأعمار'],
                'active' => ['admin.reports.sales.*', 'admin.accounting.reports.customer-statement*'],
                'children' => [
                    [
                        'label' => 'customer_statement',
                        'title' => 'Customer Statement',
                        'icon' => 'file-invoice',
                        'route' => 'admin.accounting.reports.customer-statement',
                        'permission' => 'reports.customer_statement.view',
                        'subgroup' => 'sales_cycle_reports',
                        'active' => ['admin.accounting.reports.customer-statement*'],
                        'children' => [],
                    ],
                    $salesReport('sales_report_financial', 'Sales Financial Analysis', 'financial', 'coins'),
                    $salesReport('sales_report_period', 'Sales by Period', 'period', 'calendar-alt'),
                    $salesReport('sales_report_customer', 'Sales by Customer', 'customers', 'user-chart'),
                    $salesReport('sales_report_product', 'Sales by Product', 'products', 'boxes'),
                    $salesReport('sales_report_invoices', 'Sales Invoices Report', 'invoices', 'file-invoice-dollar'),
                    $salesReport('sales_report_receivables', 'Customer Receivables and Aging', 'receivables', 'hourglass-half'),
                    $salesReport('sales_report_collections', 'Collections Forecast', 'collections', 'hand-holding-usd'),
                    $salesReport('sales_report_returns', 'Sales Returns Analysis', 'returns', 'undo-alt'),
                    $salesReport('sales_report_quotations', 'Quotation Pipeline', 'quotations', 'file-signature'),
                    $salesReport('sales_report_fulfillment', 'Sales Order Fulfillment', 'fulfillment', 'shipping-fast'),
                    $salesReport('sales_report_pricing', 'Sales Pricing Coverage', 'pricing', 'tags'),
                    $salesReport('sales_report_operational', 'Sales Operational Overview', 'operational', 'chart-line'),
                ],
            ],
        ],
    ],
];
