<?php

return [
    [
        'label' => 'tools',
        'title' => 'Tools',
        'icon' => 'tools',
        'route' => null,
        'permission' => null,
        'keywords' => ['tools', 'open document', 'reopen documents', 'files', 'calendar', 'board', 'task management', 'manage tasks', 'chat', 'quick tasks', 'task boards', 'pwa', 'web app settings', 'الأدوات', 'فتح مستند', 'فتح المستندات', 'الملفات', 'التقويم', 'لوحتي', 'إدارة المهام', 'المهام السريعة', 'لوحات المهام', 'المحادثات', 'إعدادات تطبيق الويب'],
        'active' => [
            'admin.tools.*',
            'admin.file-manager.*',
            'admin.calendar.*',
            'admin.my-board.*',
            'admin.quick-tasks.*',
            'admin.task-boards.*',
            'admin.tools.team-board.*',
            'admin.chat.*',
            'admin.settings.pwa',
        ],
        'children' => [
            [
                'label' => 'open_documents',
                'title' => 'Open Document',
                'icon' => 'unlock',
                'route' => 'admin.tools.open-documents.index',
                'permission' => 'tools.open_documents.view',
                'keywords' => ['open document', 'reopen documents', 'closed documents', 'فتح مستند', 'فتح المستندات'],
                'actions' => [
                    'view' => 'tools.open_documents.view',
                    'execute' => 'tools.open_documents.execute',
                ],
                'active' => [
                    'admin.tools.open-documents.*',
                ],
                'children' => [],
            ],
            [
                'label' => 'file_manager',
                'title' => 'File Manager',
                'icon' => 'folder',
                'route' => 'admin.file-manager.index',
                'permission' => 'file_manager.view',
                'keywords' => ['files', 'archive', 'documents', 'manager', 'الملفات', 'الأرشيف', 'المستندات'],
                'actions' => [
                    'view' => 'file_manager.view',
                    'view_trashed' => 'file_manager.view_trashed',
                    'upload' => 'file_manager.upload',
                    'update_picker_visibility' => 'file_manager.update_picker_visibility',
                    'move' => 'file_manager.move',
                    'download' => 'file_manager.download',
                    'delete' => 'file_manager.delete',
                    'restore' => 'file_manager.restore',
                    'document_number_settings_update' => 'file_manager.document_number_settings.update',
                    'folders_create' => 'file_manager.folders.create',
                    'folders_rename' => 'file_manager.folders.rename',
                    'folders_delete' => 'file_manager.folders.delete',
                    'folders_restore' => 'file_manager.folders.restore',
                    'public_links_create' => 'file_manager.public_links.create',
                    'public_links_view' => 'file_manager.public_links.view',
                    'public_links_revoke' => 'file_manager.public_links.revoke',
                ],
                'active' => [
                    'admin.file-manager.*',
                ],
                'children' => [],
            ],
            [
                'label' => 'calendar',
                'title' => 'Calendar',
                'icon' => 'calendar-alt',
                'route' => 'admin.calendar.index',
                'permission' => 'calendar.view',
                'keywords' => ['events', 'event', 'reminders', 'التقويم', 'الأحداث', 'مواعيد'],
                'actions' => [
                    'view' => 'calendar.view',
                    'create' => 'calendar.create',
                    'edit' => 'calendar.edit',
                    'delete' => 'calendar.delete',
                    'complete' => 'calendar.complete',
                ],
                'active' => [
                    'admin.calendar.*',
                ],
                'children' => [],
            ],
            [
                'label' => 'my_board',
                'title' => 'My Board',
                'icon' => 'columns',
                'route' => 'admin.my-board.index',
                'permission' => 'my_board.view',
                'keywords' => ['board', 'kanban', 'tasks', 'notes', 'لوحتي', 'المهام', 'الملاحظات'],
                'actions' => [
                    'view' => 'my_board.view',
                    'create' => 'my_board.create',
                    'edit' => 'my_board.edit',
                    'delete' => 'my_board.delete',
                    'clone' => 'my_board.clone',
                    'view_trashed' => 'my_board.view_trashed',
                    'restore' => 'my_board.restore',
                    'reorder' => 'my_board.reorder',
                    'assign' => 'my_board.assign',
                    'view_any' => 'my_board.view_any',
                    'manage_any' => 'my_board.manage_any',
                    'lists_create' => 'my_board.lists.create',
                    'lists_edit' => 'my_board.lists.edit',
                    'lists_delete' => 'my_board.lists.delete',
                    'lists_reorder' => 'my_board.lists.reorder',
                    'comments_create' => 'my_board.comments.create',
                    'comments_delete' => 'my_board.comments.delete',
                    'tasks_view_all' => 'my_board.tasks.view_all',
                    'notes_view_all' => 'my_board.notes.view_all',
                ],
                'active' => [
                    'admin.my-board.index',
                    'admin.my-board.data',
                    'admin.my-board.all-*',
                    'admin.my-board.store',
                    'admin.my-board.show',
                    'admin.my-board.update',
                    'admin.my-board.move',
                    'admin.my-board.destroy',
                    'admin.my-board.lists.*',
                    'admin.my-board.comments.*',
                ],
                'children' => [],
            ],
            [
                'label' => 'task_boards',
                'title' => 'Task Boards',
                'icon' => 'columns',
                'route' => 'admin.task-boards.index',
                'permission' => 'task_boards.view',
                'keywords' => ['task boards', 'task board monitors', 'display urls', 'kds', 'لوحات المهام', 'روابط شاشة العرض', 'شاشات عرض المهام'],
                'actions' => [
                    'view' => 'task_boards.view',
                    'create' => 'task_boards.create',
                    'update' => 'task_boards.update',
                    'delete' => 'task_boards.delete',
                    'view_trashed' => 'task_boards.view_trashed',
                    'restore' => 'task_boards.restore',
                    'bulk_activate' => 'task_boards.bulk_activate',
                    'bulk_deactivate' => 'task_boards.bulk_deactivate',
                    'display' => 'task_boards.display',
                    'public_settings' => 'task_boards.public_settings',
                    'regenerate_public_url' => 'task_boards.regenerate_public_url',
                ],
                'active' => [
                    'admin.task-boards.*',
                ],
                'children' => [],
            ],
            [
                'label' => 'team_board',
                'title' => 'Task Management',
                'icon' => 'table',
                'route' => 'admin.tools.team-board.index',
                'permission' => [
                    'my_board.tasks.view_all',
                    'my_board.notes.view_all',
                ],
                'keywords' => ['task management', 'manage tasks', 'all tasks', 'user tasks', 'task report', 'إدارة المهام', 'كل المهام', 'مهام المستخدمين'],
                'actions' => [
                    'tasks_view_all' => 'my_board.tasks.view_all',
                    'notes_view_all' => 'my_board.notes.view_all',
                    'create' => 'my_board.create',
                    'edit' => 'my_board.edit',
                    'delete' => 'my_board.delete',
                    'view_trashed' => 'my_board.view_trashed',
                    'restore' => 'my_board.restore',
                    'manage_attachments' => 'quick_tasks.manage_attachments',
                    'quick_tasks_start' => 'quick_tasks.start',
                    'quick_tasks_mark_ready' => 'quick_tasks.mark_ready',
                    'quick_tasks_mark_done' => 'quick_tasks.mark_done',
                    'quick_tasks_view' => 'quick_tasks.view',
                    'quick_tasks_create' => 'quick_tasks.create',
                    'quick_tasks_update' => 'quick_tasks.update',
                    'quick_tasks_delete' => 'quick_tasks.delete',
                    'quick_tasks_restore' => 'quick_tasks.restore',
                    'quick_tasks_change_status' => 'quick_tasks.change_status',
                    'quick_tasks_bulk_delete' => 'quick_tasks.bulk_delete',
                ],
                'active' => [
                    'admin.tools.team-board.*',
                    'admin.tools.users-tasks-report.*',
                    'admin.quick-tasks.*',
                ],
                'children' => [],
            ],
            [
                'label' => 'chat',
                'title' => 'Chat',
                'icon' => 'comments',
                'route' => null,
                'permission' => null,
                'keywords' => ['chat', 'messages', 'conversation', 'chat report', 'محادثات', 'رسائل', 'تقرير المحادثات'],
                'active' => [
                    'admin.chat.*',
                ],
                'children' => [
                    [
                        'label' => 'chat',
                        'title' => 'Chat',
                        'icon' => 'comment-dots',
                        'route' => 'admin.chat.index',
                        'permission' => 'chat.view',
                        'keywords' => ['chat', 'messages', 'conversation', 'محادثات', 'رسائل'],
                        'actions' => [
                            'view' => 'chat.view',
                            'create' => 'chat.create',
                            'send' => 'chat.send',
                        ],
                        'active' => [
                            'admin.chat.index',
                            'admin.chat.conversations*',
                            'admin.chat.messages*',
                            'admin.chat.attachments*',
                        ],
                        'children' => [],
                    ],
                    [
                        'label' => 'chat_report',
                        'title' => 'Chat Report',
                        'icon' => 'clipboard-list',
                        'route' => 'admin.chat.reports.index',
                        'permission' => 'chat.reports.view',
                        'keywords' => ['chat report', 'conversation report', 'message audit', 'تقرير المحادثات', 'مراجعة الرسائل'],
                        'actions' => [
                            'view' => 'chat.reports.view',
                            'export' => 'chat.reports.export',
                            'pdf' => 'chat.reports.pdf',
                            'print' => 'chat.reports.print',
                        ],
                        'active' => [
                            'admin.chat.reports.*',
                        ],
                        'children' => [],
                    ],
                ],
            ],
            [
                'label' => 'pwa_settings',
                'title' => 'PWA Settings',
                'icon' => 'mobile-alt',
                'route' => 'admin.settings.pwa',
                'permission' => 'settings.pwa.view',
                'keywords' => ['pwa', 'progressive web app', 'manifest', 'offline', 'mobile app', 'تطبيق', 'أوفلاين', 'بدون إنترنت', 'إعدادات تطبيق الويب'],
                'actions' => [
                    'view' => 'settings.pwa.view',
                    'update' => 'settings.pwa.update',
                ],
                'active' => [
                    'admin.settings.pwa',
                ],
                'children' => [],
            ],
        ],
    ],
];
