<section class="card my-3"><div class="card-header"><h5>{{ __('Sales Ledger') }}</h5></div><div class="table-responsive"><table class="table table-sm report-table"><thead><tr><th>{{ __('Date') }}</th><th>{{ __('Customer') }}</th><th>{{ __('Invoice') }}</th><th>{{ __('Order') }}</th><th>{{ __('Delivery') }}</th><th>{{ __('Currency') }}</th><th>{{ __('Gross Value') }}</th><th>{{ __('Discount') }}</th><th>{{ __('Tax') }}</th><th>{{ __('Net Invoice') }}</th><th>{{ __('Returns') }}</th><th>{{ __('Net Sales') }}</th><th>{{ __('Collected') }}</th><th>{{ __('Outstanding') }}</th></tr></thead><tbody>
@forelse($salesLedger as $invoice)
<tr><td>{{ $invoice->invoice_date?->toDateString() }}</td><td>{{ $invoice->customer?->name }}</td><td><a href="{{ route('admin.sales.sales-invoices.show', $invoice) }}">{{ $invoice->doc_num }}</a></td><td>@if($invoice->order)<a href="{{ route('admin.sales.sales-orders.show', $invoice->order) }}">{{ $invoice->order->doc_num }}</a>@endif</td><td>@foreach($invoice->deliveries as $delivery)<a href="{{ route('admin.sales.delivery-notes.show', $delivery) }}">{{ $delivery->doc_num }}</a> @endforeach</td><td>{{ $invoice->currency?->code }}</td><td>{{ $numbers->format($invoice->subtotal_amount) }}</td><td>{{ $numbers->format($invoice->discount_amount) }}</td><td>{{ $numbers->format($invoice->tax_amount) }}</td><td>{{ $numbers->format($invoice->total_amount) }}</td><td>{{ $numbers->format($invoice->returns_amount) }}</td><td>{{ $numbers->format(bcsub($invoice->total_amount, (string) ($invoice->returns_amount ?? 0), 4)) }}</td><td>{{ $numbers->format($invoice->paid_amount) }}</td><td>{{ $numbers->format($invoice->remaining_amount) }}</td></tr>
<tr><td colspan="14"><details><summary>{{ __('Invoice lines') }} · {{ $invoice->doc_num }}</summary><table class="table table-sm report-table"><thead><tr><th>{{ __('Item') }}</th><th>{{ __('Category') }}</th><th>{{ __('Quantity') }}</th><th>{{ __('Price') }}</th><th>{{ __('Discount') }}</th><th>{{ __('Tax') }}</th><th>{{ __('Returned quantity') }}</th><th>{{ __('Net sold quantity') }}</th></tr></thead><tbody>
@foreach($invoice->lines as $line)
<tr><td>{{ $line->product?->doc_num }} · {{ $line->description }}</td><td>{{ $line->product?->category?->name }}</td><td>{{ $numbers->format($line->quantity) }}</td><td>{{ $numbers->format($line->unit_price) }}</td><td>{{ $numbers->format($line->discount_amount) }}</td><td>{{ $numbers->format($line->tax_amount) }}</td><td>{{ $numbers->format($line->returned_quantity) }}</td><td>{{ $numbers->format(bcsub($line->quantity, (string) ($line->returned_quantity ?? 0), 8)) }}</td></tr>
@endforeach</tbody></table></details></td></tr>
@empty<tr><td colspan="14">{{ __('No matching records.') }}</td></tr>@endforelse
</tbody></table></div></section>

@if($salesLedger instanceof \Illuminate\Contracts\Pagination\Paginator)<div class="my-3">{{ $salesLedger->links() }}</div>@endif
