<h1>{{ $reportTitle }}</h1>

@if($section === 'overview')
    <table><thead><tr><th>{{ __('production_execution.reports.columns.metric') }}</th><th class="number">{{ __('production_execution.reports.columns.value') }}</th></tr></thead><tbody>@foreach($kpis as $label => $value)<tr><td>{{ __('production_execution.reports.kpis.'.$label) }}</td><td class="number">{{ $numbers->format($value) }}</td></tr>@endforeach</tbody></table>
@elseif($section === 'orders')
    <table><thead><tr><th>{{ __('production_execution.reports.columns.order') }}</th><th>{{ __('production_execution.reports.columns.date') }}</th><th>{{ __('production_execution.reports.columns.source') }}</th><th>{{ __('production_execution.reports.columns.sales_order') }}</th><th class="number">{{ __('production_execution.reports.columns.planned_quantity') }}</th><th class="number">{{ __('production_execution.reports.columns.received_quantity') }}</th><th>{{ __('production_execution.reports.columns.status') }}</th></tr></thead><tbody>@foreach($orders as $order)<tr><td>{{ $order->doc_num }}</td><td>{{ $dates->formatDate($order->production_order_date) }}</td><td>{{ __('production_execution.source_types.'.$order->source_type) }}</td><td>{{ $order->salesOrder?->doc_num ?: '—' }}</td><td class="number">{{ $numbers->format($order->lines->sum('base_quantity')) }}</td><td class="number">{{ $numbers->format($order->lines->sum('received_base_quantity')) }}</td><td>{{ __('production_execution.statuses.'.$order->status) }}</td></tr>@endforeach</tbody></table>
@elseif($section === 'runs')
    <table><thead><tr><th>{{ __('production_execution.reports.columns.run') }}</th><th>{{ __('production_execution.reports.columns.order') }}</th><th>{{ __('production_execution.reports.columns.stage') }}</th><th>{{ __('production_execution.reports.columns.fixed_asset') }}</th><th>{{ __('production_execution.reports.columns.product') }}</th><th class="number">{{ __('production_execution.reports.columns.planned') }}</th><th class="number">{{ __('production_execution.reports.columns.good') }}</th><th class="number">{{ __('production_execution.reports.columns.rejected') }}</th><th class="number">{{ __('production_execution.reports.columns.rework') }}</th><th class="number">{{ __('production_execution.reports.columns.scrap') }}</th><th class="number">{{ __('production_execution.reports.columns.yield_percent') }}</th><th>{{ __('production_execution.reports.columns.status') }}</th></tr></thead><tbody>@foreach($runs as $run)<tr><td>{{ $run->run_number }}</td><td>{{ $run->order?->doc_num }}</td><td>{{ $run->stageSnapshot?->stage_name ?: '—' }}</td><td>{{ $run->fixedAsset?->asset_name ?: '—' }}</td><td>{{ $run->product?->name }}</td><td class="number">{{ $numbers->format($run->planned_base_quantity) }}</td><td class="number">{{ $numbers->format($run->good_base_quantity) }}</td><td class="number">{{ $numbers->format($run->rejected_base_quantity) }}</td><td class="number">{{ $numbers->format($run->rework_base_quantity) }}</td><td class="number">{{ $numbers->format($run->scrap_base_quantity) }}</td><td class="number">{{ $numbers->format($run->yield_percent) }}</td><td>{{ __('production_execution.statuses.'.$run->status) }}</td></tr>@endforeach</tbody></table>
@elseif($section === 'materials')
    <table><thead><tr><th>{{ __('production_execution.reports.columns.run') }}</th><th>{{ __('production_execution.reports.columns.material') }}</th><th class="number">{{ __('production_execution.reports.columns.planned') }}</th><th class="number">{{ __('production_execution.reports.columns.issued') }}</th><th class="number">{{ __('production_execution.reports.columns.returned') }}</th><th class="number">{{ __('production_execution.reports.columns.consumed') }}</th><th class="number">{{ __('production_execution.reports.columns.waste') }}</th><th class="number">{{ __('production_execution.reports.columns.quantity_variance') }}</th><th class="number">{{ __('production_execution.reports.columns.accountability_variance') }}</th></tr></thead><tbody>@foreach($materials as $line)<tr><td>{{ $line->run?->run_number }}</td><td>{{ $line->product?->doc_num }} — {{ $line->product?->name }}</td><td class="number">{{ $numbers->format($line->planned_quantity) }}</td><td class="number">{{ $numbers->format($line->issued_total_quantity) }}</td><td class="number">{{ $numbers->format($line->returned_quantity) }}</td><td class="number">{{ $numbers->format($line->consumed_quantity) }}</td><td class="number">{{ $numbers->format($line->waste_quantity) }}</td><td class="number">{{ $numbers->format($line->quantity_variance) }}</td><td class="number">{{ $numbers->format($line->accountability_variance) }}</td></tr>@endforeach</tbody></table>
@elseif($section === 'quality')
    <table><thead><tr><th>{{ __('production_execution.reports.columns.inspection') }}</th><th>{{ __('production_execution.reports.columns.sampled_at') }}</th><th>{{ __('production_execution.reports.columns.run') }}</th><th>{{ __('production_execution.reports.columns.stage') }}</th><th>{{ __('production_execution.reports.columns.inspection_type') }}</th><th>{{ __('production_execution.reports.columns.result') }}</th><th>{{ __('production_execution.reports.columns.disposition') }}</th><th class="number">{{ __('production_execution.reports.columns.affected_quantity') }}</th><th>{{ __('production_execution.reports.columns.status') }}</th></tr></thead><tbody>@foreach($qualityInspections as $inspection)<tr><td>{{ $inspection->doc_num }}</td><td>{{ $dates->formatDateTime($inspection->sampled_at) }}</td><td>{{ $inspection->run?->run_number }}</td><td>{{ $inspection->stageSnapshot?->stage_name ?: '—' }}</td><td>{{ $inspection->qualityType?->name ?: '—' }}</td><td>{{ __('production_execution.quality_results.'.$inspection->result) }}</td><td>{{ __('production_execution.quality_dispositions.'.($inspection->disposition ?: 'hold')) }}</td><td class="number">{{ $numbers->format($inspection->affected_base_quantity) ?: '—' }}</td><td>{{ __('production_execution.statuses.'.$inspection->status) }}</td></tr>@endforeach</tbody></table>
@elseif($section === 'receipts')
    <table><thead><tr><th>{{ __('production_execution.reports.columns.receipt') }}</th><th>{{ __('production_execution.reports.columns.date') }}</th><th>{{ __('production_execution.reports.columns.run') }}</th><th>{{ __('production_execution.reports.columns.order') }}</th><th>{{ __('production_execution.reports.columns.store') }}</th><th>{{ __('production_execution.reports.columns.product') }}</th><th class="number">{{ __('production_execution.reports.columns.quantity') }}</th></tr></thead><tbody>@foreach($finishedGoodsReceipts as $document)@foreach($document->lines as $line)<tr><td>{{ $document->doc_num }}</td><td>{{ $dates->formatDate($document->document_date) }}</td><td>{{ $document->productionRun?->run_number }}</td><td>{{ $document->productionRun?->order?->doc_num }}</td><td>{{ $document->branchStore?->name }}</td><td>{{ $line->product?->doc_num }} — {{ $line->product?->name }}</td><td class="number">{{ $numbers->format($line->base_quantity) }}</td></tr>@endforeach @endforeach</tbody></table>
@endif
