<h1>{{ $reportTitle }}</h1>

<table><thead><tr>@foreach($kpis as $label => $value)<th>{{ __(str($label)->replace('_', ' ')->title()->toString()) }}</th>@endforeach</tr></thead><tbody><tr>@foreach($kpis as $value)<td class="number">{{ $value }}</td>@endforeach</tr></tbody></table>

<h2>{{ __('Production Orders and Sales Origin') }}</h2>
<table><thead><tr><th>{{ __('Order') }}</th><th>{{ __('Date') }}</th><th>{{ __('Source') }}</th><th>{{ __('Sales order') }}</th><th class="number">{{ __('Planned') }}</th><th class="number">{{ __('Received') }}</th><th>{{ __('Status') }}</th></tr></thead><tbody>@foreach($orders as $order)<tr><td>{{ $order->doc_num }}</td><td>{{ $order->production_order_date?->toDateString() }}</td><td>{{ __(str($order->source_type)->replace('_', ' ')->title()->toString()) }}</td><td>{{ $order->salesOrder?->doc_num }}</td><td class="number">{{ $order->lines->sum('base_quantity') }}</td><td class="number">{{ $order->lines->sum('received_base_quantity') }}</td><td>{{ __(str($order->status)->replace('_', ' ')->title()->toString()) }}</td></tr>@endforeach</tbody></table>

<h2>{{ __('Runs — Plan vs Actual, Waste and Yield') }}</h2>
<table><thead><tr><th>{{ __('Run') }}</th><th>{{ __('Order / Sales') }}</th><th>{{ __('Stage') }}</th><th>{{ __('Fixed Asset') }}</th><th>{{ __('Product') }}</th><th class="number">{{ __('Planned') }}</th><th class="number">{{ __('Good') }}</th><th class="number">{{ __('Rejected') }}</th><th class="number">{{ __('Rework') }}</th><th class="number">{{ __('Scrap') }}</th><th class="number">{{ __('Yield %') }}</th></tr></thead><tbody>@foreach($runs as $run)<tr><td>{{ $run->run_number }}</td><td>{{ $run->order?->doc_num }} / {{ $run->order?->salesOrder?->doc_num }}</td><td>{{ $run->stageSnapshot?->stage_name }}</td><td>{{ $run->fixedAsset?->asset_name }}</td><td>{{ $run->product?->name }}</td><td class="number">{{ $run->planned_base_quantity }}</td><td class="number">{{ $run->good_base_quantity }}</td><td class="number">{{ $run->rejected_base_quantity }}</td><td class="number">{{ $run->rework_base_quantity }}</td><td class="number">{{ $run->scrap_base_quantity }}</td><td class="number">{{ $run->yield_percent }}</td></tr>@endforeach<tr class="total"><td colspan="5">{{ __('Total') }}</td><td class="number">{{ $kpis['planned_base_quantity'] }}</td><td class="number">{{ $kpis['good_base_quantity'] }}</td><td colspan="4"></td></tr></tbody></table>

<h2>{{ __('production_execution.quality.stage_inspections') }}</h2>
<table><thead><tr><th>{{ __('production_execution.fields.document') }}</th><th>{{ __('production_execution.fields.sampled_at') }}</th><th>{{ __('production_execution.fields.run') }}</th><th>{{ __('production_execution.fields.stage') }}</th><th>{{ __('production_execution.fields.inspection_type') }}</th><th>{{ __('production_execution.fields.result') }}</th><th>{{ __('production_execution.fields.disposition') }}</th><th class="number">{{ __('production_execution.fields.affected_quantity') }}</th><th class="number">{{ __('production_execution.fields.attachments') }}</th><th>{{ __('production_execution.fields.status') }}</th></tr></thead><tbody>@foreach($qualityInspections as $inspection)<tr><td>{{ $inspection->doc_num }}</td><td>{{ $inspection->sampled_at?->format('Y-m-d H:i') }}</td><td>{{ $inspection->run?->run_number }}</td><td>{{ $inspection->stageSnapshot?->stage_name }}</td><td>{{ $inspection->qualityType?->name }}</td><td>{{ __('production_execution.quality_results.'.$inspection->result) }}</td><td>{{ __('production_execution.quality_dispositions.'.($inspection->disposition ?: 'hold')) }}</td><td class="number">{{ $inspection->affected_base_quantity ?? '—' }}</td><td class="number">{{ count($inspection->evidence ?? []) }}</td><td>{{ __('production_execution.statuses.'.$inspection->status) }}</td></tr>@endforeach</tbody></table>

<h2>{{ __('Material Requirements, Consumption and Variance') }}</h2>
<table><thead><tr><th>{{ __('Run') }}</th><th>{{ __('Material') }}</th><th class="number">{{ __('Planned') }}</th><th class="number">{{ __('Issued') }}</th><th class="number">{{ __('Returned') }}</th><th class="number">{{ __('Consumed') }}</th><th class="number">{{ __('Waste') }}</th><th class="number">{{ __('Qty variance') }}</th><th class="number">{{ __('Accountability variance') }}</th>@if($canViewFinancial)<th class="number">{{ __('Actual cost') }}</th><th class="number">{{ __('Waste cost') }}</th><th class="number">{{ __('Cost variance') }}</th>@endif</tr></thead><tbody>@foreach($materials as $line)<tr><td>{{ $line->run?->run_number }}</td><td>{{ $line->product?->doc_num }} — {{ $line->product?->name }}</td><td class="number">{{ $line->planned_quantity }}</td><td class="number">{{ $line->issued_total_quantity }}</td><td class="number">{{ $line->returned_quantity }}</td><td class="number">{{ $line->consumed_quantity }}</td><td class="number">{{ $line->waste_quantity }}</td><td class="number">{{ $line->quantity_variance }}</td><td class="number">{{ $line->accountability_variance }}</td>@if($canViewFinancial)<td class="number">{{ $line->actual_cost }}</td><td class="number">{{ $line->waste_cost }}</td><td class="number">{{ $line->cost_variance }}</td>@endif</tr>@endforeach</tbody></table>

<h2>{{ __('Finished Goods Receipts and Traceability') }}</h2>
<table><thead><tr><th>{{ __('Receipt') }}</th><th>{{ __('Run') }}</th><th>{{ __('Order / Sales') }}</th><th>{{ __('Product') }}</th><th class="number">{{ __('Quantity') }}</th>@if($canViewFinancial)<th class="number">{{ __('Value') }}</th><th>{{ __('Journal') }}</th>@endif</tr></thead><tbody>
@foreach($finishedGoodsReceipts as $document)
    @foreach($document->lines as $line)
        <tr><td>{{ $document->doc_num }}</td><td>{{ $document->productionRun?->run_number }}</td><td>{{ $document->productionRun?->order?->doc_num }} / {{ $document->productionRun?->order?->salesOrder?->doc_num }}</td><td>{{ $line->product?->name }}</td><td class="number">{{ $line->base_quantity }}</td>@if($canViewFinancial)<td class="number">{{ $line->total_cost }}</td><td>{{ $document->journalEntry?->doc_num }}</td>@endif</tr>
    @endforeach
@endforeach
</tbody></table>

@if($canViewFinancial)
<h2>{{ __('Production Cost and Work in Process') }}</h2>
<table><thead><tr><th>{{ __('Run') }}</th><th>{{ __('Order') }}</th><th class="number">{{ __('Issued') }}</th><th class="number">{{ __('Returned') }}</th><th class="number">{{ __('Waste') }}</th><th class="number">{{ __('Capitalizable') }}</th><th class="number">{{ __('Finished goods') }}</th><th class="number">{{ __('WIP') }}</th></tr></thead><tbody>@foreach($runCosts as $row)<tr><td>{{ $row->run?->run_number }}</td><td>{{ $row->run?->order?->doc_num }}</td><td class="number">{{ $row->issued }}</td><td class="number">{{ $row->returned }}</td><td class="number">{{ $row->waste }}</td><td class="number">{{ $row->capitalizable }}</td><td class="number">{{ $row->finished_goods }}</td><td class="number">{{ $row->wip }}</td></tr>@endforeach</tbody></table>
@endif

@if(isset($backorders))@include('modules.sales.cycle.partials.production-demand-summary')@endif
