<h1>{{ $reportTitle }}</h1>

<table>
    <thead><tr><th>{{ __('production_execution.fields.document') }}</th><th>{{ __('production_execution.fields.reinspection') }}</th><th>{{ __('production_execution.fields.requested_at') }}</th><th>{{ __('production_execution.fields.inspection_subject') }}</th><th>{{ __('production_execution.fields.product') }}</th><th>{{ __('production_execution.fields.store') }}</th><th>{{ __('production_execution.fields.run') }}</th><th>{{ __('production_execution.fields.stage') }}</th><th>{{ __('production_execution.fields.inspection_type') }}</th><th>{{ __('production_execution.fields.result') }}</th><th>{{ __('production_execution.fields.disposition') }}</th><th class="number">{{ __('production_execution.fields.affected_quantity') }}</th><th>{{ __('production_execution.fields.reports_count') }}</th><th>{{ __('production_execution.fields.status') }}</th><th>{{ __('production_execution.fields.notes') }}</th><th>{{ __('production_execution.fields.corrective_action') }}</th><th class="number">{{ __('production_execution.fields.attachments') }}</th><th>{{ __('production_execution.fields.reviewed_at') }}</th><th>{{ __('production_execution.fields.closed_at') }}</th></tr></thead>
    <tbody>
        @forelse($inspections as $inspection)
            <tr><td>{{ $inspection->doc_num }}</td><td>{{ $inspection->reinspection_number }}</td><td>{{ $inspection->requested_at?->format('Y-m-d H:i') }}</td><td>{{ __('production_execution.quality_subjects.'.$inspection->subject_type) }}</td><td>{{ $inspection->run?->product?->name ?? $inspection->product?->name }}</td><td>{{ $inspection->branchStore?->name }}</td><td>{{ $inspection->run?->run_number }}</td><td>{{ $inspection->stageSnapshot?->stage_name }}</td><td>{{ $inspection->qualityType?->name }}</td><td>{{ __('production_execution.quality_results.'.$inspection->result) }}</td><td>{{ $inspection->disposition ? __('production_execution.quality_dispositions.'.$inspection->disposition) : '—' }}</td><td class="number">{{ $inspection->affected_base_quantity ?? '—' }}</td><td class="number">{{ $inspection->reports->count() }}</td><td>{{ __('production_execution.statuses.'.$inspection->status) }}</td><td>{{ $inspection->notes }}</td><td>{{ $inspection->corrective_action }}</td><td class="number">{{ count($inspection->evidence ?? []) }}</td><td>{{ $inspection->reviewed_at?->format('Y-m-d H:i') }}</td><td>{{ $inspection->closed_at?->format('Y-m-d H:i') }}</td></tr>
        @empty
            <tr><td colspan="19">{{ __('production_execution.quality.no_inspections') }}</td></tr>
        @endforelse
    </tbody>
</table>
