@php
    $fields = $entry->sheet_fields;
    $kind = $fields['sheet_kind'] ?? 'injection';
    $columns = $kind === 'cover'
        ? ['product_size', 'cover_components', 'machine_speed', 'pack_ratio', 'carton_type', 'carton_size']
        : ['cavities', 'cycle_seconds', 'piece_weight_grams', 'average_piece_weight_grams', 'bag_type', 'bag_size', 'carton_type', 'carton_size', 'pack_ratio'];
@endphp
<h3>{{ __('production_execution.shift_evidence.report_title') }} — {{ __('production_execution.shift_evidence.'.$kind) }}</h3>
<table dir="{{ $direction ?? 'ltr' }}" class="report-table"><tbody>
    <tr><th>{{ __('production_execution.shift_evidence.work_date') }}</th><td>{{ $dates->formatDate($entry->work_date) }}</td><th>{{ __('production_execution.shift_evidence.day') }}</th><td>{{ \Carbon\CarbonImmutable::parse($entry->work_date)->locale(app()->getLocale())->translatedFormat('l') }}</td><th>{{ __('production_execution.fields.shift') }}</th><td>{{ $fields['shift_name'] }}</td></tr>
    <tr><th>{{ __('production_execution.fields.run') }}</th><td dir="ltr">{{ $record->run_number }}</td><th>{{ __('production_execution.fields.production_order') }}</th><td dir="ltr">{{ $record->order?->doc_num }}</td><th>{{ __('production_execution.fields.product') }}</th><td>{{ $fields['product_name'] }}</td></tr>
    <tr><th>{{ __('production_execution.fields.fixed_asset') }}</th><td colspan="3">{{ $entry->equipment_snapshot['number'] }} — {{ $entry->equipment_snapshot['name'] }}</td><th>{{ __('production_execution.shift_evidence.working_hours') }}</th><td dir="ltr">{{ $numbers->format($entry->working_hours) }}</td></tr>
    <tr><th>{{ __('production_execution.shift_evidence.actual_start') }}</th><td>{{ $dates->formatDateTime($entry->started_at) }}</td><th>{{ __('production_execution.shift_evidence.actual_end') }}</th><td>{{ $dates->formatDateTime($entry->ended_at, '—') }}</td><th>{{ __('production_execution.shift_evidence.downtime') }}</th><td dir="ltr">{{ $numbers->format($entry->downtime_minutes) }}</td></tr>
</tbody></table>
<table dir="{{ $direction ?? 'ltr' }}" class="report-table"><thead><tr>@foreach($columns as $field)<th>{{ __('production_execution.shift_evidence.'.$field) }}</th>@endforeach</tr></thead><tbody><tr>@foreach($columns as $field)<td>{{ isset($fields[$field]) ? (is_numeric($fields[$field]) ? $numbers->format($fields[$field]) : $fields[$field]) : '—' }}</td>@endforeach</tr></tbody></table>
<table dir="{{ $direction ?? 'ltr' }}" class="report-table"><thead><tr><th>{{ __('production_execution.shift_evidence.output_base_units') }}</th><th>{{ __('production_execution.shift_evidence.output_pieces') }}</th><th>{{ __('production_execution.shift_evidence.material_used') }}</th><th>{{ __('production_execution.shift_evidence.material_waste') }}</th><th>{{ __('production_execution.fields.production_scrap_weight_kg') }}</th></tr></thead><tbody><tr><td dir="ltr">{{ $numbers->format($entry->good_base_quantity) }} {{ $record->product?->unit?->name }}</td><td dir="ltr">{{ $numbers->format($entry->output_pieces) }} {{ $fields['basis_unit_name'] }}</td><td dir="ltr">{{ $numbers->format($entry->material_used) }}</td><td dir="ltr">{{ $numbers->format($entry->material_waste) }}</td><td dir="ltr">{{ $numbers->format($entry->scrap_weight_kg) }}</td></tr></tbody></table>
<table dir="{{ $direction ?? 'ltr' }}" class="report-table"><thead><tr><th>{{ __('production_execution.fields.worker_name') }}</th><th>{{ __('production_execution.fields.worker_role') }}</th><th>{{ __('production_execution.fields.planned_hours') }}</th><th>{{ __('production_execution.shift_evidence.signature') }}</th></tr></thead><tbody>@foreach($entry->crew_snapshot as $worker)<tr><td>{{ $worker['name'] }}</td><td>{{ __('production_execution.shift_evidence.role_'.$worker['role']) }}</td><td dir="ltr">{{ $numbers->format($worker['planned_hours']) }}</td><td>________________</td></tr>@endforeach</tbody></table>
@if($entry->notes)<p>{{ $entry->notes }}</p>@endif
<table dir="{{ $direction ?? 'ltr' }}" class="report-table"><thead><tr><th>{{ __('production_execution.fields.date') }}</th><th>{{ __('production_execution.fields.notes') }}</th><th>{{ __('production_execution.shift_evidence.material_used') }} / {{ __('production_execution.shift_evidence.material_waste') }}</th></tr></thead><tbody>@foreach($entry->notes_log as $note)<tr><td>{{ $dates->formatDateTime($note['at']) }}</td><td>{{ $note['notes'] ?: '—' }}</td><td>@foreach($note['materials'] as $material){{ $material['material_name'] ?? '—' }} ({{ $material['unit_name'] ?? '—' }}): {{ $numbers->format($material['consumed_quantity']) }} / {{ $numbers->format($material['waste_quantity']) }} @if($material['waste_classification']){{ __('production_execution.evidence.'.$material['waste_classification']) }}: {{ $material['notes'] }}@endif<br>@endforeach</td></tr>@endforeach</tbody></table>
