@php
    $fields = $entry->sheet_fields;
    $kind = $fields['sheet_kind'] ?? 'injection';
    $daily = ($fields['entry_source'] ?? null) === 'daily_sheet';
    $columns = $kind === 'cover'
        ? ['product_size', 'cover_components', 'machine_speed', 'pack_ratio', 'carton_type', 'carton_size']
        : ['cavities', 'cycle_seconds', 'piece_weight_grams', 'average_piece_weight_grams', 'bag_type', 'bag_size', 'carton_type', 'carton_size', 'pack_ratio'];
    if ($daily) {
        $columns = array_values(array_diff($columns, ['product_size', 'pack_ratio']));
        $columns = array_merge($columns, ['packing_ratio', 'carton_count', 'intact_roll_waste']);
        if ($kind === 'cover') {
            array_unshift($columns, 'customer_name');
        }
    }
@endphp
<h3>{{ __('production_execution.shift_evidence.report_title') }} — {{ __('production_execution.shift_evidence.'.$kind) }}</h3>
<table dir="{{ $direction ?? 'ltr' }}" class="report-table"><tbody>
    <tr><th>{{ __('production_execution.shift_evidence.work_date') }}</th><td>{{ $dates->formatDate($entry->work_date) }}</td><th>{{ __('production_execution.shift_evidence.day') }}</th><td>{{ \Carbon\CarbonImmutable::parse($entry->work_date)->locale(app()->getLocale())->translatedFormat('l') }}</td><th>{{ __('production_execution.fields.shift') }}</th><td>{{ $fields['shift_name'] }}</td></tr>
    <tr><th>{{ __('production_execution.fields.run') }}</th><td dir="ltr">{{ $record->run_number }}</td><th>{{ __('production_execution.fields.production_order') }}</th><td dir="ltr">{{ $record->order?->doc_num }}</td><th>{{ __('production_execution.fields.product') }}</th><td>{{ $fields['product_name'] }}</td></tr>
    <tr><th>{{ __('production_execution.fields.fixed_asset') }}</th><td colspan="3">{{ $entry->equipment_snapshot['number'] }} — {{ $entry->equipment_snapshot['name'] }}</td><th>{{ __('production_execution.shift_evidence.working_hours') }}</th><td dir="ltr">{{ $numbers->format($entry->working_hours) }}</td></tr>
    @if($daily)<tr><th>{{ __('production_daily_report.time_basis') }}</th><td colspan="5">{{ __('production_daily_report.'.$fields['time_basis']) }}@if($fields['time_basis'] === 'hr_schedule') — {{ __('production_daily_report.derived_time_help') }}@endif</td></tr>
    @if($fields['time_basis'] === 'reported_clock')<tr><th>{{ __('production_daily_report.from_time') }}</th><td>{{ $dates->formatDateTime($entry->started_at) }}</td><th>{{ __('production_daily_report.to_time') }}</th><td colspan="3">{{ $dates->formatDateTime($entry->ended_at, '—') }}</td></tr>@endif
    @else<tr><th>{{ __('production_execution.shift_evidence.actual_start') }}</th><td>{{ $dates->formatDateTime($entry->started_at) }}</td><th>{{ __('production_execution.shift_evidence.actual_end') }}</th><td>{{ $dates->formatDateTime($entry->ended_at, '—') }}</td><th>{{ __('production_execution.shift_evidence.downtime') }}</th><td dir="ltr">{{ $numbers->format($entry->downtime_minutes) }}</td></tr>@endif
</tbody></table>
<table dir="{{ $direction ?? 'ltr' }}" class="report-table"><thead><tr>@foreach($columns as $field)<th>{{ __($daily ? 'production_daily_report.fields.'.$field : 'production_execution.shift_evidence.'.$field) }}</th>@endforeach</tr></thead><tbody><tr>@foreach($columns as $field)<td>{{ isset($fields[$field]) ? (is_numeric($fields[$field]) ? $numbers->format($fields[$field]) : $fields[$field]) : '—' }}</td>@endforeach</tr></tbody></table>
@if($daily)
<p>{{ __('production_daily_report.help') }}</p>
<table dir="{{ $direction ?? 'ltr' }}" class="report-table"><thead><tr><th>{{ __(($entry->has_quantity_corrections ?? false) ? 'production_daily_report.correction.original' : 'production_daily_report.quantity') }}</th><th>{{ __('production_daily_report.fields.actual_pieces') }}</th><th>{{ __('production_daily_report.fields.material_used') }}</th><th>{{ __('production_daily_report.fields.actual_waste') }}</th></tr></thead><tbody><tr><td>{{ $numbers->format($fields['reported_quantity']) }} {{ $fields['reported_unit_name'] }}</td><td>{{ $entry->output_pieces === null ? '—' : $numbers->format($entry->output_pieces) }}</td><td>{{ isset($fields['material_used']) ? $numbers->format($fields['material_used']).' '.($fields['material_unit'] ?? '') : '—' }}</td><td>{{ isset($fields['actual_waste']) ? $numbers->format($fields['actual_waste']).' '.($fields['waste_unit'] ?? '') : '—' }}</td></tr></tbody></table>
@if(isset($fields['reported_outcomes']))
<table dir="{{ $direction ?? 'ltr' }}" class="report-table"><thead><tr>@foreach(['good', 'rejected', 'rework', 'scrap'] as $outcome)<th>{{ __('production_stage_transfer.output_'.$outcome) }}</th>@endforeach</tr></thead><tbody><tr>@foreach($fields['reported_outcomes'] as $quantity)<td>{{ $numbers->format($quantity) }} {{ $fields['reported_unit_name'] }}</td>@endforeach</tr></tbody></table>
@endif
@if($entry->has_quantity_corrections ?? false)<p>{{ __('production_daily_report.correction.original') }}: {{ $numbers->format($fields['reported_quantity']) }} — {{ __('production_daily_report.correction.effective') }}: {{ $numbers->format(bcdiv($entry->good_base_quantity, (string) $record->conversion_factor, 8)) }} {{ $fields['reported_unit_name'] }}</p>@endif
@if($kind === 'cover')<table dir="{{ $direction ?? 'ltr' }}" class="report-table"><tbody><tr><th>{{ __('production_daily_report.fields.material_name') }}</th><td>{{ $fields['material_name'] ?? '—' }}</td><th>{{ __('production_daily_report.fields.roll_reference') }}</th><td>{{ $fields['roll_reference'] ?? '—' }}</td></tr></tbody></table>@endif
@if(filled($fields['technician_names'] ?? null))<p>{{ __('production_daily_report.technician_names') }}: {{ $fields['technician_names'] }}</p>@endif
@else
<table dir="{{ $direction ?? 'ltr' }}" class="report-table"><thead><tr><th>{{ __('production_execution.shift_evidence.output_base_units') }}</th><th>{{ __('production_execution.shift_evidence.output_pieces') }}</th><th>{{ __('production_execution.shift_evidence.material_used') }}</th><th>{{ __('production_execution.shift_evidence.material_waste') }}</th><th>{{ __('production_execution.fields.production_scrap_weight_kg') }}</th></tr></thead><tbody><tr><td dir="ltr">{{ $numbers->format($entry->good_base_quantity) }} {{ $record->product?->unit?->name }}</td><td dir="ltr">{{ $numbers->format($entry->output_pieces) }} {{ $fields['basis_unit_name'] }}</td><td dir="ltr">{{ $numbers->format($entry->material_used) }}</td><td dir="ltr">{{ $numbers->format($entry->material_waste) }}</td><td dir="ltr">{{ $numbers->format($entry->scrap_weight_kg) }}</td></tr></tbody></table>
@endif
<table dir="{{ $direction ?? 'ltr' }}" class="report-table"><thead><tr><th>{{ __('production_execution.fields.worker_name') }}</th><th>{{ __('production_execution.fields.worker_role') }}</th><th>{{ __('production_execution.fields.planned_hours') }}</th><th>{{ __('production_execution.shift_evidence.signature') }}</th></tr></thead><tbody>@foreach($entry->crew_snapshot as $worker)<tr><td>{{ $worker['name'] }}</td><td>{{ __('production_execution.shift_evidence.role_'.$worker['role']) }}</td><td dir="ltr">{{ $numbers->format($worker['planned_hours']) }}</td><td>________________</td></tr>@endforeach</tbody></table>
@if($entry->notes)<p>{{ $entry->notes }}</p>@endif
<table dir="{{ $direction ?? 'ltr' }}" class="report-table"><thead><tr><th>{{ __('production_execution.fields.date') }}</th><th>{{ __('production_execution.fields.notes') }}</th><th>{{ __('production_execution.shift_evidence.material_used') }} / {{ __('production_execution.shift_evidence.material_waste') }}</th></tr></thead><tbody>@foreach($entry->notes_log as $note)<tr><td>{{ $dates->formatDateTime($note['at']) }}</td><td>{{ $note['notes'] ?: '—' }}</td><td>@foreach($note['materials'] as $material){{ $material['material_name'] ?? '—' }} ({{ $material['unit_name'] ?? '—' }}): {{ $numbers->format($material['consumed_quantity']) }} / {{ $numbers->format($material['waste_quantity']) }} @if($material['waste_classification'] ?? null){{ __('production_execution.evidence.'.$material['waste_classification']) }}: {{ $material['notes'] }}@endif<br>@endforeach</td></tr>@endforeach</tbody></table>
